### ISSUE TITLE
Ad Manager mediation with facebook not working Need Help

### ISSUE THREAD

**Issue by Rohan487** [googleads/googleads-mobile-flutter#1000]
I am on windows 11

## Plugin Version

pakage google_mobile_ads: ^4.0.0
google mobile ads SDK v22.5.0

### Describe the problem

I am trying to add mediation in google admanager with facebook ( Meta ) , I have followed the 2 guides 

1 - https://developers.google.com/ad-manager/mobile-ads-sdk/android/mediation/meta
2 - for flutter -> https://developers.google.com/ad-manager/mobile-ads-sdk/flutter/mediation

I have done exact steps , and added dependencies in my app level build.gradle 
![image](https://github.com/googleads/googleads-mobile-flutter/assets/72985121/526b29da-30c1-4215-9762-b6d2e6a6e325)

But the problem is google mobile ads sdk is not able to find any adapter at , i am using ad inspector to inspect it and also using code in flutter to print the status of adapters it also not finding it 

![image](https://github.com/googleads/googleads-mobile-flutter/assets/72985121/c6753263-a131-4dd4-88c4-3724dfc4e6cd)

and due to this issue only ad manager ads are visible (test and real) , mediation is not working

<details>
  <summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale en-IN)
    • Flutter version 3.16.9 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (8 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Rohan\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Rohan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2017 15.9.54)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.33529.398
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\Rohan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0
```
</details>

**Comment by Rohan487** [comment]
Updates:
There is no implementation error on my side, I have verified this by logging the version of the mediation adapter and SDK from the native side at runtime

I don't know why Google mobile ads can't detect the mediation adapter. Is there a step I'm missing 🤔?

**Comment by malandr2** [comment]
Hi @Rohan487, this appears to be related to the mediation network on Android rather than directly related to the google_mobile_ads Flutter plugin.

As an actionable next step, please create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk), you can link to this GitHub if you choose, and please include your App ID so your issue can be appropriately triaged. Closing this issue out. Thanks!
