### ISSUE TITLE
Conflicting info regarding forwarding consent to the Google Mobile Ads SDK

### ISSUE THREAD

**Issue by absar** [googleads/googleads-mobile-flutter#1001]
There is conflicting info regarding forwarding consent to the Google Mobile Ads SDK:

Flutter docs here https://developers.google.com/admob/flutter/eu-consent#forward_consent_to_the_google_mobile_ads_sdk mentions

> The default behavior of the Google Mobile Ads SDK is to serve personalized ads. If a user has consented to receive only non-personalized ads, you can configure an AdRequest object with the following code to specify that only non-personalized ads should be requested

```dart
final AdRequest = AdRequest(nonPersonalizedAds: true);
```

Whereas https://github.com/googleads/googleads-mobile-flutter/issues/837#issuecomment-1546271344 mentions:

> "It's not necessary to forward any information to the AdRequest. GMASDK is able to figure out the consent status from UMP SDK and handle it behind the scenes"
nonPersonalizedAds is for if you don't use UMPSDK, or if you have some other reason for always wanting non personalized ads.

**My question is**: which one is the correct way, ideally since the consent screen is part of this package shouldn't it auto inform `Google Mobile Ads SDK`. If it is the responsibility of Flutter app then this package should expose a dart getter to get the consent status for atleast `nonPersonalizedAds` flag. There is also nothing in the samples for consent screen, which should be added to minimize support issues.

Sorry if this is not the correct forum to post it, can't create an issue in general AdMob forum since this seems like a Flutter docs issue

**Comment by malandr2** [comment]
Hey @absar, the UMP SDK and the GMA SDK are separate entities. As written, the flutter docs are correct. 

The comment is also correct, you don't need to set `nonPersonalizedAds` if you are using the UMP SDK (or any other third-party CMP). 

Both are correct but depend on your implementation. In short, if you're using a Google-certified consent management platform to gather consent, you don't need to explicitly use the `nonPersonalizedAds` API.

**Comment by absar** [comment]
Hi @malandr2 thank you for the clarification, it would be helpful for developers if the same clarifications are updated in the [docs](https://developers.google.com/admob/flutter/eu-consent#forward_consent_to_the_google_mobile_ads_sdk) since this section only exists in Flutter docs and does not exist in either [Android](https://developers.google.com/admob/android/privacy) or [iOS](https://developers.google.com/admob/ios/privacy) docs
There were two more concerns in my OP would be helpful if you comment on these as well:

1. Expose a platform agnostic dart only getter to get the consent status, at least `IABTCF_PurposeConsents` tag
2. There are no samples for consent screen in this repo, which should be added to minimize support issues

**Comment by vacating** [comment]
@malandr2  catch u man was looking for u ages, look man we have issue some ppl say ur admobe account should be verified some say otherthings,   since we have u here  , lemme ask u  am not willing to use  kotlin or java , so am doing it in flutter side and it doesnt work man  been stuck weeks wifey dont respect me anymore cuz am stuck for ever now,     can u tell me how to do it in flutter side ??   what package to use to get this   'IABTCF_PurposeConsents  ?   is doing it via flutter side would work ?

**Comment by vacating** [comment]
@malandr2  we really dont care about user consent statues why u  guys keep it hidden for developers ?  ew we just wanna close or open the ads based on it so why not just   make a simple getter to show the ads or no.     anyways i respect what u guys do but could u please guide what i can do here to do it in flutter side ? i need to show or hide the ads based on consent and i dont have access to consent statues what to do here ?

**Comment by vacating** [comment]
@malandr2   

this package return  obtained for both cases :  consented or didnt consent  google_mobile_ads  


now here 


same code : 


import 'dart:async';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:get_storage/get_storage.dart';
import 'dart:developer' as developer;

class InitializationHelper {
  final GetStorage storage = GetStorage('ConsentStorage');
  final StreamController<bool> _consentStreamController = StreamController<bool>.broadcast();
  bool _isInitialized = false;

  InitializationHelper() {
    initialize();
  }

  Stream<bool> get consentStream => _consentStreamController.stream;

  Future<void> initialize() async {
    if (_isInitialized) {
      developer.log('Initialization already performed.', name: 'InitializationHelper');
      return;
    }

    // Check stored consent from GetStorage
    String purposesConsents = storage.read('IABTCF_PurposeConsents') ?? "";
    if (purposesConsents.isNotEmpty) {
      bool hasConsentForPurposeOne = purposesConsents[0] == '1';
      _consentStreamController.add(hasConsentForPurposeOne);
      if (hasConsentForPurposeOne) {
        _initializeAds();
      } else {
        developer.log('No ads will be shown because user did not consent.', name: 'InitializationHelper');
      }
      return;
    }

    final ConsentRequestParameters params = ConsentRequestParameters(
      consentDebugSettings: ConsentDebugSettings(
        debugGeography: DebugGeography.debugGeographyEea, // For testing
      ),
    );

    ConsentInformation.instance.requestConsentInfoUpdate(
      params,
      () async {
        if (await ConsentInformation.instance.isConsentFormAvailable()) {
          loadForm();
        }
      },
      (FormError error) {
        developer.log('Error requesting consent info update: ${error.message}', name: 'InitializationHelper');
        _consentStreamController.add(false);
      },
    );

    _isInitialized = true;
  }

  void loadForm() {
    ConsentForm.loadConsentForm(
      (ConsentForm form) {
        form.show(
          (FormError? error) {
            if (error != null) {
              developer.log('Error showing consent form: ${error.message}', name: 'InitializationHelper');
              _consentStreamController.add(false);
            } else {
              _checkConsentAndInitializeAds();
            }
          }
        );
      },
      (FormError error) {
        developer.log('Error loading consent form: ${error.message}', name: 'InitializationHelper');
        _consentStreamController.add(false);
      },
    );
  }

  Future<void> _checkConsentAndInitializeAds() async {
    bool canRequestAds = await ConsentInformation.instance.canRequestAds();
    bool userConsented = canRequestAds;

    storage.write('userConsented', userConsented);
    _consentStreamController.add(userConsented);

    if (userConsented) {
      _initializeAds();
    } else {
      developer.log('No ads will be shown because user did not consent.', name: 'InitializationHelper');
    }
  }

  void _initializeAds() {
    MobileAds.instance.initialize().then((InitializationStatus status) {
      developer.log('Ads SDK Initialized: $status', name: 'InitializationHelper');
    }).catchError((error) {
      developer.log('Failed to initialize ads: $error', name: 'InitializationHelper');
    });
  }

  void dispose() {
    _consentStreamController.close();
  }
}



when i dont consent  it still load the ads why @malandr2   come on man  tell us nw
