### ISSUE TITLE
Please cleanup code quality (use futures, stop using typedefs for trivial types, etc)

### ISSUE THREAD

**Issue by caseycrogers** [googleads/googleads-mobile-flutter#1024]
The poor code quality in this package makes this API very hard to use. Most of the issues here feel like someone was trying to write old school Java in Dart. These conventions make no sense in a Dart context. This issue is a bit overlapping with my previous one asking for Dart idioms, but it felt different enough to justify a second issue.

1. Don't use verbose names
https://github.com/googleads/googleads-mobile-flutter/blob/8378dcf25699e44a01f30de669ed68ce45fb3911/packages/google_mobile_ads/lib/src/ump/consent_information.dart#L21
2. Don't make unique typedefs, use existing core lib typedefs or other typedefs from within the same project. Here `VoidCallback` is the appropriate type.
(same link as above)
3. Don't use an abstract class when you're only ever going to create a single implementing class. The separate interface and implementation just splits the code and makes it harder to follow.
https://github.com/googleads/googleads-mobile-flutter/blob/8378dcf25699e44a01f30de669ed68ce45fb3911/packages/google_mobile_ads/lib/src/ump/consent_information.dart#L42
4. (Redundant with https://github.com/googleads/googleads-mobile-flutter/issues/890) Use futures, not callbacks

**Comment by malandr2** [comment]
Also want to add for #1 our APIs are named similarly to our Google Mobile Ads Android & iOS SDKs with emphasis on parity. As a result, names may be more verbose than others.

**Comment by malandr2** [comment]
Going to mark this as duplicate because our UMP code updates can be followed using https://github.com/googleads/googleads-mobile-flutter/issues/852. Also as stated this is similar to https://github.com/googleads/googleads-mobile-flutter/issues/890. Thanks for your feedback you should be seeing these updates in upcoming PRs. Feel free to comment on them as well. Thanks!

**Comment by malandr2** [comment]
@caseycrogers take a look at https://github.com/googleads/googleads-mobile-flutter/pull/1062 if feel free to leave any comments
