### ISSUE TITLE
On Android 11, 12 ads are not visible if impeller is enabled.

### ISSUE THREAD

**Issue by cristian1980** [googleads/googleads-mobile-flutter#1025]
### [REQUIRED] Step 1: Describe your environment
I was able to reproduce on:
Samsung T510 running Android 11
Xiaomi Redmi Note 11 running Android 11 and Android 12

After updating Xiaomi Redmi Note 11 to Android 13, ads started appearing.
Galaxy A12 running Android 13 is working correctly.

## Plugin Version
I tried 4.0.0 and 3.1.0

### [REQUIRED] Step 2: Describe the problem

I am using this code https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example/lib .
I enabled Impeller using this procedure https://docs.flutter.dev/perf/impeller#android .

The problem is that all the ads except interstitial and rewarded are invisible but when tapping on them the page is opened, so ads are there but not visible.

I can't be sure its a general android 11, 12 version since I had a limited number of devices to test.

## Steps to Reproduce

Just run the test app with impeller enabled see https://docs.flutter.dev/perf/impeller#android .

**Expected results:**Ads should be visible

**Actual results:**  All ads except interstitial and rewarded are invisible.
![image](https://github.com/googleads/googleads-mobile-flutter/assets/5364569/92be7213-dd0a-453e-bad3-6e0b43e90f94)

<details>
  <summary>Logs</summary>

[flutter_run_v.txt](https://github.com/googleads/googleads-mobile-flutter/files/14601039/flutter_run_v.txt)

```
```

Mac-Studio:admob_test_app cristi$ flutter analyze
Analyzing admob_test_app...                                             

   info • Constructors for public widgets should have a named 'key' parameter • lib/anchored_adaptive_example.dart:27:7 •
          use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/anchored_adaptive_example.dart:29:3 • library_private_types_in_public_api
   info • Don't use 'BuildContext's across async gaps • lib/anchored_adaptive_example.dart:55:27 • use_build_context_synchronously
   info • Don't invoke 'print' in production code • lib/anchored_adaptive_example.dart:58:7 • avoid_print
   info • Use 'const' with the constructor to improve performance • lib/anchored_adaptive_example.dart:67:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/anchored_adaptive_example.dart:70:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/anchored_adaptive_example.dart:79:11 • avoid_print
   info • Use 'const' with the constructor to improve performance • lib/anchored_adaptive_example.dart:117:18 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/anchored_adaptive_example.dart:126:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/anchored_adaptive_example.dart:128:30 • prefer_const_constructors
   info • Constructors for public widgets should have a named 'key' parameter • lib/fluid_example.dart:22:7 • use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/fluid_example.dart:24:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/fluid_example.dart:34:16 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/fluid_example.dart:70:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/fluid_example.dart:72:22 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/fluid_example.dart:74:24 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/fluid_example.dart:87:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/fluid_example.dart:90:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/fluid_example.dart:93:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/fluid_example.dart:96:32 • avoid_print
   info • Don't invoke 'print' in production code • lib/fluid_example.dart:97:32 • avoid_print
   info • Constructors for public widgets should have a named 'key' parameter • lib/inline_adaptive_example.dart:25:7 •
          use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/inline_adaptive_example.dart:27:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/inline_adaptive_example.dart:60:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/inline_adaptive_example.dart:63:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/inline_adaptive_example.dart:71:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/inline_adaptive_example.dart:82:11 • avoid_print
   info • Use a 'SizedBox' to add whitespace to a layout • lib/inline_adaptive_example.dart:102:22 • sized_box_for_whitespace
   info • Use 'const' with the constructor to improve performance • lib/inline_adaptive_example.dart:123:16 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/inline_adaptive_example.dart:139:22 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/inline_adaptive_example.
dart:141:24 • prefer_const_constructors
   info • Constructors for public widgets should have a named 'key' parameter • lib/main.dart:41:7 • use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/main.dart:43:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/main.dart:47:36 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/main.dart:90:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:96:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:108:7 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:113:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:115:9 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:120:9 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:137:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:142:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:154:7 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:159:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:161:9 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:166:9 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:175:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:188:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:193:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:205:7 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:211:15 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:213:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:219:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/main.dart:228:11 • avoid_print
   info • Use 'const' with the constructor to improve performance • lib/main.dart:314:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:316:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:318:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:320:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:322:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:324:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:326:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:328:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:330:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:332:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:334:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:336:28 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:338:19 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/main.dart:340:28 • prefer_const_constructors
   info • Constructors for public widgets should have a named 'key' parameter • lib/native_template_example.dart:22:7 •
          use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/native_template_example.dart:24:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/native_template_example.dart:35:16 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/native_template_example.dart:61:22 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/native_template_example.dart:63:24 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/native_template_example.dart:76:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/native_template_example.dart:79:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/native_template_example.dart:85:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/native_template_example.dart:88:32 • avoid_print
   info • Don't invoke 'print' in production code • lib/native_template_example.dart:89:32 • avoid_print
   info • Constructors for public widgets should have a named 'key' parameter • lib/reusable_inline_example.dart:24:7 •
          use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/reusable_inline_example.dart:26:3 • library_private_types_in_public_api
   info • Use a 'SizedBox' to add whitespace to a layout • lib/reusable_inline_example.dart:53:24 • sized_box_for_whitespace
   info • Use a 'SizedBox' to add whitespace to a layout • lib/reusable_inline_example.dart:63:24 • sized_box_for_whitespace
   info • Use a 'SizedBox' to add whitespace to a layout • lib/reusable_inline_example.dart:71:24 • sized_box_for_whitespace
   info • Use 'const' with the constructor to improve performance • lib/reusable_inline_example.dart:75:22 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/reusable_inline_example.dart:77:24 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:95:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:101:13 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:104:34 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:105:34 • avoid_print
   info • Use 'const' with the constructor to improve performance • lib/reusable_inline_example.dart:107:18 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/reusable_inline_example.dart:114:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:118:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:124:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:127:32 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:128:32 • avoid_print
   info • Use 'const' with the constructor to improve performance • lib/reusable_inline_example.dart:134:16 • prefer_const_constructors
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:138:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:144:11 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:147:32 • avoid_print
   info • Don't invoke 'print' in production code • lib/reusable_inline_example.dart:148:32 • avoid_print
   info • The imported package 'webview_flutter' isn't a dependency of the importing package • lib/webview_example.dart:19:8 •
          depend_on_referenced_packages
   info • The imported package 'webview_flutter_android' isn't a dependency of the importing package • lib/webview_example.dart:20:8 •
          depend_on_referenced_packages
   info • Constructors for public widgets should have a named 'key' parameter • lib/webview_example.dart:23:7 • use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/webview_example.dart:25:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/webview_example.dart:65:11 • prefer_const_constructors
warning • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
warning • Unused import: 'package:admob_test_app/main.dart' • test/widget_test.dart:11:8 • unused_import

107 issues found. (ran in 0.9s)

```
```

Mac-Studio:admob_test_app cristi$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
    • Flutter version 3.19.3 on channel stable at /Users/cristi/Desktop/work/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (7 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cristi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (6 available)
    • SM T510 (mobile)           • R52N81CYF5M                              • android-arm    • Android 11 (API 30)
    • SM A127F (mobile)          • R58RB4LCHNP                              • android-arm64  • Android 13 (API 33)
    • Constantin’s iPad (mobile) • b1ef8b2504b35534e5217f197a197dc34b9b368c • ios            • iOS 15.6.1 19G82
    • iPhone (mobile)            • 00008030-000130512213802E                • ios            • iOS 17.3.1 21D61
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 122.0.6261.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```

</details>

**Comment by Phlphat746** [comment]
It's been fixed. My team is the best.

ในวันที่ พฤ. 14 มี.ค. 2024 17:49 น. cristian1980 ***@***.***>
เขียนว่า:

**Comment by malandr2** [comment]
Hey @cristian1980, I am getting a crash when using impeller with a Pixel 6 Pro API 33. There's also an existing [issue](https://github.com/flutter/flutter/issues/139731) (closed) where this has happened. I'll put this on the engineering team's radar to take a closer look.

**Comment by cristian1980** [comment]
Hey @malandr2 , did not know about Pixel 6 Pro API 33 issues. Thank you for the heads up.

**Comment by malandr2** [comment]
Hi @all,

It should be reiterated that impeller is [currently in preview](https://docs.flutter.dev/perf/impeller#android) and that we don't recommend releasing applications with it yet. As of now we don't expect ads to work in impeller. We will provide an update when we have full support for it. Thanks!

**Comment by cristian1980** [comment]
@jonahwilliams  I confirm that ads are working using latest beta branch but ar not working using latest stable.

**Comment by jonahwilliams** [comment]
Thats great! We'll have a new stable coming up soon too
