### ISSUE TITLE
google_mobile_ads 4.0.0 craches app , Fatal error  => lost connection to device

### ISSUE THREAD

**Issue by mirdods** [googleads/googleads-mobile-flutter#1027]
<!-- Thank you for using Google Mobile Ads for Flutter!

 W/alneb.takespart(29211): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
W/alneb.takespart(29211): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->c:Ljava/util/Collection; (unsupported, reflection, allowed)
W/alneb.takespart(29211): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
W/alneb.takespart(29211): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
W/DynamiteModule(29211): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule(29211): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(29211): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
V/NativeCrypto(29211): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 305 native methods...
W/alneb.takespart(29211): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
I/ProviderInstaller(29211): Installed default security provider GmsCore_OpenSSL
D/TrafficStats(29211): tagSocket(286) with statsTag=0xffffffff, statsUid=-1
W/alneb.takespart(29211): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
W/alneb.takespart(29211): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
E/AndroidRuntime(29211): FATAL EXCEPTION: main
E/AndroidRuntime(29211): Process: com.nuomamlahcerhalneb.takespart, PID: 29211
E/AndroidRuntime(29211): java.lang.NoSuchMethodError: No virtual method setRequestAgent(Ljava/lang/String;)Lcom/google/android/gms/ads/AdRequest$Builder; in class Lcom/google/android/gms/ads/AdRequest$Builder; or its super classes (declaration of 'com.google.android.gms.ads.AdRequest$Builder' appears in /data/app/~~YH2TxFqCztEVfZ6wHoiUww==/com.nuomamlahcerhalneb.takespart-SIvE_iv-o_Y-JP1EooE8Tg==/base.apk)
E/AndroidRuntime(29211): 	at io.flutter.plugins.googlemobileads.FlutterAdRequest.updateAdRequestBuilder(FlutterAdRequest.java:235)
E/AndroidRuntime(29211): 	at io.flutter.plugins.googlemobileads.FlutterAdRequest.asAdRequest(FlutterAdRequest.java:240)
E/AndroidRuntime(29211): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:51)
E/AndroidRuntime(29211): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:439)
E/AndroidRuntime(29211): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(29211): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(29211): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(29211): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(29211): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(29211): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29211): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(29211): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(29211): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(29211): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29211): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(29211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (29211): Sending signal. PID: 29211 SIG: 9
Lost connection to device.

</details>

When i remove inatialAD it works like a charm

**Comment by GuvanchBayryyyev** [comment]
I am also getting this error on IOS

**Comment by malandr2** [comment]
Closing this out. Please follow the bug template so we can properly triage. A quick google search leads me to believe this issue isn't related to the `google_mobile_ads' plugin but an environment setup issue. If you end creating a proper thread, please include a stack trace and steps to reproduce but initial triage looks rather infeasible. Thanks!

**Comment by josemiguelvarela** [comment]
I had the same issue on Android when updating flutter to the latest version. It seems that using the latest master commits fixes the issue, try adding the library with
```
google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter.git
      ref: main
      path: packages/google_mobile_ads
```

**Comment by GuvanchBayryyyev** [comment]
@mirdods @josemiguelvarela what was your solution?

**Comment by josemiguelvarela** [comment]
> @mirdods @josemiguelvarela what was your solution?

For me the workaround was replacing in pubspec.yaml the line

`google_mobile_ads: ^4.0.0`

for 

```
google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter.git
      ref: main
      path: packages/google_mobile_ads
```

But in my case iOS was working fine. Anyway, I'll wait for the next google_mobile_ads version before deploying anything.

**Comment by GuvanchBayryyyev** [comment]
I've solved by 

using the [app id](https://developers.google.com/admob/ios/quick-start#expandable-1) on Info.plist file
```
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~1458002511</string>
```
and [adUnit id](https://developers.google.com/admob/flutter/banner#always_test_with_test_ads) worked for me
```
 BannerAd bAd = BannerAd(
      size: AdSize.banner,
      adUnitId: 'ca-app-pub-3940256099942544/2934735716',
      listener: BannerAdListener(onAdLoaded: (Ad ad) {
      ...
```

**Comment by Phlphat746** [comment]
ขอบคุณที่ช่วยกันทำงานนะครับ
