### ISSUE TITLE
How to increase the show rate in AdMob?

### ISSUE THREAD

**Issue by aivagroup** [googleads/googleads-mobile-flutter#1031]
Hello,
In my applications, I have around 100-140 active users in the last 30 minutes, yet I'm experiencing a very low show rate. I'm a Flutter application developer, and I use the library https://pub.dev/packages/google_mobile_ads/versions/4.0.0 for displaying ads. For over a year now, I've been unable to solve the problem of low show rates. I don't have any ad restrictions, and the applications are used in different countries with different audiences, but the problem persists across all applications. Could someone please suggest any ideas on what the problem might be and how to solve it? I have attached a screenshot from AdMob. Additionally, I have added a video where it can be seen that even though banner ads may show for the first time, they don't show upon revisiting the same section.

![2024-03-21_09-17](https://github.com/googleads/googleads-mobile-flutter/assets/106317508/99ab2787-e27f-4ce9-824b-2760bd0177e8)

https://github.com/googleads/googleads-mobile-flutter/assets/106317508/647a4916-5416-43d0-8c03-03442f8588c8

**Comment by malandr2** [comment]
Hey @aivagroup, this question isn't directly related to the `google_mobile_ads` plugin (more of an ad serving question) would be best suited for the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk). Please add this information when creating the new thread. Closing this out. Thanks!
