### ISSUE TITLE
iOS 12.5 'await MobileAds.instance.initialize()' never ends with 5.0.0 plugin version

### ISSUE THREAD

**Issue by nadrolinux** [googleads/googleads-mobile-flutter#1033]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/flutter/quick-start),
   send your feedback by pressing the **Send Feedback** button at the top right of the
   documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

---

## Plugin Version

5.0.0

## Steps to Reproduce

1. Use real device with iOS 12.5.7 (I think that all iOS 12 devices are affected), because with iOS 17.2 all works fine.
2. Execute: 'await MobileAds.instance.initialize();'

**Expected results:** 'await MobileAds.instance.initialize();' finish after some time like with 4.0.0 plugins version and older

**Actual results:** App wait forever at 'await MobileAds.instance.initialize();'

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-x64, locale pl-PL)
    • Flutter version 3.19.3 on channel stable at /Users/patryk/Programowanie/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.87.0)
    • VS Code at /Users/patryk/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (1 available)
    • iPad mini 2 (mobile)   • 00000000-00XXXXXXXXXXXXXX                • ios        • iOS 12.5.7 16H81

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```
```

</details>

**Comment by malandr2** [comment]
Hi @nadrolinux, with the `5.0.0` update it uses iOS Google Mobile Ads version `11.2.0` which raised the minimum deployment version of ads serving to iOS 13. ([Release notes](https://developers.google.com/admob/ios/rel-notes)). Your app should still able to compile/deploy in iOS 12 but there won't be any ads activity. 

In theory, if you test the 4.0.0 plugin version with iOS 11 devices you get the same behavior?

**Comment by nadrolinux** [comment]
@malandr2 
Sorry for delayed reply. I don't have an access to iOS 11 device, but if iOS 12 support was dropped thats fine. I'll stick with 4.0.0 in this situation.

**Comment by nadrolinux** [comment]
Hi @malandr2 
Thanks for info and sorry for delayed reply. I don't have an access to iOS 11 device, but if iOS 12 support was dropped thats fine (it looks like an AdMob SDK v11.0.0 was a 'game changer'). I'll stick with 4.0.0 in this situation.
