### ISSUE TITLE
Native Ad Request Triggered continuously multiple times for single ad load call

### ISSUE THREAD

**Issue by techashonline** [googleads/googleads-mobile-flutter#1034]
## Plugin Version - google_mobile_ads: ^5.0.0

This problem exists in pervious versions of the package also. So no problem with the new version

### [REQUIRED] Step 2: Describe the problem

I have implemented Native Ad using google_mobile_ads package. I created custom xml template to show native ads.
While loading the Native Ads the ad requests are sending multiple times but the ad load is called only once in the entire code.
I found the problem using network tracing logs. I have called the load call in initState() so i also checked if the load call is trigged on any widget rebuilds but it called only once.Because of multiple ad requests are sending it affects the match rate and show rate resulting in huge revenue loss. Kindly help me to fix this problem. 

**Expected results:** Only one Request has to send for single ad load call

**Actual results:**  Multiple ad Requests are sending for single ad load call
<details>
  <summary>Logs</summary>

[   +5 ms] I/Ads     (  810): GMA Debug BEGIN
[   +1 ms] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334242,"event":"onNetworkRequest","components":["network_request_659cef11-ccdd-4d6b-9f61-4c4bf0d8eabb"],"params":{"firstline":{"uri":"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-
core-v40-impl.html","verb":"GET"},"headers":[{"name":"sec-ch-ua-arch","value":"\"\""},{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exch
ange;v=b3;q=0.7"},{"name":"User-Agent","value":"Mozilla/5.0 (Linux; Android 12; HD1901 Build/SKQ1.211113.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 (Mobile;
afma-sdk-a-v240304999.240304000.1)"},{"name":"sec-ch-ua","value":"\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Android WebView\";v=\"122\""},{"name":"sec-ch-ua-full-version-list","value":"\"Chromium\";v=\"122.0.6261.119\",   
\"Not(A:Brand\";v=\"24.0.0.0\", \"Android
WebView\";v=\"122.0.6261.119\""},{"name":"sec-ch-ua-mobile","value":"?1"},{"name":"Upgrade-Insecure-Requests","value":"1"},{"name":"sec-ch-ua-platform","value":"\"Android\""},{"name":"sec-ch-ua-bitness","value":"\"\""},{"name":"sec-
ch-ua-model","value":"\"HD1901\""},{"name":"sec-ch-ua-platform-version","value":"\"12.0.0\""},{"name":"sec-ch-ua-wow64","value":"?0"}]}}
[   +1 ms] I/Ads     (  810): GMA Debug FINISH
[ +207 ms] I/Ads     (  810): GMA Debug BEGIN
[   +1 ms] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334451,"event":"onNetworkResponse","components":["network_request_659cef11-ccdd-4d6b-9f61-4c4bf0d8eabb"],"params":{"firstline":{"code":200},"headers":[{"name":null,"value":"HTTP/1.1 200
OK"},{"name":"Alt-Svc","value":"h3=\":443\"; ma=2592000,h3-29=\":443\";
ma=2592000"},{"name":"Server","value":"cafe"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"P3P","value":"policyref=\"https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml\", CP=\"CURa ADMa DEVa TAIo PSAo PSDo OUR  
IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR\""},{"name":"X-Android-Received-Millis","value":"1711078334448"},{"name":"Date","value":"Thu, 21 Mar 2024 04:01:46
GMT"},{"name":"X-Android-Selected-Protocol","value":"http/1.1"},{"name":"Cache-Control","value":"public,
max-age=86400"},{"name":"ETag","value":"8293937808077725434"},{"name":"Timing-Allow-Origin","value":"*"},{"name":"X-Android-Response-Source","value":"NETWORK
200"},{"name":"Vary","value":"Accept-Encoding"},{"name":"Cross-Origin-Resource-Policy","value":"cross-origin"},{"name":"Expires","value":"Fri, 22 Mar 2024 04:01:46
GMT"},{"name":"X-Android-Sent-Millis","value":"1711078334365"},{"name":"X-XSS-Protection","value":"0"},{"name":"Age","value":"84630"},{"name":"Content-Type","value":"text/html; charset=UTF-8"}]}}
[   +1 ms] I/Ads     (  810): GMA Debug FINISH
[ +120 ms] I/Ads     (  810): HTTP timeout: 60000 milliseconds.
[   +1 ms] I/Ads     (  810): GMA Debug BEGIN
[        ] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334580,"event":"onNetworkRequest","components":["network_request_12d3325d-365d-47df-bcd1-94b15379a61f"],"params":{"firstline":{"uri":"https://googleads.g.doubleclick.net/favicon.ico","verb":"GET"},"headers":[{"na
me":"sec-ch-ua","value":"\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Android
WebView\";v=\"122\""},{"name":"sec-ch-ua-mobile","value":"?1"},{"name":"Accept","value":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"},{"name":"sec-ch-ua-platform","value":"\"Android\""},{"name":"Referer","value
":"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html"},{"name":"User-Agent","value":"Mozilla/5.0 (Linux; Android 12; HD1901 Build/SKQ1.211113.001; wv) AppleWebKit/537.36 (KHTML, like   
Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 (Mobile; afma-sdk-a-v240304999.240304000.1)"}]}}
[        ] I/Ads     (  810): GMA Debug FINISH
[  +30 ms] I/Ads     (  810): GMA Debug BEGIN
[        ] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334607,"event":"onNetworkResponse","components":["network_request_12d3325d-365d-47df-bcd1-94b15379a61f"],"params":{"firstline":{"code":200},"headers":[{"name":null,"value":"HTTP/1.1 200
OK"},{"name":"Alt-Svc","value":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"},{"name":"Server","value":"sffe"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"Last-Modified","value":"Thu, 03 Oct 2019 10:15:00    
GMT"},{"name":"X-Android-Received-Millis","value":"1711078334605"},{"name":"Date","value":"Wed, 20 Mar 2024 22:44:07
GMT"},{"name":"Accept-Ranges","value":"bytes"},{"name":"X-Android-Selected-Protocol","value":"http/1.1"},{"name":"Cache-Control","value":"public,
max-age=31536000"},{"name":"Report-To","value":"{\"group\":\"static-on-bigtable\",\"max_age\":2592000,\"endpoints\":[{\"url\":\"https://csp.withgoogle.com/csp/report-to/static-on-bigtable\"}]}"},{"name":"Cross-Origin-Opener-Policy-R
eport-Only","value":"same-origin; report-to=\"static-on-bigtable\""},{"name":"X-Android-Response-Source","value":"NETWORK
200"},{"name":"Vary","value":"Accept-Encoding"},{"name":"Cross-Origin-Resource-Policy","value":"cross-origin"},{"name":"Expires","value":"Thu, 20 Mar 2025 22:44:07
GMT"},{"name":"X-Android-Sent-Millis","value":"1711078334582"},{"name":"X-XSS-Protection","value":"0"},{"name":"Age","value":"103689"},{"name":"Content-Type","value":"image/x-icon"}]}}
[   +1 ms] I/Ads     (  810): GMA Debug FINISH
[   +2 ms] I/flutter (  810): NativeAdRequested
[   +8 ms] D/DynamitePackage(  810): Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
[   +5 ms] I/flutter (  810): MyWidget rebuilt
[   +3 ms] I/Ads     (  810): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("A8B62C6145E49684611D56A72A38B64D")) to get test ads on this device.
[  +11 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device HD1901... (completed in 813ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +9 ms] Connected to _flutterView/0xb400007a314e7820.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on HD1901 is available at: http://127.0.0.1:59729/3dqpYvFZ89c=/
[   +1 ms] The Flutter DevTools debugger and profiler on HD1901 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:59729/3dqpYvFZ89c=/
[   +9 ms] E/rumana_porutha(  810): Attempt to load writable dex file: /data/user/0/com.techashonline.thirumana_porutham/app_pccache/5/D3993C68292D3C7E932B1CC97EF3BD39BDE8187B/pcam.jar
[   +1 ms] W/ziparchive(  810): Unable to open '/data/user/0/com.techashonline.thirumana_porutham/app_pccache/5/D3993C68292D3C7E932B1CC97EF3BD39BDE8187B/pcam.dm': No such file or directory
[  +23 ms] I/AudioManager(  810): In isSpeakerphoneOn(), calling application: com.techashonline.thirumana_porutham
[   +2 ms] D/AudioManagerExtImpl(  810): getStreamVolume packageName=com.techashonline.thirumana_porutham, index=30, streamType=3
[        ] W/ConnectionStatusConfig(  810): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.CACHE
[   +3 ms] D/AudioManagerExtImpl(  810): getStreamVolume packageName=com.techashonline.thirumana_porutham, index=0, streamType=2
[        ] W/Ads     (  810): Invoke Firebase method getInstance error.
[        ] W/Ads     (  810): The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date
[   +2 ms] I/Ads     (  810): JS: The jsLoaded GMSG has been sent (https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html:790)
[        ] I/chromium(  810): [INFO:CONSOLE(790)] "The jsLoaded GMSG has been sent", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html (790)
[        ] I/Quality (  810): Skipped: false 5 cost 94.07049 refreshRate 0 processName com.techashonline.thirumana_porutham
[  +13 ms] D/UserMessagingPlatform(  810): Stored info not exists: IDFA_freqCapNumViews
[  +18 ms] D/nativeloader(  810): Configuring clns-13 for other apk . target_sdk_version=33, uses_libraries=ALL, library_path=, permitted_path=/data:/mnt/expand
[        ] D/nativeloader(  810): Extending system_exposed_libraries:
libvraudio_client.qti.so:libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libSloganJni.oplus.so:libsuperNight_mtk.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:libqesdk_ndk_pla
tform.qti.so:liblistenjni.qti.so
[        ] W/AdWorker(Defaul(  810): type=1400 audit(0.0:343174): avc: granted { execute } for path="/data/data/com.techashonline.thirumana_porutham/app_pccache/5/D3993C68292D3C7E932B1CC97EF3BD39BDE8187B/pcam.jar" dev="dm-45"       
ino=1344749 scontext=u:r:untrusted_app:s0:c212,c263,c512,c768 tcontext=u:object_r:app_data_file:s0:c212,c263,c512,c768 tclass=file
[        ] I/Ads     (  810): HTTP timeout: 60000 milliseconds.
[        ] I/Quality (  810): Skipped: false 1 cost 28.495516 refreshRate 0 processName com.techashonline.thirumana_porutham
[        ] I/Ads     (  810): GMA Debug BEGIN
[  +10 ms] I/Ads     (  810): HTTP timeout: 60000 milliseconds.
[        ] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334747,"event":"onNetworkRequest","components":["network_request_93d025eb-7245-4db2-902b-6aa842d4d7e3"],"params":{"firstline":{"uri":"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/nati
ve_ads.html","verb":"GET"},"headers":[{"name":"sec-ch-ua","value":"\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Android
WebView\";v=\"122\""},{"name":"sec-ch-ua-mobile","value":"?1"},{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},{"nam
e":"Upgrade-Insecure-Requests","value":"1"},{"name":"sec-ch-ua-platform","value":"\"Android\""},{"name":"User-Agent","value":"Mozilla/5.0 (Linux; Android 12; HD1901 Build/SKQ1.211113.001; wv) AppleWebKit/537.36 (KHTML, like Gecko)  
Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36 (Mobile; afma-sdk-a-v240304999.240304000.1)"}]}}
[        ] I/Ads     (  810): GMA Debug FINISH
[        ] I/Ads     (  810): GMA Debug BEGIN
[        ] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334755,"event":"onNetworkRequest","components":["network_request_cc7ba9de-59ae-401e-8a75-6733ef6e60ec"],"params":{"firstline":{"uri":"https://googleads.g.doubleclick.net/getconfig/pubsetting?app_name=com.techasho
nline.thirumana_porutham&vnm=30000010&eid=318500618%2C318486317%2C318491267%2C318482031%2C318482079%2C318483611%2C318484141%2C318484497%2C318501517%2C318503149%2C318503826%2C318504752%2C318511100%2C318512573%2C318512763%2C318513741%
2C318514154%2C318513308%2C318513386&js=afma-sdk-a-v240304999.240304000.1&client=ca-app-pub-7152320266992965&admob_appcc=1620194814","verb":"GET"},"headers":[{"name":"sec-ch-ua","value":"\"Chromium\";v=\"122\",
\"Not(A:Brand\";v=\"24\", \"Android
WebView\";v=\"122\""},{"name":"sec-ch-ua-mobile","value":"?1"},{"name":"Accept","value":"*/*"},{"name":"sec-ch-ua-platform","value":"\"Android\""},{"name":"Referer","value":"https://googleads.g.doubleclick.net/mads/static/mad/sdk/na
tive/production/sdk-core-v40-impl.html"},{"name":"User-Agent","value":"Mozilla/5.0 (Linux; Android 12; HD1901 Build/SKQ1.211113.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36  
(Mobile; afma-sdk-a-v240304999.240304000.1)"}]}}
[   +1 ms] I/Ads     (  810): GMA Debug FINISH
[  +11 ms] W/Ads     (  810): Not retrying to fetch app settings
[  +25 ms] I/Ads     (  810): GMA Debug BEGIN
[        ] I/Ads     (  810): GMA Debug CONTENT
{"timestamp":1711078334799,"event":"onNetworkResponse","components":["network_request_93d025eb-7245-4db2-902b-6aa842d4d7e3"],"params":{"firstline":{"code":200},"headers":[{"name":null,"value":"HTTP/1.1 200
OK"},{"name":"Alt-Svc","value":"h3=\":443\"; ma=2592000,h3-29=\":443\";
ma=2592000"},{"name":"Server","value":"cafe"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"P3P","value":"policyref=\"https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml\", CP=\"CURa ADMa DEVa TAIo PSAo PSDo OUR  
IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR\""},{"name":"X-Android-Received-Millis","value":"1711078334798"},{"name":"Date","value":"Thu, 21 Mar 2024 16:29:27
GMT"},{"name":"X-Android-Selected-Protocol","value":"http/1.1"},{"name":"Cache-Control","value":"public,
max-age=86400"},{"name":"ETag","value":"6609160214934558157"},{"name":"Timing-Allow-Origin","value":"*"},{"name":"X-Android-Response-Source","value":"NETWORK
200"},{"name":"Vary","value":"Accept-Encoding"},{"name":"Cross-Origin-Resource-Policy","value":"cross-origin"},{"name":"Expires","value":"Fri, 22 Mar 2024 16:29:27
GMT"},{"name":"X-Android-Sent-Millis","value":"1711078334760"},{"name":"X-XSS-Protection","value":"0"},{"name":"Age","value":"39769"},{"name":"Content-Type","value":"text/html; charset=UTF-8"}]}}
[        ] I/Ads     (  810): GMA Debug FINISH
[  +53 ms] I/Ads     (  810): HTTP timeout: 60000 milliseconds.

Analyzing thirumana_porutham...                                         

warning - The include file 'package:flutter_lints/flutter.yaml' in 'C:\Users\admin\StudioProjects\thirumana_porutham\analysis_options.yaml' can't be found when analyzing 'C:\Users\admin\StudioProjects\thirumana_porutham' -
       analysis_options.yaml:10:10 - include_file_not_found
   info - The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/services.dart' - lib\pages\Databse\DBUtil.dart:3:8 - unnecessary_import
warning - The value of the local variable 'status' isn't used - lib\pages\MyHomePage.dart:34:12 - unused_local_variable
warning - Unused import: 'package:thirumana_porutham/Services/AdUtil.dart' - lib\pages\PorunthumNatchathirangal.dart:4:8 - unused_import
warning - The value of the field '_interstitialAd' isn't used - lib\pages\PorunthumNatchathirangal.dart:23:19 - unused_field
warning - Unused import: '../Services/AdUtil.dart' - lib\pages\PoruthamDetails.dart:5:8 - unused_import
warning - Unused import: 'package:thirumana_porutham/Services/AdUtil.dart' - lib\pages\PoruthamPaarka.dart:4:8 - unused_import
   info - The import of 'dart:ui' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\pages\SubaMugoorthaNatkal.dart:1:8 - unnecessary_import

8 issues found. (ran in 20.8s)

[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22621.3235], locale en-US)
    • Flutter version 3.19.4 on channel stable at D:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (28 hours ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\SDKs\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34009.444
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (4 available)
    • HD1901 (mobile)   • 870416f3 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.3235]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 123.0.6312.58
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 119.0.2151.97

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

</details>

**Comment by malandr2** [comment]
Hey @techashonline, can you share the network logs as a .chls file? It's a little hard to read as it's been included. Thanks!

**Comment by techashonline** [comment]
hi @malandr2 i am not using Charles Proxy to monitor network logs. I enabled Network tracing and watch the logs on android studio. Still i filtered only Information-level Ads output logs to logs.txt file. Kindly check the attached file. 
[logs.txt](https://github.com/googleads/googleads-mobile-flutter/files/14724859/logs.txt)

**Comment by techashonline** [comment]
@malandr2 I have created sample project and used your native_template_example. I am still able to reproduce the problem. Logs.txt for the example project is attached. Thank You.
[logs.txt](https://github.com/googleads/googleads-mobile-flutter/files/14730197/logs.txt)

**Comment by malandr2** [comment]
Hi @techashonline, thank your confirming you tested with the `native_template_example`. I used that example as well but was unable to replicate the behavior, I was only seeing one ad request at a time. 

Network tracing logs requests from the Google Mobile Ads SDK, but not _all_ requests are the ad request. If you filter the log using `/mads/gma?` then you'll only see the ad requests. Doing that, I only see one ad request at a time. Are you able to also observe this behavior?

**Comment by techashonline** [comment]
Hi @malandr2 I think i have taken all **onNetworkRequest** as ad requests. I filtered the logs using **/mads/gma?** and i found only one ad request is triggered for one load call for native ads. But If I load an interstitial ad I am able to found  **/mads/gma?**
in logs multiple times for single call. I have tested with your interstitial example also. Please check the logs.txt and confirm. Thank you.
[logs.txt](https://github.com/googleads/googleads-mobile-flutter/files/14751847/logs.txt)

**Comment by malandr2** [comment]
Hey @techashonline, I see what you're seeing but only one of them is the ad request. As a follow-up if you happen to see filtered requests like this, the `uri` with _dozens_ of parameters is the ad request. I edited my previous statement to better reflect this. As it stands, everything is working as intended. 

**AD REQUEST**
<img width="1308" alt="Screenshot 2024-03-26 at 10 37 47 AM" src="https://github.com/googleads/googleads-mobile-flutter/assets/5905170/0f40cc08-5779-4558-9c9c-df1906eea300">

**NOT THE AD REQUEST**
<img width="1279" alt="Screenshot 2024-03-26 at 10 37 54 AM" src="https://github.com/googleads/googleads-mobile-flutter/assets/5905170/7cf237e9-cdd9-4a66-a8a3-4b7981ff7dde">

**Comment by techashonline** [comment]
hi @malandr2 Thank you for make me understand this. I have checked the logs only one request is going for one load call. Now i close this issue.
