### ISSUE TITLE
 New instances of Banner Ads can trigger Ad Request within the recommended 60 seconds. 

### ISSUE THREAD

**Issue by Wenutz** [googleads/googleads-mobile-flutter#1037]
I have a custom BannerAd widget that is shown across multiple screens. When users navigate through the app, it can lead to frequent ad requests within just a few seconds. I am worried this will lead to invalid traffic violations or some other rule violation.

Admob supports state that:
 _**Also, if users navigate to and from pages with ads in an app over a short period of time, a new ad request should not be made sooner than the recommended 60 second rate.**_

The  **google_mobile_ads** package documentation doesn't seem to adress ad request frequency. So my question is: 
can we just stick an BannerAd widget like in the example provided in the tutorials in every page without worrying about the request frequency or do we have to take this into account and cap the frequency ourselves ?

I know it may seem like a stackoverflow question but I have seen this question unanswered across all platorm:
- it was asked on[ google support forum.](https://support.google.com/admob/thread/182289252/should-bannerad-load-be-requested-only-once-if-the-banner-ad-unit-is-set-to-refresh-flutter?hl=en).
- in [Google Mobile Ads SDK Developers group ](https://groups.google.com/g/google-admob-ads-sdk). Where the user was told to ask here.
- This question was also asked here in [December 2022 ](https://github.com/googleads/googleads-mobile-flutter/issues/721 )on this platform and went also unanswered. 

A proper answer will perhaps resolve  many of the unresolved violation for other users.

**Comment by malandr2** [comment]
Hey @Wenutz, I see [question](https://groups.google.com/g/google-admob-ads-sdk/c/oQZG8T42r4s/m/fPCjwtAfAgAJ) you're referring where the SDK forum referred you here. That question was back in 2022 prior to official support from Google Mobile Ads. As of 2023, the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) now supports Flutter queries such as this one. 

So to best triage your question, this would be better suited for the forum as it's more related to general implementation than anything specific to the Flutter plugin. Closing this out. Thanks!
