### ISSUE TITLE
New App Instance on Click with latest IMA SDK in the project

### ISSUE THREAD

**Issue by atrope** [googleads/googleads-mobile-flutter#1040]
## Plugin Version

v5

## Steps to Reproduce
In the provided `build.gradle` file located at `googleads-mobile-flutter/packages/google_mobile_ads/example/android/app/build.gradle`, include the line `implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.32.0'` within the dependencies section.

Proceed to launch the application as usual. Navigate to a banner ad example (such as anchored, inline, etc.) and interact with the banner by clicking on it.

Upon doing this, open the task manager. You will observe a new instance appearing as a black screen. Notably, this instance remains active even after the application has been terminated.
![image](https://github.com/googleads/googleads-mobile-flutter/assets/2945478/bae6f5e7-61f3-41f0-8f75-a300a6a7559d)

**Expected results:**  No other instances of the app opened.

**Actual results:**  Ghost instances of the app.

**Comment by malandr2** [comment]
Hi @atrope, 

I am able to reproduce in the Flutter example and I am _also_ able to reproduce this in our [Android Banner example project](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/BannerExample) which leads me to believe this is an Android issue and not specifically a Flutter `google_mobile_ads_plugin` issue. To properly triage this, the next step would be to create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk), feel free to include the link to this issue.

Closing this out. Thanks!

**Comment by atrope** [comment]
https://issuetracker.google.com/issues/331086936
