### ISSUE TITLE
Interstitial ads miss placed and cutt off with super bad user experience 

### ISSUE THREAD

**Issue by patolax** [googleads/googleads-mobile-flutter#1042]
### [REQUIRED] Step 1: Describe your environment
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)  
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.34)
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.3)
[√] VS Code, 64-bit edition (version 1.87.2)   
[√] Connected device (4 available)
[√] Network resources

## Plugin Version
 google_mobile_ads: ^5.0.0

Existed in 4.0 tried upgrading but no change.

### [REQUIRED] Step 2: Describe the problem
Interstitial ad getting cut off with bad user experience 
## Steps to Reproduce

Follow the guidelines https://developers.google.com/admob/flutter/quick-start
and integrate interstitial ads. Show the ad. This is no test mode or production mode.
Android version 13 and 10 I was able to recreate this.
The results are shown in the attached image.
The same problem exists with banner ads from time to time, where add get cut off.

**Expected results:** 
Miss-placed ads, bad user experience.
**Actual results:** 
Proper ad placement 

![Screenshot_20240329-222247 (1)](https://github.com/googleads/googleads-mobile-flutter/assets/29444156/b07b9677-7704-490c-892e-5ddffa09c5f3)

**Comment by malandr2** [comment]
Hi @patolax,

This looks like an issue with the ad itself and not the flutter plugin. Please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be properly addressed. Closing this out. Thanks!
