### ISSUE TITLE
test ads crash flutter app

### ISSUE THREAD

**Issue by Jibran111** [googleads/googleads-mobile-flutter#1043]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/flutter/quick-start),
   send your feedback by pressing the **Send Feedback** button at the top right of the
   documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

---

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by malandr2** [comment]
Closing this out. Please provide the appropriate information for us to debug. If there is crash, please provide steps to reproduce and a stack trace. Thanks!

**Comment by shahidhasan66ss** [comment]
> Closing this out. Please provide the appropriate information for us to debug. If there is crash, please provide steps to reproduce and a stack trace. Thanks!



My app crashes when resumed from the background after showing a Google AdMob Banner Ad. It works fine on app restart but crashes when the app is minimized and brought back to the foreground.

I’m using google_mobile_ads with WidgetsBindingObserver to handle lifecycle events, and disposing/reloading the ad when the app goes into the background and comes back.

Anyone know why this might happen or how to fix it?
