### ISSUE TITLE
[📚] Example app?

### ISSUE THREAD

**Issue by kollinmurphy** [googleads/googleads-mobile-flutter#107]
I had firebase admob ads fully implemented in my app, and with Flutter 2 I'm now trying to migrate over to googleads. I've followed the documentation, but I'm still having trouble displaying a simple banner. It seems like it will show sometimes, and other times it will give me an error saying that there's already an ad with that adId. I know I can figure this out eventually, but a simple example app would be very much appreciated. At https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter there's a sample app using the deprecated admob package. Perhaps that could be refactored to use the new googleads package.

Thanks!

**Comment by gabxap** [comment]
This one is a good guide. 

[https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#0](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#0)

**Comment by jjliu15** [comment]
The codelab shared above is a good reference. You can also look at the example app in the github repo:https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example
