### ISSUE TITLE
Deprecation warning in 5.1.0

### ISSUE THREAD

**Issue by under3415** [googleads/googleads-mobile-flutter#1089]
Hi
This is a continuation of https://github.com/googleads/googleads-mobile-flutter/issues/1036

One warning remains in 5.1.0:

.\pub.dev\google_mobile_ads-5.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java:31: warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated
.getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
^

**Comment by malandr2** [comment]
Thanks @under3415, this will be resolved in the next release

**Comment by malandr2** [comment]
Closing as this was resolved with #1092
