### ISSUE TITLE
Interstitial Ad Fails to Show Due to "Provided view controller is not being presented" Error

### ISSUE THREAD

**Issue by superwebarmy** [googleads/googleads-mobile-flutter#1091]
I'm trying to display an interstitial ad after the user selects an image or video from the gallery using the image_picker plugin. Here's the relevant code:

```
void pickFromGallery() async {
  ImagePicker imagePicker = ImagePicker();
  XFile? pickedVideo = await imagePicker.pickVideo(source: ImageSource.gallery);
  if (pickedVideo != null) {
    initialise(pickedVideo.path);
  }
}

void initialise(String path) async {
  if (interstitialAd != null) {
    interstitialAd!.fullScreenContentCallback =
        FullScreenContentCallback(
          onAdDismissedFullScreenContent: (ad) {
            // Perform some operation
          },
          onAdFailedToShowFullScreenContent: (ad, adError) {
            print(adError);
          },
        );

    await interstitialAd!.show();
  } else {
    // Perform some operation
  }
}

```

However, when I try to show the interstitial ad using interstitialAd!.show();, I'm getting the following error:

```
error(code: 17, domain: com.google.admob, message: the provided view controller is not being presented.)

```

**Comment by malandr2** [comment]
hi @superwebarmy, the error you are seeing means there is a view controller that is already being presented. Without knowing much about the `image_picker` picker plugin, is the plugin presenting a separate screen to pick the images from?

Make sure any views that are presented from that class are dismissed before showing the interstitial ad.

**Comment by superwebarmy** [comment]
hi @malandr2, image_picker opens up the gallery of device from where user pick/select the media file, on selecting that, gallery disappears and at this moment, I'm trying to display an interstitial ad

**Comment by superwebarmy** [comment]
@malandr2 you were right! the culprit lies in Image picker, the image picker plugin doesn't dismiss the view controller immediately, it takes 1-2 seconds to get it dismissed
