### ISSUE TITLE
Optimize initialization and ad loading

### ISSUE THREAD

**Issue by marcellocamara** [googleads/googleads-mobile-flutter#1098]
Do this plugin have plans to implement both Optimize initialization and ad loading declarations on manifest.xml file ? Asking because we are getting warnings from the play console to manually insert this on the apps. I imagine if this could be added into [this plugin manifest](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/android/src/main/AndroidManifest.xml) file.

---

## Plugin Version

`google_mobile_ads: ^5.1.0`

## Steps to Reproduce

Just use the package to display ads in production.

**Expected results:** 

No ANRs, neither SDK provider help notes/advices

**Actual results:**

The SDK provider added a note to help you understand and avoid this ANR:
![Captura de Tela 2024-05-20 às 09 34 22](https://github.com/googleads/googleads-mobile-flutter/assets/18273071/0c5a4cab-2efe-465d-ad7e-eba03223df46)

The documentation: 
https://developers.google.com/admob/android/optimize-initialization#update_your_manifest_file

```xml
<manifest>
  ...
  <application>
      ...
      <meta-data
          android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION"
          android:value="true"/>
      <meta-data
          android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING"
          android:value="true"/>
  </application>
</manifest>
```

**Comment by malandr2** [comment]
Hi @marcellocamara the optimize initialization and ad loading is specifically for your `AndroidManifest.xml` file. The plugin never explicitly calls initialize that is done from your code. Follow the [guide](https://developers.google.com/admob/android/optimize-initialization) to include for your Android project. It is optional to include but recommended.

**Comment by marcellocamara** [comment]
> Follow the [guide](https://developers.google.com/admob/android/optimize-initialization) to include for your Android project. It is optional to include but recommended.

@malandr2 
I'm publishing my apps, with this implementation, to see if this Play Console ANRs disappears 👍🏻

**Comment by malandr2** [comment]
If the issue still persists you can create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be properly triaged

**Comment by MaherSafadii** [comment]
> > Follow the [guide](https://developers.google.com/admob/android/optimize-initialization) to include for your Android project. It is optional to include but recommended.
> 
> [@malandr2](https://github.com/malandr2) I'm publishing my apps, with this implementation, to see if this Play Console ANRs disappears 👍🏻

any update after shipping with them?

**Comment by marcellocamara** [comment]
> any update after shipping with them?

I removed the manual tags in manifest.xml months ago, and I haven't noticed this specific issue anymore. I didn't find this specific ANR on Play Console.
