### ISSUE TITLE
Using the plugin exclusively on iOS without modifying AndroidManifest

### ISSUE THREAD

**Issue by br-programmer** [googleads/googleads-mobile-flutter#1099]
Hi,

I would like to know if it's possible to use the Google Ads plugin for Flutter exclusively on the iOS platform without having to modify the `AndroidManifest.xml` file for the Android project. Currently, the plugin requires changes in both manifests. Specifically, these are the modifications the plugin asks for on Android:

1. Adding permissions:
   ```xml
   <uses-permission android:name="android.permission.INTERNET"/>
   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
   ```
2. Including the AdMob application ID in the `AndroidManifest.xml`:
   ```xml
   <meta-data
       android:name="com.google.android.gms.ads.APPLICATION_ID"
       android:value="YOUR_ADMOB_APP_ID"/>
   ```

My goal is to avoid these changes and still prevent the Android app from breaking or blocking. Is there any configuration or workaround that allows this?

Thank you for your assistance.

---

**Comment by malandr2** [comment]
Hi @br-programmer it is not possible to run an Android project with the google_mobile_ads flutter plugin installed and not include the necessary installation materials for Android. Theoretically you would have to integrate the iOS Google Mobile Ads  SDK and not the Flutter plugin to achieve this

**Comment by Phlphat746** [comment]
คุณต้องใช้ให้ถูกต้องสิ่ครับ
