### ISSUE TITLE
[Android] Stuck installing the app

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#1102]
New project and only this package installed using latest version. First time, it suggests to manually specify `minSdkVersion 21`.
After this change, it gets stuck when running the app:

> Flutter: Installing build\app\outputs\flutter-apk\app-debug.apk...

https://github.com/erperejildo/lint_error

**Plugin Version**
`google_mobile_ads: ^5.1.0`

**Steps to reproduce**
Clone project and run on Android emulator

**Comment by erperejildo** [comment]
I just found the issue. The id in `AndroidManifest` was not added. For some reason, this error didn't appear when running the app in emulator but it did when using a real device instead.

**Comment by CodeRebirth** [comment]
> I just found the issue. The id in `AndroidManifest` was not added. For some reason, this error didn't appear when running the app in emulator but it did when using a real device instead.

Which Id we need to add? Please tell.
