### ISSUE TITLE
native ad is getting overlap on banner ad when banner and native ad displayed in single page.

### ISSUE THREAD

**Issue by dev3-tech** [googleads/googleads-mobile-flutter#1111]
google_mobile_ads: ^5.1.0

When a banner ad and a native ad are placed on the same screen, the banner ad loads and displays normally at first. However, when the native ad loads on same page and displays, it also overlaps the banner ad. The overlapping view is automatically removed when we tap on the screen or when the banner reloads automatically.

https://github.com/googleads/googleads-mobile-flutter/assets/152849772/913ba6ab-1f28-461b-95c4-c41edc1022c0

https://github.com/googleads/googleads-mobile-flutter/assets/152849772/dfbb611b-1053-4f1a-9f06-a42561be9ff9

[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-x64, locale en-IN)
    • Flutter version 3.19.6 on channel stable at /Applications/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (8 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mac007/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mac007/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by malandr2** [comment]
Hi @dev3-tech, do you mind sharing a minimum reproducible sample that reproduces that issue? From there we can try to replicate and debug. Thanks!

**Comment by dev3-tech** [comment]
i regenerated this issue and attaching sample code.
[ads_sample.zip](https://github.com/user-attachments/files/16569152/ads_sample.zip)

**Comment by malandr2** [comment]
Hi @dev3-tech, I'm unable to reproduce what you're experiencing the sample app. Are there are specific steps to reproduce? I'm testing on an Android Pixel 4 API 34 and just opening the secondary screen. 

![Screenshot_1725375155](https://github.com/user-attachments/assets/8820fc08-51d4-4888-8133-ce00c514f54f)
