### ISSUE TITLE
[Rewarded Ad] When using `UnityAdapter` `onUserEarnedReward` RewardItem has an empty string type

### ISSUE THREAD

**Issue by phamconganh** [googleads/googleads-mobile-flutter#1113]
## Plugin Version

`google_mobile_ads: ^5.1.0`

## Steps to Reproduce

1. Request Reward ad with setting `Single ad source test` enable, then choose `Unity Ads`.
2. `onUserEarnedReward` RewardItem has an empty string type

**Comment by malandr2** [comment]
Hi @phamconganh, this is more of a problem with the `Unity Ads` adapter than the `google_mobile_ads` SDK. If you'd like you can create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) to have the issue properly triaged. To help, please include a sample application in the new thread to demonstrate your issue.

Closing this out. Thanks!
