### ISSUE TITLE
Does it support dynamic app IDs?

### ISSUE THREAD

**Issue by huythao99** [googleads/googleads-mobile-flutter#1114]
## Plugin Version

ad sdk: 5.1.0 flutter:3.19.1

## Steps to Reproduce
Hello,
The app I'm currently working on has various product flavors corresponding to different countries. This means my app will have more than one app_id. However, based on the documentation, it seems that the app_id can only be filled in the AndroidManifet.xml (android) and Info.plist(ios)

So, does it support dynamic app IDs, or is there a possibility to make it dynamic?

</details>

**Comment by malandr2** [comment]
Hi @huythao99, at this time we do not support dynamic app ids.
