### ISSUE TITLE
Admob mediation with meta ads failing - Flutter

### ISSUE THREAD

**Issue by Jaydeep-vasan** [googleads/googleads-mobile-flutter#1117]
Hello There, @LTPhantom @malandr2 

I've been trying to implement google admob with meta mediation setup in my flutter project, but it is not working in my case.

Following is my flutter code

```
InitializationStatus initializationStatus = await MobileAds.instance.initialize();
    initializationStatus.adapterStatuses.forEach((key, value) {
      debugPrint('Adapter status for $key: ${value.state.toString()}');
    });
    if (kDebugMode) {
      MobileAds.instance
          .updateRequestConfiguration(RequestConfiguration(testDeviceIds: [
        'CE62E3187ACE24520024C76D1BGFHKM',
      ]));
    }

    // Initialise Facebook Audience Network SDK.
    FacebookAudienceNetwork.init(
      testingId: 'f6280961-0f66-410d-b878-f77ac9d47e45', 
    );
```

Following is my pubspec.yaml file

 ```
 gma_mediation_meta: ^1.0.0
  google_mobile_ads: ^5.0.0
facebook_audience_network: ^1.0.1
```

Following is my android.manifest file content

```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-My-App-Id" />

```

I'm testing mediation ads in test mode for admob and meta ad network, But I'm only getting admob test ads. Following is my mediation network status,

```
Adapter status for com.google.android.gms.ads.MobileAds: AdapterInitializationState.ready
I/flutter (21702): Adapter status for com.google.ads.mediation.facebook.FacebookMediationAdapter: AdapterInitializationState.
```

I have created ad unit for my app todo 1 banner ad and 1 native add in admob panel

Then i created a fb property todo app and there i created  1 banner ad and 1 native ad

Then in admob panel ui mediation setup, I've created a native ad mediation group and attached bidding and waterfall ad placements of facebook audience network.

But still when i try to load my banner ad widget, everytime I'm getting only admob ads. No fb ads are loading through mediation group, even though in admob waterfall panel i've setup ecpm to 0.1$

Can anyone please let me know what I'm missing on this?

Thanks

**Comment by malandr2** [comment]
Hi @Jaydeep-vasan, you should launch ad inspector and turn on [Single ad source testing](https://developers.google.com/admob/flutter/ad-inspector#single_ad_source_testing) to isolate _only_ fb ads to diagnose your issue.

If you are still having issues you should create a case in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) as the Flutter plugins do not control what ads get served. Closing this out. Thanks!
