### ISSUE TITLE
I did add "gma_mediation_pangle" package -> The 'Pods-Runner' target has transitive dependencies that include statically linked binaries:

### ISSUE THREAD

**Issue by jtaxiexpress** [googleads/googleads-mobile-flutter#1118]
#### package version
```
  google_mobile_ads: ^5.1.0
  gma_mediation_pangle: ^1.1.0
```

#### Flutter doctor
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources
```

### [REQUIRED] Step 2: Describe the problem

Flutter gave me this error .

>[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: ({{fluter project"s directory}}/ios/Pods/GoogleMobileAdsMediationPangle/PangleAdapter-5.9.0.7.0/PangleAdapter.xcframework)

## Steps to Reproduce

1. Run `cd ios `.
2. Run `pod install`.

**Comment by malandr2** [comment]
Hey @jtaxiexpress, have you tried any of the solutions from this [StackOverflow thread](https://stackoverflow.com/questions/50306019/flutter-cocoapods-the-pods-runner-target-has-transitive-dependencies-that-inc). Looks similar to your issue

**Comment by jtaxiexpress** [comment]
> Hey @jtaxiexpress, have you tried any of the solutions from this [StackOverflow thread](https://stackoverflow.com/questions/50306019/flutter-cocoapods-the-pods-runner-target-has-transitive-dependencies-that-inc). Looks similar to your issue

All of those things did not work.

**Comment by jtaxiexpress** [comment]
I did add " :linkage => :static" on use_frameworks!
Then I t works 

```
target 'Runner' do
  use_frameworks! :linkage => :static # I did add  ":linkage => :static"
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```

**Comment by felipecastrosales** [comment]
hey, did you manage to mediate? I'm still having problems. Currently it's: `Library 'BURelyFoundationGlobalAFN' not found`; I don't know what I need do to work.
