### ISSUE TITLE
Problem kotlin version i use last version flutter

### ISSUE THREAD

**Issue by habe90** [googleads/googleads-mobile-flutter#1123]
PS F:\tasko\task_management_app> flutter build apk

Note: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 2600 bytes (99.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Running Gradle task 'assembleRelease'...     y

**Comment by malandr2** [comment]
Hi @habe90, this looks like log output from the Flutter console. For the 5.1.0 deprecation warning log, that's been [resolved](https://github.com/googleads/googleads-mobile-flutter/issues/1089) and will be observed in the next release.
