### ISSUE TITLE
No implementation found for method loadBannerAd on channel plugins.flutter.io/google_mobile_ads

### ISSUE THREAD

**Issue by yashanghan22** [googleads/googleads-mobile-flutter#1124]
## Plugin Version
google_mobile_ads: 5.1.0
flutter: 3.22.2
dart: 3.4.3

### [REQUIRED] Step 2: Describe the problem
I initialized the Mobile SDK and displayed a banner widget. However, when I call the load function, it throws a MissingPluginException. This means it can't find the method to show ads using both testing and real IDs.

I've tried cleaning the project and pub cache many times, but it didn't work.

**Expected results:** 
it should show the Ads without any error.

**Actual results:** 
The app is showing a MissingPluginException error because it can't find the method for the method channel, even after trying to fix it by cleaning the pub cache and running flutter clean. The error still appears.

<details>
  <summary>Logs</summary>

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method loadBannerAd on channel plugins.flutter.io/google_mobile_ads)
E/flutter (13537): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (13537): <asynchronous suspension>
E/flutter (13537): #1      BannerAd.load (package:google_mobile_ads/src/ad_containers.dart:891:5)
E/flutter (13537): <asynchronous suspension>
E/flutter (13537): #2      _HomePageState.initState.<anonymous closure> (package:edit_image/home_page.dart:59:11)
E/flutter (13537): <asynchronous suspension>
```

</details>

**Comment by malandr2** [comment]
Hi @yashanghan22 there is no `loadBannerAd` method on the Flutter plugin [BannerAd](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/BannerAd-class.html) class. Please see our [Banner guide](https://developers.google.com/admob/flutter/banner) for an example implementation.

**Comment by yashanghan22** [comment]
@malandr2  code of the BannerAd is shown below, let me know if it contains any issue.

```
late BannerAd banner;
  ValueNotifier<bool> showBanner = ValueNotifier(false);

  @override
  void initState() {
    super.initState();
    try {
      banner = BannerAd(
          size: AdSize(width: double.maxFinite.toInt(), height: 50),
          adUnitId: "ca-app-pub-3940256099942544/6300978111",
          request: const AdRequest(),
          // request: const AdManagerAdRequest(),
          listener: BannerAdListener(
            onAdFailedToLoad: (ad, e) {
              log('Add Failed to load ${ad.responseInfo} - $e');
            },
            onAdLoaded: (ad) {
              showBanner.value = true;
              log('Add Loaded${ad.responseInfo}');
            },
          ));
      Future.delayed(
        const Duration(milliseconds: 0),
        () async {
          await banner.load();
        },
      );
    } catch (e) {
      log('Banner Ad error:$e');
    }
  }
```
