### ISSUE TITLE
Admob mediation Ironsource not compiling

### ISSUE THREAD

**Issue by dvlprtoastguyz** [googleads/googleads-mobile-flutter#1133]
Hey There

I've been trying to test mediation flow using flutter, 

So I've just added following flutter dependencies for mediation in my project

  ```
  google_mobile_ads: ^5.1.0
  gma_mediation_applovin: ^1.1.0
  gma_mediation_inmobi: ^1.0.0
  gma_mediation_ironsource: ^1.0.0
  gma_mediation_meta: ^1.0.1
  gma_mediation_unity: ^1.0.0
```

But after adding those dependencies, I'm getting following error. I'm using flutter SDK 3.22.2 and Dart SDK Version 3.4.3 

```
What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.ironsource.sdk:mediationsdk:8.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/ironsource/sdk/mediationsdk/8.0.0/mediationsdk-8.0.0.pom
       - https://repo.maven.apache.org/maven2/com/ironsource/sdk/mediationsdk/8.0.0/mediationsdk-8.0.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/ironsource/sdk/mediationsdk/8.0.0/mediationsdk-8.0.0.pom
     Required by:
         project :app > project :gma_mediation_ironsource > com.google.ads.mediation:ironsource:8.0.0.0
```

Those are the latest flutter packages and version, still it's not working which it should.

Can you investigate and fix this issue for ironsource package at least? 

Thanks

**Comment by malandr2** [comment]
Hi @dvlprtoastguyz, this appears to be an issue with `gma_mediation_ironsource: ^1.0.0`. I can reproduce your issue. I've escalated this to engineering to begin the troubleshooting process.

**Comment by malandr2** [comment]
Hi @dvlprtoastguyz, have you followed this step for Android? https://developers.google.com/admob/flutter/mediation/ironsource#integration_through_pubdev

**Comment by malandr2** [comment]
Closing this out as solution as been provided previous response

**Comment by ntdogmm** [comment]
ironsource has a lot of dependency issues,  i wonder if they even bother testing their sdk and all the staffs,
