### ISSUE TITLE
RewardedAd' onAdFailedToShowFullScreenContent: AdError(code: 17, domain: com.google.admob, message: The provided view controller is not being presented.)

### ISSUE THREAD

**Issue by webby-genius** [googleads/googleads-mobile-flutter#1134]
1st time ads show perfectly but 2nd time get error (RewardedAd' onAdFailedToShowFullScreenContent: AdError(code: 17, domain: com.google.admob, message: The provided view controller is not being presented.)) 
then 3rd time ads show perfectly and it's sequent continue..
it's issue generate in iOS device only. android device wok perfectly 

google_mobile_ads: ^5.1.0
3.19.6 -> Flutter SDK
3.3.4 ->  (Flutter)Dart SDK

this is my code 
  
static RewardedAd? rewardedAd;
  static int numRewardedLoadAttempts = 0;
  static int maxFailedLoadAttempts = 3;
  static int life = 0; 

 void createRewardedAd() {
    RewardedAd.load(
      adUnitId: AdHelper.rewardedAdUnitId,
      request: AdRequest(),
      rewardedAdLoadCallback: RewardedAdLoadCallback(
        onAdLoaded: (RewardedAd ad) {
          debugPrint('$ad loaded....Done');
          rewardedAd = ad;
          numRewardedLoadAttempts = 0;
        },
        onAdFailedToLoad: (LoadAdError error) {
          debugPrint('RewardedAd failed to load: $error');
          rewardedAd = null;
          numRewardedLoadAttempts += 1;
          if (numRewardedLoadAttempts < maxFailedLoadAttempts) {
            createRewardedAd();
          }
        },
      ),
    );
  }

 void showRewardedOneTimeAd({void Function(RewardedAd)? onAdDismissedFullScreenContent}) {
    if (rewardedAd == null) {
      debugPrint('Warning: attempt to show rewarded before loaded.');
      // Optionally, show a message to the user that the ad is not ready yet.
      return;
    }

    rewardedAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (RewardedAd ad) {
        debugPrint('ad onAdShowedFullScreenContent.');
        Future.delayed(
          const Duration(seconds: 3),
          () {
            debugPrint("---------- AD CREATE SUCCESS ------------");
            createRewardedAd();
          },
        );
      },
      onAdDismissedFullScreenContent: onAdDismissedFullScreenContent ??
          (RewardedAd ad) {
            debugPrint('$ad onAdDismissedFullScreenContent.');
            ad.dispose();
            // Optionally, load a new ad after the current one is dismissed.
            debugPrint("isShowAgain 000000--->>>>> $isShowAgain");
          },
      onAdFailedToShowFullScreenContent: (RewardedAd ad, AdError error) {
        debugPrint('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        createRewardedAd();
      },
    );

    rewardedAd!.setImmersiveMode(true);
    rewardedAd!.show(onUserEarnedReward: (AdWithoutView ad, RewardItem reward) {
      life += 1;
      debugPrint('User earned reward: ${reward.amount} ${reward.type}');
    });
    rewardedAd = null;
  }

**Comment by malandr2** [comment]
Hi @webby-genius, this code snippet looks fine in regards to your error. "The provided view controller is not being presented" error happens when the provided view controller view's window is `nil`. Can you please share a minimal, reproducible example of your issue so we can take a closer look? Thanks

**Comment by webby-genius** [comment]
RewardedeAdsWidget().showRewardedOneTimeAd(
                              onAdDismissedFullScreenContent: (RewardedAd ad) async {
                                ad.dispose();
                                await RewardedeAdsWidget().createRewardedAd();
                                      RewardedeAdsWidget().showRewardedOneTimeAd(
                                        onAdDismissedFullScreenContent: (RewardedAd ad) async {
                                          ad.dispose();
                                          await RewardedeAdsWidget().createRewardedAd();
                                        },
                                      );
                              },
                            );
![Screenshot 2024-07-17 at 9 53 36 AM](https://github.com/user-attachments/assets/40d94752-9657-45e8-aa1b-8e6ac4f26d76)

**Comment by webby-genius** [comment]
i need to rewarded ad show back to back 2 times and it's working fine in android device but in iOS device i found upper error when 2nd time ad show  and this (2nd ad call) onAdDismissedFullScreenContent event as i show above code

**Comment by malandr2** [comment]
Hi @webby-genius, the error you are experiencing is iOS-only so it is expected to work on Android. It also against policy to serve back-to-back rewarded ads. See #2 of [implementation requirements](https://support.google.com/admob/answer/7313578#implementation-requirements). You can only serve rewarded ads after a user has opted in to be served that particular ad. It's recommended to update your implementation and in doing so, you will avoid this error
