### ISSUE TITLE
Call `MobileAds.initialize` on background thread

### ISSUE THREAD

**Issue by blaugold** [googleads/googleads-mobile-flutter#1135]
The [Google Ads team now recommends](https://ads-developers.googleblog.com/2024/07/reduce-anrs-when-implementing-mobile-ads.html) calling `MobileAds.initialize` on a background thread to avoid ANRs.

Currently, this Plugin calls `MobileAds.initialize` on the UI thread.

https://github.com/googleads/googleads-mobile-flutter/blob/8e0834ee7f9b8f0ac1b886c5b3cae8937835c605/packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/GoogleMobileAdsPlugin.java#L349

https://github.com/googleads/googleads-mobile-flutter/blob/8e0834ee7f9b8f0ac1b886c5b3cae8937835c605/packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterMobileAdsWrapper.java#L39

**Comment by malandr2** [comment]
Hi @blaugold, thanks for flagging. I've shared this with engineering to determine next steps.

**Comment by Gilianp** [comment]
Is there any workaround we can do on the flutter side while this lib is not updated? Can we call `MobileAds.initialize` in another Isolate safely?

**Comment by malandr2** [comment]
Hi @Gilianp, we have a PR in the works https://github.com/googleads/googleads-mobile-flutter/pull/1165 that will be included in the next version. Please see until it's submitted

**Comment by Gilianp** [comment]
> Hi @Gilianp, we have a PR in the works #1165 that will be included in the next version. Please see until it's submitted

Thanks @malandr2 , I will wait the next update!

**Comment by marcellocamara** [comment]
I saw that this is implemented on the example folder:

```XML
<meta-data
    android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING"
    android:value="true" />
```
https://github.com/googleads/googleads-mobile-flutter/pull/1172/files#diff-ff9e788ea8dece69ea4d0ca791b99ba327608e161b3f5b4aa0c94245e3012652

This shouldn't be added into the plugin android manifest too ?
Otherwise everyone will have to implement this manually.

**Comment by malandr2** [comment]
Hi @marcellocamara, those flags are optional. They are needed if you're not calling `MobileAds.initialize` on a background thread. When the `google_mobile_ads` plugin adds the background thread functionality, these flags will no longer be needed in our samples. See https://developers.google.com/admob/android/optimize-initialization#update_your_manifest_file for more details

**Comment by malandr2** [comment]
This has been resolved in https://github.com/googleads/googleads-mobile-flutter/pull/1179 and will be included in the next release `.5.2.0`

**Comment by peterweb2005** [comment]
@LTPhantom thanks
is that, seems there is `InitializationStatus` return, or related,
so the (my) app shouldn't await `MobileAds.instance.initialize()`?
thanks
