### ISSUE TITLE
Facebook Meta unable to add Admob mediation

### ISSUE THREAD

**Issue by parmeetmaster** [googleads/googleads-mobile-flutter#1137]
My App is getting crashed

W/FirebaseCrashlytics(25475): Timeout exceeded while awaiting app exception callback from Analytics listener.
E/AndroidRuntime(25475): FATAL EXCEPTION: main
E/AndroidRuntime(25475): Process: com.tv.animetv, PID: 25475
E/AndroidRuntime(25475): java.lang.NoSuchMethodError: No virtual method setRequestAgent(Ljava/lang/String;)Lcom/google/android/gms/ads/AdRequest$Builder; in class Lcom/google/android/gms/ads/AdRequest$Builder; or its super classes (declaration of 'com.google.android.gms.ads.AdRequest$Builder' appears in /data/app/~~rLD1Ogt5I7WUPA6yuy43nA==/com.tv.animetv-sY8MN-jFoDoK7B8yaWxqNQ==/base.apk!classes9.dex)
E/AndroidRuntime(25475): 	at io.flutter.plugins.googlemobileads.FlutterAdRequest.updateAdRequestBuilder(FlutterAdRequest.java:235)
E/AndroidRuntime(25475): 	at io.flutter.plugins.googlemobileads.FlutterAdRequest.asAdRequest(FlutterAdRequest.java:240)
E/AndroidRuntime(25475): 	at io.flutter.plugins.googlemobileads.FlutterNativeAd.load(FlutterNativeAd.java:230)
E/AndroidRuntime(25475): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:427)
E/AndroidRuntime(25475): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(25475): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(25475): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(25475): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(25475): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(25475): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25475): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(25475): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(25475): 	at android.app.ActivityThread.main(ActivityThread.java:8377)
E/AndroidRuntime(25475): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(25475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Gradle Files are :**
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
// Add this line

//changes ndk version and ndk varients changes

android {
    compileSdkVersion 34
   // ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

   signingConfigs {
        release {
            storeFile file("animekill_key.jks")
            storePassword "asd1236547899"
            keyAlias "key0"
            keyPassword "asd1236547899"
        }
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://develop
        //  er.android.com/studio/build/application-id.html).
        applicationId "com.tv.animetv"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            ndk {
              //  abiFilters 'armeabi-v7a','arm64-v8a','x86_64'
                /*
                    abiFilters "armeabi", "x86", "armeabi-v7a","x86_64", "mips",
                    "mips64","arm64-v8a"
                * */
                //  abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            }
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
    buildFeatures {
        viewBinding true
    }
}

flutter {
    source '../..'
}

repositories {
    maven {
        name "Chartboost Mediation’s maven repo"
        url "https://cboost.jfrog.io/artifactory/chartboost-mediation"
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
  //   implementation 'com.google.android.gms:play-services-ads:23.2.0'
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
    implementation("com.google.ads.mediation:facebook:6.17.0.0")
    // implementation 'com.google.ads.mediation:adcolony:4.8.0.2'
   // implementation 'com.google.ads.mediation:vungle:6.12.1.1'
    //implementation 'com.google.ads.mediation:facebook:6.16.0.0'
    //implementation "androidx.activity:activity:1.8.0-alpha04"

}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.firebase.crashlytics'`

**Plugin Files:**
`name: animekillapp2023
description: Watch Latest anime free at anime tv
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.84+84

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.2
  injectable: ^2.3.0
  flutter_riverpod: ^2.3.10
  flutter_gen: ^5.3.1
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.26.0
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17
  firebase_messaging: ^14.7.18
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  dropdown_button2: ^2.3.9
  json_serializable: ^6.7.1
  #beamer: ^1.5.4
  #flex_color_scheme: ^7.0.5
  url_strategy: ^0.2.0
  another_flushbar: ^1.12.30
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.14
  pull_to_refresh_flutter3: ^2.0.1
  firebase_performance: ^0.9.2+5
  open_settings_plus: ^0.1.0
  app_settings: ^5.0.0
  flutter_email_sender: ^6.0.1
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  connectivity_plus: ^4.0.2
  collection: ^1.18.0
  package_info_plus: ^4.1.0
  flutter_spinkit: ^5.2.0
  logger: ^2.0.2
  flutter_screenutil: ^5.9.0
  sembast: ^3.5.0+1
  shared_preferences: ^2.2.1
  auto_size_text: ^3.0.0
  toggle_switch: ^2.1.0
  in_app_review: ^2.0.8
  sms_autofill: ^2.3.0
  dio_smart_retry: ^6.0.0
  sign_button: ^2.0.6
  google_sign_in: ^6.1.5
  device_info_plus: ^9.1.0
 # geolocator: ^10.1.0
  #location: ^5.0.3
  android_id: ^0.3.6
  visibility_detector: ^0.4.0+2
  flutter_local_notifications: ^16.3.0
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.19.0
  hexcolor:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  #pretty_dio_logger: ^1.3.1
  talker_dio_logger: ^2.3.3
  injectable_generator: ^2.4.0
  talker_logger: ^3.1.0

dependency_overrides:
  build: ^2.4.0
#  http: ^1.0.0
  file: ^7.0.0
  collection: ^1.17.2
  flutter_gen_core: 5.3.1
  analyzer: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/pngs/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/gifs/
  #  - assets/images/svgs/

flutter_gen:
  output: lib/constants/
  # Optional
  line_length: 80
  colors:
    inputs:
      - assets/colors/color.xml
      - assets/colors/text_colors.xml
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by malandr2** [comment]
Hi @parmeetmaster can you please create a new ticket that is easier to read. Please only provide pertinent information such as the stack and trace and also please provide reproducible steps (if you haven't already)
