### ISSUE TITLE
Admob email asked to upgrade gma sdk for android and ios

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#1139]
as title

"必須更新至 GMA SDK 11.3.0 (iOS) 及 23.2.0 (Android) 版本"

**Comment by malandr2** [comment]
Hi @peterweb2005, this feels like something to be raised in the [AdMob developers form](https://groups.google.com/g/google-admob-ads-sdk)

Closing this out . Thanks!

**Comment by peterweb2005** [comment]
@malandr2 no, now version
5.0.0 
Updates GMA iOS dependency to 11.2.0
Updates GMA Android dependency to 23.0.0

so should bump sdk

**Comment by kaya-lab2ai** [comment]
Hi. I got that email too. 
It says that if you use admob in integration with other google services like firebase, you need to update the GMA sdk version to ios(11.3.0), android(23.2.0). 
I think you should update the GMA sdk for android and ios by yourself, not Admob developer. 
```
//googleads-mobile-flutter/packages/google_mobile_ads/android/build.gradle
 api 'com.google.android.gms:play-services-ads:23.0.0' <<update to 23.2.0
 
//packages/google_mobile_ads/ios/google_mobile_ads.podspec
 s.dependency 'Google-Mobile-Ads-SDK','~> 11.2.0' <<update to 11.3.0
 
```
Please update it for users who use admob in integration with other Google services. 
Thanks .
