### ISSUE TITLE
NativeAdError, No NativeAdFactory with id: listTile or nativeTemplateStyle, null, null

### ISSUE THREAD

**Issue by vidhi002** [googleads/googleads-mobile-flutter#1141]
PlatformException(NativeAdError, No NativeAdFactory with id: listTile or nativeTemplateStyle, null, null)
I/flutter (13445): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (13445): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (13445): <asynchronous suspension>
I/flutter (13445): #2      NativeAd.load (package:google_mobile_ads/src/ad_containers.dart:1070:5)
I/flutter (13445): <asynchronous suspension>

**Comment by malandr2** [comment]
HI @vidhi002, can you please create an issue with the information stubbed in the `Bug Report` section so we can begin the troubleshooting process. Thanks
