### ISSUE TITLE
when i used rectangular banner ads im getting frame drop Error in console 

### ISSUE THREAD

**Issue by Roshan-pcy** [googleads/googleads-mobile-flutter#1142]
---

  im using vs code for flutter App development

  plugin version is google_mobile_ads: ^5.1.0

### [REQUIRED] Step 2:  when im using banner ad in 300x250  size banner ad when its load that its showing frame drop issue

each time reload banner ads frame drop issue

 
<img width="705" alt="image" src="https://github.com/user-attachments/assets/8a79c61e-081e-4471-ab33-903dd0d61b30">

**Comment by malandr2** [comment]
Hi @Roshan-pcy, see #954 and specicically the linked comment https://github.com/flutter/flutter/issues/104268#issuecomment-1134964433 in which the Flutter team mentions the error is not something to be worried about

**Comment by Roshan-pcy** [comment]
ok thanks

**Comment by eneugut** [comment]
Understood that it's nothing to worry about, but it's clogging up my console with hundreds of messages. Is there a way to disable the error messages at the very least?
