### ISSUE TITLE
When showing Collapsible Banner at the same time as using the device's keyboard, the keyboard is behind the ad

### ISSUE THREAD

**Issue by AnhPhon** [googleads/googleads-mobile-flutter#1143]
- google_mobile_ads: ^5.1.0
- Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-VN)
- Dart version 3.4.1
- DevTools version 2.34.3

When showing Collapsible Banner at the same time as using the device's keyboard, the keyboard is behind the ad.
How to make the device's keyboard always appear at the top.

I tested on some real devices but still got the error.

<img width="500" alt="Screenshot 2024-07-23 at 16 06 05" src="https://github.com/user-attachments/assets/ebe295f3-4883-4dd4-b626-cdfb2af3a78e">

**Comment by malandr2** [comment]
Hi @AnhPhon, thanks for flagging. I tested this with our [Android Banner Example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/BannerExample) on Android Pixel 4 and was also able to replicate the issue you are experiencing. 

This leads me to believe it is not an issue that the flutter plugin can resolve but rather more associated with the Android platform. Please start a thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for your issue to be properly triaged. Thanks!

![Screenshot_1721744216](https://github.com/user-attachments/assets/b17fd892-a959-49b9-a333-104c20116cca)

**Comment by AnhPhon** [comment]
Thank you for your answer @malandr2 
Is there a way to make the keyboard appear above the Collapsible Banner? Because it is affecting the user's experience

**Comment by malandr2** [comment]
Right now there's not; however, you can create request for this at the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk).
