### ISSUE TITLE
AppTrackingTransparency and Google consent management platform

### ISSUE THREAD

**Issue by DamianMarkowski** [googleads/googleads-mobile-flutter#1144]
## Plugin Version

3.0.0

## Steps to Reproduce

Hello, I show Google AdMob ads in my app so I needed to add Google consent management platform prompt provided by Google (documentation can be found here https://support.google.com/admob/answer/13554116). But at the same time, Apple wants me to use their prompt using the AppTrackingTransparency framework and remove the "custom" one (one from Google). How could I resolve that? Is the only way to resolve that to show a prompt using the AppTrackingTransparency framework first and once a user accepts that, show the one from Google CMP? 

Apple rejected my app update because of this, giving the following reason: "The app does not use App Tracking Transparency to request the user's permission before collecting data used to track them. Instead, the app displays a custom prompt that requests the user to allow tracking. Apps need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them. Requesting permission with a custom prompt is not appropriate.". 

Maybe there is some Google endpoint that I could call once a user accepts the prompt from AppTrackingTransparency framework?

**Comment by malandr2** [comment]
Hi @DamianMarkowski, if you are using the [UMP SDK](https://developers.google.com/admob/flutter/privacy) the order of the privacy messages is automatically handled for you. See [Available user message types](https://support.google.com/admob/answer/10114020), specifically behavior on app start. 

We also recommend to updating to the [latest version of the plugin](https://pub.dev/packages/google_mobile_ads/changelog) which has the latest available UMP SDK APIs. 

If you believe you have set this up correctly, you can always the app rejection directly with Apple.

**Comment by DamianMarkowski** [comment]
I see, thanks for your answer @malandr2. I will double check the documentation and update the Flutter Google AdMob Ads package to the latest version. I will update you all here once I'm done with those things.
