### ISSUE TITLE
cornerRadius not works for android for Native Ad Template 

### ISSUE THREAD

**Issue by amitbutani18** [googleads/googleads-mobile-flutter#1148]
Please check the screenshot and code snippet

`class NativeExample extends StatefulWidget {
  const NativeExample({super.key, this.templateType = TemplateType.medium});

  final TemplateType templateType;

  @override
  State<NativeExample> createState() => _NativeExampleState();
}

class _NativeExampleState extends State<NativeExample> {
  NativeAd? _nativeAd;

  bool _nativeAdIsLoaded = false;

  // TODO: replace this test ad unit with your own ad unit.
  final String _adUnitId = Platform.isAndroid
      ? 'ca-app-pub-3940256099942544/2247696110'
      : 'ca-app-pub-3940256099942544/3986624511';

  /// Loads a native ad.
  void loadAd() {
    _nativeAd = NativeAd(
        adUnitId: _adUnitId,
        listener: NativeAdListener(
          onAdLoaded: (ad) {
            debugPrint('$NativeAd loaded.');
            setState(() {
              _nativeAdIsLoaded = true;
            });
          },
          onAdFailedToLoad: (ad, error) {
            // Dispose the ad here to free resources.
            debugPrint('$NativeAd failed to load: $error');
            ad.dispose();
          },
        ),
        request: const AdRequest(),
        // Styling
        nativeTemplateStyle: NativeTemplateStyle(
            // Required: Choose a template.
            templateType: widget.templateType,
            // Optional: Customize the ad's style.
            mainBackgroundColor: AppColor.blackColor,
            cornerRadius: 200.0,
            callToActionTextStyle: NativeTemplateTextStyle(
                textColor: AppColor.blackColor,
                backgroundColor: AppColor.primaryColor,
                style: NativeTemplateFontStyle.bold,
                size: 16.0),
            primaryTextStyle: NativeTemplateTextStyle(
                textColor: AppColor.primaryColor,
                backgroundColor: AppColor.blackColor,
                style: NativeTemplateFontStyle.italic,
                size: 16.0),
            secondaryTextStyle: NativeTemplateTextStyle(
                textColor: Colors.green,
                backgroundColor: Colors.black,
                style: NativeTemplateFontStyle.bold,
                size: 16.0),
            tertiaryTextStyle: NativeTemplateTextStyle(
                textColor: AppColor.whiteColor,
                backgroundColor: Colors.black,
                style: NativeTemplateFontStyle.normal,
                size: 16.0)))
      ..load();
  }

  @override
  void initState() {
    loadAd();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return _nativeAdIsLoaded
        ? widget.templateType == TemplateType.medium
            ? ConstrainedBox(
                constraints: const BoxConstraints(
                  minWidth: 320, // minimum recommended width
                  minHeight: 320, // minimum recommended height
                  maxWidth: double.infinity,
                  maxHeight: 360,
                ),
                child: AdWidget(ad: _nativeAd!),
              )
            : ConstrainedBox(
                constraints: const BoxConstraints(
                  minWidth: 320, // minimum recommended width
                  minHeight: 90, // minimum recommended height
                  maxWidth: 400,
                  maxHeight: 200,
                ),
                child: AdWidget(ad: _nativeAd!),
              )
        : Container();
  }
}`

![image](https://github.com/user-attachments/assets/8e0fe7d8-0640-4bca-be86-545e0f8ba917)

**Comment by malandr2** [comment]
Hi @amitbutani18, the [cornerRadius](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/NativeTemplateStyle/cornerRadius.html) API is an iOS-only configurable setting. What you're experiencing is the intended behavior
