### ISSUE TITLE
Admob Mediation Ad Inspector Support In flutter - Mediation Ads Are Not Loading

### ISSUE THREAD

**Issue by dvlprtoastguyz** [googleads/googleads-mobile-flutter#1150]
Hey There,

I've been trying to test mediation flow using flutter,

So I've just added following flutter dependencies for mediation in my project

```
google_mobile_ads: ^5.1.0
gma_mediation_applovin: ^1.1.0
gma_mediation_inmobi: ^1.0.0
gma_mediation_ironsource: ^1.0.0
gma_mediation_meta: ^1.0.1
gma_mediation_unity: ^1.0.0
```

But even after adding those dependencies, I'm still not able to get any mediation ads. Tried and activated all accounts. Mapped all the added keys and tokens in admob console. Also added values in app-ads.txt file of website. Still not able to get any ads loaded with flutter mediation.

I'm not getting any ads as well and initialization status of all this ad providers is also showing to be ready. I do not know what is missing in my implementation. Not getting any errors as well.

I've been waiting for more than 20 days to load any mediation ads. So At least you can add ad inspector support. So at least we get to know what is getting filled, bidded or any thing else. 

Anyway this is very crucial requirement for flutter mediation packages to debug. So can we expect at least ad inspector in nearest package updates and also can you please try this packages are working for your sample examples or not as well.

Thanks

**Comment by malandr2** [comment]
Hi @dvlprtoastguyz, this is more a question for the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) as the flutter plugin does not control ad serving - please create a new thread there for it to be properly triaged. You can also troubleshoot with [Ad inspector](https://developers.google.com/admob/flutter/ad-inspector) to inspect the ad request.
