### ISSUE TITLE
Incompatibility issues with new flutter version 3.24

### ISSUE THREAD

**Issue by stanimeros** [googleads/googleads-mobile-flutter#1152]
Hello, app crashing on start when I include the package on my pub spec.

Package: google_mobile_ads: ^5.1.0
Flutter is already up to date on channel stable
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (8 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

**Comment by malandr2** [comment]
And as reference, I'm able to run our [banner_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/banner_example) just fine on 3.24.0
