### ISSUE TITLE
warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated

### ISSUE THREAD

**Issue by marcosmessias-src** [googleads/googleads-mobile-flutter#1156]
Hello, I'm having this warning when I compile the application.

C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java:31: warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated
              .getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
              ^
1 warning

**Comment by malandr2** [comment]
This is a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1089, which has been resolved and will be officially fixed in the next release. Thanks for flagging
