### ISSUE TITLE
DartError: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)

### ISSUE THREAD

**Issue by mRcOol7** [googleads/googleads-mobile-flutter#1168]
How I solve this error?
**DartError: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)**

**Comment by malandr2** [comment]
Hi @mRcOol7, I haven't come across this error before. Can you provide steps to reproduce? Are you able to build our sample projects? Can you share your own sample project?

Have you followed our Flutter plugin [Get started](https://developers.google.com/admob/flutter/quick-start) guide?

**Comment by jakenoble** [comment]
Have you tried rebuilding the app? Hot restart does not work after adding the dep.
