### ISSUE TITLE
In the provided BannerAdWidget example, it constantly throws a Future already completed exception

### ISSUE THREAD

**Issue by MagnusJohansson** [googleads/googleads-mobile-flutter#117]
After letting the example app running for a minute or so, an Exception of type:

> StateError (Bad state: Future already completed)

In the line
```
bannerCompleter.complete(ad as BannerAd);
```
https://github.com/googleads/googleads-mobile-flutter/blob/b32a33b6fd93b4fd0a0073c22196e925c15f2bc0/packages/google_mobile_ads/example/lib/main.dart#L240

**Comment by 2shrestha22** [comment]
Banner ad refresh automatically after some interval and ` bannerCompleter.complete(ad as BannerAd);` runs again second time which is not allowed and hence throwing error. Why official example using completer anyway?

**Comment by jjliu15** [comment]
The example app no longer uses `completer`. Would recommend following the [updated example](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/example/lib/reusable_inline_example.dart#L88-L108) as a reference.
