### ISSUE TITLE
Full-Screen Native Ads Support in Google Mobile Ads Flutter Plugin

### ISSUE THREAD

**Issue by alixumer** [googleads/googleads-mobile-flutter#1173]
A new ad format called Full-Screen Native Ads has been introduced, which seamlessly integrates with the app's UI, providing a rich and immersive user experience. These ads take up most of the screen and are commonly used in apps with full-screen content (Social, News, Weather, Entertainment, Tools). The format offers user-friendly features such as swipe-to-dismiss and video playback controls.

However, it appears that the Google Mobile Ads Flutter plugin does not yet fully support this format. The following issues have been encountered:

Missing full-screen native ad implementation: The current version of the plugin does not provide API or documentation for integrating full-screen native ads within Flutter apps.
Swipe-to-dismiss and video playback control functionality: These features, which are mentioned as part of the native ad format policy, are either not available or do not function as expected within the plugin.
Layout inconsistencies: Attempting to manually integrate full-screen native ads leads to UI issues, such as improper scaling, overlap with app content, and difficulty in maintaining swipe-to-dismiss functionality.
![unnamed](https://github.com/user-attachments/assets/eb2970e9-628c-4a59-9606-55722905898e)

**Comment by malandr2** [comment]
Hi @alixumer, at this time for Flutter implementations you can configure a full-screen native ad using the platform setup for Native ads https://developers.google.com/admob/flutter/native/platforms which would involve writing code in the native layer (Android, iOS)

**Comment by Hieuntdz** [comment]
@malandr2  so how to "swipe-to-dismiss and video playback controls.". To implment this function need write code in native layer (Android, iOS) ?.

**Comment by malandr2** [comment]
Hi @Hieuntdz, yes the native layer supports that functionality.

**Comment by alixumer** [comment]
@malandr2 Thanks
