### ISSUE TITLE
gma_mediation_unity - Update Unity libs/pods

### ISSUE THREAD

**Issue by wazasoft** [googleads/googleads-mobile-flutter#1175]
Hi,

Can you please update the unity libs/pods used by the`gma_mediation_unity` plugin to the latest version? Its almost 4 months old since the `gma_mediation_unity` was last released and there have been few updates to the unity libs/pods already.

Thanks!

**Comment by malandr2** [comment]
Hi @wazasoft, this is something we are aware of and will update the `gma_mediation_unity` plugin soon

**Comment by wazasoft** [comment]
Hi there,

Could anyone please comment on the planned release date for updating the unity libs used by the plugin? 

Thanks!

**Comment by malandr2** [comment]
Hi @wazasoft, you should expect an update the the unity lib tomorrow

**Comment by malandr2** [comment]
Hi @wazasoft it should be live https://pub.dev/packages/gma_mediation_unity

**Comment by wazasoft** [comment]
> Hi @wazasoft it should be live https://pub.dev/packages/gma_mediation_unity

Thanks!
