### ISSUE TITLE
Mediation Adapters Updates and Pangle Consent Settings

### ISSUE THREAD

**Issue by t3chno** [googleads/googleads-mobile-flutter#1176]
1. Mediation Adapters Updates:
I would like to inquire about the update schedule for mediation adapters, specifically for Pangle, InMobi, Liftoff, and Meta. Can you provide information on when these adapters were last updated and the estimated dates for future updates?

2. Pangle Consent Settings:
I couldn't find the consent settings for Pangle in my Xcode iOS project. As a result, I set up the consent manually using the MethodChannel approach. However, the Ad Inspector still shows "no user consent provided".

My question is: How can Google Mobile Ads be aware of the consent information I manually provided to Pangle? Do you have any suggestions on how to resolve this issue?

Thank you for your assistance.

**Comment by malandr2** [comment]
Hi @t3chno,

1. Those mediation adapters will have rolling updates in the coming weeks. Release information can be found on PubDev (For example, Meta's package url is https://pub.dev/packages/gma_mediation_meta). Estimating future updates are inherently difficult to have a predicable cadence as it depends on the third-party. That being said, we will try out best to update them after the third-party has updated their adapter. 

2. Have you added Pangle as an [ad partner](https://support.google.com/admob/answer/10113004) in the AdMob UI? It's possible you have everything set up correctly but you need add the ad partner for consent to apply to them.

**Comment by t3chno** [comment]
Hi @malandr2 ,

Thank you very much for your valuable feedback.

1. Regarding the mediation adapters updates:
We appreciate the information about the rolling updates in the coming weeks. We'll be sure to monitor the updates on PubDev. We understand that a precise schedule can't be provided due to third-party dependencies. If the updates take longer than expected, we might consider forking the code and making necessary changes ourselves as an option. However, for now, we'll continue to wait patiently. Thank you for your efforts on this.

2. Concerning the Pangle consent settings:
Your suggestion worked and solved our issue. We had overlooked adding Pangle as an ad partner in the AdMob UI. Thank you for this reminder. It was a small but crucial step that we should not have missed.

Once again, we appreciate your help and prompt response. This information is invaluable for our project.
