### ISSUE TITLE
Is version google_mobile_ads ^4.0.0 supported Collapsible Banner ads?

### ISSUE THREAD

**Issue by hhzhangzy** [googleads/googleads-mobile-flutter#1178]
According to the document: https://developers.google.cn/admob/flutter/banner/collapsible ，Can I use version plugin 4.0.0 for development? Or do we have to upgrade the plugin to version 5.1.0?

**Comment by malandr2** [comment]
HI @hhzhangzy, yes collapsible banner ads work with version `4.0.0`. That being said, we always recommend updating to the latest available version to access the most up-to-date builds

**Comment by Jigneshiosdeveloper** [comment]
Hi @hhzhangzy 

With google_mobile_ads: ^5.1.0 version, [collapsible banner ads](https://fluttertutorialhub.com/admob/collapsible-banner-admob-ads-flutter/) are working well for Android and iOS in the Flutter project.
