### ISSUE TITLE
Error when run app using google ads 

### ISSUE THREAD

**Issue by Roshan-pcy** [googleads/googleads-mobile-flutter#1180]
E/GoogleApiManager(29642): Failed to get service from broker. 
E/GoogleApiManager(29642): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(29642): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
E/GoogleApiManager(29642): 	at android.os.Parcel.createException(Parcel.java:2995)
E/GoogleApiManager(29642): 	at android.os.Parcel.readException(Parcel.java:2978)
E/GoogleApiManager(29642): 	at android.os.Parcel.readException(Parcel.java:2920)
E/GoogleApiManager(29642): 	at amok.a(:com.google.android.gms@243633029@24.36.33 (190400-675378931):36)
E/GoogleApiManager(29642): 	at ammr.z(:com.google.android.gms@243633029@24.36.33 (190400-675378931):143)
E/GoogleApiManager(29642): 	at altt.run(:com.google.android.gms@243633029@24.36.33 (190400-675378931):54)
E/GoogleApiManager(29642): 	at android.os.Handler.handleCallback(Handler.java:942)
E/GoogleApiManager(29642): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager(29642): 	at bqoh.ml(:com.google.android.gms@243633029@24.36.33 (190400-675378931):1)
E/GoogleApiManager(29642): 	at bqoh.dispatchMessage(:com.google.android.gms@243633029@24.36.33 (190400-675378931):5)
E/GoogleApiManager(29642): 	at android.os.Looper.loopOnce(Looper.java:211)
E/GoogleApiManager(29642): 	at android.os.Looper.loop(Looper.java:300)
E/GoogleApiManager(29642): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by malandr2** [comment]
Please create a valid issue that include steps to reproduce, and diagnostic information so we can begin the debugging process. Thanks!

**Comment by malandr2** [comment]
Please follow the [Get Started](https://developers.google.com/admob/flutter/quick-start) guide for a proper integration.

**Comment by jansvanda** [comment]
Having the same issue:
`E/GoogleApiManager(27236): Failed to get service from broker. 
E/GoogleApiManager(27236): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(27236): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/GoogleApiManager(27236): 	at android.os.Parcel.createException(Parcel.java:2357)
E/GoogleApiManager(27236): 	at android.os.Parcel.readException(Parcel.java:2340)
E/GoogleApiManager(27236): 	at android.os.Parcel.readException(Parcel.java:2282)
E/GoogleApiManager(27236): 	at aljh.a(:com.google.android.gms@243934022@24.39.34 (150400-683343373):36)
E/GoogleApiManager(27236): 	at alho.z(:com.google.android.gms@243934022@24.39.34 (150400-683343373):150)
E/GoogleApiManager(27236): 	at akos.run(:com.google.android.gms@243934022@24.39.34 (150400-683343373):54)
E/GoogleApiManager(27236): 	at android.os.Handler.handleCallback(Handler.java:938)
E/GoogleApiManager(27236): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager(27236): 	at bozu.lR(:com.google.android.gms@243934022@24.39.34 (150400-683343373):1)
E/GoogleApiManager(27236): 	at bozu.dispatchMessage(:com.google.android.gms@243934022@24.39.34 (150400-683343373):5)
E/GoogleApiManager(27236): 	at android.os.Looper.loop(Looper.java:233)
E/GoogleApiManager(27236): 	at android.os.HandlerThread.run(HandlerThread.java:67)`

dependencies: dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_pagination: ^4.0.1
  cupertino_icons: ^1.0.8
  share_plus: ^10.0.3
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.3.2
  diacritic: ^0.1.5
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.2
  cloud_firestore: ^5.4.4
  google_mobile_ads: ^5.2.0
  contactus: ^1.2.3
  in_app_purchase: ^3.2.0
  fading_edge_scrollview: ^4.1.1
  auto_size_text: ^3.0.0
  firebase_crashlytics: ^4.1.3
  package_info_plus: ^8.0.3
  flutter_settings_ui: ^3.0.0
  
  build.gradle: dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.4.0')
    implementation("com.google.firebase:firebase-analytics")
    implementation("com.google.firebase:firebase-crashlytics")
    implementation 'com.google.firebase:firebase-messaging:24.0.2'
    implementation 'com.google.android.gms:play-services-ads:23.4.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.2'
}

settings.gradle: plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.6.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.20" apply false
    id "com.google.gms.google-services" version "4.4.0" apply false
    id "com.google.firebase.crashlytics" version "2.9.9" apply false
}

**Comment by Thiiagoac** [comment]
despite not having reported more about the issue, i have the same issue in my project and the only solution that i found was wipe data from de emulator and start again the application, if does not work, in this thread exist some possible solutions.

https://github.com/firebase/flutterfire/issues/13486

**Comment by TaotheTaoist** [comment]
Having the same problem as you............

**Comment by APEGames** [comment]
> despite not having reported more about the issue, i have the same issue in my project and the only solution that i found was wipe data from de emulator and start again the application, if does not work, in this thread exist some possible solutions.
> 
> [firebase/flutterfire#13486](https://github.com/firebase/flutterfire/issues/13486)

Wiping the emulator data and restarting fixed this problem for me, too. Thanks for the post!
