### ISSUE TITLE
Native Ads not work, Showing message: Internal error 

### ISSUE THREAD

**Issue by VimeshLunagariya** [googleads/googleads-mobile-flutter#1195]
LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Internal error., responseInfo: ResponseInfo(responseId: lvQVZ9yUIZagssUP0r36yAE, mediationAdapterClassName: , adapterResponses: [AdapterResponseInfo(adapterClassName: com.google.ads.mediation.admob.AdMobAdapter, latencyMillis: 13, Description: {
"Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
"Latency": 13,
"Ad Source Name": "Reservation campaign",
"Ad Source ID": "7068401028668408324",
"Ad Source Instance Name": "[DevRel] [DO NOT EDIT] Native Ads Campaign",
"Ad Source Instance ID": "3518433842871043",
"Credentials": {
  "pubid": "ca-app-pub-3940256099942544\/2247696110\/cak=no_cache&cadc=ee&caqid=lvQVZ-WUIJmassUPhYPmqAg",
  "campaign_type": "1",
  "campaign_id": "12584073087"
},
"Ad Error": {
  "Code": 0,
  "Message": "Internal error.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null"
}
I/flutter ( 8471): }, adUnitMapping: {campaign_type: 1, pubid: ca-app-pub-3940256099942544/2247696110/cak=no_cache&cadc=ee&caqid=lvQVZ-WUIJmassUPhYPmqAg, campaign_id: 12584073087}, adError: AdError(code: 0, domain: com.google.android.gms.ads, message: Internal error.), adSourceName: Reservation campaign, adSourceId: 7068401028668408324, adSourceInstanceName: [DevRel] [DO NOT EDIT] Native Ads Campaign, adSourceInstanceId: 3518433842871043)], loadedAdapterResponseInfo: null), responseExtras: {mediation_group_name: Campaign})

HERE IS MY CODE:
`loadAdxNativeAd() async {
    setState(() {
      adxNativeAd = NativeAd(
        adUnitId: kDebugMode ? 'ca-app-pub-3940256099942544/2247696110' : myAdsId.googleNativeId,
        factoryId: 'listTileMedium',
        nativeTemplateStyle: NativeTemplateStyle(templateType: TemplateType.small),
        request: const AdRequest(),
        listener: NativeAdListener(
          onAdLoaded: (ad) {
            setState(() {
              _isAdxNativeAdLoaded = true;
            });
          },
          onAdFailedToLoad: (ad, error) {
            customDebugPrintWidget('Native Ads ERROR ::: $error');
            setState(() {
              _isAdxNativeAdLoaded = false;
              _isAdxNativeAdFailed = true;
            });
            ad.dispose();
          },
        ),
      );
      adxNativeAd!.load();
    });
  }`

**Comment by malandr2** [comment]
Hi @VimeshLunagariya, this issue is more related to ad serving which the google mobile ads Flutter plugin doesn't control. This can be better addressed in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) - please create a new thread there to begin the troubleshooting process. 

Closing this out - thanks!
