### ISSUE TITLE
Create in-line Ads - Doc / Example

### ISSUE THREAD

**Issue by marcellocamara** [googleads/googleads-mobile-flutter#1198]
There are no examples or guides on how to create in-line ads
There is only one way to create a simple banner, which can cause problems of ban or limitations of our AdMob account if not implemented correctly

**The problem**: Every time when user scrolls the list, the Ads can't be reloaded, causing a new impression.
**Example scenario**: The user loads a list of widgets and a banner Ads should appear in one of the indexes in the list.
When opens one of the list items (with navigator.push), ensure that the Ad that was on the back stack does not generate an impression or is reloaded (as it is on the back screen and not the front one).

Therefore, I think the support team of this package should create a sample to avoid developers' mistakes and getting bans or limitations from AdMob.

This old tutorial (2022) has the code is already archived: https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter
See this sample lists: https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob

**Comment by malandr2** [comment]
Hi @marcellocamara, the docs can be found here: https://developers.google.com/admob/flutter/banner/inline-adaptive

You can also see an inline adaptive example in our `google_mobile_ads` package example here: https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/inline_adaptive_example.dart

**Comment by marcellocamara** [comment]
> You can also see an inline adaptive example in our `google_mobile_ads` package example here: https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/inline_adaptive_example.dart

I didn't saw this folder! 
Shouldn't this be moved to **/samples** folder !?

Thanks, it works.
I was using a custom widget, inside the list, to load and show the the ad.
But the banner should be loaded on the list side (outside of list), instead of the widget side (inside of list items), to avoid rebuild.
