### ISSUE TITLE
Unable to obtain javascript engine (Android-iOS interstitial ad load issue)

### ISSUE THREAD

**Issue by aykutuludag** [googleads/googleads-mobile-flutter#1199]
Flutter version: 3.24.3
Dart version: 3.5.3
Affected Android versions: Happening in every Android versions:
Affected iOS versions: Happening in every iOS versions.

The issue
This issue is still present google_mobile_ads: ^5.2.0. About every 1 of 5 requests can't be loaded because of various reasons. It is normal that admob can't return all ad request but last 3-4 months, frequency of issue increased day by day.

![image](https://github.com/user-attachments/assets/9dd8e235-63d6-40bf-b467-102beda85ebd)

Error Reasons:

- Unable to obtain a JavaScriptEngine (What exactly does this error mean?)
- Network error
- Internal error
- No fill
- Some polish words i can't understand
- ...

As you can see, %90 of error reasons are **Unable to obtain a JavaScriptEngine** and **Network error**.

According to my research, possible reasons are following:

- US Sanctions _(I couldn't find exact list that which countries supported by admob? There is a sanctions on Iran and Syria but I get requests and shows on those countries. I found this https://support.google.com/admob/answer/6163675 but according to this I couldn't get any ad request from Iran but I am getting? Also Russia is not on that list but I couldn't get any ad request from Russia since the beginning of the war.)_
- AdBlock on device
- AdBlock on network/dns level
- Google Play Services not available _(Huawei devices etc)_
- Google Play Services is not up to date.
- ...

I am not fully understand why Admob on Android devices requires Google Play Services. Neither iOS nor Web doesn't have Google Play Services, too.

Issue happened following countries:

![image](https://github.com/user-attachments/assets/1034dfd7-a77b-4169-ac5e-e18158269fbd)
I understand Russia and Syria (US Sanctions) and Ukraine (war) but rest of them not understandable.

Sceneario
As general the other apps, I am starting to load ads when app start (For me main.dart because it is flutter project) Here is the minimal, reproducible example of code:

```
InterstitialAd? fullPageAd;

Future<void> main() async {
  try {
    await initializeAdmob();
  } catch (error) {
    if (kDebugMode) {
      print(error);
    }
  }

  runApp(const MyApp());
}
```

```
Future<void> createInterstitialAd() async {
  await InterstitialAd.load(
      adUnitId: Platform.isAndroid ? interstitialAndroid : interstitialiOS,
      request: request,
      adLoadCallback: InterstitialAdLoadCallback(
        onAdLoaded: (InterstitialAd ad) {
          fullPageAd = ad;
          fullPageAd!.setImmersiveMode(true);
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialLOAD",
          );
        },
        onAdFailedToLoad: (LoadAdError error) async {
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialFAILLOAD",
            parameters: {
              "errorReason": error.message,
            },
          );
        },
      ));
}
```

As you can see it is pretty simple code. I tried to find why it is happening but couldn't find a real result and couldn't decrease frequency of this error. Kind regards

**Comment by malandr2** [comment]
Hi @aykutuludag, these errors are surfaced by the iOS and Android SDKs. See `AdLoad errors` for each platform ([Android](https://developers.google.com/admob/android/ad-load-errors) | [iOS](https://developers.google.com/admob/ios/ad-load-errors))

AdMob also does not require Google Play services but it is recommended, per https://firebase.google.com/docs/android/android-play-services#google_play_services_required_or_recommended

For any additional questions related to these ad errors, please create a new thread in the [AdMob developers forum](https://groups.google.com/g/google-admob-ads-sdk) as they are not controlled by the flutter plugin but the respective iOS/Android SDKs.

Closing this out - thanks!
