### ISSUE TITLE
Consent Form is stuck on Mac M1 devices

### ISSUE THREAD

**Issue by kreativityapps** [googleads/googleads-mobile-flutter#1206]
### [REQUIRED] Step 1: Describe your environment

MacBook Pro M1 2021, 15.1 (24B83)
Macbook Air M1 2020, 15.1 (24B83)

Flutter 3.24.4 • channel stable
Dart 3.5.4

## Plugin Version

google_mobile_ads: 5.2.0

### [REQUIRED] Step 2: Describe the problem

The Consent Form is stuck on Mac M1 devices when the app is launched in the mode `Mac Designed for iPad (desktop)` or downloaded from the MacBook App Store.
The consent form is shown, but when clicking on the `Continue` button nothing happens, the user is blocked, can't advance to use the app.
![Screenshot 2024-11-02 at 11 17 45 AM](https://github.com/user-attachments/assets/c9b878f3-2f72-4e26-8bf4-b4df63b88537)

On other devices like iPhone (real device) and iPad (could try it only in the simulator) it works as expected.

Do we have to detect in our code that we are running on a MacBook and skip the Consent Form or can this be fixed?
 
## Steps to Reproduce

1. Include ConsentForm in your app
2. Call `consentForm.show`
3. Start the app on a Mac M1, make sure that the consent form is shown
4. Click on the `Continue` button in the form

**Expected results:** 
The form shows the next screen and the user can advance

**Actual results:** 
The user is blocked at the `Continue` button and can't use the app

There are no error messages in the logs.

**Comment by malandr2** [comment]
Hi @kreativityapps, because this issue persists in the iOS layer and it's not something the Flutter plugin controls, this is better suited for the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk). Please create a new thread (you can reference this original link) for your issue to be properly triaged. 

Closing this out - thanks!
