### ISSUE TITLE
Flutter 3.27.x - PlatformException(recreating_view, trying to create an already created view

### ISSUE THREAD

**Issue by manojdcoder** [googleads/googleads-mobile-flutter#1217]
### [REQUIRED] Step 1: Describe your environment

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter Stable: 3.27.1 or 3.27.0 (reproduced in both versions)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (6 available)
[✓] Network resources

## Plugin Version

5.2.0

### [REQUIRED] Step 2: Describe the problem

Since upgrading to Flutter SDK 3.27.x, seeing  PlatformException(recreating_view, trying to create an already created view on iOS only when reloading the app. 

## Steps to Reproduce

1. Add a banner ad to yoru view
2. Run the app
3. Use the reload button on VS Code
4. App reloads, as soon banner is loaded, throws exception 

**Expected results:** No Exception, banner reloads with the app

**Actual results:** Seeing unhandled exception _PlatformException(recreating_view, trying to create an already created view_ 

Only downgrading to flutter 3.24.5 solves the problem.

**Comment by malandr2** [comment]
Hi @manojdcoder,

from https://github.com/pichillilorenzo/flutter_inappwebview/issues/2405#issuecomment-2462043664

"For unknown reasons, the Flutter PlatformView is not disposed automatically on Hot Restart.
It works as expected on Android, iOS, and Windows but not on macOS.
I think this has something to do with how Flutter manages the native PlatformView under the hood as this plugin is using the Flutter official API to render native views.
Probably, you should open an issue on the Flutter official repo and you can mention this issue."

---

This appears to be a general issue with platform views on iOS. It is being tracked in https://github.com/flutter/flutter/issues/110381

Kindly follow up in the original issue for updates.

Closing from here as duplicate.

Thank you!

**Comment by PaulAllanSturm** [comment]
> "For unknown reasons, the Flutter PlatformView is not disposed automatically on Hot Restart. It works as expected on Android, iOS, and Windows but not on macOS. ..."
> 
> This appears to be a general issue with platform views on iOS. It is being tracked in [flutter/flutter#110381](https://github.com/flutter/flutter/issues/110381)

That Flutter issue has a fix, but it is for macOS, not iOS.

**Comment by PaulAllanSturm** [comment]
The iOS version of this problem is tracked at https://github.com/flutter/flutter/issues/163935. It has a fix in PR.
