### ISSUE TITLE
Ad failed to load : 3

### ISSUE THREAD

**Issue by uugurbas** [googleads/googleads-mobile-flutter#122]
## Bug report

**Describe the bug**
Even if I use the test ID, banner ads are not shown and i got error "Ad failed to load : 3".

### Steps to reproduce

Just add a banner ad. Since I got the "Ad failed to load : 3" error, codes are supposed to work fine.

### Expected behavior

Show a test banner ad.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Microsoft Windows [Version 10.0.19042.868]
(c) 2020 Microsoft Corporation. All rights reserved.

D:\Ugur\Flutter\projeler\kelime_dunyasi_3>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.868], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
D:\Ugur\Flutter\projeler\kelime_dunyasi_3>flutter pub deps -- --style=compact
Dart SDK 2.12.2
Flutter SDK 2.0.3
kelime_dunyasi_3 1.1.0+4

dependencies:
- audioplayers 0.17.4 [uuid path_provider flutter flutter_web_plugins]
- auto_size_text 2.1.0 [flutter]
- cupertino_icons 1.0.2
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_sequence_animation 3.0.1 [flutter meta]
- get 3.26.0 [flutter]
- get_it 6.0.0 [async collection]
- google_mobile_ads 0.11.0+4 [meta flutter]
- sqflite 2.0.0+3 [flutter sqflite_common path]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_sp
an stream_channel string_scanner term_glyph typed_data]
- integration_test 0.9.2+2 [flutter flutter_driver flutter_test path vm_service archive args async boolean_selector characters charcode clock collection convert
crypto fake_async file matcher meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.0.0 [meta path]
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters cha
rcode clock collection convert crypto fake_async matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typ
ed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.5 [path_provider_platform_interface meta path flutter ffi win32]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- process 4.0.0 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.2.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0
- vm_service 5.5.0 [meta]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- win32 2.0.4 [ffi]
- xdg_directories 0.1.2 [meta path process]

```

</details>
Here is the terminal reult

D/DynamitePackage( 5804): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     ( 5804): This request is sent from a test device.
I/DynamiteModule( 5804): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 5804): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101
I/DynamiteModule( 5804): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 5804): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101
I/Ads     ( 5804): Ad failed to load : 3
---

**Comment by kunny** [comment]
Error code 3 (on Android) means AdMob successfully received an ad request but there are no ads to show. (Which may happen and not a bug)

DId you use test banner ad unit(`ca-app-pub-3940256099942544/6300978111`), which can be found on https://developers.google.com/admob/android/test-ads?

**Comment by uugurbas** [comment]
This is the exact ad unit id I used.
What is strange is, i get this error when I use test ad unit ID. Why there is no ad to show even I requested test ads? Here are the lines;
class AdmobIslemleri {
  static final String bannerCanli = "ca-app-pub-7692215741308282/7344562383";
  static final String bannerTest = "ca-app-pub-3940256099942544/6300978111";
  static final String interstitialCanli =
      "ca-app-pub-7692215741308282/4842522127";
  static final String interstitialTest =
      "ca-app-pub-3940256099942544/1033173712";

  static BannerAd buildBannerAd() {
    return BannerAd(
      adUnitId: bannerTest,
      size: AdSize.banner,
      request: AdRequest(),
      listener: AdListener(),
    );
  }
}

**Comment by uugurbas** [comment]
This is the exact ad unit id I used.
What is strange is, i get this error when I use test ad unit ID. Why there is no ad to show even I requested test ads? Here are the lines;
class AdmobIslemleri {
  static final String bannerReal = i deleted
  static final String bannerTest = "ca-app-pub-3940256099942544/6300978111";
  static final String interstitialCanli = i deleted
  static final String interstitialTest =
      "ca-app-pub-3940256099942544/1033173712";

  static BannerAd buildBannerAd() {
    return BannerAd(
      adUnitId: bannerTest,
      size: AdSize.banner,
      request: AdRequest(),
      listener: AdListener(),
    );
  }
}

**Comment by untp** [comment]
@uugurbas Can you try example app in this repository? It is working well on my devices.

Maybe an ad blocker or a firewall blocks ads. Can you turn off them, if you are using an ad blocker?

**Comment by uugurbas** [comment]
I do not use adblocker and also firewall is turned off. When i run my project with real id's on my emulator, I get the test ads but it gives a warning about the internet connection. But my connection is OK since I can connect the sites using my web browser. Another strange thing is last time I used this project about one month ago everything was fine. I didn't change anything but now it doesn't work

**Comment by untp** [comment]
Can you try these example projects?
[Flutter example](https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example) 
[Android example](https://github.com/googleads/googleads-mobile-android-examples/tree/master/java/admob/BannerExample)

If Android example work and Flutter example doesn't work, we can say this is a problem for this package. Can you build and test these examples?

**Comment by uugurbas** [comment]
I will try asap.

This is the warning i get:

W/Ads     ( 5313): JS: A parser-blocking, cross site (i.e. different eTLD+1) script, https://pagead2.googlesyndication.com/pagead/js/r20210322/r20110914/abg_lite_fy2019.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details. (https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318486317%2C318484676%2C318491267%2C318482077%2C318483611%2C318484497%2C318484801%2C318486978%2C318491315%2C318491831%2C318492496%2C318493865%2C318494215%2C318495060%2C318495894%2C318495752%2C318475417%2C318489659%2C318495357%2C318495358%2C318494842&format=320x50_as&heap_free=17679184&heap_max=201326592&heap_total=27730352&js=afma-sdk-a-v210402999.204204000.1&msid=com.ugurbas.kelime_dunyasi_6&preqs=0&request_pkg=io.flutter.plugins.googlemobileads.FlutterBannerAd&seq_num=1&target_api=30:1)
I/chromium( 5313): [INFO:CONSOLE(1)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://pagead2.googlesyndication.com/pagead/js/r20210322/r20110914/abg_lite_fy2019.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318486317%2C318484676%2C318491267%2C318482077%2C318483611%2C318484497%2C318484801%2C318486978%2C318491315%2C318491831%2C318492496%2C318493865%2C318494215%2C318495060%2C318495894%2C318495752%2C318475417%2C318489659%2C318495357%2C318495358%2C318494842&format=320x50_as&heap_free=17679184&heap_max=201326592&heap_total=27730352&js=afma-sdk-a-v210402999.204204000.1&msid=com.ugurbas.kelime_dunyasi_6&preqs=0&request_pkg=io.flutter.plugins.googlemobileads.FlutterBannerAd&seq_num=1&target_api=30 (1)
W/Ads     ( 5313): JS: A parser-blocking, cross site (i.e. different eTLD+1) script, https://pagead2.googlesyndication.com/pagead/js/r20210322/r20110914/abg_lite_fy2019.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details. (https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318486317%2C318484676%2C318491267%2C318482077%2C318483611%2C318484497%2C318484801%2C318486978%2C318491315%2C318491831%2C318492496%2C318493865%2C318494215%2C318495060%2C318495894%2C318495752%2C318475417%2C318489659%2C318495357%2C318495358%2C318494842&format=320x50_as&heap_free=17679184&heap_max=201326592&heap_total=27730352&js=afma-sdk-a-v210402999.204204000.1&msid=com.ugurbas.kelime_dunyasi_6&preqs=0&request_pkg=io.flutter.plugins.googlemobileads.FlutterBannerAd&seq_num=1&target_api=30:1)
I/chromium( 5313): [INFO:CONSOLE(1)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://pagead2.googlesyndication.com/pagead/js/r20210322/r20110914/abg_lite_fy2019.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_xSeconds&eid=318486317%2C318484676%2C318491267%2C318482077%2C318483611%2C318484497%2C318484801%2C318486978%2C318491315%2C318491831%2C318492496%2C318493865%2C318494215%2C318495060%2C318495894%2C318495752%2C318475417%2C318489659%2C318495357%2C318495358%2C318494842&format=320x50_as&heap_free=17679184&heap_max=201326592&heap_total=27730352&js=afma-sdk-a-v210402999.204204000.1&msid=com.ugurbas.kelime_dunyasi_6&preqs=0&request_pkg=io.flutter.plugins.googlemobileads.FlutterBannerAd&seq_num=1&target_api=30 (1)
I/DynamiteModule( 5313): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 5313): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101
