### ISSUE TITLE
🐛 [Native Ad] MediaView not working on Android

### ISSUE THREAD

**Issue by thegrxp** [googleads/googleads-mobile-flutter#125]
## Bug report

**Describe the bug**
According to https://support.google.com/admob/answer/6329638, MediaView is required to render the main video or image asset in an ad. 
No image is displayed on Android, but it is working with ImageView. This workaround might lead to an account suspension?

### Steps to reproduce

XML
```
<com.google.android.gms.ads.nativead.MediaView
          android:id="@+id/mv_post_native_ad_media"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_gravity="center_vertical"
          android:scaleType="fitXY"
/>
```

Factory
```
val nativeAdView = layoutInflater.inflate(R.layout.post_native_ad, null) as UnifiedNativeAdView
val mediaView = nativeAdView.findViewById<MediaView>(R.id.mv_post_native_ad_media)

mediaView.setMediaContent(nativeAd.mediaContent) 
nativeAdView.setNativeAd(nativeAd)
nativeAdView.mediaView = mediaView

return nativeAdView
```

### Flutter dependencies

```
google_mobile_ads: ^0.11.0+4
```

**Comment by dupovalo** [comment]
Try the following (change the order of calls):

```
mediaView.setMediaContent(nativeAd.mediaContent) 
nativeAdView.mediaView = mediaView // <--- 1
nativeAdView.setNativeAd(nativeAd). // <--- 2
```

Not sure if this is a bug or a feature. This works for me though.

**Comment by thegrxp** [comment]
> Try the following (change the order of calls):
> 
> ```
> mediaView.setMediaContent(nativeAd.mediaContent) 
> nativeAdView.mediaView = mediaView // <--- 1
> nativeAdView.setNativeAd(nativeAd) // <--- 2
> ```
> 
> Not sure if this is a bug or a feature. This works for me though.

This is working thanks!
Also I was using `import com.google.android.gms.ads.nativead.MediaView` instead of `import com.google.android.gms.ads.formats.MediaView`
