### ISSUE TITLE
🐛  Banner Ad takes a long time (1 minute) to reload

### ISSUE THREAD

**Issue by palicka** [googleads/googleads-mobile-flutter#131]
EDIT: See my next comment

Banner Ad created according to example code:

```
class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    // Load ads.
  }
```

is not reloading on iPhones, user still see the same ad when he returns back to the app (even after one day). It's probably because lifecycle in iOS is different than in Android and initState is not called.  I think it "doesn't count" if there is always the same ad, so it's causing loss in revenues. Is developer supposed to manage reloading by himself, or is it a bug ?  There is no word about reloading in docs.
Thank you

affected version: 0.11.0+3

**Comment by kunny** [comment]
Could you please add a listener and see whether `onAdLoaded()` is called or not?

Also, please note that it's possible to see the same ad (the same ad creative) even when the ad is reloaded. (thus it's not a bug)

**Comment by palicka** [comment]
I need to update and clarify what I said earlier. When the app is started for the first time, ad is loaded within a second. But after a long time, when the app is reopened from the background, behaviour is the same on both platforms (Android and iOS), and the ad IS eventually reloaded, BUT after one minute (60 seconds).  Also, when I start the app while internet is off, and then turn internet on, it took 60 seconds to load the ad. And when I try to recreate `BannerAd` instance or call `load()` by myself, it also took 60 seconds to reload the ad.  Ad loading is fast only when opening app, that was closed/killed before. 
The problem is, user might finish using the app before the ad is loaded...
 
(I have another native app with ads, and reloading is instant every time)

This is how it looks in my code, basically the same as it is in the example, am I missing something ? or is it really a bug ? 
```
  @override
  void initState() {
    super.initState();

      myBanner = BannerAd(
        adUnitId: Platform.isAndroid ? 'ca-app-pub-...' : 'ca-app-pub-...',
        size: AdSize.banner,
        request: AdRequest(),
        listener: AdListener(..),
      );
      myBanner.load();

  }
...
          Container(
            alignment: Alignment.center,
            child: AdWidget(
                ad: myBanner),
            width: myBanner.size.width.toDouble(),
            height: myBanner.size.height.toDouble(),
          )

```

**Comment by kunny** [comment]
That's an intended behavior I believe. Banner won't be re-loaded until you call `load()` method. And the banner won't be refreshed if the app is on the background.

However, you are requesting the banner in `initState()` method. It's not called when the app comes back to the foreground, so the banner (that was loaded before) remains still.

Refer to the [Help Center](https://support.google.com/admob/answer/3245199?hl=en) article for more details about the refresh rate.

**Comment by palicka** [comment]
Calling `load()` or recreating Banner instance doesn't take effect when coming from background, or when user triggers content refresh manually(and I call `load()` there). It always takes 60 seconds to reload.. It looks like it's being ignored...

**Comment by palicka** [comment]
When I recreate `BannerAd` instance and then call` .load()` it looks like it's working. Closing this issue. Thanks for the info.
