### ISSUE TITLE
🐛 the Future of ad.load() does not return isLoaded

### ISSUE THREAD

**Issue by kohry** [googleads/googleads-mobile-flutter#143]
## Bug report

**Describe the bug**
the return value of ad.load() is Future, but it does not do anything. 

### Steps to reproduce

ad.load().whenComplete((){
   ad.show()
}) 

and you will see 99% of Ads will not be properly loaded before showing

### Expected behavior

It should be return false if Ad failed to load the ad, and true if ad is loaded

**Comment by bounty1342** [comment]
Actually that's quite normal :
![image](https://user-images.githubusercontent.com/6307253/113073601-ae150800-91c9-11eb-9d0f-ae76769d6d90.png)

You should do something like (as per ex https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#6):
```
onAdLoaded: (_) {
        setState(() {
          _isAdLoaded = true;
        });
      },
```

Regards

**Comment by bparrishMines** [comment]
As @bounty1342 stated, this is working as intended. `Ad.show` should only be called after `AdListener.onAdLoaded` is called as explained here https://pub.dev/packages/google_mobile_ads#display-an-interstitial-ad
