### ISSUE TITLE
Banner on Android gave AdMob Policy Issue : Modified ad code: Resizing Ad Frames

### ISSUE THREAD

**Issue by yosus** [googleads/googleads-mobile-flutter#146]
Similar to this previous issue : https://github.com/FirebaseExtended/flutterfire/issues/2198

Admob is limiting my ads because of **policy violation**. My app **doesn't have any popup or UI blocking the ad**.

Message from AdMob : 

```
Modified ad code: Resizing Ad Frames
This is a policy violation. You must fix this issue.

MODIFIED ADS: Publishers are not permitted to alter the behavior of Google ads in any way. This includes resizing ad frames to cut off parts of ads or hiding the Ads by Google moniker.
```

I am using the example code with `AdSize.fullBanner`. I even tried to remove any padding in the Container.

```
return Container(
  padding: const EdgeInsets.all(0),
  ...
```

Using `google_mobile_ads: ^0.11.0+3`

Any ideas on how to solve this ?

**Comment by leonardodincalci** [comment]
Same issue.

**Comment by yosus** [comment]
i solved it by submitting to admob asking where exactly is the violation. Their messages are not specific enough.

for my case, when using fullbanner size, there was a black-dot on the ad during Admob's review. None of my real android devices showed it. Since I couldn't replicate it, i change it to smartbanner. Problem solved for my case.

**Comment by sooxt98** [comment]
Same here, im using AdSize.fullBanner too
![image](https://user-images.githubusercontent.com/13378059/118494424-b4991800-b754-11eb-82d8-b10e3b397af3.png)

**Comment by leonardodincalci** [comment]
> Same here, im using AdSize.fullBanner too
> ![image](https://user-images.githubusercontent.com/13378059/118494424-b4991800-b754-11eb-82d8-b10e3b397af3.png)

Change AdSize.fullBanner to AdSize.smartBanner

**Comment by yosus** [comment]
> i have the same problem. I made a few changes and requested a review, but the problem still persists. @yosus how did you contact Google? I need this

you can contact google from your admob page. But the recommended way is to 

- submit a new app, 
- let the app be approved in the store. 
- Then from your admob policy page, click something like 'request review'. 

It will take a few days for them to review it. If it is rejected again, you will see the reason and date. If it passes, there won't be any message to notify you. You will just need to check that policy page daily to see updates.

**Comment by dmrcierhn** [comment]
The help option on the admob page is not working. It keeps saying something went wrong, please try again. Is there any other way for this?

**Comment by maheshmnj** [comment]
Hi @yosus, is this issue still valid as of the latest `google_mobile_ads: 0.13.4`? 

Thanks

**Comment by morio77** [comment]
me too.

**Comment by yosus** [comment]
I am still using `google_mobile_ads: ^0.11.0+3`

I have just updated an app last week. So far, no policy violations. Still using smartBanner for Android.

`...Size:  (defaultTargetPlatform == TargetPlatform.android) ? AdSize.smartBanner : AdSize.smartBannerPortrait,`
