### ISSUE TITLE
[📚] 'com.google.android.gms.ads.formats.UnifiedNativeAdView' is deprecated 

### ISSUE THREAD

**Issue by ramtinq** [googleads/googleads-mobile-flutter#148]
In the documentation example for Native Ads, the section for implementing Native Ad views for Android, the class "UnifiedNativeAdView" is used, which is deprecated.
The exact message is:

`**public final class UnifiedNativeAdView extends FrameLayout** 
 
This class is deprecated. Use NativeAdView.`

I tried to replace it with "NativeAdView" but got lots of build errors. The IDE also tells that "NativeAdView" is deprecated, and should use "NativeAdView" instead.

Would appreciate any clearance about the correct usage of NativeAdView with Flutter without depending on deprecated classes.

Thanks.

**Comment by KotonoSora** [comment]
I also had the same problem, I moved native code from kotlin to java to be able to build apk file.

**Comment by ramtinq** [comment]
Google has even removed the documentation pages for "UnifiedNativeAd":
[https://developers.google.com/android/reference/com/google/android/gms/ads/formats/UnifiedNativeAd](https://developers.google.com/android/reference/com/google/android/gms/ads/formats/UnifiedNativeAd)

Now it gives 404 (Not Found). it's been removed today.

Would be helpful if anyone would implement a NativeAdFactory example with the new "com.google.android.gms.ads.nativead.NativeAd" class.

**Comment by KotonoSora** [comment]
@ramtinq I think we can't do anything else, just only wait for their update documents and pub

**Comment by jjliu15** [comment]
The latest version of the plugin (0.13.0) now supports [NativeAd](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAd).
