### ISSUE TITLE
It is very heavy when add banner Ads to web view implemented with webview_flutter.

### ISSUE THREAD

**Issue by aoboinfo** [googleads/googleads-mobile-flutter#170]
Failed to get fallback IMM with expected displayId=122 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{cd252f1 VFEDHVC.. ........ 0,0-1080,1649}
I/DynamiteModule( 3287): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 3287): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101

**Comment by maheshmnj** [comment]
Hi @aoboinfo, There is already an open issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/32 you may follow up there for further updates closing this issue as a duplicate.
If you disagree feel free to write in the comments and I will reopen it.

Thank you.
