### ISSUE TITLE
[📚] Add Support for app open ads

### ISSUE THREAD

**Issue by see** [googleads/googleads-mobile-flutter#171]
Please Add Support for app open ads

**Comment by bdlukaa** [comment]
I use [native_admob_flutter](https://pub.dev/packages/native_admob_flutter) for it.

**Comment by YuriOliveiraAbel** [comment]
ward

**Comment by malaxmimdkm** [comment]
When flutter team want to develop this feature please tell us.

**Comment by jjliu15** [comment]
Support was added in https://github.com/googleads/googleads-mobile-flutter/pull/337
See integration guide: https://developers.google.com/admob/android/app-open
