### ISSUE TITLE
🐛 [Banner Ad] ad view getting weird floating behavior with serious performance issues when scrolling

### ISSUE THREAD

**Issue by priyanthabuddhika** [googleads/googleads-mobile-flutter#174]
## Bug report

**Describe the bug**
When scrolling on pages that contain banner ads shows weird adview floating behavior with a huge scroll performance drop on the android release version. App just works fine before it loads ads and whenever it loads an ad it is causing this issue. 

![output1](https://user-images.githubusercontent.com/36040643/114755993-e266f780-9d77-11eb-88d3-8f1f31e94a20.gif)

### Steps to reproduce

Minimal code with a banner ad implementation needs to be reproduced this issue is attached below:

<details><summary>Click To Expand</summary>

```
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class CourseListPage extends StatefulWidget {

  CourseListPage();
  @override
  _CourseListPageState createState() => _CourseListPageState();
}

class _CourseListPageState extends State<CourseListPage> {

  BannerAd _ad;
  bool _isAdLoaded = false;


  @override
  void initState() {
    super.initState();

    _ad = BannerAd(
      adUnitId: AdHelper.courseListBannerAdUnitId,
      size: AdSize.mediumRectangle,
      request: AdRequest(),
      listener: AdListener(
        onAdLoaded: (_) {
          setState(() {
            _isAdLoaded = true;
          });
        },
        onAdFailedToLoad: (ad, error) {
          // Releases an ad resource when it fails to load
          ad.dispose();

          print('Ad load failed (code=${error.code} message=${error.message})');
        },
      ),
    );

    _ad.load();
  }

  @override
  Widget build(BuildContext context) {


    return Scaffold(
   
        body: ListView(
          physics: BouncingScrollPhysics(),
          padding: EdgeInsets.zero,
          children: <Widget>[
                SizedBox(height: 5),
              //  Some widgets
                showAd(),
              ] +
              [SizedBox(height: 10)],
        ));
  }

  Widget showAd() {
    if (_isAdLoaded) {
      return Container(
        margin: EdgeInsets.symmetric(vertical: 15),
        child: AdWidget(ad: _ad),
        width: _ad.size.width.toDouble(),
        height: 72.0,
        alignment: Alignment.center,
      );
    } else
      return Container();
  }

  @override
  void dispose() {
    _ad?.dispose();
    super.dispose();
  }
}


```

</details>

---

### Expected behavior

The adview should maintain its position on the screen correctly.

---

## Additional context

When the app is running on AVD it seems to be working fine as excepted.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.55.1)
[✓] Connected device (2 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter pub deps -- --style=compact
Dart SDK 2.12.2
Flutter SDK 2.0.3
freeco 1.0.4+4

dependencies:
- cached_network_image 2.5.1 [flutter flutter_cache_manager octo_image]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- dio 3.0.10 [http_parser path]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_rating_bar 3.2.0+1 [flutter]
- google_mobile_ads 0.12.1 [meta flutter]
- infinite_scroll_pagination 2.3.0 [flutter sliver_tools]
- material_floating_search_bar 0.2.6 [flutter meta]
- provider 4.3.3 [collection flutter nested]
- share 0.6.5+4 [meta mime flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 0.9.7
- nested 0.0.4 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- sky_engine 0.0.99
- sliver_tools 0.1.10+1 [flutter]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 1.3.2+4 [flutter sqflite_common path]
- sqflite_common 1.0.3+3 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
```

</details>

---

**Comment by arunchaudharyweb** [comment]
You are requesting medium rectangle size banner ad. But in the code that you have provided, the height of container is only 72.0. Try increasing the height of the container to 250.0 or request a different size banner ad.

**Comment by priyanthabuddhika** [comment]
> You are requesting medium rectangle size banner ad. But in the code that you have provided, the height of container is only 72.0. Try increasing the height of the container to 250.0 or request a different size banner ad.

Thank you for pointing out that error. I changed my code and provided a bigger size and still get scrolling issues as shown in the below screen record.

![output5](https://user-images.githubusercontent.com/36040643/114842259-50520400-9df6-11eb-9724-0610280383ca.gif)

**Comment by Nader2004** [comment]
I think this is the same as #139. And it may be a problem with the flutter engine itself.

**Comment by priyanthabuddhika** [comment]
> I think this is the same as #139. And it may be a problem with the flutter engine itself.

Yeah, it seems to be a similar issue. Do you have any recommendations about an alternative flutter admob package that works fine for banner ads till this issue get fixed?

**Comment by Nader2004** [comment]
Yeah I think there is the admob_flutter package at : https://pub.dev/packages/admob_flutter/versions/2.0.0-nullsafety.1

But to be honest I haven’t tried it yet in terms of that floating issue. But you can give it a try

**Comment by skchowdhury** [comment]
> > You are requesting medium rectangle size banner ad. But in the code that you have provided, the height of container is only 72.0. Try increasing the height of the container to 250.0 or request a different size banner ad.
> 
> Thank you for pointing out that error. I changed my code and provided a bigger size and still get scrolling issues as shown in the below screen record.
> 
> ![output5](https://user-images.githubusercontent.com/36040643/114842259-50520400-9df6-11eb-9724-0610280383ca.gif)

same as here when i use banner ad bottom of the page or middle of list view it's lagging,slowing down scrolling,this is serious.did u solved ??

**Comment by royibernthal** [comment]
Joining the issue.

On IOS the ad positioning is weirder and sometimes flickers, but there's no noticeable performance issue.

On Android the ad positioning is a bit more stable (though still problematic), but there's a huge drop in performance whenever an ad is displayed inside a scrolled list.

**Comment by priyanthabuddhika** [comment]
> > > You are requesting medium rectangle size banner ad. But in the code that you have provided, the height of container is only 72.0. Try increasing the height of the container to 250.0 or request a different size banner ad.
> > 
> > 
> > Thank you for pointing out that error. I changed my code and provided a bigger size and still get scrolling issues as shown in the below screen record.
> > ![output5](https://user-images.githubusercontent.com/36040643/114842259-50520400-9df6-11eb-9724-0610280383ca.gif)
> 
> same as here when i use banner ad bottom of the page or middle of list view it's lagging,slowing down scrolling,this is serious.did u solved ??

I used another package named [native_admob_flutter](https://pub.dev/packages/native_admob_flutter) and it just works fine so far.
