### ISSUE TITLE
Problem with google mobile ads errors(make the app exit )

### ISSUE THREAD

**Issue by ninehichem** [googleads/googleads-mobile-flutter#176]
## Bug report

Problem with Google mobile ads 
when i add Bannerad i get error 2 as you see in the picture below :

and i have a good connection .
<details>
<summary>Code screenshots</summary>

![adfailed2](https://user-images.githubusercontent.com/36598259/114895424-58914b80-9dc4-11eb-910f-abdd6f171f27.PNG)

then i wanted to use Intertialad and Rewardedvideoad but when i click on button for exemple to see the ads
the app exit and i lose connection to device  as you can see in the picture below:

![problempig](https://user-images.githubusercontent.com/36598259/114895733-97bf9c80-9dc4-11eb-9d01-1c9dee18638e.png)

so This is my initstate : 

![initstate](https://user-images.githubusercontent.com/36598259/114895867-b160e400-9dc4-11eb-8aa4-9f17c241d390.PNG)
my main.dart:

![maindart](https://user-images.githubusercontent.com/36598259/114895901-b756c500-9dc4-11eb-8234-2c32c36a8b9e.PNG)

</details>

What i tried : 
flutter clean
upgrade flutter 
upgrade android studio
open new project
upgrade gradle to latest version
nothing happen ..
looking for solution thanks .

### Flutter doctor

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1500], locale en-US)
    • Flutter version 2.0.4 at D:\src\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\everythingAndroid\Android_SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\everythingAndroid\Android_SDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
---

**Comment by nilotpalkapri** [comment]
I am also facing the same issue with interstitial ad, implemented exactly as in example.

**Comment by dsdsharma** [comment]
I am having the same issue with interstitial ads, banner ads are working fine but when i try to load interstitial ad it crashes the app.
I am getting an error log like this
![Screenshot 2021-04-25 230412](https://user-images.githubusercontent.com/35690440/116003193-a0ad3b00-a61a-11eb-89c3-0c1edcab8ba3.png)

**Comment by ninehichem** [comment]
> I am having the same issue with interstitial ads, banner ads are working fine but when i try to load interstitial ad it crashes the app.
> I am getting an error log like this
> ![Screenshot 2021-04-25 230412](https://user-images.githubusercontent.com/35690440/116003193-a0ad3b00-a61a-11eb-89c3-0c1edcab8ba3.png)

the same problem me to stil didnt find a solution, while iam previous app , i worked with admobfirebase and its working fine !
but when i tried to use the same code in my last app it crashe .
i think the problem is with new update..

**Comment by dsdsharma** [comment]
Any updates on the Solution?

**Comment by ninehichem** [comment]
> Any updates on the Solution?

didnt Find a solution stil waiting :(

**Comment by Klein-Kodes** [comment]
> didnt Find a solution stil waiting :(

I have the exact same issue too.

**Comment by kk-boss** [comment]
Me too faced the same error. Banner Ads work fine when I try to show Intrestrial Ads, The emulator closes and I lost connection to the device. Banner Ads work fine.

**Comment by jjliu15** [comment]
In latest major update of GMA (20.0.0), InterstitialAd was moved from `com.google.android.gms.ads` to `com.google.android.gms.ads.interstitital`. Looks like the error is related to that. Could you check that your `build.gradle` is not refencing an older version of play-services-ads, or try updating your gradle version?

**Comment by maheshmnj** [comment]
Hi @ninehichem, Thanks for filing the issue, please try the solution mentioned by @jjliu15, If you the issue still persists feel free to write back with more details 
 - flutter doctor -v
 - version of the ads plugin
 - [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) 

 Thanks
