### ISSUE TITLE
Support for minSdkVersion 16 and above

### ISSUE THREAD

**Issue by talent-apps** [googleads/googleads-mobile-flutter#178]
## Bug report

The `minSdkVersion` of the plugin is set to 19, hence making it unavailable for ~2% to 3% of Android devices in the market.
After inspecting the plugin's code, only `FlutterServerSideVerificationOptions` class uses APIs that require API version 19:
`Objects.equals` and `Objects.hash`. Both can be easily replaced with other implementations that will not force increasing `minSdkVersion`.

### Expected behavior

The plugin should be available for API 16 and above exactly like the native Android Firebase SDK.
 See the official [Android Firebase docs](https://firebase.google.com/docs/android/setup).

**Comment by computerzman** [comment]
We hope google to support at least minSDKVersion 16 or 17

**Comment by jjliu15** [comment]
This plugin's minSdkVersion is constricted by PlatformView support. There are no plans to support API 16, as the latest GMA android release also dropped support for API 16: https://developers.google.com/admob/android/migration#minsdkversion
