### ISSUE TITLE
🐛 Deprecated API usage on Android

### ISSUE THREAD

**Issue by talent-apps** [googleads/googleads-mobile-flutter#179]
## Deprecated API usage

The Android code of the plugin (version `0.12.1+1`) has 75 deprecated API usages.
Some examples are: 
- `com.google.android.gms.ads.InterstitialAd` is deprecated
- `com.google.android.gms.ads.formats.UnifiedNativeAdView` is deprecated
- `addTestDevice` is deprecated

**Comment by jjliu15** [comment]
Deprecated API warnings should be fixed in v0.13.2.
