### ISSUE TITLE
Question: How i can know if a rewarded ad is loaded?

### ISSUE THREAD

**Issue by Hakentha** [googleads/googleads-mobile-flutter#188]
I call myRewarded.load() (with or without await) and then myRewarded.show(), but allways have "ad no loaded".
(Note: if i call myRewarded.show() after a couple of seconds the video shows perfect).

I try to use the method myRewarded.isLoaded(), but is for other thing. (only change to true when the reward is taken)

I apreciate ur help!!

**Comment by yusuf-khamis** [comment]
AdListener has an `onAdLoaded` function that is called when ad is loaded, see snippet below

```
final AdListener listener = AdListener(
 // Called when an ad is successfully received.
 onAdLoaded: (Ad ad) => print('Ad loaded.'),
 // Called when an ad request failed.
 onAdFailedToLoad: (Ad ad, LoadAdError error) {
   ad.dispose();
   print('Ad failed to load: $error');
 },
 // Called when an ad opens an overlay that covers the screen.
 onAdOpened: (Ad ad) => print('Ad opened.'),
 // Called when an ad removes an overlay that covers the screen.
 onAdClosed: (Ad ad) {
   ad.dispose();
   print('Ad closed.');
 },
 // Called when an ad is in the process of leaving the application.
 onApplicationExit: (Ad ad) => print('Left application.'),
);
```

**Comment by Hakentha** [comment]
I apréciate ur response. i call a funtion in onAdLoaded, with ad; and then call the show(), and work perfect!!

Thank you!!!
