### ISSUE TITLE
Poor performance with `google_mobile_ads`.

### ISSUE THREAD

**Issue by AndersonFiorini** [googleads/googleads-mobile-flutter#189]
I am having severe performance problems when a banner or a rewarded is loaded. Smartphones like Galaxy S10 and newer, the performance does not drop so much, however average smartphones the problems are severe, causing crashes. The very example of using this plugin that was made available by Google on GitHub is experiencing performance problems on average smartphones.

**Comment by jangruenwaldt** [comment]
+1 please... this needs to be fixed, as in current state, this plugin is unusable. Who wants to get spammed with 1* reviews because the app is super laggy suddenly? Its impossible to test this for all devices

**Comment by armandojimenez** [comment]
Any fix for this?

**Comment by guidospadavecchia** [comment]
I agree with @jangruenwaldt , the plugin in it's current state cannot be used. Google really needs to fix this ASAP. I won't use `google_mobile_ads` like this and ruin my app.

**Comment by sageata** [comment]
> Any fix for this?

@armandojimenez, I downgraded to ```0.12.1```  by removing ```^``` and the performance issues have disappeared.

I this they will fix this before Google I/O. It seems they have a very big release in the pipeline.

**Spoiler alert**

They will be introducing Rewarded Interstitials

**Comment by shofizone** [comment]
Teue. 
App is super laggy in all of the low end devices or little older smart phone. Peoples are complaining about app performance. This issue should have heigh priority.

**Comment by jangruenwaldt** [comment]
> Teue.
> App is super laggy in all of the low end devices or little older smart phone. Peoples are complaining about app performance. This issue should have heigh priority.

Yeah this plugin is unusable. I recomnend you to switch to `native_admob_flutter` if you want to make your app usable for more than high end devices. A third party developer makes a better plugin than Google. Strange world.

**Comment by blasten** [comment]
Platform views come with some performance tradeoffs: https://flutter.dev/docs/development/platform-integration/platform-views#performance

We are constantly looking for ways to improve performance, and this feedback this valuable for future improvements.

**Comment by blasten** [comment]
Thanks for the feedback. We are constantly looking for ways to improve. 

Our [docs](https://flutter.dev/docs/development/platform-integration/platform-views#performance) explains the issues that you are seeing.

Performance is better on Android 10, and it will continue to get better as more users upgrade. (Currently at 35.3%, but rapidly [growing](https://www.appbrain.com/stats/top-android-sdk-versions)).

**Comment by shofizone** [comment]
@blasten You should check performance in mid and low-budget android, which has an android version below android 10.  The app is almost unusable on those devices. Because of horrible performance we have to disable ads in low-end old devices. We can't depend on 35.3%. 
....   Thanks.

**Comment by blasten** [comment]
@shofizone understood. One workaround is to use the `device_info` plugin to obtain the Android version, and add the widget to the tree if the Android version is least 10.

**Comment by blasten** [comment]
We have added a flag to the Flutter master channel that helps improve the performance. 

It's not a perfect fix since the Ad may be a few frames behind the Flutter frame, but depending on the layout you use, it could be useful.  

Please try it out, and let us know if the performance is improved.

To use this flag, set `PlatformViewsService.synchronizeToNativeViewHierarchy(false)`.  For example: 

```dart
import 'package:flutter/services.dart';

void main() {
   PlatformViewsService.synchronizeToNativeViewHierarchy(false);
   runApp(MyApp());
}
```

I'm closing this issue, and moving the conversation to: https://github.com/googleads/googleads-mobile-flutter/issues/269
