### ISSUE TITLE
Support for Rewarded Interstitial Ads 

### ISSUE THREAD

**Issue by sunjianan9900** [googleads/googleads-mobile-flutter#190]
This is a new ads format. Hope you can support it:
https://developers.google.com/admob/android/rewarded-interstitial
https://developers.google.com/admob/ios/rewarded-interstitial

**Comment by bdlukaa** [comment]
I use [native_admob_flutter](https://pub.dev/packages/native_admob_flutter) for this.

**Comment by sageata** [comment]
Any update or plan to support this?

**Comment by armandojimenez** [comment]
Any updates?

**Comment by edscodeblenders** [comment]
We would love to try this as well.

**Comment by maheshmnj** [comment]
Labelling the issue as a valid feature request.

**Comment by pyaehein** [comment]
Any update or plan?

**Comment by srichakradhar** [comment]
Added support for [Rewarded Interstitial](https://support.google.com/admob/answer/9884467) (beta) in [PR#489](https://github.com/googleads/googleads-mobile-flutter/pull/489). Minimum supported version: [1.1.0](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/CHANGELOG.md#110)
