### ISSUE TITLE
Include example of migrating from firebase_admob

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#192]
Include a similar migration guide as shown in [firebase_admob](https://pub.dev/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).

From: https://github.com/googleads/googleads-mobile-flutter/discussions/118 (now inaccessible)
"On firebase_admob package i just did a banner ad and it just shows on all screens of the app. How do i manage ads now with googleads_mobile_flutter package once i need create ad on the page and put inside a widget, when i go to the next page the ad is not there, do i need close the first one and create another one on the new page? and if yes, when i back to the first page, need i close the ad on the new page then back and load it again on the first page? i am confuse.

Thanks in advance."

**Comment by maheshmnj** [comment]
Hi @bparrishMines, Is this issue still valid provided that we have code labs and documentation well written for each ad.

PS:  the discussion link is broken.

Thanks.

**Comment by bparrishMines** [comment]
Since the plugin has now been out 5 months, this should no longer be necessary. Users will still have access to https://pub.dev/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter if they would like to see a relatively recent example. 

cc @jjliu15
