### ISSUE TITLE
Flutter google_mobile_ads only not working in android 7 API level 25.

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#193]
@SourabhMahale98

Transfer from: https://github.com/googleads/googleads-mobile-flutter/discussions/162 (now inaccessible)

As I wanted to show native ads in my app I use this package google_mobile_ads. It works very well in all devices except one android 7 with API 25. only for that device, it will show error like
`AdWidget requires Ad.load to be called before AdWidget is inserted into the tree.`

**Comment by maheshmnj** [comment]
Hi @bparrishMines, Is this issue still valid as of today using the latest ads plugin `0.13.4` ? If yes please share the output of 
`flutter doctor -v` .

Thanks

**Comment by bparrishMines** [comment]
@maheshmnj I believe this is no longer valid. The `AdWidget` error should be expected behavior.

@SourabhMahale98 Feel free to reopen/leave a comment if you are still experiencing this error with the latest version of the plugin. And also provide a small example of how to reproduce the error.

**Comment by maheshmnj** [comment]
Thanks for the confirmation.

**Comment by CripyIce** [comment]
This issue seems to happen again on **iPhone 12 Pro (iOS 14.8.1)**:
`AdWidget requires Ad.load to be called before AdWidget is inserted into the tree. Error thrown Instance of 'ErrorDescription'.`

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (2 available)

• No issues found!
```

`google_mobile_ads: 1.0.1`

**Comment by maheshmnj** [comment]
Hi @CripyIce, Could you please file a separate issue with all the details requested in the issue template.
