### ISSUE TITLE
[Feature Request] Add Mediation Support

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#194]
@mnarinsky Transfer from: https://github.com/googleads/googleads-mobile-flutter/discussions/31

This is a feature request to add support for AdMob and AdManager mediation to the GMA SDK for Flutter.

Mediation increases mobile apps revenue by calling a series of third-party ad networks to fill an ad request, ordered by expected yield. The request is to support all Google certified third party mediation networks supported by AdMob and Google Ad Manager:

- [AdMob iOS Mediation Partners](https://developers.google.com/admob/ios/mediate)
- [AdMob Android Mediation Partners](https://developers.google.com/admob/android/mediate)
- [Ad Manager iOS Mediation Partners](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/mediate)
- [Ad Manager Android Mediation Partners](https://developers.google.com/ad-manager/mobile-ads-sdk/android/mediate)

**Comment by kunny** [comment]
@bparrishMines @mnarinsky

I'm using my own plugin for Facebook (https://github.com/kunny/googleads-mobile-flutter/tree/add_facebook_mediation/packages/google_mobile_ads_facebook) which depends on:
- Android: `'com.google.ads.mediation:facebook:6.3.0.1'`
- iOS: `'GoogleMobileAdsMediationFacebook', '6.0.0.0'`

As I intended to use this plugin just for my personal application, it needs a few more work (e.g., version matching, documentation) to be as a part of the official plugin.

I'm happy to contribute at least for the Facebook plugin if you don't mind. :)

**Comment by mathalaichandar** [comment]
Is there a way we could do admediation for adcolony as well? the existing methods given were failing.

**Comment by theeomm** [comment]
Any update on this?

**Comment by MattyBoy4444** [comment]
What is going on with Mediation and Adapters??

**Comment by MaximeDelhorme** [comment]
Any news on this request?

**Comment by MattyBoy4444** [comment]
[https://github.com/googleads/googleads-mobile-flutter/issues/355](https://github.com/googleads/googleads-mobile-flutter/issues/355)

**Comment by jjliu15** [comment]
Closing as we now have mediation support: https://developers.google.com/admob/flutter/mediation/get-started
