### ISSUE TITLE
Navigator.pop() ... frame rate falls

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#197]
@hojuni Transfer from discussion to issue

Hello
I'm exposing the banner in the place where it's moved toward Navigator.push(). The problem is that the frame rate falls during Navigator.pop(), which causes the afterimage to be seen and the banner to disappear late. Is there a way to solve this problem?

**Comment by maheshmnj** [comment]
Hi @bparrishMines, I am not sure I understand the issue, Is this for internal tracking? if not could you please describe the issue with the exact steps.

Thanks.

**Comment by bparrishMines** [comment]
@maheshmnj I copied from a Github discussion when we removed all of them from the repo. 

@hojuni Do you have sample code to reproduce this performance bug?
