### ISSUE TITLE
App removed from Google play alleged Ad Fraud....

### ISSUE THREAD

**Issue by samutec1** [googleads/googleads-mobile-flutter#198]
I've received a notification on my App saying that my app infringes the Google play police "AD Fraud", but I'm not doing anything wrong, do you guys have facing something like that?

**Comment by amrmuhamed200** [comment]
i'm facing the same problem my app got accepted a weeks ago but now i can't upload any new update the store keeps rejecting the app for AD Fraud idk why

**Comment by samutec1** [comment]
> i'm facing the same problem my app got accepted a weeks ago but now i can't upload any new update the store keeps rejecting the app for AD Fraud idk why

Im using the oficial Api from Google, now my update  worked, what I needed to do?, I was using a Interstitial when the app was opened, I needed to put a dialog showing to the user that was going to appears an Interstitial, I needed to verify how many requests my App was getting when the Api request an Ads, because if your App get an Ad Request in background and doesn’t show an Ads it’s AdFraud too, please verify if your App is doing that.

**Comment by amrmuhamed200** [comment]
> > i'm facing the same problem my app got accepted a weeks ago but now i can't upload any new update the store keeps rejecting the app for AD Fraud idk why
> 
> Im using the oficial Api from Google, now my update worked, what I needed to do?, I was using a Interstitial when the app was opened, I needed to put a dialog showing to the user that was going to appears an Interstitial, I needed to verify how many requests my App was getting when the Api request an Ads, because if your App get an Ad Request in background and doesn’t show an Ads it’s AdFraud too, please verify if your App is doing that.

I have implemented the interstitial to load when the app loads but it will then been shown to the user after 90 sec and load another one after the first one is closed and so on. does that recognized as Ad Fraud ? if so my first production release was approve and i didn't change any thing in the update for that part. but my updates keep rejected

**Comment by EArminjon** [comment]
https://github.com/googleads/googleads-mobile-flutter/issues/211

Maybe it's about that.

**Comment by maheshmnj** [comment]
@samutec1 is this issue resolved ?
