### ISSUE TITLE
Cannot compile and run app in Android  (A problem occurred configuring project ':google_mobile_ads')

### ISSUE THREAD

**Issue by vivekwebdesk** [googleads/googleads-mobile-flutter#202]
### Describe the bug
I can't seem to run my app on Android

Steps to reproduce

Add google_mobile_ads to pubspec.yaml
Pull dependencies
Run app for Android

### Expected behavior
Should compile normally and run in emulator/device

### This is the output:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_mobile_ads'.
> Could not open cp_proj generic class cache for build file '/home/vivek/.pub-cache/hosted/pub.dartlang.org/google_mobile_ads-0.12.1+1/android/build.gradle' (/home/vivek/.gradle/caches/6.5/scripts/7x7fiwv0i2hn1byd30c4dxq3h/cp_proj6418c6d726070f323dbddda2aadc82ef).
   > Unexpected lock protocol found in lock file. Expected 3, found 0.
> Could not get unknown property 'android' for project ':google_mobile_ads' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by maheshmnj** [comment]
Hi @vivekwebdesk, Thanks for filing the issue. Please share the output of `flutter doctor -v` and the version of the ads plugin that you are using and the complete output of `flutter run -v` to better address the issue.

Thanks
