### ISSUE TITLE
iOS: there are Ad requests but no impressions on my released App

### ISSUE THREAD

**Issue by Andro-Samurai** [googleads/googleads-mobile-flutter#203]
v0.12.1+1
iOS only (Android is working properly)
test Ads work correctly
the app is released more than 1 week ago

**Comment by stelselim** [comment]
I have the same problem, too. I published the app on App Store 2 weeks ago.  Still, interstitial ads does not show up.

**Comment by leonardodincalci** [comment]
same issue for me

**Comment by marcio-ota** [comment]
+1

**Comment by leonardodincalci** [comment]
> v0.12.1+1
> iOS only (Android is working properly)
> test Ads work correctly
> the app is released more than 1 week ago

Did you solve?

**Comment by marcio-ota** [comment]
v0.12.2 same problem...
(AdMob don't find my app in store, 10 days published only to Brazil)

**Comment by 159159951** [comment]
Same here.
So said!

**Comment by 159159951** [comment]
It is worked after I link my app with Apple Store.
It take 2-3 hours after link app in Admob with Apple Store to serve my ad request.
https://support.google.com/admob/answer/9989980
![image](https://user-images.githubusercontent.com/11333632/122211686-348bdc80-ced1-11eb-80da-8877d138116e.png)

**Comment by andynvt** [comment]
> It is worked after I link my app with Apple Store.
> It take 2-3 hours after link app in Admob with Apple Store to serve my ad request.
> 
> ![image](https://user-images.githubusercontent.com/11333632/122213683-67cf6b00-ced3-11eb-83c1-01d0f2f281c8.png)
> 
> https://support.google.com/admob/answer/9989980

when does your app available in the search form of Admob website? I can't find my app in this form (Ready for Sale - released)
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/26719596/123440795-5dad1b00-d5fd-11eb-9f40-df3d4a9109c2.png">

**Comment by maheshmnj** [comment]
HI @Andro-Samurai, Thanks for filing the issue, Is this issue still reproducible with the latest ads plugin `0.13.4`?

Thanks

**Comment by Andro-Samurai** [comment]
> HI @Andro-Samurai, Thanks for filing the issue, Is this issue still reproducible with the latest ads plugin `0.13.4`?
> 
> Thanks

the issue was resolved, thanks

**Comment by maheshmnj** [comment]
Thanks for the confirmation. Provided your last message, I feel it's safe to close the issue. Anyone who is still facing a similar issue feel free to file a new issue with the exact steps and the information requested in the issue template.
Closing this issue as fixed.

Thanks
