### ISSUE TITLE
Bug When execute after kill operations like notification

### ISSUE THREAD

**Issue by mustafa-707** [googleads/googleads-mobile-flutter#206]
## Issue : 

After upgrading to flutter 2 , my notification system based on firebase ,  begin to have issues after killing the app , which when  press on notification the app not getting any data from the notification , i already made an issue in `firebase_messaging` ,So when i push to a screen and that screen have an interstitial Ads , the close button of the interstitial Ads make pop to the screen  , So i got it back to flutter 1.66.2 to run the app smoothly and this's my plugins used in my project and all flutter doctor is give me √  , and the app still running good except this issue :

```
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_messaging: ^9.1.3
  google_mobile_ads: ^0.12.1+1
```

**Comment by maheshmnj** [comment]
Hi @mustafa-707  is this issue fixed?

**Comment by mustafa-707** [comment]
@maheshmnj  yes ,the problem came from an old plugin named `apns_config` and when it removed the problem solved
