### ISSUE TITLE
Test ad not working in iOS

### ISSUE THREAD

**Issue by casualcoder404** [googleads/googleads-mobile-flutter#209]
Whenever I run my app, I am getting following error with no ad:

<Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];
flutter: ###### Ad failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show.)

**Comment by zenkog** [comment]
Got the same problem. +1

**Comment by casualcoder404** [comment]
I tried adding my physical iphone as test device on admob console but issue is still there.

Also the following documentation says that iOS simulators doesn't need any id , however i am getting same output in simulator as well. With only difference that in place of kGADSimulatorID I'm getting @[ @"e09a______________________" ];

documentation link: https://developers.google.com/admob/ios/test-ads#enable_test_devices

**Comment by sultanmyrza** [comment]
## To set simulator id you can try 
```
GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ kGADSimulatorID as! String ];
```
## also try to upgrade  google_mobile_ads
in `pubspec.yaml`
```
dependencies:
  flutter:
    sdk: flutter
  # google_mobile_ads: ^0.12.0
  google_mobile_ads: ^0.12.2
```

**Comment by corymalcolmtaylor** [comment]
Test interstitial ads on ios simulator are failing to load for me, i get this error:
` flutter: InterstitialAd failed to load: LoadAdError(code: 9, domain: com.google.admob, message: Request Error: No ad to show from all configured ad networks., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))`
I was using this unit id: /6499/example/interstitial     
I have tried it with my own app id and the test app id `ca-app-pub-3940256099942544~1458002511 `
For the test ads what SKAdNetworkIdentifier do we need this thats what is missing?

I also sometimes see this message: 
`<Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];`  -- where do we put that code if I am to do so on the simulator?

and this: 
`[Firebase/Crashlytics][I-CLS000000] Warning: NSUncaughtExceptionHandler is 'GADRegisterExceptionHandler' in ....`

**Comment by byferdi42** [comment]
i have the same problem in interstitial ad

**Comment by byferdi42** [comment]
i have the same problem in interstitial ad

output

`To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"" ];

flutter: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))`

**Comment by maheshmnj** [comment]
Hi, @casualcoder404 Thanks for filing the issue, please share a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v`,  Is the issue on IOS simulator or real device? Also please share the complete logs of `flutter run -v` in a text file.

Thank you.

**Comment by maheshmnj** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by cgutierr-zgz** [comment]
U might want to change the kGADSimulatorID to GADSimulatorID
`GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]`

**Comment by adsazad** [comment]
do i have to remove ` GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ kGADSimulatorID ]` this in production code?
