### ISSUE TITLE
NativeAd not loading in release mode

### ISSUE THREAD

**Issue by FetFrumos** [googleads/googleads-mobile-flutter#216]
I use google_mobile_ads in my flutter app. In debug mode, the test advertisement is loaded. For debug I use NativeAd.testAdUnitId. I have build the application in release mode(apk for Android), when loading ads I get an error - Error loading NativeAd.
This is my code(I took this from an example):

 `
        return FutureBuilder<NativeAd>(
        future: nativeAdCompleter.future,
        builder: (BuildContext context, AsyncSnapshot<NativeAd> snapshot) {
        Widget child;

        switch (snapshot.connectionState) {
          case ConnectionState.none:
          case ConnectionState.waiting:
          case ConnectionState.active:
            child = Container();
            break;
          case ConnectionState.done:
            if (snapshot.hasData) {
              child = AdWidget(ad: _nativeAd);
            } else {
              child = Text('Error loading $NativeAd');
            }
        }
`
means snapshot.hasData == false, 

I checked the id - it is correct. any ideas how I can fix this problem?
Any suggestions I will be grateful

**Comment by arunchaudharymax** [comment]
What is nativeAdCompleter.future? Please provide more information.

**Comment by aoboinfo** [comment]
In release mode, no ads.
Ads only show after download from Play store.

**Comment by TusharPatel18** [comment]
> In release mode, no ads.
> Ads only show after download from Play store.

Test ads always shows in debug or release

**Comment by jjliu15** [comment]
@FetFrumos can you share error logs from when the ad fails to load, and also any details in the `LoadAdError` that is returned when the ad fails to load callback?

**Comment by maheshmnj** [comment]
@FetFrumos, could you please try the solutions mentioned here and see if this works https://stackoverflow.com/a/61539203/8253662
