### ISSUE TITLE
I follow 'codelab for inline ads in Flutter ' to create a native ads, but not work at all.

### ISSUE THREAD

**Issue by aoboinfo** [googleads/googleads-mobile-flutter#221]
## Plugin Version
google_mobile_ads: ^0.12.1+1

Android studio 4.2

when create the class

import com.google.android.gms.ads.formats.UnifiedNativeAd
import com.google.android.gms.ads.formats.UnifiedNativeAdView
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory;

class ListTileNativeAdFactory (val context: Context) : NativeAdFactory {
  *****
}

//the IDE can not find :'GoogleMobileAdsPlugin.NativeAdFactorya' at all
when I add it by hand, show red color to me.

When executed,  failed with ava.lang.ClassCastException

D/DynamitePackage(16314): Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
I/Ads     (16314): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("68B79BBE7F23CCD028B7F89C67517F9D")) to get test ads on this device.
I/DynamiteModule(16314): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule(16314): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
D/DynamitePackage(16314): Instantiating com.google.android.gms.ads.ChimeraNativeAdViewDelegateCreatorImpl
D/AndroidRuntime(16314): Shutting down VM
E/AndroidRuntime(16314): FATAL EXCEPTION: main
E/AndroidRuntime(16314): Process: com.aobocorp.chinesepinyin, PID: 16314
E/AndroidRuntime(16314): java.lang.ClassCastException: com.google.android.gms.ads.nativead.NativeAdView cannot be cast to com.google.android.gms.ads.formats.UnifiedNativeAdView
E/AndroidRuntime(16314): 	at com.aobocorp.chinesepinyin.ListTileNativeAdFactory.createNativeAd(ListTileNativeAdFactory.kt:15)
E/AndroidRuntime(16314): 	at io.flutter.plugins.googlemobileads.FlutterNativeAd$2.onUnifiedNativeAdLoaded(FlutterNativeAd.java:165)
E/AndroidRuntime(16314): 	at com.google.android.gms.internal.ads.zzahh.zza(com.google.android.gms:play-services-ads-lite@@19.7.0:6)
E/AndroidRuntime(16314): 	at com.google.android.gms.internal.ads.zzagj.zza(com.google.android.gms:play-services-ads-lite@@19.7.0:18)
E/AndroidRuntime(16314): 	at com.google.android.gms.internal.ads.zzgy.onTransact(com.google.android.gms:play-services-ads-base@@19.7.0:13)
E/AndroidRuntime(16314): 	at android.os.Binder.transact(Binder.java:1043)
E/AndroidRuntime(16314): 	at gc.bb(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
E/AndroidRuntime(16314): 	at com.google.android.gms.ads.internal.formats.client.ak.e(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
E/AndroidRuntime(16314): 	at com.google.android.gms.ads.nonagon.ad.nativead.ad.run(Unknown Source:5)
E/AndroidRuntime(16314): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(16314): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16314): 	at qy.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
E/AndroidRuntime(16314): 	at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:1)
E/AndroidRuntime(16314): 	at qy.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
E/AndroidRuntime(16314): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(16314): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(16314): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(16314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by aoboinfo** [comment]
java.lang.ClassCastException: com.google.android.gms.ads.nativead.NativeAdView cannot be cast to com.google.android.gms.ads.formats.UnifiedNativeAdView

**Comment by SharatAlwyn** [comment]
follow the example file it works fine.

**Comment by aoboinfo** [comment]
> follow the example file it works fine.

I can not  import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin

How did you fix this problem?

**Comment by SharatAlwyn** [comment]
The code will work even if it is in red color, I followed this example app https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example. Hope this will help.

**Comment by aoboinfo** [comment]
> The code will work even if it is in red color, I followed this example app https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example. Hope this will help.

Thank you very much for your reply, I know passing compile is no problem, but I run it, there follow error
The latest Ads sdk ver. 20 has different interface with the sample.

java.lang.ClassCastException: com.google.android.gms.ads.nativead.NativeAdView cannot be cast to com.google.android.gms.ads.formats.UnifiedNativeAdView

**Comment by aoboinfo** [comment]
> The code will work even if it is in red color, I followed this example app https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example. Hope this will help.

It turned out that I used  com.google.android.gms.ads.nativead.NativeAdView
in my layout.xml.

when I replaced it with com.google.android.gms.ads.formats.UnifiedNativeAdView, the native ads shows normally.

Thank you very much.
