### ISSUE TITLE
Please add "setAppMuted" & "setAppVolume" functions.

### ISSUE THREAD

**Issue by erickcchoi** [googleads/googleads-mobile-flutter#236]
## Use case

Need functions to mute or adjust audio volume when showing interstitial ads with video.

## Proposal

Please add "setAppMuted" function to mute the audio during showing interstitial ads.
Please add "setAppVolume" function to adjust the audio volume during showing interstitial ads.

**Comment by D3m1tx** [comment]
This improvement should be a priority. 

I have users who rate my apps negatively only for this reason.

**Comment by maheshmnj** [comment]
Closing as already fixed.
