### ISSUE TITLE
Conflict dependencies

### ISSUE THREAD

**Issue by kietdinh** [googleads/googleads-mobile-flutter#238]
I got error:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':google_mobile_ads:compileDebugAidl'.
> The library com.google.android.gms:play-services-ads-base is being requested by various other libraries at [[20.0.0,20.0.0]], but resolves to 19.7.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

I'm using `classpath 'com.google.gms:google-services:4.1.0'`

**Comment by syedecryptr** [comment]
working fine with : `classpath 'com.google.gms:google-services:4.3.5'`

**Comment by jjliu15** [comment]
It looks like you have a conflict in your dependencies using different versions of play-services-ads. 

Can you share your `build.gradle` and also which version of the plugin are you using? 

v0.13.0 bumped the GMASDK dependencies to the latest major version, so you could also try migrating to the latest version of the plugin.

**Comment by maheshmnj** [comment]
@kietdinh Please share the output of `flutter doctor -v` and also can you try with `classpath 'com.google.gms:google-services:4.3.5' as suggested above.

> working fine with : classpath 'com.google.gms:google-services:4.3.5'
