### ISSUE TITLE
Google mobile ads still depends on the archaic Google-Mobile-Ads-SDK 7.69.0

### ISSUE THREAD

**Issue by hicnar** [googleads/googleads-mobile-flutter#241]
Is there any particular reason why this package still depends on Google-Mobile-Ads-SDK = 7.69.0 ?

After the recent release of google_analytics this is what I am getting (and I guess it is not only me)

CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 7.1.1, which depends on
      Firebase/Analytics (= 8.0.0) was resolved to 8.0.0, which depends on
        Firebase/Core (= 8.0.0) was resolved to 8.0.0, which depends on
          FirebaseAnalytics (~> 8.0.0) was resolved to 8.0.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 8.0.0) was resolved to 8.0.0, which depends on
              GoogleAppMeasurement (= 8.0.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 7.69.0) was resolved to 7.69.0, which depends on
        GoogleAppMeasurement (~> 7.0)

**Comment by jjliu15** [comment]
Version 0.13.0 of the plugin now supports 8.5.0 for iOS and 20.1.0 on Android.
