### ISSUE TITLE
My application stopped launching after switching to version 0.13.

### ISSUE THREAD

**Issue by ale-getman** [googleads/googleads-mobile-flutter#246]
## Plugin Version

google_mobile_ads: ^0.13.0

## Steps to Reproduce

My application stopped launching after switching to version 0.13.

<details>
  <summary>Logs</summary>

[+2636 ms] E/AndroidRuntime(16226): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(16226): Process: com.braingames.braintraining, PID: 16226
[        ] E/AndroidRuntime(16226): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/reward/RewardedVideoAdListener;
[        ] E/AndroidRuntime(16226):     at com.shatsy.admobflutter.AdmobFlutterPlugin.<clinit>(Unknown Source:0)
[        ] E/AndroidRuntime(16226):     at com.shatsy.admobflutter.AdmobFlutterPlugin.registerWith(Unknown Source:0)
[        ] E/AndroidRuntime(16226):     at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
[        ] E/AndroidRuntime(16226):     at com.braingames.braintraining.MainActivity.configureFlutterEngine(MainActivity.kt:23)
[        ] E/AndroidRuntime(16226):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
[        ] E/AndroidRuntime(16226):     at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
[        ] E/AndroidRuntime(16226):     at android.app.Activity.performCreate(Activity.java:7458)
[        ] E/AndroidRuntime(16226):     at android.app.Activity.performCreate(Activity.java:7448)
[        ] E/AndroidRuntime(16226):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
[        ] E/AndroidRuntime(16226):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
[        ] E/AndroidRuntime(16226):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
[        ] E/AndroidRuntime(16226):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
[        ] E/AndroidRuntime(16226):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/AndroidRuntime(16226):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/AndroidRuntime(16226):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
[        ] E/AndroidRuntime(16226):     at android.os.Handler.dispatchMessage(Handler.java:112)
[        ] E/AndroidRuntime(16226):     at android.os.Looper.loop(Looper.java:216)
[        ] E/AndroidRuntime(16226):     at android.app.ActivityThread.main(ActivityThread.java:7625)
[        ] E/AndroidRuntime(16226):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(16226):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
[        ] E/AndroidRuntime(16226):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
[        ] E/AndroidRuntime(16226): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.reward.RewardedVideoAdListener" on
path: DexPathList[[zip file
"/data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw=
=/lib/arm64, /data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
[        ] E/AndroidRuntime(16226):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
[        ] E/AndroidRuntime(16226):     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[        ] E/AndroidRuntime(16226):     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[        ] E/AndroidRuntime(16226):     ... 21 more

```
```

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.6 19G2021 darwin-x64, locale ru-RU)
    • Flutter version 2.2.0 at /Users/ag/Documents/flutter
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ag/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • BND L21 (mobile) • xxx • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
```

</details>

**Comment by romarito** [comment]
Mine too. The error is "MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)"

**Comment by EArminjon** [comment]
> ## Plugin Version
> google_mobile_ads: ^0.13.0
> 
> ## Steps to Reproduce
> My application stopped launching after switching to version 0.13.
> 
> Logs
> [+2636 ms] E/AndroidRuntime(16226): FATAL EXCEPTION: main
> [ ] E/AndroidRuntime(16226): Process: com.braingames.braintraining, PID: 16226
> [ ] E/AndroidRuntime(16226): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/reward/RewardedVideoAdListener;
> [ ] E/AndroidRuntime(16226): at com.shatsy.admobflutter.AdmobFlutterPlugin.(Unknown Source:0)
> [ ] E/AndroidRuntime(16226): at com.shatsy.admobflutter.AdmobFlutterPlugin.registerWith(Unknown Source:0)
> [ ] E/AndroidRuntime(16226): at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
> [ ] E/AndroidRuntime(16226): at com.braingames.braintraining.MainActivity.configureFlutterEngine(MainActivity.kt:23)
> [ ] E/AndroidRuntime(16226): at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
> [ ] E/AndroidRuntime(16226): at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
> [ ] E/AndroidRuntime(16226): at android.app.Activity.performCreate(Activity.java:7458)
> [ ] E/AndroidRuntime(16226): at android.app.Activity.performCreate(Activity.java:7448)
> [ ] E/AndroidRuntime(16226): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
> [ ] E/AndroidRuntime(16226): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
> [ ] E/AndroidRuntime(16226): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
> [ ] E/AndroidRuntime(16226): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
> [ ] E/AndroidRuntime(16226): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> [ ] E/AndroidRuntime(16226): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> [ ] E/AndroidRuntime(16226): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
> [ ] E/AndroidRuntime(16226): at android.os.Handler.dispatchMessage(Handler.java:112)
> [ ] E/AndroidRuntime(16226): at android.os.Looper.loop(Looper.java:216)
> [ ] E/AndroidRuntime(16226): at android.app.ActivityThread.main(ActivityThread.java:7625)
> [ ] E/AndroidRuntime(16226): at java.lang.reflect.Method.invoke(Native Method)
> [ ] E/AndroidRuntime(16226): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> [ ] E/AndroidRuntime(16226): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> [ ] E/AndroidRuntime(16226): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.reward.RewardedVideoAdListener" on
> path: DexPathList[[zip file
> "/data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw=
> =/lib/arm64, /data/app/com.braingames.braintraining-IZRuVR5FwyfihNBI00csDw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
> [ ] E/AndroidRuntime(16226): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> [ ] E/AndroidRuntime(16226): at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> [ ] E/AndroidRuntime(16226): at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> [ ] E/AndroidRuntime(16226): ... 21 more
> 
> [✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.6 19G2021 darwin-x64, locale ru-RU)
> • Flutter version 2.2.0 at /Users/ag/Documents/flutter
> • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
> • Engine revision a9d88a4d18
> • Dart version 2.13.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
> • Android SDK at /Users/ag/Library/Android/sdk
> • Platform android-30, build-tools 30.0.0
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
> • Xcode at /Applications/Xcode.app/Contents/Developer
> • Xcode 12.4, Build version 12D4e
> • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
> • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.0)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 51.0.1
> • Dart plugin version 193.7547
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Community Edition (version 2020.3.2)
> • IntelliJ at /Applications/IntelliJ IDEA CE.app
> • Flutter plugin version 54.0.3
> • Dart plugin version 203.7759
> 
> [✓] VS Code (version 1.56.2)
> • VS Code at /Applications/Visual Studio Code.app/Contents
> • Flutter extension version 3.22.0
> 
> [✓] Connected device (2 available)
> • BND L21 (mobile) • xxx • android-arm64 • Android 9 (API 28)
> • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
> 
> • No issues found!

Maybe you add in past some depenciens about ads in your app/build.gradle ?

**Comment by romarito** [comment]
In my case nothing has changed in the whole code, besides the "load ads" section, of course. All dependencies are already nullsafet and the app is already published, I just came to update firebase_core and ended up giving an error in GMA.
When returning to version 0.12.2 + 1, everything works correctly, including firebase_core 1.2.0.

**Comment by EArminjon** [comment]
@romarito when Missing plugin exception happen => close app, flutter clean / flutter pub get / flutter analyze

**Comment by romarito** [comment]
> @romarito Can you check if your issue is the same as in #249?

Yes, it is.

**Comment by ale-getman** [comment]
Solved the problem by removing the dependencies of another ad plugin from the project
