### ISSUE TITLE
App crashing with null object[0] in iOS

### ISSUE THREAD

**Issue by nagarjunvv** [googleads/googleads-mobile-flutter#247]
I am using rewarded and interstitial ads. It is failing in initialisation itself. Also it is mentioning to mention test device id which I already specified as per example and device if as per log.I followed all the steps as mentioned in pub.Dev

Android it is working fine.

## Plugin version
0.13.0
## Steps to reproduce

Unable to initialise itself

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** app should open
**Actual results:** failed with adding null ad. If I comment ads the app is working fine.no issues in android.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by blasten** [comment]
We need more information. Please paste the full logs, any relevant file (e.g. main.dart).

**Comment by nagarjunvv** [comment]
The below is the exception i am getting.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1965699d8 0x1aa8ecb54 0x1965d3d98 0x1965df1f4 0x1964648a8 0x196457c04 0x1048f4fcc 0x1048f261c 0x1048633b8 0x104863240 0x1047e9fb4 0x1961a1298 0x1961a2280 0x1961845b0 0x1964e95e0 0x1964e3a88 0x1964e2ba0 0x1ad248598 0x198dd42f4 0x198dd9874 0x1046a0560 0x1961c1568)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001c242a84c libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c242a84c <+8>:  b.lo   0x1c242a868               ; <+36>
    0x1c242a850 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1c242a854 <+16>: mov    x29, sp
    0x1c242a858 <+20>: bl     0x1c2407f5c               ; cerror_nocancel

The below is the code i am using.

InterstitialAd? _interstitialAd;
  RewardedAd? _rewardedAd;
 int _numInterstitialLoadAttempts = 0;
  int maxFailedLoadAttempts = 5;
  int _numRewardedLoadAttempts = 0;


  void _createInterstitialAd() {
    InterstitialAd.load(
        adUnitId: InterstitialAd.testAdUnitId,
        request: request,
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (InterstitialAd ad) {
            print('$ad loaded');
            _interstitialAd = ad;
            _numInterstitialLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('InterstitialAd failed to load: $error.');
            _numInterstitialLoadAttempts += 1;
            _interstitialAd = null;
            if (_numInterstitialLoadAttempts <= maxFailedLoadAttempts) {
              _createInterstitialAd();
            }

          },
        ));
  }
  void _showInterstitialAd() {
    if (_interstitialAd == null) {
      print('Warning: attempt to show interstitial before loaded.');
      return;
    }
    _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (InterstitialAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },
      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },
    );
    _interstitialAd!.show();
    _interstitialAd = null;
  }

  void _createRewardedAd() {
    RewardedAd.load(
        adUnitId: RewardedAd.testAdUnitId,
        request: request,
        rewardedAdLoadCallback: RewardedAdLoadCallback(
          onAdLoaded: (RewardedAd ad) {
            print('$ad loaded.');
            _rewardedAd = ad;
            _numRewardedLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('RewardedAd failed to load: $error');
            _rewardedAd = null;
            _numRewardedLoadAttempts += 1;
            if (_numRewardedLoadAttempts <= maxFailedLoadAttempts) {
              _createRewardedAd();
            }
          },
        ));
  }

  void _showRewardedAd() {
    if (_rewardedAd == null) {
      print('Warning: attempt to show rewarded before loaded.');
      return;
    }
    _rewardedAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (RewardedAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (RewardedAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createRewardedAd();
      },
      onAdFailedToShowFullScreenContent: (RewardedAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createRewardedAd();
      },
    );

    _rewardedAd!.show(onUserEarnedReward: (RewardedAd ad, RewardItem reward) {
     // print('$ad with reward $RewardItem(${reward.amount}, ${reward.type}');
      if (get_votes > 0) {
        setState(() {
          votes_available = votes_available + 1;
          get_votes = get_votes - 1;
        });

      }
    });
    _rewardedAd = null;
  }

During init i am calling below

 _createInterstitialAd();
 _createRewardedAd();

The moment the page is loading the app is crashing. Before when i am using 12.0. it is working fine.

**Comment by nagarjunvv** [comment]
Let me know if you need more info , I am just waiting for this bug to close to release my project. Please help me.

**Comment by luis-cruzt** [comment]
I'm getting the exact same issue reported on crashlytics.
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/55716036/119902589-0c7e0e80-bf0d-11eb-9ebb-0f87ffede3d2.png">

**Comment by EArminjon** [comment]
@nagarjunvv please use quote to well format your code.

![image](https://user-images.githubusercontent.com/37028599/120069653-5985f000-c087-11eb-9099-97b4c0903cc0.png)

**Comment by nagarjunvv** [comment]
Hello @EArminjon 

By the way I am using Macbook M1 chip

Sorry i just copied the code from my main code.
Below is the formatted code.

  InterstitialAd? _interstitialAd;
  RewardedAd? _rewardedAd;
  int _numInterstitialLoadAttempts = 0;
  int maxFailedLoadAttempts = 5;
  int _numRewardedLoadAttempts = 0;

  void _createInterstitialAd() {
    InterstitialAd.load(
        adUnitId: InterstitialAd.testAdUnitId,
        request: request,
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (InterstitialAd ad) {
            print('$ad loaded');
            _interstitialAd = ad;
            _numInterstitialLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('InterstitialAd failed to load: $error.');
            _numInterstitialLoadAttempts += 1;
            _interstitialAd = null;
            if (_numInterstitialLoadAttempts <= maxFailedLoadAttempts) {
              _createInterstitialAd();
            }
          },
        ));
  }

  void _showInterstitialAd() {
    if (_interstitialAd == null) {
      print('Warning: attempt to show interstitial before loaded.');
      return;
    }
    _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (InterstitialAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },
      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },
    );
    _interstitialAd!.show();
    _interstitialAd = null;
  }

  void _createRewardedAd() {
    RewardedAd.load(
        adUnitId: RewardedAd.testAdUnitId,
        request: request,
        rewardedAdLoadCallback: RewardedAdLoadCallback(
          onAdLoaded: (RewardedAd ad) {
            print('$ad loaded.');
            _rewardedAd = ad;
            _numRewardedLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('RewardedAd failed to load: $error');
            _rewardedAd = null;
            _numRewardedLoadAttempts += 1;
            if (_numRewardedLoadAttempts <= maxFailedLoadAttempts) {
              _createRewardedAd();
            }
          },
        ));
  }

  void _showRewardedAd() {
    if (_rewardedAd == null) {
      print('Warning: attempt to show rewarded before loaded.');
      return;
    }
    _rewardedAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (RewardedAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (RewardedAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createRewardedAd();
      },
      onAdFailedToShowFullScreenContent: (RewardedAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createRewardedAd();
      },
    );

    _rewardedAd!.show(onUserEarnedReward: (RewardedAd ad, RewardItem reward) {
      // print('$ad with reward $RewardItem(${reward.amount}, ${reward.type}');
      if (get_votes > 0) {
        setState(() {
          votes_available = votes_available + 1;
          get_votes = get_votes - 1;
        });
      }
    });
    _rewardedAd = null;
  }

**Comment by nagarjunvv** [comment]
> Hello @nagarjunvv,
> 
> Please use magic quote to well format your code...
> 
> ![image](https://user-images.githubusercontent.com/37028599/120069653-5985f000-c087-11eb-9099-97b4c0903cc0.png)

Anything else i need to do other than formatting code? Please suggest

**Comment by nagarjunvv** [comment]
adding MobileAds.instance.initialize(); in init and
WidgetsFlutterBinding.ensureInitialized(); solved the issue.

**Comment by MichalDanielDobrzanski** [comment]
Any update on this case?

**Comment by MichalDanielDobrzanski** [comment]
I have been able reproduce it only on iOS builds. It happens when my app is published to App Store  and when Ad Serving Limit is applied on my AdMob account.

**Comment by maheshmnj** [comment]
Hi @nagarjunvv @MichalDanielDobrzanski  are you still facing this issue as of the latest `google_mobile_ads plugin 0.13.4`, if so please share the output of `flutter doctor -v` and a minimal reproducible code sample. And does the app crash when you run it in release/ debug mode?

**Comment by usman-whizpool** [comment]
We are still facing it
