### ISSUE TITLE
iOS app crashing after updating to 12.2 and 13.0.

### ISSUE THREAD

**Issue by Vijay053** [googleads/googleads-mobile-flutter#248]
In my iOS app following crash is trending in Firebase Crashlytics since I have upgraded google_mobile_ads sdk to 12.2. I have updated to latest 13.0 version of sdk but the crash presist.  I am using Facebook audience as mediation partner.

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18526186c __exceptionPreprocess
1  libobjc.A.dylib                0x19a27ac50 objc_exception_throw
2  CoreFoundation                 0x1852d1e1c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1852de270 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5
4  CoreFoundation                 0x185152550 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x185144dd0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  Runner                         0x102c909a8 -[FLTAdInstanceManager onAdFailedToLoad:error:] + 91 (FLTAdInstanceManager_Internal.m:91)
7  Runner                         0x102c8e49c -[FLTBannerAd bannerView:didFailToReceiveAdWithError:] + 211 (FLTAd_Internal.m:211)
8  Runner                         0x102bae918 GAD_GADBannerView_arm64_8_5_0
9  Runner                         0x102c02d70 __destroy_helper_block_e8_32s40s48s56s64s72w
10 Runner                         0x102c02930 GAD_GADInternalBannerView_arm64_8_5_0
11 Runner                         0x102c024f8 GAD_GADInternalBannerView_arm64_8_5_0
12 Runner                         0x102c02ba8 GAD_GADInternalBannerView_arm64_8_5_0
13 libdispatch.dylib              0x184e5424c _dispatch_call_block_and_release
14 libdispatch.dylib              0x184e55db0 _dispatch_client_callout
15 libdispatch.dylib              0x184e637ac _dispatch_main_queue_callback_4CF
16 CoreFoundation                 0x1851dd11c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
17 CoreFoundation                 0x1851d7120 __CFRunLoopRun
18 CoreFoundation                 0x1851d621c CFRunLoopRunSpecific
19 GraphicsServices               0x19cda0784 GSEventRunModal
20 UIKitCore                      0x187c16ee8 -[UIApplication _run]
21 UIKitCore                      0x187c1c75c UIApplicationMain
22 Runner                         0x102a5c220 main + 5 (AppDelegate.swift:5)
23 libdyld.dylib                  0x184e966b0 start

## Plugin Version
google_mobile_ads: 12.2 and 0.13.0

doctor -v output:

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale
    en-IN)
    • Flutter version 2.2.0 at /Users/vijaymeena/Documents/flutter
    • Framework revision b22742018b (8 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

**Comment by ThrowJojo** [comment]
This looks like it might be related to #138 judging from the stack trace

**Comment by Vijay053** [comment]
@ThrowJojo Thanks for pointing that out. We can close this one. I didn't realized that this issue is this much old and didn't checked old bugs.
