### ISSUE TITLE
Native ads didn't show in debug

### ISSUE THREAD

**Issue by TusharPatel18** [googleads/googleads-mobile-flutter#254]
After download the example given this repo and then i run the app, all ads are showing perfectly only native ads didn't.
 
<img src="https://user-images.githubusercontent.com/71643678/119774073-3e787c00-bedf-11eb-8cf9-69e2254f09c1.jpg" width ="300">

Check this image ..
 If any one has idea please comment below 
Thank you :)

**Comment by phuocco** [comment]
The yellow one is native ad, you have to config xml file in this case is android, or xib if ios

**Comment by tp-coderbabu** [comment]
> The yellow one is native ad, you have to config xml file in this case is android, or xib if ios

so repository example lacks the xml files, Also they haven't change the codeLab code for implementing native ads with new class names

**Comment by phuocco** [comment]
> > The yellow one is native ad, you have to config xml file in this case is android, or xib if ios
> 
> so repository example lacks the xml files, Also they haven't change the codeLab code for implementing native ads with new class names

just change edit the xml file

**Comment by maheshmnj** [comment]
Hi @TusharPatel18, Thanks for filing the issue, I ran the codelabs sample and it seems to show the native ads, please take a look at this [codelab for more details](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7)

Thanks

**Comment by maheshmnj** [comment]
Hi @TusharPatel18, Thanks for filing the issue, I ran the codelabs sample and it seems to show the native ads using the latest ads plugin `0.13.4`, please take a look at this [codelab for more details](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7)

Thanks
