### ISSUE TITLE
[📚] Vague Docs on NativeAd Implementations

### ISSUE THREAD

**Issue by theniceboy** [googleads/googleads-mobile-flutter#26]
Documentation regarding how to implement native ads is not really accessible for developers lacking native platform knowledge.

**Comment by zaidkazi** [comment]
Agreed documentation needs serious work on the native ad side.

I just managed to get mine working after tinkering around for the last hour or so. Something that really helped me was the following google code lab which was rather hard to find but briefly mentioned during todays flutter engage. 

Good luck!

https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7

**Comment by theniceboy** [comment]
Thanks for the info, @zaidkazi!

**Comment by theniceboy** [comment]
Another thought went through my head: I wonder what's the native ads' performance like since they are platform views integrated into a flutter listview. Did you have anytime to test your implementation? @zaidkazi

**Comment by jjliu15** [comment]
Added references to the codelab in https://github.com/googleads/googleads-mobile-flutter/pull/23

**Comment by QuentinSc** [comment]
Hello!
Someone could post the kotlin version of the native code?

Thank you :
