### ISSUE TITLE
Type com.google.android.gms.measurement.internal.zzgx is referenced as an interface from `com.google.android.gms.measurement.internal.AppMeasurementDynamiteService$zzb`

### ISSUE THREAD

**Issue by savanbthakkar** [googleads/googleads-mobile-flutter#260]
## Steps to Reproduce
- We are trying to include google_mobile_ads in existing mobile game without upgrading flutter. Here is some core version information.

minSdkVersion 21
targetSdkVersion 29 

dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }

google_mobile_ads: ^0.13.0

**NOTE: IF WE CHANGE GOOGLE_MOBILE_ADS VERSION TO 0.12.2+1 IN PUBSPEC.YAML, IT WORKS FINE.**

**Expected results:** 
Run the app with ads

**Actual results:** 

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
AGPBI: {"kind":"error","text":"Type com.google.android.gms.measurement.internal.zzgx is referenced as an interface from `com.google.android.gms.measurement.internal.AppMeasurementDynamiteService$zzb`.","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Type com.google.android.gms.measurement.internal.zzgz is referenced as an interface from `com.google.android.gms.measurement.api.AppMeasurementSdk$OnEventListener(classpath class)`.","sources":[{}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Type com.google.android.gms.internal.measurement.zzib is referenced as an interface from `com.google.android.gms.internal.measurement.zzck$zzb$zza`.","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.measurement.zzlp found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.internal.measurement.zzm found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.internal.measurement.zzn found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.internal.measurement.zzo found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.internal.measurement.zzp found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.measurement.internal.zzgz found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.measurement.internal.zzia found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Duplicate class com.google.android.gms.measurement.internal.zzig found in modules play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and play-services-measurement-impl-17.6.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.6.0)
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 1m 18s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\XXXX.dart:1616:28 -
          deprecated_member_use

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at D:\dev\flutter
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\dev\android-sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = D:\dev\android-sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed) (EVEN IF IT SAYS ANDROID STUDIO IS NOT INSTALLED, IT IS INSTALLED)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 2 categories.

</details>

**Comment by maheshmnj** [comment]
Hi @savanbthakkar, Thanks for filing the issue. Could you please try upgrading to the latest ads plugin 0.13.4 and see if that fixes the issue.And if it fails please share the output of `flutter run -v`.

Thanks
