### ISSUE TITLE
Let us the possibility to react of interstitial close event.

### ISSUE THREAD

**Issue by EArminjon** [googleads/googleads-mobile-flutter#267]
## Use case

We have a music app where users can do many things like read some actuality messages or adjust some settings through other pages. Audio run in the background to let users navigate in the app without interruption.
Before showing interstitial we stop our background audio, but there is no method to wait until ads closed by the user...
## Proposal

Create a callback to let us the possibility to start again our audio when ad is closed :) .

**Comment by jjliu15** [comment]
You can implement `FullScreenContentCallback.onAdDismissedFullScreenContent` to be notified of when the interstitial is closed.
You can also see this in the [example app](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/example/lib/main.dart#L92-L95).
