### ISSUE TITLE
Ad.isLoaded() should be sync

### ISSUE THREAD

**Issue by sperochon** [googleads/googleads-mobile-flutter#27]
Hello,

This is not really a bug but small code improvment (v0.11.0+1)

## Bug report

The Ad.isLoaded() method should be sync since it doesn't call any async method

### Actual code

`  Future<bool> isLoaded() async {
    return instanceManager.adIdFor(this) != null &&
        instanceManager.onAdLoadedCalled(this);
  }`

### Expected code

`  bool isLoaded() {
    return instanceManager.adIdFor(this) != null &&
        instanceManager.onAdLoadedCalled(this);
  }`

Thanks.

**Comment by jjliu15** [comment]
This API was removed in #214. Reasons being that this API was a bit misleading since it actually only returned if we attempted to load the ad, rather than the ad actually being loaded.

Instead of using this API, you should use the `onAdLoaded` callbacks to track whether an ad is loaded.
