### ISSUE TITLE
Build Failed when using google_mobile_ads: ^0.13.0

### ISSUE THREAD

**Issue by abinmittu** [googleads/googleads-mobile-flutter#271]
Unable to build when using google_mobile_ads: ^0.13.0. I am getting the following error.

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/myname/.gradle/caches/transforms-2/files-2.1/198d36345a95daa6a968d9edf9e74fdb/play-services-ads-lite-20.1.0/AndroidManifest.xml:27:5-43:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s ```

**Comment by arunchaudharymax** [comment]
Possible duplicate of  #264

**Comment by aspiiire** [comment]
I have the same issue, have you solved? if yes how?

**Comment by maheshmnj** [comment]
Hi @abinmittu, Thanks for filing the issue.Are you still facing the build issue using the latest `gooogle_mobile_Ads: 0.13.4`, if so, Please share the output of `flutter doctor -v` along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by maheshmnj** [comment]
Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/271, You may follow up there for further updates. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
