### ISSUE TITLE
@implementation FLTSmartBannerSize - Assigning to 'GADAdSize' from incompatible type

### ISSUE THREAD

**Issue by kz2021** [googleads/googleads-mobile-flutter#274]
## Plugin Version

google_mobile_ads: ^0.13.0

## Steps to Reproduce

I am building an app in flutter, and I am using the google_mobile_ads pub.

My iOS builds are failing now due to this issue:
Assigning to 'GADAdSize' (aka 'struct GADAdSize') from incompatible type 'GADAdSize (CGFloat)' (aka 'struct GADAdSize (float)')
1. install the pub dependency on pubspec.yaml
2. flutter pub get
3. do the Pods install
4. Open project workspace in xCode
5. Attempt xCode -> Product -> Build 

**Expected results:** 
iOS builds fine
**Actual results:** 
![image](https://user-images.githubusercontent.com/2509364/121670764-a643d080-ca62-11eb-9140-387df9e5516f.png)
![image](https://user-images.githubusercontent.com/2509364/121670774-aa6fee00-ca62-11eb-87d0-b4f5544e92f2.png)

Errors shown in the screenshots above
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jjliu15** [comment]
Did you modify that fille locally? The code you're sharing differs from what I'm seeing in v0.13.0 of [`FLTAd_Internal.m`](https://github.com/googleads/googleads-mobile-flutter/blob/v0.13.0/packages/google_mobile_ads/ios/Classes/FLTAd_Internal.m#L67-L74)

```dart
- (instancetype _Nonnull)initWithOrientation:(NSString *_Nonnull)orientation {
  GADAdSize size;
  if ([orientation isEqualToString:@"portrait"]) {
    size = kGADAdSizeSmartBannerPortrait;
  } else if ([orientation isEqualToString:@"landscape"]) {
    size = kGADAdSizeSmartBannerLandscape;
  } else {
    NSLog(@"SmartBanner orientation should be 'portrait' or 'landscape': %@", orientation);
    return nil;
  }
```
