### ISSUE TITLE
Retrieve Loaded AdSize when passing multiple AdSizes to AdManagerBannerAd

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#276]
## Use case

When a user sets `AdManagerBannerAd.adSizes` they should be able to retrieve the size of the Ad once the Ad is loaded. 

## Proposal

This can be retrieved by calling `BaseAdView.getAdSize()` on the native side according to: https://developers.google.com/android/reference/com/google/android/gms/ads/admanager/AdManagerAdView#setAdSizes(com.google.android.gms.ads.AdSize...). This may be solved by simply adding an async method similar to `load()` for the `AdManagerBannerAd` or returning the value in load.

**Comment by jjliu15** [comment]
This is supported by `AdManagerBannerAd.getPlatformAdSize()` and `BannerAdd.getPlatformAdSize()`
