### ISSUE TITLE
If many ads are loaded at the same time ads limitation will not work as expected

### ISSUE THREAD

**Issue by EArminjon** [googleads/googleads-mobile-flutter#279]
## Plugin Version

 google_mobile_ads: ^0.13.0

## Steps to Reproduce

Problem : Its seems like InterstitialAd.load & interstitialA.show did check ad limitation before load or display.

I've a Listview with many articles.  Each item is a stateful widget and are declared like bellow. 
I've limited ads to 1 per day per user. I've set limit in ads block and app on abmod website. I've no third-party mediation, self-promotions ordirect-sold campaigns (all these page are empty on abmod website).

When clicking on each of my articles, an interstitial is shown. I believe (I'm wrong ?) It should normally fail because of ads limitation and fall back in onAdFailedToLoad or onAdFailedToShowFullScreenContent right ?

Notice that when I closed the app and reopen it again, no ads are shown because limitations work... What should I do ?  

#### Admob custom limitation :
![image](https://user-images.githubusercontent.com/37028599/122264403-cac30100-ced7-11eb-8aed-feed49a0b9a2.png)

#### Article (onclick I call showInterstitialAd)
```dart
class _ArticlePageState extends State<ArticlePage> with AppInterstitiel {}
```

#### Interstitials part :
```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:mobile_app_factory/ad_manager.dart';

const int maxFailedLoadAttempts = 3;

mixin AppInterstitiel<T extends StatefulWidget> on State<T> {
  bool enabled = true;
  InterstitialAd? _interstitialAd;
  int _numInterstitialLoadAttempts = 0;

  @override
  void dispose() {
    _interstitialAd?.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _createInterstitialAd();
  }

  bool get _isReady => AdManager.enabled && mounted && WidgetsBinding.instance!.lifecycleState == AppLifecycleState.resumed;

  void _createInterstitialAd() {
    if (!AdManager.enabled) return;
    InterstitialAd.load(
        adUnitId: AdManager.interstitialAdUnitId!,
        request: AdRequest(),
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (InterstitialAd ad) {
            print('$ad loaded');
            _interstitialAd = ad;
            _numInterstitialLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('InterstitialAd failed to load: $error.');
            _numInterstitialLoadAttempts += 1;
            _interstitialAd = null;
            if (_numInterstitialLoadAttempts <= maxFailedLoadAttempts) {
              _createInterstitialAd();
            }
          },
        ));
  }

  void showInterstitialAd() {
    if (_interstitialAd == null)
      return;
    else if (!_isReady) {
      print('Warning: app is not ready to display ads.');
      return;
    }
    _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (InterstitialAd ad) => print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },
      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },
    );
    _interstitialAd!.show();
    _interstitialAd = null;
  }
}

```

**Expected results:** 

**Actual results:** 

No logs, It's on production. Cannot test ads limitation with test ads...
<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [version 10.0.19043.1055], locale fr-FR)
    • Flutter version 2.2.2 at C:\Users\githubdemo\Documents\Softwares\flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\githubdemo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7322048\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at D:\dev
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio
    • Android Studio at C:\Users\githubdemo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7322048
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • android-studio-dir = C:\Users\githubdemo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7322048
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\githubdemo\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19043.1055]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!

```

</details>

**Comment by EArminjon** [comment]
To avoid that, I force my app to load only one interstitial and not several at once. You can close it if this is the right method.

**Comment by maheshmnj** [comment]
@EArminjon As per the docs Only one interstitial ad can be shown at a time

> An InterstitialAd can only be shown once. Subsequent calls to show will trigger onAdFailedToShowFullScreenContent.

Provided your last message I feel its safe to close this issue.If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by maheshmnj** [comment]
@EArminjon As per the [docs](https://pub.dev/packages/google_mobile_ads) Only one interstitial ad can be shown at a time

> An InterstitialAd can only be shown once. Subsequent calls to show will trigger onAdFailedToShowFullScreenContent.

Provided your last message I feel its safe to close this issue.If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by EArminjon** [comment]
```
An InterstitialAd can only be shown once. Subsequent calls to show will trigger onAdFailedToShowFullScreenContent.
```

My issue it's not about displaying but loading.

**Comment by maheshmnj** [comment]
Can you provide a minimal code sample that does not work?

**Comment by EArminjon** [comment]
Hi,

I provided in the original post the code used.  I've a list of articles, each one extend my interstitial class.

We cannot reproduce the problem in debug but only in production mode. If you load many ads without displaying them and if theses ads have a displaying limit like 1 in admob website you will have an issue. Because, you will display the same ads for every loaded ads.After showing, the next ads futur loading will failed successfully because the ads limit was reached and that's good.

**Comment by maheshmnj** [comment]
@EArminjon could you provide a minimal and complete code sample that should be ready to run with minimal and no code changes this helps to debug the exact cause of the issue.

Thanks
