### ISSUE TITLE
Change volume for interstitial ads

### ISSUE THREAD

**Issue by krunduev** [googleads/googleads-mobile-flutter#283]
## Use case

Need possibility to change sound volume of interstitial ads

## Proposal

Add possibility to call native Android / iOS
`MobileAds.setAppVolume(value);`
`[GADMobileAds sharedInstance].applicationVolume = value;`
and
`MobileAds.setAppMuted(true);`
`[GADMobileAds sharedInstance].applicationMuted = YES;`

**Comment by nathanogunleye** [comment]
+1

Would be good to have the ability to control the volume or turn it off altogether. It's a bit annoying when it randomly turns on

**Comment by maheshmnj** [comment]
Labelling as a valid feature request
