### ISSUE TITLE
App crashes while using mediation with facebook audience network

### ISSUE THREAD

**Issue by lostidol355** [googleads/googleads-mobile-flutter#285]
My app crashes when i use admob adunit with mediation enbaled. I have followed everything mentioned in the official documentation. Despite my apps crashes . Here is message log shown in console
![image](https://user-images.githubusercontent.com/61495242/122884394-d3935700-d35d-11eb-8459-c2fd92bede37.png)
![image](https://user-images.githubusercontent.com/61495242/122884427-df7f1900-d35d-11eb-9108-fe88b336520f.png)
![image](https://user-images.githubusercontent.com/61495242/122884456-e9088100-d35d-11eb-8710-2baaf4f1dba1.png)
 
Please let me know if mediation through this plugin is possible or not? if it possible then please refer me the proper documentation

**Comment by arunchaudharyweb** [comment]
Yes, Mediation is possible. 
I have tried this plugin with MoPub, Unity and FAN.
But FAN native ads are not clickable using mediation however MoPub native ads are clickable with this plugin.

Follow these steps to successfully integrate FAN ads.
Step 1: Don't use the latest FAN adapter, it crashes the application. So use an older version instead.
Step 2: Map the placement ids of FAN with the ad units of your Admob account in the Mediation tab of Admob UI.
Step 3: Add your device as a test device and enable ad inspector in Admob and also add your device as a test device in FAN.
Step 4: Load Admob ads as given in the documentation of this plugin. 
Step 5: It will also request the ads from FAN. But FAN ads will always not be visible. Sometimes you will see Admob ads and sometimes FAN ads.
Step 6: See the ad inspector to see how your ads are being requested for more details.

**Comment by lostidol355** [comment]
Thanks it is fixed by using older adapter

**Comment by namchuai** [comment]
@arunchaudharyweb @lostidol355 sorry, I'm newbie here. May I ask for the document link to integrate FAN mediation with `google_mobile_ads` please? Thank you!
