### ISSUE TITLE
Question about pre-release ad delivery

### ISSUE THREAD

**Issue by TheMcSebi** [googleads/googleads-mobile-flutter#289]
## Plugin Version

google_mobile_ads: "^0.12.2+1"

## Steps to Reproduce

1. Include any ad in a flutter project and upload a version to TestFlight with the real ad IDs (not the testing ones)

**Expected results:** See ads

**Actual results:** Don't see ads. Instead it just shows a grey box for banners and nothing for interstitials.

My question is actually really simple. On Android I see real ads being displayed with the "Test Ad" banner when I include my real config (app-ad-id and e.g. a banner ad with its own ad-id). On iOS, I don't. Is that due to the app not being released in the App Store? It's the very first version I'm trying to publish and I'm afraid I made a mistake during setup.

**Comment by BrunoEleodoro** [comment]
Having the same issue here, ads don't display on release mode on Android and IOS.

using `google_mobile_ads: ^0.13.1`

**Comment by maheshmnj** [comment]
Hi @TheMcSebi, Please make sure your app is linked and verified in the admob dashboard?  

Thanks.

**Comment by maheshmnj** [comment]
Hi @TheMcSebi, Please make sure your app is linked and verified in the admob dashboard?  

Thanks.
