### ISSUE TITLE
Improve Interstitial Ad example in example app

### ISSUE THREAD

**Issue by bparrishMines** [googleads/googleads-mobile-flutter#295]
Change the `InterstitialAd` example in the example app to be shown in between navigation transitions. This could help users avoid avoid https://support.google.com/admob/answer/6201362?hl=en.

**Comment by aanantt** [comment]
Hi @bparrishMines I have made a [PR](https://github.com/googleads/googleads-mobile-flutter/pull/372) related to this Issue. Please review It and let me know if I have to do any correction in the PR.

**Comment by bparrishMines** [comment]
cc @jjliu15

**Comment by jjliu15** [comment]
There are sample apps in https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob that follow best practices
