### ISSUE TITLE
NativeAd - Huge Performance issues

### ISSUE THREAD

**Issue by mkassan** [googleads/googleads-mobile-flutter#297]
## Plugin Version : 0.13.2 
I have NativeAd widgets inside a ListView.
I am testing on an Android device : version 9, Samsung Note 8.

Without Native Ads:
![WithoutNativeAds](https://user-images.githubusercontent.com/45078310/124316049-40d09480-db75-11eb-9e05-c58cda0fc661.png)

With Native Ads:
![WithNativeAds](https://user-images.githubusercontent.com/45078310/124315779-c273f280-db74-11eb-8283-4b7bbe7f4f7f.png)

Reproducing is simple, create a listview with 100 items and 5 nativeAds.

Thank you

**Comment by mkassan** [comment]
I have created a public Github repository to reproduce the problem: [Link](https://github.com/mkassan/nativeadproblem)

Here is a video showing the problem from the testing app above:

https://user-images.githubusercontent.com/45078310/124322841-8050ae00-db80-11eb-9e2a-c2d8f1557e5f.mp4

**Comment by ninoorta** [comment]
Hi @mkassan , I'm struggling with the setting up for native ad. Can you please show me your settings for this one ?

**Comment by mkassan** [comment]
Hi @ninoorta, you can refer to my example code described in the [Link ](https://github.com/mkassan/nativeadproblem)above shared with the video.
It is a mini-app that demonstrates the issue.

**Comment by ninoorta** [comment]
Thank you @mkassan . I will check it out.

**Comment by ninoorta** [comment]
Excuse me, @mkassan , Did your app just work fine three days ago, right ? Can you check the native ad one more time please ? When I start the project, it gives me the ad error code 0

**Comment by tp-coderbabu** [comment]
> Excuse me, @mkassan. Your app just worked fine three days ago, right?
> Can you check the native ad one more time, please?
> When I start the project, it gives me the ad error code 0

hi, @ninoorta 

Error Code 0 : ERROR_CODE_INTERNAL_ERROR

This indicates that something happened internally; for instance, an invalid response was received from the ad server.

**Comment by ninoorta** [comment]
@tp-coderbabu yup, so it means there is nothing I can do to prevent it , right ?

**Comment by tp-coderbabu** [comment]
> @tp-coderbabu yup, so it means there is nothing I can do to prevent it, right?

yes wait for sometimes then check it again 

please refere: https://support.google.com/admob/thread/3494603/admob-error-codes-logs?hl=en

**Comment by ninoorta** [comment]
> > @tp-coderbabu yup, so it means there is nothing I can do to prevent it, right?
> 
> yes wait for sometimes then check it again
> 
> please refere: https://support.google.com/admob/thread/3494603/admob-error-codes-logs?hl=en

That's bad. Thank you

**Comment by mkassan** [comment]
Any news about this issue? 
If you are facing the same issue, can you upvote this thread please? 
Thank you

**Comment by jangruenwaldt** [comment]
This has been happening since this plugin existed, no news, this plugin is unusable. You can try native_admob_flutter. Sorry. 

I wish I could give my users a better experience with native ads, but sadly no. The code would be ready to ship. If this lag wasn't there.

**Comment by mkassan** [comment]
I have seen native_admob_flutter.
The problem is that in my use case, it will not help.
From what I have seen, It allows a single instance of native ads, so it is not thought to be used inside lists.
On the other hand, from their documentation, it supports NativeAds only for Android and not for iOS.

**Comment by jangruenwaldt** [comment]
I know, like I said: since I'm using native_admob_flutter, I can not use native ads either. I already had the code ready with this plugin, but it was too laggy. They won't fix, I'm afraid. Get ready to live without native ads. Sorry.

**Comment by jja08111** [comment]
Same issue

**Comment by blasten** [comment]
We have added a flag to the Flutter master channel that helps improve the performance. 

It's not a perfect fix since the Ad may be a few frames behind the Flutter frame, but depending on the layout you use, it could be useful.  

Please try it out, and let us know if the performance is improved.

To use this flag, set `PlatformViewsService.synchronizeToNativeViewHierarchy(false)`.  For example: 

```dart
import 'package:flutter/services.dart';

void main() {
   PlatformViewsService.synchronizeToNativeViewHierarchy(false);
   runApp(MyApp());
}
```

I'm closing this issue, and moving the conversation to: https://github.com/googleads/googleads-mobile-flutter/issues/269
