### ISSUE TITLE
Google ad keep reloading window

### ISSUE THREAD

**Issue by ashut08** [googleads/googleads-mobile-flutter#300]
Below i attached video of the issue
https://user-images.githubusercontent.com/49301530/124384330-44d3f200-dcee-11eb-9f1a-3ccf80185bb6.mp4
Attaching output of **flutter doctor -v** command
```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/ashu/flutter_linux_1.22.6-stable/flutter
    • Framework revision 9b2d32b605 (5 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ashu/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-0.fc32.x86_64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-b10)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/ashu/android-studio-ide-201.7042882-linux/android-studio/bin
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /home/ashu/android-studio-ide-201.7042882-linux/android-studio/bin
    ✗ Android Studio not found at /home/ashu/android-studio-ide-201.7042882-linux/android-studio/bin
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Redmi Y3 (mobile) • 666b7162 • android-arm64 • Android 10 (API 29)
```

**Comment by Albertbol** [comment]
I have a similar issue with PopupMenuBuytton and PopupMenuItems inside. When I click on the popup button AdWidget is reloading the screen all the time.

**Comment by Ashutoshparas** [comment]
I have also face similar issue any solution  @jonahwilliams

**Comment by DanielSeldura** [comment]
Same issue here, and if I leave it on for long enough, it crashes the app.

**Comment by maheshmnj** [comment]
Hi @ashut08, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by zerox1212** [comment]
Same issue for me. In my case it's very obvious when using a "Speed Dial FAB". When the speed dial is open, the ad keeps taking focus and reloading the entire screen. I will try to make a minimal example soon.

**Comment by zerox1212** [comment]
@maheshmnj So I made a minimal example and the issue is not there. I then went back and looked at the OPs video and saw he is using Google Maps. My app is also using google maps. Considering how many other issues I have had in the past with `google_maps_flutter` I suspect this is the source of the problem.

I will try to add google maps widget to my minimal example and test again. Might me a while to create code since gmaps requires API keys and stuff...

**Comment by maheshmnj** [comment]
Thanks for the update @zerox1212, if this is an issue when using Google Maps  please try using Google maps with Hybrid Composition and see if there is any difference

**Comment by zerox1212** [comment]
@maheshmnj FYI this issue only occurs on Android. iOS works as expected.

**Comment by zerox1212** [comment]
@ashut08 @maheshmnj Enabling hybrid composition seems to resolve my issue with GoogleMaps.

I added the following code:
```dart
import 'package:flutter/foundation.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (defaultTargetPlatform == TargetPlatform.android) {
    AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
  }
  runApp(MyApp());
}

I will test it on some real devices. From what I understand this Hybrid Composition will hurt performance on older phones.
