### ISSUE TITLE
Native Ad Templates

### ISSUE THREAD

**Issue by bdlukaa** [googleads/googleads-mobile-flutter#302]
It'd be good to have native ad templates available easily for the developers.

- [Native Ad Templates for iOS](https://developers.google.com/admob/ios/native/templates)
- [Native Ad Templates for Android](https://developers.google.com/admob/android/native/templates)

**Comment by maheshmnj** [comment]
Hi @bdlukaa, There is already a codelab to implement native ads you can [find it here](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7), This is also mentioned on the [google_mobile_ads documentation](https://pub.dev/packages/google_mobile_ads) on pub.dev
