### ISSUE TITLE
lagg / performance problem in emulator.

### ISSUE THREAD

**Issue by canergulay** [googleads/googleads-mobile-flutter#305]
I implemented google mobile ads in android part and every millisecond, every moment it prints things like following.

E/eglCodecCommon( 3464): glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation( 3464): eglMakeCurrent: 0xe95e5fa0: ver 2 0 (tinfo 0xce9af820)
I/chatty  ( 3464): uid=10079(com.example.matchify) identical 1 line
D/EGL_emulation( 3464): eglMakeCurrent: 0xe95e5fa0: ver 2 0 (tinfo 0xce9af820)

E/eglCodecCommon( 3464): glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation( 3464): eglMakeCurrent: 0xe95e5fa0: ver 2 0 (tinfo 0xce9af

it prints those things every moment without stopping and app is frozen. I get the apk and tried in real device, it wasn't that bad in real device( observations with naked eyes), but  I was not able to test see if it is problematic in the real device as well.

**Comment by maheshmnj** [comment]
HI @canergulay
Thanks for filing the issue, Please share the output of `flutter doctor -v`,
what version of the [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) plugin are you using and in what type of ad is the issue in?

**Comment by Mehu007** [comment]
`[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/mehulgohil/flutter_sdks/flutter_2_0_1
    • Framework revision c5a4b4029c (7 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mehulgohil/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Users/mehulgohil/MEHUL_GOHIL/Softwares/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
`

Here is the flutter doctor output.
