### ISSUE TITLE
Future to check if nativeAd is loaded before displaying in the UI

### ISSUE THREAD

**Issue by BrianTum** [googleads/googleads-mobile-flutter#309]
## Use case

     I would like to have a future that checks if an Ad is loaded before rendering a widget

     There used to be a NativeAd.isloaded() future which helped to check the loading process of the app.

     Currently, I have to use google_mobile_ads: ^0.12.1+1 version which still has the isloaded() future.

## Proposal
     I am loading multiple native ad units and inserting them into a map. I need to check if a particular ad unit is loaded before displaying it on the UI. I consider this for a great user experience.

**Comment by westy92** [comment]
Can you use the `onAdLoaded` callback to only insert the Ad into the widget tree after it's loaded?

**Comment by maheshmnj** [comment]
@BrianTum, You can use the NativeAdListener which provides you the `onAdLoaded` callback Heres a short code snippet

```dart
    _ad = NativeAd(
      adUnitId: AdManager.nativeAdUnitId,
      factoryId: 'listTile',
      request: AdRequest(),
      listener: NativeAdListener(
        onAdLoaded: (_) {
          setState(() {
            _isAdLoaded = true;
          });
        },
        onAdFailedToLoad: (ad, error) {
          // Releases an ad resource when it fails to load
          ad.dispose();

          print('Ad load failed (code=${error.code} message=${error.message})');
        },
      ),
    );
```
