### ISSUE TITLE
Adaptive banner is out of place

### ISSUE THREAD

**Issue by chitgoks** [googleads/googleads-mobile-flutter#314]
I followed the code in the example to show an adaptive banner but this is the result.
<img src="https://user-images.githubusercontent.com/3955470/126064091-d5108a25-72f8-465d-8f5d-ff7af31923ca.png" height="450" />	
thoughts?

**Comment by TahaTesser** [comment]
Hi @chitgoks 
I just tried the official example, it looks fine. 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample and `flutter pub deps -- --style=compact`
Thank you

**Comment by chitgoks** [comment]
i taha sorry. ill close this. i thought i did. not an issue anymore for me
