### ISSUE TITLE
Admob ads not working in playstore my app

### ISSUE THREAD

**Issue by lkrjangid1** [googleads/googleads-mobile-flutter#315]
After download my app from play store ads not showing in the app But it's working in my flutter release app.

**Comment by trunghieuvn** [comment]
I also have the same problem in only Android, 
doesn't happen on iOS

**Comment by TahaTesser** [comment]
Hi @trunghieuvn  @lkrjangid1 
Can you please explain the issue in detail? Are ads complete missing? or ads replaced with test ads?  Provide a screenshot if possible 
Please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`
Thank you
