### ISSUE TITLE
All but one rewarded ad ending onAdDismissedFullScreenContent

### ISSUE THREAD

**Issue by jbryanh** [googleads/googleads-mobile-flutter#316]
## Plugin Version
google_mobile_ads: ^0.13.2

## Steps to Reproduce

1. Flutter, debug, using emulator with iOS
2. Using the following code:
`  static String get rewardedAdUnitIdGame {
    if (Platform.isAndroid) {
      return "ca-app-pub-3940256099942544/5224354917";
    } else if (Platform.isIOS) {
      return "ca-app-pub-3940256099942544/1712485313";
    } else {
      throw new UnsupportedError("Unsupported platform");
    }
  }`
3. When the test rewarded ads load, any ad (philips ad, empire level...anything EXCEPT the Bingo ad, the counter does not count down like it used to, and it kicks out with onAdDismissedFullScreenContent (no I'm not clicking the dismiss, doing nothing).

The Bingo test ad works as expected, so I can test by just opening the rewarded ad repeatedly until I get Bingo.  All the others (which coincidentally have counters, which bingo does not) fail.

4. 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @jbryanh, Could you please share the output of `flutter doctor -v`.
 
Do you mean the ad is dismissing automatically on timer ads? I verified on the iphone12 pro max simulator the rewarded ad runs completely.

**Comment by maheshmnj** [comment]
@xmkevinchen updated my commment its basically the [example from the docs](https://pub.dev/packages/google_mobile_ads/example),  @jbryanh thanks for the confirmation

**Comment by xmkevinchen** [comment]
The reward callback was called when I was using the testAdUnitId, but not with my testing ad unit id. It was working before.

**Comment by maheshmnj** [comment]
@xmkevinchen Could you please file a new issue with appropriate details and tag me.

**Comment by maheshmnj** [comment]
@jbryanh provided your last message I feel it's safe to close the issue. if you disagree feel free to comment and I will reopen it.

Thank you.
