### ISSUE TITLE
Performance issue when displaying ad

### ISSUE THREAD

**Issue by anuragsoni300** [googleads/googleads-mobile-flutter#318]
your admob checks in every frame that if the ad is in the screen view which cost too much performence in android(Dont know about ios).
it almost giving a 60 fps app to hardly 20 fps.
please fix it...

**Comment by phanvanluan94** [comment]
I got the same issue in Android.

**Comment by maheshmnj** [comment]
HI @anuragsoni300, Thanks for filing the issue, please share the output of `flutter doctor -v`,In order for this issue to be actionable please provide more details 
-  Is the performance issue with a specific ad or all the ads
-  what platform are you facing the issue on? 
-  what version of the google_mobile_ads plugin is this issue for.
And also share a[ minimal reproducible code ](https://stackoverflow.com/help/minimal-reproducible-example) sample with the exact steps to reproduce the issue

Please provide the requested information, it helps to better investigate the issue.

Thanks

**Comment by anuragsoni300** [comment]
`[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/maddog/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/lib/Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0
`

Issue is with all ads.
Android platform.
version - 0.13.2+1

One thing is [Native Admob Flutter](https://pub.dev/packages/native_admob_flutter) works fine with the same code.

**Comment by anuragsoni300** [comment]
> I got the same issue in Android.

just use [Native Admob flutter](https://pub.dev/packages/native_admob_flutter). Its Works fine.

**Comment by maheshmnj** [comment]
This issue is reproducible the `interstitial ad` and the `rewarded ad` roughly run around 20 fps, This issue was verified on the latest stable channel with `google_mobile_ads: ^0.13.2+1` on Xiaomi K20 pro (Api 30).

![image](https://user-images.githubusercontent.com/31410839/128009529-c5a8150b-945c-42dc-901d-bae6048ea92f.png)

This issue was verified against the [official code sample](https://pub.dev/packages/google_mobile_ads/example)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by erkihindo** [comment]
Same, showing banner ad completely ruins the app experience by making everything 3 times slower...

**Comment by anuragsoni300** [comment]
> Same, showing banner ad completely ruins the app experience by making everything 3 times slower...

**Comment by westy92** [comment]
@anuragsoni300 this issue should remain open until this library is fixed.

**Comment by anuragsoni300** [comment]
issue is still not fixed ...

**Comment by anuragsoni300** [comment]
> HI @anuragsoni300, Thanks for filing the issue, please share the output of `flutter doctor -v`,In order for this issue to be actionable please provide more details
> 
> * Is the performance issue with a specific ad or all the ads
> * what platform are you facing the issue on?
> * what version of the google_mobile_ads plugin is this issue for.
>   And also share a[ minimal reproducible code ](https://stackoverflow.com/help/minimal-reproducible-example) sample with the exact steps to reproduce the issue
> 
> Please provide the requested information, it helps to better investigate the issue.
> 
> Thanks

issue still there ...:((
