### ISSUE TITLE
Displaying an AdWidget with another Platform view like GoogleMap or WebView freeze those views.

### ISSUE THREAD

**Issue by sperochon** [googleads/googleads-mobile-flutter#32]
## Bug report

(Android only. iOS seems fine)
I've got a screen containing a Platform view widget (Google Maps and/or WebView)
As soon as the Adwidget is displayed (=once the load method is called), the others platform views freeze = i can not interact/scroll inside them anymore.

### Steps to reproduce

Use those packages:
  google_maps_flutter: ^1.2.0
  google_mobile_ads: ^0.11.0+1
  webview_flutter: ^1.0.7

Use this code :
```import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:webview_flutter/webview_flutter.dart';

import 'ad_state.dart';

class AdPage extends StatefulWidget {
  AdPage({Key key}) : super(key: key);

  @override
  _AdPageState createState() => _AdPageState();
}

class _AdPageState extends State<AdPage> {
  BannerAd banner;
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    
    banner = BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      request: AdRequest(),
      listener: AdState.adListener,
    ); //..load();
    
    Future<void>.delayed(
        Duration(seconds: 15),
        () => setState(() {
              banner?.load();
              isLoading = true;
            }));
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          height: 300,
          child: WebView(
            javascriptMode: JavascriptMode.unrestricted,
            initialUrl: "https://www.flutter.dev",
          ),
        ),
        Container(
          height: 300,
          child: GoogleMap(
              initialCameraPosition:
                  CameraPosition(target: LatLng(46.0, -0.36), zoom: 15.0)),
        ),
        Container(
          height: 50,
          child: isLoading ? AdWidget(ad: banner) : null,
        ),
      ],
    );
  }
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H15 darwin-x64, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.53.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
google_mobile_ads_bug 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- google_maps_flutter 1.2.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_mobile_ads 0.11.0+1 [meta flutter]
- provider 4.3.3 [collection flutter nested]
- webview_flutter 1.0.7 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- google_maps_flutter_platform_interface 1.2.0 [flutter meta plugin_platform_interface stream_transform collection]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- plugin_platform_interface 1.0.3 [meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by jjliu15** [comment]
I am able to reproduce this issue on Android only. Is this the same for you?

I am able to fix the issue for `Webview` by configuring it to use hybrid composition. Can you try adding the following line to `initState()`? 
```
if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
```

Not sure about a fix for the maps plugin yet. It seems like the issue could be related to mixing hybrid composition and virtual displays, and the [maps plugin](https://github.com/flutter/plugins/blob/b3369c3d11df1b33b901cba2106f23e2ab792aa5/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart) only uses virtual displays.
@blasten @bparrishMines Do either of you know if there's any known issue mixing hybrid composition and Virtual Display?

**Comment by sperochon** [comment]
@jjliu15 Yes, I forgot to mention it but it happens only on Android. I'm going to edit the title and description.

adding the line
`if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();`

makes the web view "working" but lagging a lot and if a Google Maps is still there too then this one freeze from the start (black screen with Google logo only).

**Comment by blasten** [comment]
We are planning to do something similar to what we did for WebView in Google maps. Until then, it's unsupported.

**Comment by blasten** [comment]
@bparrishMines Maurice, could you look into this issue when you get a chance?

**Comment by craigjp99** [comment]
Hi, I have a similar problem, but for me it's not freezing.  I get a crash in my app which starts up and displays a GoogleMap widget and a placeholder for a BannerAd.  In the init of my app I initialise Mobile Ads, and then I have a BannerAdState widget, using a listener / banner completer, as per the example.

If I put a delay (say 30 seconds or so) on the "load()" method of the banner ad, then my app loads and I can do some interactions with all aspects of the app (including the Google Map), but then once the "complete()" method of the banner ad complete runs, and the BannerAd widget actually tries to display the ad, I get the following crash:

===========================================================================

F/libc    (10126): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 10150 (RenderThread), pid 10126 (.shows_near_me1)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-03-13 14:00:29+1100
pid: 10126, tid: 10150, name: RenderThread  >>> com.example.shows_near_me1 <<<
uid: 10148
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    eax cc831000  ebx d87be864  ecx d86285c0  edx 0000001d
    edi c8f8d328  esi cc950400
    ebp c8f8d2ec  esp c8f8d28c  eip 00000000
backtrace:
      #00 pc 00000000  <unknown>
      #01 pc 0286c771  /system/product/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x66c000) (BuildId: ffe50d4377c82928759c1f40f1b35ba9f411454a)
Lost connection to device.
Exited (sigterm)

===========================================================================

It is only the final step of the actual BannerAd widget that causes the crash, and the crash only occurs if the GoogleMap widget is also shown.  That is, the following occurs without a crash:
- don't render the GoogleMap widget, the BannerAd widget displays an ad successfully
- don't render the BannerAd widget (the completer's "complete()" method still runs, I just comment out the line that has the BannerAd widget as a child of its container), and the GoogleMap widget can continue to be interacted with successfully

**Comment by craigjp99** [comment]
@blasten @jjliu15 @bparrishMines  would you suspect that the crash I'm having (while a GoogleMap widget is displayed, the BannerAd tries to show - *crash*) is likely related, or should I open a separate issue?

**Comment by bparrishMines** [comment]
@craigjp99 As @blasten stated above, the GoogleMap widget and AdWidget are currently incompatible. Ads use [hybrid composition](https://github.com/flutter/flutter/wiki/Hybrid-Composition) while `google_maps_flutter` uses [virtual displays](https://flutter.dev/docs/development/platform-integration/platform-views#virtual-display). 

I created an issue in flutter/flutter to track the transition: https://github.com/flutter/flutter/issues/78578

**Comment by lisuizhe** [comment]
I am using https://pub.dev/packages/flutter_echarts which internally using WebView and have very similar/probably same issue.
The Echarts freezes after AdWidget renders

**Comment by kaboc** [comment]
> the GoogleMap widget and AdWidget are currently incompatible. Ads use hybrid composition while google_maps_flutter uses virtual displays.

I came across this issue while I was using google_mobile_ads together with [qr_code_scanner](https://pub.dev/packages/qr_code_scanner), which uses the virtual display, but noticed that it also occured with the official [camera](https://pub.dev/packages/camera) plugin.

Having looked at the source code, I couldn't tell if the virtual display was used for the plugin. Does anyone have any idea about it, or could anyone look into it please?

**Comment by bunjongy** [comment]
I have the same issue. any update?

**Comment by philipxj** [comment]
same issue ,freeze the screen

**Comment by aniket4390** [comment]
I'm facing the same issue for long. is there any other workaround to implement both google map and admob in same screen

**Comment by maheshmnj** [comment]
I am able to reproduce the issue on the latest stable and the master channel with the latest google_mobile

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:video_player/video_player.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(
            primaryColor: Colors.red,
            colorScheme: ColorScheme.light(onPrimary: Colors.red)),
        home: IssueSample(title: 'title'));
  }
}

class IssueSample extends StatefulWidget {
  IssueSample({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _IssueSampleState createState() => _IssueSampleState();
}

class _IssueSampleState extends State<IssueSample> {
  VideoPlayerController? controller;
  BannerAd? anchoredBanner;

  @override
  void initState() {
    super.initState();
    // if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  Future<void> createAnchoredBanner() async {
    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getAnchoredAdaptiveBannerAdSize(
      Orientation.portrait,
      MediaQuery.of(context).size.width.truncate(),
    );
    if (size == null) {
      print('Unable to get height of anchored banner.');
      return;
    }
    final BannerAd banner = BannerAd(
      size: size,
      request: AdRequest(),
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          print('$BannerAd loaded.');
          anchoredBanner = ad as BannerAd?;
          setState(() {});
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          print('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => print('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => print('$BannerAd onAdClosed.'),
      ),
    );
    return banner.load();
  }

  @override
  Widget build(BuildContext context) {
    if (anchoredBanner == null) createAnchoredBanner();
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Stack(
          children: [
            // const Center(
            //     child: WebView(
            //   initialUrl: 'https://flutter.dev',
            // )),
            /// Google maps
            Container(
              height: 300,
              child: GoogleMap(
                  initialCameraPosition:
                      CameraPosition(target: LatLng(46.0, -0.36), zoom: 15.0)),
            ),
            Align(
                alignment: Alignment.bottomCenter,
                child: anchoredBanner == null
                    ? Container()
                    : Container(
                        color: Colors.black54,
                        width: anchoredBanner!.size.width.toDouble(),
                        height: anchoredBanner!.size.height.toDouble(),
                        child: AdWidget(ad: anchoredBanner!),
                      ))
          ],
        ));
  }

  @override
  void dispose() {
    controller!.dispose();
    super.dispose();
  }
}

```
</details>

<details>
<summary>Output</summary>

### Webview Virtual displays

https://user-images.githubusercontent.com/31410839/129718822-23e7fab1-7ce9-4733-beba-6721709975a1.mov


### Webview with Hybrid composition
https://user-images.githubusercontent.com/31410839/129717673-beeb9d69-422b-4e1c-bb79-48a8bb63b9b1.mov


### Google maps

The video shows the google maps works fine but as soon as the banner ad is loaded Ui freezes

https://user-images.githubusercontent.com/31410839/129718911-f3bbf252-53fe-4b27-ae96-c02bb8801e0d.mov

</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.8, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.8 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (7 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```
</details>

**Comment by speedlightwp** [comment]
I am facing the same issue. IOS working fine, load smoothly. Android not working.

google_mobile_ads: ^0.13.3
google_maps_flutter: ^2.0.6

**Comment by bunjongy** [comment]
any update?

**Comment by bparrishMines** [comment]
WebView already supports hybrid composition and GoogleMaps has been updated with: flutter/flutter#78578. See https://pub.dev/packages/webview_flutter and https://pub.dev/packages?q=google_maps_flutter for more information on how to use Hybrid Composition with either of the plugins.

**Comment by philipxj** [comment]
how can I use the GoogleMapsFlutterPlatform to fix google map with admob freeze?

**Comment by KaranMehta3984** [comment]
> WebView already supports hybrid composition and GoogleMaps has been updated with: [flutter/flutter#78578](https://github.com/flutter/flutter/issues/78578). See https://pub.dev/packages/webview_flutter and https://pub.dev/packages?q=google_maps_flutter for more information on how to use Hybrid Composition with either of the plugins.

@bparrishMines & @maheshmnj 
Have you got any solution?
If yes please provide a link or details with brief details.
Thank you In Advance.

**Comment by KaranMehta3984** [comment]
Thanks buddy……😀

**Comment by maheshmnj** [comment]
Update: Google Maps now supports hybrid composition, 

from the docs https://pub.dev/packages/google_maps_flutter use 

```
if (defaultTargetPlatform == TargetPlatform.android) {
  AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
}
```

**Comment by KaranMehta3984** [comment]
👍🏻

**Comment by mdusaama0** [comment]
> > the GoogleMap widget and AdWidget are currently incompatible. Ads use hybrid composition while google_maps_flutter uses virtual displays.
> 
> I came across this issue while I was using google_mobile_ads together with [qr_code_scanner](https://pub.dev/packages/qr_code_scanner), which uses the virtual display, but noticed that it also occured with the official [camera](https://pub.dev/packages/camera) plugin.
> 
> Having looked at the source code, I couldn't tell if the virtual display was used for the plugin. Does anyone have any idea about it, or could anyone look into it please?

did you find solution on this. I'm facing it with camera plugin.

**Comment by kaboc** [comment]
@bparrishMines 
#288 is the one. I mentioned the camera issue here after filing it because I thought it might be related and of help in some way. Thanks for clarifying it is unrelated.
