### ISSUE TITLE
frame of ads 

### ISSUE THREAD

**Issue by JumanDhaher** [googleads/googleads-mobile-flutter#323]
with banner ads "google ads manager"
the frame of ads is show with bottom and app bar {IOS}
it show like line behind the bottom or app bar 
when screenshot the frame/line gone

**Comment by TahaTesser** [comment]
Hi @JumanDhaher 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample and `flutter pub deps -- --style=compact`
Thank you

**Comment by JumanDhaher** [comment]
flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.121, on macOS 11.4 20F71 darwin-arm, locale en-SA)
    • Flutter version 2.3.0-17.0.pre.121 at /opt/homebrew/Caskroom/flutter/2.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71e711547f (8 weeks ago), 2021-05-30 19:31:03 -0700
    • Engine revision 73fe3dd31c
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/juman/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/juman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Users/juman/Documents/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 9F1FC7CB-05D7-4943-B729-787B000E45A4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 92.0.4515.107

! Doctor found issues in 1 category.

---
flutter pub deps -- --style=compact
Dart SDK 2.14.0-165.0.dev
Flutter SDK 2.3.0-17.0.pre.121
hwapp 1.0.0+1

dependencies:
- another_flushbar 1.10.24 [pedantic flutter]
- bubble 1.2.1 [flutter]
- cupertino_icons 1.0.3
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_absolute_path 1.0.6 [flutter]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_slidable 0.6.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_user_agent 1.2.2 [flutter]
- flutter_widget_from_html_core 0.6.1+3 [csslib flutter html]
- google_mobile_ads 0.13.2 [meta flutter]
- http 0.13.3 [async http_parser meta path pedantic]
- image_picker 0.8.1+3 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- introduction_screen 2.1.0 [flutter dots_indicator]
- liquid_pull_to_refresh 3.0.0 [flutter]
- multi_image_picker 4.8.01 [flutter meta]
- provider 5.0.0 [collection flutter nested]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- simple_splashscreen 0.1.3 [flutter]
- user_messaging_platform 1.0.0 [flutter collection meta]

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_native_splash 1.1.8+4 [image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.7.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- dots_indicator 2.0.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 4.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.4.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- petitparser 4.2.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- process 4.2.1 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.0
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

**Comment by TahaTesser** [comment]
Hi @JumanDhaher 
Also a complete reproducible minimal code sample to reproduce this issue
Thankyou

**Comment by JumanDhaher** [comment]
sample code:

AdManagerBannerAd bannerAd;
  bool isBannerAdLoad = false;
  bool first = true;
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (first) {
      first = false;
      _getAd();
    }
  }

  @override
  void dispose() {
    if (bannerAd != null) bannerAd.dispose();
    super.dispose();
  }


  _getAd() {
    bannerAd = AdManagerBannerAd(
      adUnitId: AdManager.nativeAdHomePage,
      sizes: [AdSize.mediumRectangle],
      request: AdManagerAdRequest(
        customTargeting: <String, String>{
          'gender': 'Female',
          'topic': 'الرئيسية',
          'pt': 'homepage',
          'platform': 'app',
        },
        customTargetingLists: <String, List<String>>{
          'pos': <String>['n_ma_homepage', 'MPU']
        },
      ),
      listener: AdManagerBannerAdListener(
        onAdLoaded: (Ad ad) {
          print('$BannerAd loaded.');
          setState(() {
            isBannerAdLoad = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          print('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => print('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => print('$BannerAd onAdClosed.'),
        onAdImpression: (Ad ad) => print('$BannerAd Ad impression.'),
      ),
    )..load();
  }


in build method inside column: 
 if (bannerAd != null && isBannerAdLoad)
                              Container(
                                alignment: Alignment.center,
                                child: AdWidget(ad: bannerAd),
                                width: bannerAd.sizes[0].width.toDouble(),
                                height: bannerAd.sizes[0].height.toDouble(),
                              ),


I use different code in many page but the same concept + problem of frame

**Comment by TahaTesser** [comment]
Hi @JumanDhaher 
Since the code sample is not complete, I am assuming you're not using SafeArea Widget,  the official sample uses SafeArea Widget to keep any widgets under safe area 
```dart
         body: Stack(
            alignment: AlignmentDirectional.bottomCenter,
            children: <Widget>[
              ReusableInlineExample(),
              if (_anchoredBanner != null)
                Container(
                  color: Colors.green,
                  width: _anchoredBanner!.size.width.toDouble(),
                  height: _anchoredBanner!.size.height.toDouble(),
                  child: AdWidget(ad: _anchoredBanner!),
                ),
            ],
          ),
```

> in build method inside column:


Please wrap your column or stack with zSafeAreaz widget

**Comment by JumanDhaher** [comment]
Not work still the frame show it from appBar and bottomBar
