### ISSUE TITLE
Update example for device orientation 

### ISSUE THREAD

**Issue by chitgoks** [googleads/googleads-mobile-flutter#324]
The ads are sized correctly on first load. however, if i start in landscape mode, and change orientation the size of the ads does not fill the width cscreen of the tablet. If i start the app in portrait mode , it resizes the width correctly and fills it.

I figure the only way for this to correctly size the ad in any orientation change is by removing it from widget tree and re-adding it?

How to possibly do so?

**Comment by TahaTesser** [comment]
Hi @chitgoks 
I think the better question would to how we can rebuild the ads widget based on the orientation 

For testing, I tried this but it doesn't rebuild the ads widget
```dart
   if (MediaQuery.of(context).orientation == Orientation.landscape) {
      size = await AdSize.getAnchoredAdaptiveBannerAdSize(
        Orientation.landscape,
        MediaQuery.of(context).size.width.truncate(),
      );
    } else
      size = await AdSize.getAnchoredAdaptiveBannerAdSize(
        Orientation.portrait,
        MediaQuery.of(context).size.width.truncate(),
      );
```

It would be nice to have a solution for this in the official wxaple

**Comment by chitgoks** [comment]
whats wxaple? yes we have the same code.  thank you for considering this

**Comment by jjliu15** [comment]
You can use [OrientationBuilder](https://flutter.dev/docs/cookbook/design/orientation#2-use-an-orientationbuilder-to-change-the-number-of-columns) to update the layout based on orientation. 

https://github.com/googleads/googleads-mobile-flutter/pull/418 updated the anchored adaptive example to do so.

**Comment by chitgoks** [comment]
> You can use [OrientationBuilder](https://flutter.dev/docs/cookbook/design/orientation#2-use-an-orientationbuilder-to-change-the-number-of-columns) to update the layout based on orientation.
> 
> #418 updated the anchored adaptive example to do so.

Sorry, i do not see the anchored adaptive example file in the repository. is it inside another dart file? I was thinking something like anchored_adaptive.dart file

**Comment by jjliu15** [comment]
See [anchored_adaptive_example.dart](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/example/lib/anchored_adaptive_example.dart)
