### ISSUE TITLE
[google_mobile_ads] App crashes on API 31

### ISSUE THREAD

**Issue by squallsama** [googleads/googleads-mobile-flutter#330]
## Plugin Version
```yaml
google_mobile_ads: ^0.13.2+1
```
## Steps to Reproduce
Put 31 version into `android\app\build.gradle`
```console
compileSdkVersion 31
targetSdkVersion 31
```

<details>
  <summary>pubspec.yml</summary>
  
```yml
name: android12test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_mobile_ads: ^0.13.2+1

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
```
  
</details>

<details>
 <summary>main.dart</summary>
 
 ```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
  <summary>build.gradle</summary>
  
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.example.android12test"
        minSdkVersion 26
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

</details>

<details>
  <summary>AndroidManifest.xml</summary>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.android12test">

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
   <application
        android:label="android12test"
        android:icon="@mipmap/ic_launcher">

       <meta-data
           android:name="com.google.android.gms.ads.APPLICATION_ID"
           android:value="ca-app-pub-3940256099942544~3347511713"/>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true"
            tools:replace="android:exported">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

</details>

**Comment by TahaTesser** [comment]
Hi @squallsama 
Are you using the API 31 emulator or a physical device? 
I just tried the emulator, app crashes even without `google_mobile_ads` 

Can you please provide `flutter doctor -v` and `flutter run -v`

**Comment by squallsama** [comment]
I tried both - official emulator with sdk31 and pixel 5. Both crashes with google_mobile_ads and works fine without it (with android:exported="true" in manifest.xml fix)

<details>
  <summary>flutter doctor -v</summary>

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (2 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\squall\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\squall\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\ojdkbuild\java-11-openjdk-11.0.11-1\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62
</details>


<details>
<summary>flutter run -v</summary>
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 install -t -r C:\Users\squall\AndroidStudioProjects\android12test\build\app\outputs\flutter-apk\app.apk
[+9116 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 9,1s)
[   +1 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell echo -n b0b7614d77329acf1c0527225648a9a4dbad5149 > /data/local/tmp/sky.com.example.android12test.sha1
[  +36 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell -x logcat -v time -t 1
[  +92 ms] --------- beginning of system
           08-06 13:01:15.546 W/BroadcastQueue( 1742): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.android12test flg=0x4000010 (has extras) } to org.fdroid.fdroid/.receiver.PackageManagerReceiver
[   +3 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.android12test/com.example.android12test.MainActivity
[  +83 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.android12test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +378 ms] E/AndroidRuntime(25365): FATAL EXCEPTION: pool-3-thread-1
[        ] E/AndroidRuntime(25365): Process: com.example.android12test, PID: 25365
[        ] E/AndroidRuntime(25365): java.lang.IllegalArgumentException: com.example.android12test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
[        ] E/AndroidRuntime(25365): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
[        ] E/AndroidRuntime(25365):     at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
[        ] E/AndroidRuntime(25365):     at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
[        ] E/AndroidRuntime(25365):     at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
[        ] E/AndroidRuntime(25365):     at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
[        ] E/AndroidRuntime(25365):     at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
[        ] E/AndroidRuntime(25365):     at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
[        ] E/AndroidRuntime(25365):     at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
[        ] E/AndroidRuntime(25365):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(25365):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(25365):     at java.lang.Thread.run(Thread.java:920)
</details>



And without 'google_mobile_ads' 
<details>
<summary>flutter run -v </summary>
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 install -t -r C:\Users\squall\AndroidStudioProjects\android12test\build\app\outputs\flutter-apk\app.apk
[+8301 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 8,3s)
[   +1 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell echo -n baf60f69e75295799a2a417128d3f72e0508c028 > /data/local/tmp/sky.com.example.android12test.sha1
[  +26 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell -x logcat -v time -t 1
[ +106 ms] --------- beginning of main
                    08-06 12:59:32.260 D/MediaPlayerList( 2284): Name of package changed: com.example.android12test
[   +4 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.android12test/com.example.android12test.MainActivity
[  +85 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.android12test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1918 ms] Observatory URL on device: http://127.0.0.1:40097/Gyjfrca0TZ8=/
[   +1 ms] executing: C:\Users\squall\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.170:37769 forward tcp:0 tcp:40097
[  +13 ms] 59190
[        ] Forwarded host port 59190 to device port 40097 for Observatory
[   +4 ms] Caching compiled dill
[  +20 ms] Connecting to service protocol: http://127.0.0.1:59190/Gyjfrca0TZ8=/
[ +841 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59190/Gyjfrca0TZ8=/.
[ +263 ms] DDS is listening at http://127.0.0.1:59196/JakzTW55s-g=/.
[  +53 ms] Successfully connected to service protocol: http://127.0.0.1:59190/Gyjfrca0TZ8=/
[  +42 ms] DevFS: Creating new filesystem on the device (null)
[  +42 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.android12test/code_cache/android12testNMHVZB/android12test/)
[   +1 ms] Updating assets
[  +55 ms] Syncing files to device Pixel 5...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:android12test/main.dart 0d183c1a-f0e6-48f2-b952-1ce9dbf0bf3a
[        ] <- 0d183c1a-f0e6-48f2-b952-1ce9dbf0bf3a
[  +48 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Pixel 5... (completed in 52ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +20 ms] Connected to _flutterView/0xb400007053757630.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[        ] An Observatory debugger and profiler on Pixel 5 is available at: http://127.0.0.1:59196/JakzTW55s-g=/
[  +89 ms] Activating Dart DevTools...
[ +558 ms] I/OpenGLRenderer(24653): Davey! duration=1408ms; Flags=1, FrameTimelineVsyncId=2123071, IntendedVsync=26179211924071, Vsync=26179211924071, InputEventId=0, HandleInputStart=26179212826561, AnimationStart=26179212832082, PerformTraversalsStart=26179212854165, DrawStart=26180593682168,
FrameDeadline=26179232424071, FrameInterval=26179212800103, FrameStartTime=11111111, SyncQueued=26180595982012, SyncStart=26180596047793, IssueDrawCommandsStart=26180596124043, SwapBuffers=26180614461805, FrameCompleted=26180620283056, DequeueBufferDuration=3227396, QueueBufferDuration=718073,
GpuCompleted=26180620283056, SwapBuffersCompleted=26180615601493, DisplayPresentTime=0,
[+1237 ms] Activating Dart DevTools... (completed in 1 795ms)
[ +457 ms] The Flutter DevTools debugger and profiler on Pixel 5 is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A59196%2FJakzTW55s-g%3D%2F
</details>

So, looks like some of intents in admob should use FLAG_IMMUTABLE

**Comment by iosdevmax** [comment]
Sorry for jumping in, I have a similar issue. When I set `compileSdkVersion` and`targetSdkVersion` to 29 I can see ads loading perfectly. When I put 30 in both, I get following:

```
I/flutter (13902): Failed to load a banner ad: Internal error.
I/flutter (13902): err.code - 0
I/flutter (13902): Failed to load an interstitial ad: Internal error.
I/flutter (13902): err.code - 0
```
Google play console says that the minimum supported version of a bundle is 30.

**Comment by squallsama** [comment]
@TahaTesser https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

**Comment by TahaTesser** [comment]
Hi @squallsama 
Thanks for the details, I can reproduce the issue on API S emulator aka Android 12 emulator 

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.120]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-6.0.pre.46, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.5.0-6.0.pre.46 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41ff30c871 (10 hours ago), 2021-08-10 23:03:48 -0700
    • Engine revision 4fef55db10
    • Dart version 2.14.0 (build 2.14.0-385.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64     • Android 11 (API 30) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.22000.120]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 92.0.4515.131
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 92.0.902.67

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

 For some reason, flutter doctor reports API 31 emulator as API 30

**Comment by squallsama** [comment]
Thanks @TahaTesser  . I wonder where PendingIntent used in this plugin. Can't find in repo.... 
`We couldn’t find any code matching 'PendingIntent' in googleads/googleads-mobile-flutter`

**Comment by squallsama** [comment]
Looks like this issue in ads service itself - https://groups.google.com/g/google-admob-ads-sdk/c/uCQkZcqOVtE?pli=1

**Comment by MattyBoy4444** [comment]
Any work on this.  I tried the mentioned PR and it doesn't seem to fix anything.

**Comment by squallsama** [comment]
> Any work on this? I tried the mentioned PR and it doesn't seem to fix anything.

I'm using version from my PR successfully with sdk31

```
  google_mobile_ads:
    git:
      url: https://github.com/squallsama/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: master
```

**Comment by MattyBoy4444** [comment]
I tried this and it still crashes immediately on start.  Nothing in Debug window.

**Comment by PeaceDeveloper** [comment]
> I tried this and it still crashes immediately on start. Nothing in Debug window. I am also using GoogleMobileAdsMediationFacebook and GoogleMobileAdsMediationAdColony

The same with me. The app not start with this library installed.

**Comment by maheshmnj** [comment]
Closing as fixed in https://github.com/googleads/googleads-mobile-flutter/pull/423

**Comment by MaherSafadii** [comment]
> Sorry for jumping in, I have a similar issue. When I set `compileSdkVersion` and`targetSdkVersion` to 29 I can see ads loading perfectly. When I put 30 or 31 in both, I get following:
> 
> ```
> I/flutter (13902): Failed to load a banner ad: Internal error.
> I/flutter (13902): err.code - 0
> I/flutter (13902): Failed to load an interstitial ad: Internal error.
> I/flutter (13902): err.code - 0
> ```
> 
> Google play console says that the minimum supported version of a bundle is 30.

did you solve this issue, if yes what did you do ?
