### ISSUE TITLE
Could not determine the dependencies of task ':compileReleaseAidl

### ISSUE THREAD

**Issue by yousefmasry4** [googleads/googleads-mobile-flutter#34]
`Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/youssef/flutter/.pub-cache/hosted/pub.dartlang.org/google_mobile_ads-0.11.0+1/android/local.properties'.`

**Comment by jjliu15** [comment]
Closing due to lack of response. Feel free to reopen if needed.
