### ISSUE TITLE
want to know about keywords and contentUrl

### ISSUE THREAD

**Issue by aanantt** [googleads/googleads-mobile-flutter#348]
I am using ```google_mobile_ads``` and there I see  **keywords** and **contentUrl** parameter in **AdRequest**.
Can anyone please help me like what are these, how to use it correctly and is it necessary to use?? 
Thanks.

**Comment by markusaksli-nc** [comment]
The documentation could be explained in the readme as well
https://github.com/googleads/googleads-mobile-flutter/blob/eb4da7b039e6e82d21840d07cccea1170b388c5c/packages/google_mobile_ads/lib/src/ad_containers.dart#L160-L162

**Comment by srichakradhar** [comment]
1. `keywords` are words or phrases describing the current user activity such as "Sports Scores" or "Football". Set this property to `null` or `nil` to clear the keywords.
* [How to manage your keywords.](https://support.google.com/google-ads/answer/7454124) 
* [Tips for building a keyword list](https://support.google.com/google-ads/answer/2453981)

2. When requesting an ad, apps may pass the URL of the content (`contentUrl`) they are serving. This enables keyword targeting to match the ad with the content.
* For example, if your app is requesting an ad while showing content from https://awesome.new.idea, you can pass this URL to target keywords relevant to the content (thus helping the publisher / developer a bit, with the keyword list).
