### ISSUE TITLE
Rewarded Ads re-render StatelessWidget after dismiss only on Android

### ISSUE THREAD

**Issue by tgdong2296** [googleads/googleads-mobile-flutter#349]
## Plugin Version

google_mobile_ads: ^0.13.3

## Steps to Reproduce

I have a screen using `StatelessWidget`.
When i call function showing Rewarded Ads, after ads dismiss, this screen is re-render (thats mean `Widget build(BuildContext context)` is called).
Issue is only appear on Android, not appear on iOS.

`_loadedAdSuggestion!.show(onUserEarnedReward: (RewardedAd ad, RewardItem reward) {
            // do something
});`

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en)
    • Flutter version 2.2.3 at /Users/tgdong2296/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tgdong2296/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @tgdong2296, Thanks for filing the issue could you please share a [minimal and complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), The sample code should be ready to run with minimal or no code changes.  
Thanks.

**Comment by Aksoyhlc** [comment]
i am having the same problem

**Comment by maheshmnj** [comment]
@Aksoyhlc I verified this on the latest stable 2.5.0 using the latest ads plugin 0.13.4 I don't see build widgets getting rebuilt again. Could you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the exact steps to reproduce the issue.


Thanks

**Comment by PonyPC** [comment]
I have same problem. When the rewarded ad shows, back to home screen, then click the app icon, the whole app reloaded.

**Comment by maheshmnj** [comment]
@PonyPC Please file a new issue with all the details requested in the issue teamplate.
