### ISSUE TITLE
Fan ads are not clickable in mediation

### ISSUE THREAD

**Issue by arunchaudharyweb** [googleads/googleads-mobile-flutter#351]
![Screenshot (152)](https://user-images.githubusercontent.com/59797321/130589705-d975dafc-714e-4e5a-84c5-6d46231db433.png)
Facebook told me that there was no need to use MediaView in native banner ads. It's clearly a bug in this plugin so please reopen this issue.

_Originally posted by @arunchaudharyweb in https://github.com/googleads/googleads-mobile-flutter/issues/175#issuecomment-904465563_

**Comment by jjliu15** [comment]
Hi @arunchaudharyweb, I have reopened your original issue. Closing this one as duplicate.
