### ISSUE TITLE
Update Readme with information regarding Mediation and SDKs

### ISSUE THREAD

**Issue by MattyBoy4444** [googleads/googleads-mobile-flutter#355]
I have already spent many hours figuring this out and want to document what I have found out for others.

Mediation and SDKs
Mediation is provided via client side SDKs and requires the mediation packages installed in Android and iOS.

Example: Facebook Audience Network

Android: Edit the file build.gradle in ./android/app.  Add the following line to your dependencies
```
implementation 'com.google.ads.mediation:facebook:6.5.1.1'
```

iOS: Edit the Podfile in ./ios.  Add the following lines near the top of the file
```
pod 'GoogleUtilities'  # There is a dependency issue which this resolves
pod 'GoogleMobileAdsMediationFacebook'
```

This information changes from time to time and seems to be kept up to date at
https://developers.google.com/admob/ios/mediation/facebook
https://developers.google.com/admob/android/mediation/facebook

You may have additional steps to perform based on the "Step 4: Additional code required" sections.

Example: Adding addition SKAdNetworkIdentifier's for iOS

Note: For iOS tracking on iOS 14.5 and greater I used the packages app_tracking_transparency, version and device_info_plus with the following code in my main.dart. 
```
  bool trackingEnabled = true;
  if (Platform.isIOS) {
    //FROM: https://pub.dev/packages/app_tracking_transparency
    var iosDeviceInfo = await DeviceInfoPlugin().iosInfo;
    var version = Version.parse(iosDeviceInfo.systemVersion);
    if (version >= Version(14, 5, 0)) {
      TrackingStatus status = await AppTrackingTransparency.trackingAuthorizationStatus;
      if (status == TrackingStatus.notDetermined) {
        status = await AppTrackingTransparency.requestTrackingAuthorization();
      }
      if (status != TrackingStatus.authorized) {
        trackingEnabled = false;
      }
    }
  }

  AdState? adState;
  if (!kIsWeb) {
    var initMobileAds = MobileAds.instance.initialize();
    adState = AdState(initMobileAds, trackingEnabled);
  }
```

My AdState trackingEnabled property is then used when creating my AdRequest.
2 cents worth.

**Comment by namchuai** [comment]
Thank you @MattyBoy4444 , in my case, I have to add `FBAEMKit` to Podfile as well.

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

pod 'GoogleUtilities'
pod 'FBAEMKit'
pod 'GoogleMobileAdsMediationFacebook'

# The rest of Podfile
```

**Comment by srichakradhar** [comment]
The [documentation](https://developers.google.com/admob/android/mediation/meta) has been updated.
