### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by roberthook823** [googleads/googleads-mobile-flutter#356]
Google_mobile_ads is really heavy. If this package is executed, any app will be completely out of performance. Rather the admob_flutter package is lighter. Can't you make it light?

**Comment by anuragsoni300** [comment]
same #318

**Comment by maheshmnj** [comment]
Hi @roberthook823, Thanks for filing the issue, There's already an open issue describing this case #318 you may follow up there for further updates. Closing this issue as duplicate if you disagree feel free to write in comments and I will reopen it.

Thank you.
