### ISSUE TITLE
My AdMob account got disabled using this plugin...

### ISSUE THREAD

**Issue by gkovac42** [googleads/googleads-mobile-flutter#366]
The reasons named in the email from Google were:

```
Violations found:

Enables dishonest behavior:
We do not allow content that:
helps users to mislead others.
promotes any form of hacking or cracking and/or provides users with instructions or equipment that tampers with or provides unauthorized access to software, servers, or websites.
```

I am more than a little shocked at this, as I have implemented all the ads as per instructions. Anyone else had a similar experience?

**Comment by TahaTesser** [comment]
Hi @gkovac42 
Did you add your store link to the Admob dashboard? Looks like your app was reviewed and violate rules
I don't think using this package would violate any rules. Not sure why you think this is a bug?

**Comment by gkovac42** [comment]
I don't know. I'm just desperate I guess. This came out of the blue, without any prior warnings or further explanations from the AdMob team. I'm utterly confused. I'm just trying to display a few banner ads within my Play Store published game. I have been doing it for more than a year, using the same ad setup without any issues, and only switched to this plugin recently, so I thought I'd ask here. My appologies if it's completely unrelated to this plugin.

**Comment by TahaTesser** [comment]
@gkovac42 
I suggest you contact admob support, to make sure it is the misdetection, Perhaps some user content violated rules? I am not sure. 
This definitely doesn't look like a plugin issue as the reasons are not related to the package functionality 
Closing,  If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by hortigado** [comment]
Same case :(
