### ISSUE TITLE
App Open Ads Support

### ISSUE THREAD

**Issue by pmathulan** [googleads/googleads-mobile-flutter#370]
## Use case

Want to support AdMob new ad type of **App Open** Ad

## Proposal
An ad format that appears when users open or switcheses back to your app. Ad overlays loading screen.

**Comment by maheshmnj** [comment]
Admob now supports new ad Type App Open Ads: https://developers.google.com/admob/android/app-open

Marking this issue as valid feature request.

**Comment by maheshmnj** [comment]
Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/171
