### ISSUE TITLE
 Ad failed to load : 3 with Test and real ad ids (Banner, Native ad)

### ISSUE THREAD

**Issue by izzetemredemir** [googleads/googleads-mobile-flutter#371]
I am getting this error: 
`LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))
`
many people seem to have faced this problem

My app used to show ads before, but I switched to this package.

## Plugin Version
^0.13.4

**Comment by maheshmnj** [comment]
Hi @izzetemredemirm Thanks for filing the issue, Are you experiencing this issue on ios or Android or both, Please share the output of `flutter doctor -v` and also make sure you have added the AdMob App ID in the AndroidManifest.xml as mentioned in the [docs](https://pub.dev/packages/google_mobile_ads)

If you still face the issue please share a minimal reproducible code sample.

Thanks

**Comment by svprdga** [comment]
I'm facing the same situation but only for test ads.

For instance, adding a banner ad with the id of `BannerAd.testAdUnitId` fails with `Ad failed to load : 3`. This was working before but some recent change has altered the plugin behavior.

**Comment by izzetemredemir** [comment]
@maheshmnj it is very common problem so it is not about my flutter version etc.

**Comment by maheshmnj** [comment]
@izzetemredemir and everyone who is facing this issue please share what device/platform are you facing this issue on?
and share the output of `flutter run -v`.

**Comment by maheshmnj** [comment]
@izzetemredemir @svprdga There seems to be a similar issue open describing this case https://github.com/googleads/googleads-mobile-flutter/issues/59 ,You may follow up there for further updates, Closing this issue as a duplicate if you disagree feel free to wrote in the comments and I will reopen it.

Thank you.
