### ISSUE TITLE
  Admob Mediation with Facebook Audience Network 

### ISSUE THREAD

**Issue by samithe7** [googleads/googleads-mobile-flutter#380]
is this  package support Admob Mediation !!!

**Comment by Vakil-Parth** [comment]
yes, Just add mediation Adaptor.

[https://developers.google.com/admob/android/mediate](url)

**Comment by maheshmnj** [comment]
Hi @samithe7,  please also refer  https://developers.google.com/admob/android/mediation/facebook along with the above link. Closing, since this issue doesn't seem to describe a bug or a feature request, If you disagree feel free to write in the comments and I will reopen it.

Thank you.
