### ISSUE TITLE
App is crashed in Android studio..

### ISSUE THREAD

**Issue by gunatitsolutions** [googleads/googleads-mobile-flutter#385]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @gunatitsolutions, Thanks for filing the issue. Please share the output of `flutter doctor -v` the version of the ads plugin you are experiencing the crash along with the exact steps to reproduce the issue.

And when filing issues in the future please try to fill some or all of the information requested in the issue templates it helps to address the issue better.

Thanks
