### ISSUE TITLE
[google_mobile_ads] Something appear recently in my app interstitial ads - native android bar

### ISSUE THREAD

**Issue by mustafa-707** [googleads/googleads-mobile-flutter#393]
## Plugin Version
after upgrading to flutter 2.5.1 I found this kind of random behavior on interstitial ads 
I used 
`google_mobile_ads 0.13.5 ` and `google_mobile_ads 0.13.4 `

i tried it on debug and on release mode but it's also appear in both 
its looks a native android widget that came from android studio android templets 

##Screen Shot
![243153071_1238281760020518_6382467743597471074_n](https://user-images.githubusercontent.com/74349843/135177578-4528d1f5-13e1-4990-84de-f6bdd46d2159.png)

**Comment by maheshmnj** [comment]
Hi @mustafa-707, I ran the official sample app from pub and I could not reproduce the issue using `google_mobile_ads: 0.13.5`,  On which device are you seeing this issue ?  Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

Thanks

**Comment by mustafa-707** [comment]
actually i tried the same code with flutter 1.66.2 and flutter 2.2.3 and all good

the problem just happened when I upgrade to flutter 2.5.0 and flutter 2.5.1

my device is Huawei Nova 7i

flutter doctor -v
```
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\is10vmust\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (4 available)
    • JNY LX1 (mobile)                   • AUDUT20221002068 • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge             • web-javascript • Microsoft Edge 93.0.961.52

```

**Comment by maheshmnj** [comment]
@mustafa-707 does this happen on your specific device or other android device/ emulator too?

**Comment by mustafa-707** [comment]
this video using the flutter emulator also i tried it in many android devices and the result is same :

https://user-images.githubusercontent.com/74349843/135749928-86246418-12fc-4bf6-9e0a-eab84a8653d8.mp4


also its happen in other type of social login that shows also a random android native bar with the app name , all of that's only notice after moving from flutter 2.3.x to flutter 2.5.x  idk if it caused by the flutter sdk or from another dependencies will try it after removing plugins.

**Comment by maheshmnj** [comment]
@mustafa-707  does this reproduce on another device or emulator?

**Comment by mustafa-707** [comment]
No , I tried it on much devices and emulators all them have the same behavior So I guess it's a flutter 2.5.x issue or it's from my project something goes wrong , I will investigate and already wrote an issue on flutter repository

**Comment by maheshmnj** [comment]
> Please share a minimal and complete reproducible code to better address the issue

@mustafa-707  could you please share a sample code or a repository containing minimal code sample? It will help to find the cause of the issue.

Thanks

**Comment by mustafa-707** [comment]
after much investigation on my project i found the cause of the problem , it was all the time the plugin named : 

`sentry_flutter`

when i removed it it was solved ,

 i will let sentry knows that , thank you all guys
