### ISSUE TITLE
Banner Ad freezes My App during the day, works fine during the night?!

### ISSUE THREAD

**Issue by mutasimdarras** [googleads/googleads-mobile-flutter#401]
I have implemented the banner ad exactly as the readme stated, the App freezes due to this widget 
```
final AdWidget adWidget = AdWidget(ad: myBanner);
```
All the ads work fine when I open the app at night (GMT+3) but the app freezes during the day as soon as the banner ad loads.
I have also added interstitial Ads and they work at all times.
Any thoughts?

**Comment by Mehu007** [comment]
I am facing the same issue. Is there any solution?
I have Google maps with Banner ad and the bannerAd freezes the Map and the whole app.

**Comment by maheshmnj** [comment]
> am facing the same issue. Is there any solution?
I have Google maps with Banner ad and the bannerAd freezes the Map and the whole app.

@Mehu007  the issue you are referring to is about PlatformViews and you need to use Hybrid Composition for GoogleMaps as [mentioned in this comment](https://github.com/googleads/googleads-mobile-flutter/issues/32#issuecomment-929675598)

**Comment by mutasimdarras** [comment]
Solved, save yourself time and use **native_admob_flutter** package instead.

**Comment by maheshmnj** [comment]
> Solved, save yourself time and use native_admob_flutter package instead.

This does not necessarily mean the issue does not exist. In order for this issue to be actionable, we would need `reproducible steps` along with the output of `flutter doctor -v`, and `ads plugin version` that you are having issue with.

Anyone who is facing a similar issue, please provide the above info and I will reopen this issue.

Thank you.

**Comment by maheshmnj** [comment]
@Mehu007  Google maps now supports hybrid compositon https://github.com/googleads/googleads-mobile-flutter/issues/32#issuecomment-957124290 so you should no longer see a freeze when using with ads plugin. If you do feel free to file a issue.
