### ISSUE TITLE
The link in the changelog for app open ads guidance is inaccessible

### ISSUE THREAD

**Issue by digitalby** [googleads/googleads-mobile-flutter#403]
The changelog for version 0.13.5 mentions the following:

> 
> Adds support for app open.
> 
>     Implementation guidance can be found here.
>     As a reference please also see the example app.
>     Best practices can be found here.

When clicking the link for implementation guidance (https://developers.devsite.corp.google.com/admob/flutter/app-open), the website requires sign in to an internal Google resource. Thus, the guidance material cannot be accessed.

**Comment by jjliu15** [comment]
The link has been updated in the changelog. See https://developers.google.com/admob/flutter/app-open
