### ISSUE TITLE
Issue with AppOpen Ads

### ISSUE THREAD

**Issue by DabPb** [googleads/googleads-mobile-flutter#404]
## Plugin Version : 0.13.5

When we show Interstitial ads, App open ad is also displayed each time. it means display twice ads 1 interstitial and another one is App open. some times it going to in infinite loop, App open ads not close.

**Comment by DabPb** [comment]
```
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:googlemobileadverts/app_lifecycle_reactor.dart';

import 'app_open_ad_manager.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(const MyApp());
}

const String testDevice = 'YOUR_DEVICE_ID';
const int maxFailedLoadAttempts = 3;

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static final AdRequest request = AdRequest(
    keywords: <String>['foo', 'bar'],
    contentUrl: 'http://foo.com/bar.html',
    nonPersonalizedAds: true,
  );

  InterstitialAd? _interstitialAd;
  int _numInterstitialLoadAttempts = 0;

  @override
  void initState() {
    super.initState();
    _createInterstitialAd();

    AppOpenAdManager appOpenAdManager = AppOpenAdManager()..loadAd();
    WidgetsBinding.instance!
        .addObserver(AppLifecycleReactor(appOpenAdManager: appOpenAdManager));
  }

  void _createInterstitialAd() {
    InterstitialAd.load(
        adUnitId: InterstitialAd.testAdUnitId,
        request: request,
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (InterstitialAd ad) {
            print('$ad loaded');
            _interstitialAd = ad;
            _numInterstitialLoadAttempts = 0;
            _interstitialAd!.setImmersiveMode(true);
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('InterstitialAd failed to load: $error.');
            _numInterstitialLoadAttempts += 1;
            _interstitialAd = null;
            if (_numInterstitialLoadAttempts <= maxFailedLoadAttempts) {
              _createInterstitialAd();
            }
          },
        ));
  }

  void _showInterstitialAd() {
    if (_interstitialAd == null) {
      print('Warning: attempt to show interstitial before loaded.');
      return;
    }
    _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (InterstitialAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },
      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },
    );
    _interstitialAd!.show();
    _interstitialAd = null;
  }

  @override
  void dispose() {
    super.dispose();
    _interstitialAd?.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Builder(builder: (BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('AdMob Demo'),
          ),
          body: SafeArea(
            child: Center(
                child: OutlinedButton(
                    onPressed: () => _showInterstitialAd(),
                    child: const Text('View Interstitial Ads'))),
          ),
        );
      }),
    );
  }
}
```




> [✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
>     • Flutter version 2.5.2 at /Users/pradipdabhi/Library/Android/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
>     • Engine revision 6ac856380f
>     • Dart version 2.14.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/pradipdabhi/Library/Android/sdk
>     • Platform android-31, build-tools 31.0.0
>     • ANDROID_HOME = /Users/pradipdabhi/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5.1, Build version 12E507
>     • CocoaPods version 1.11.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] Connected device (2 available)
>     • Redmi 6A (mobile) • 56.223.97.183:5555 • android-arm    • Android 9 (API 28)
>     • Chrome (web)      • chrome             • web-javascript • Google Chrome 94.0.4606.81
> 
> • No issues found!
>

**Comment by maheshmnj** [comment]
Closing as fixed in https://github.com/googleads/googleads-mobile-flutter/pull/425
