### ISSUE TITLE
Banner Ads not working correctly on Android, portions of content disappear and reappear below the ads when scrolling up and down

### ISSUE THREAD

**Issue by Sunny-Aiub** [googleads/googleads-mobile-flutter#410]
<img src="https://user-images.githubusercontent.com/15309436/138161898-58e1a39c-bed3-4b2a-89b9-e04a4c8ac053.png" width ="300">

<img src="https://user-images.githubusercontent.com/15309436/138161909-9bab4389-fe3c-4e38-88b3-f4a2a7dd1126.png" width ="300">

<img src="https://user-images.githubusercontent.com/15309436/138161917-f31bb1be-41e9-46f8-9346-e1fab11bdfeb.png" width ="300">

## Details

**Target Platform:**
**Target OS version:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Sunny-Aiub 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that we can use to verify this behavior ?
Thanks.
