### ISSUE TITLE
onPaidEvent for InterstitialAd

### ISSUE THREAD

**Issue by ale-getman** [googleads/googleads-mobile-flutter#426]
NativeAd has a listener with onPaidEvent, but InterstitialAd does not

**Comment by jjliu15** [comment]
The onPaidEvent API is slightly different for full screen ads. They share an inherited property, `onPaidEvent`: https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/lib/src/ad_containers.dart#L578, which can be set after loading the ad.

**Comment by ale-getman** [comment]
> The onPaidEvent API is slightly different for full screen ads. They share an inherited property, `onPaidEvent`: https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/lib/src/ad_containers.dart#L578, which can be set after loading the ad.

Yes, it's like a function to which parameters must be passed, although the comments describe that this is a callback.
And as far as I understand, there is no place to get these input parameters, since this is not an event listener from the user.
Unfortunately, there is no understanding of how to use such a callback for InterstitialAd
![image](https://user-images.githubusercontent.com/6009175/140885844-82269350-63a7-475b-8397-166fe0417b11.png)
