### ISSUE TITLE
Blank screen after few seconds

### ISSUE THREAD

**Issue by brunodmn** [googleads/googleads-mobile-flutter#431]
## Plugin Version

google_mobile_ads: ^0.13.5

## Steps to Reproduce

I am not sure how to reproduce this, I have a lot of code and it started happening after I added googleads-mobile-flutter to it.
I know it is very hard to determine what is happening without reproducing the error, but at least someone could have a clue about this problem.

**Expected results:** 
Application runs normal and ads shown.

**Actual results:** 
Widgets get "blank" after some seconds, everything works normal (i.e. buttons, methods, classes).

**Issue**
 Really seems like some rendering problem. I also thought  could be some memory leak or something, but memory test on dev tools does not point it. Also I read something about android garbage collector and flutter embedding.
 I only happens when ads are active (if user gets premium it stops happening).
 Seems that it occurs when webview is destroyed (log: "W/Ads     (13786): 004 The webview is destroyed. Ignoring action.")

<table>
<tr>
<td >
<img src=https://user-images.githubusercontent.com/53493535/141354321-8b964c0f-ced9-444b-afae-4a4c9848fbff.jpg width="200">
</td>
<td>
<img src=https://user-images.githubusercontent.com/53493535/141354484-27f54b7e-ef77-4087-85c0-ece805833861.jpg width="200">
</td>
</tr>
<tr>
<td >
<img src=https://user-images.githubusercontent.com/53493535/141355497-10f398cd-d55b-40e5-a1f9-9d807a20d884.jpg width="200">
</td>
<td>
<img src=https://user-images.githubusercontent.com/53493535/141355584-fd319ea8-ffed-4f72-afa6-af2a70232079.jpg width="200">
</td>
</tr>
</table>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-BR)
    • Flutter version 2.5.3 at /Users/brunoandrade/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/brunoandrade/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2003J15SC (mobile) • 0fe657a70502 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos        • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 95.0.4638.69
```

</details>

**Comment by railsonsm** [comment]
I think I have something similar. When I open any page of my app that has an appbar it is blank it is a few thousandths blank.
![image](https://user-images.githubusercontent.com/35712745/141567719-6a0c7672-06fe-4042-9480-21bfb04f095e.png)

**Comment by brunodmn** [comment]
I am now using [admob_flutter](https://pub.dev/packages/admob_flutter), which works fine despite it's using a "deprecated version of the Android embedding".
 Really seems like google_mobile_ads is leaking memory (at least with the copy/paste code of sample folder), and eventually garbage collector clean up the app and screw the render up. A lot of "Background concurrent copying GC freed" is thrown while package is running.

**Comment by maheshmnj** [comment]
Hi @brunodmn, Thanks for filing the issue. I can understand creating a reproducible code might not be easy, But can you please provide some more info
- Is this issue reproducible only with a specific ad/ device/ or Platform (IOS)
- Does this issue occur on a newly created sample app with an ad too?
- Can you please try to determine the reproducible steps, and whether this occurs 100% of the time or is intermittent?

On a side note, can you please try upgrading to the latest plugin 0.13.6, and see if you are still able to reproduce the issue?

Thanks

**Comment by maheshmnj** [comment]
@railsonsm  it would be really helpful to debug the cause of the issue if you can come up with a minimal reproducible code.

Thanks

**Comment by brunodmn** [comment]
> Hi @brunodmn, Thanks for filing the issue. I can understand creating a reproducible code might not be easy, But can you please provide some more info
> 
> * Is this issue reproducible only with a specific ad/ device/ or Platform (IOS)
> * Does this issue occur on a newly created sample app with an ad too?
> * Can you please try to determine the reproducible steps, and whether this occurs 100% of the time or is intermittent?
> 
> On a side note, can you please try upgrading to the latest plugin 0.13.6, and see if you are still able to reproduce the issue?
> 
> Thanks

Hi @maheshmnj, it happens every time, some times after few seconds, sometimes few minutes. I've noticed if I try to login with Google (firebase_auth/google_sign_in) it happens right away. 
I have tried with Android only. I don't think it's with some specific ad, I tried removing banner and keeping intersticial, and the other way around, same results.
 I did upgrade to latest version 0.13.6 and it keeps going.
 I will create a new app and try to reproduce by today, I'll keep you posted.
 Thank you.

**Comment by brunodmn** [comment]
@maheshmnj, I just started a new project and now I am not even able to run it.

 Using de version 1.0.0, bellow error is throw:
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)

```
 To reproduce, start a new project and initialize the instance:
```
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}

```
On Manifest add:
  ```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxx~xxxx"/>
```

already tried without success, add bellow snippet at debug config:
```
configurations.all {
    resolutionStrategy { force 'androidx.core:core-ktx:1.6.0' }
}
```
I also tried to change minSdkVersion/targetSdkVersion to 31 with no success.

Also tried to override workmanager dependency.
 ```
dependencies {
      implementation('androidx.work:work-runtime') {
          version {
              strictly '2.6.0'
          }
      }
  }
```

I am trying to run it on Android device, on a Linux Mint machine.

**Comment by brunodmn** [comment]
> @maheshmnj, I just started a new project and now I am not even able to run it.
> 
> Using de version 1.0.0, bellow error is throw:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
>    > The minCompileSdk (31) specified in a
>      dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
> ```
> 
> To reproduce, start a new project and initialize the instance:
> 
> ```
> import 'package:google_mobile_ads/google_mobile_ads.dart';
> import 'package:flutter/material.dart';
> 
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   MobileAds.instance.initialize();
>   runApp(const MyApp());
> }
> ```
> 
> On Manifest add:
> 
> ```
> <meta-data
>           android:name="com.google.android.gms.ads.APPLICATION_ID"
>           android:value="ca-app-pub-xxxx~xxxx"/>
> ```
> 
> already tried without success, add bellow snippet at debug config:
> 
> ```
> configurations.all {
>     resolutionStrategy { force 'androidx.core:core-ktx:1.6.0' }
> }
> ```
> 
> I also tried to change minSdkVersion/targetSdkVersion to 31 with no success.
> 
> Also tried to override workmanager dependency.
> 
> ```
> dependencies {
>      implementation('androidx.work:work-runtime') {
>          version {
>              strictly '2.6.0'
>          }
>      }
>  }
> ```
> 
> I am trying to run it on Android device, on a Linux Mint machine.

Nevermind, I made it work with some changes, as follows:

On build.gradle  (project level), changed `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.4.32'`.
On build.gradle  (app level), changed `compileSdkVersion 30` to `compileSdkVersion 31` and  `minSdkVersion 16` to `minSdkVersion 19`.
Should it be in documentation or it happened just on my machine?

Now I'll check if blank screen will be shown with this minimal app and I'll let you know. Thanks.

**Comment by mattf80** [comment]
I'm also having the same issue as reported above. 

1. Create brand new flutter app
2. Add google_mobile_ads package
3. Update main.dart to

`import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}`

Try to run and get error message:

`* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
`

I also tried manually updating ../app/build.gradle to:

`compileSdkVersion 30` => `compileSdkVersion 31` and also

```
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.ad_testing"
        minSdkVersion 21
        targetSdkVersion 30 => targetSkdVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```

But this then also doesn't compile and throws errors related to Kotlin version.

Running on Windows with an Android virtual device. Thanks.

**Comment by maheshmnj** [comment]
> But this then also doesn't compile and throws errors related to Kotlin version.

Running on Windows with an Android virtual device. Using Flutter Stable channel. Thanks.

@mattf80 please file this as a separate issue to track.

**Comment by maheshmnj** [comment]
@brunodmn  use `ext.kotlin_version = '1.6.10'`
