### ISSUE TITLE
Native Ads does not show on iOS!

### ISSUE THREAD

**Issue by fatihmerickoc** [googleads/googleads-mobile-flutter#432]
I want to make an app that shows native ads for iOS and Android.

First I decided to show a native ad in Android.
I followed documentation in "https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7".
and it worked!

but when i followed the same documentation on iOS i got this error: 
"Thread 1: "Could not load NIB in bundle: 'NSBundle".

I made a research but i found nothing.
Please help!

**Comment by fatihmerickoc** [comment]
Btw i am beginner so if do you need any files for solving the problem, please ask.

**Comment by maheshmnj** [comment]
Hi @fatihmerickoc, Thanks for filing the issue. Please share the output of `flutter doctor -v` and the version of ads plugin you are having issues with. 

Thanks.

**Comment by fatihmerickoc** [comment]
Thanks for replyling me. I just solved the problem yesterday. There is no problem it was just my stupid brain. 
i typed wrong class for wrong thing.
