### ISSUE TITLE
[Docs] Admob banner app link broken

### ISSUE THREAD

**Issue by maheshmnj** [googleads/googleads-mobile-flutter#437]
The banner app page is broken on Admob https://developers.google.com/admob/flutter/banner

cc: @jjliu15

**Comment by SoftWyer** [comment]
This is the correct link:

https://developers.google.com/admob/flutter/banner/get-started

**Comment by maheshmnj** [comment]
@SoftWyer yes, but the issue is when you click on implement bannerAd it points to the link (broken) I shared above.  

![image](https://user-images.githubusercontent.com/31410839/142355772-97ec3c76-1e93-445f-a3b5-acc186f11789.png)

**Comment by jjliu15** [comment]
The link is fixed now.
