### ISSUE TITLE
Compile time errors using google_mobile_ads plugin

### ISSUE THREAD

**Issue by mattf80** [googleads/googleads-mobile-flutter#438]
## Plugin Version

version 1.0.0

## Steps to Reproduce

1. Create brand new flutter app
2. Add google_mobile_ads package
3. Update main.dart to:

```
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}
```
4. Try to run the app.

Running on Windows with an Android virtual device. Using Flutter Stable channel. 

**Expected results:**

Flutter stater template app to compile and run normally

**Actual results:**

Compile time error:

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
```

Based on the error I tried manually updating ../app/build.gradle to:

`compileSdkVersion 30 => compileSdkVersion 31` and also

```
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.ad_testing"
        minSdkVersion 21
        targetSdkVersion 30 => targetSkdVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

```
But this also doesn't compile and throws errors related to Kotlin version.

```
 Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by brunodmn** [comment]
Hi @mattf80 ,

 Try this:

On file android/build.gradle: 
**ext.kotlin_version = '1.3.50'** to **ext.kotlin_version = '1.4.32'**.

On file android/app/build.gradle:
**compileSdkVersion 30** to **compileSdkVersion 31**  (its NOT targetSdkVersion, look for it under android tag above)
 **minSdkVersion 16** to **minSdkVersion 19**.

After you change everything:
**flutter clean**
**flutter pub get**

**Comment by mattf80** [comment]
Thank you, that has worked! I missed updating the ext.kotline_version value. 

Appreciate you taking the time to help.

**Comment by Somtobro** [comment]
@mattf80 @brunodmn I did these exact stuff but my apps still crashing on start??
You know what's up??

**Comment by brunodmn** [comment]
Hi @Somtobro, did you add your app id on manifest? As below:
```
<manifest>
    <application>
        <!-- TODO: Replace with your real AdMob app ID -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-################~##########"/>
    </application>
</manifest>
```

If you did, add some logs so we can try to help you out.
