### ISSUE TITLE
Unable to show test ads. Getting erro code 3 while using test app id and test ad units. 

### ISSUE THREAD

**Issue by imyogisingh** [googleads/googleads-mobile-flutter#439]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @imyogisingh, Thanks for filing the issue. Can you please share the complete logs I suspect this to be same as https://github.com/googleads/googleads-mobile-flutter/issues/59

**Comment by angelbuzon** [comment]
in the emulator: 
if I set the good banner ids, the advertising is displayed, but if I set the test ids, for example "ca-app-pub-3940256099942544/6300978111" for the banner, it doesn't work.
Something happens with the test ids that do not work.

**Comment by angelbuzon** [comment]
and another thing: the command to include test devices does not work:
for example:

MobileAds.instance.initialize().then((InitializationStatus status) {

    print('Initialization done: ${status.adapterStatuses}');
    MobileAds.instance.updateRequestConfiguration(
      RequestConfiguration(tagForChildDirectedTreatment: TagForChildDirectedTreatment.unspecified, testDeviceIds: <String>[
        '40D226F0D6F1FBE1A859873764935895',
      ]),  
    );

  });

the line " print('Initialization done: ${status.adapterStatuses}');"  is never executed.
it doesn't matter if I set an awaite like  "await MobileAds.instance.initialize...."  or not.

**Comment by maheshmnj** [comment]
> if I set the good banner ids, the advertising is displayed, but if I set the test ids, for example "ca-app-pub-3940256099942544/6300978111" for the banner, it doesn't work.
Something happens with the test ids that do not work.

@angelbuzon please share the logs

> the line " print('Initialization done: ${status.adapterStatuses}');" is never executed.
it doesn't matter if I set an awaite like "await MobileAds.instance.initialize...." or not.

This issue may be related to https://github.com/googleads/googleads-mobile-flutter/issues/429
