### ISSUE TITLE
request iOS mediation example in swift

### ISSUE THREAD

**Issue by Hasankanso** [googleads/googleads-mobile-flutter#441]
I don't know swift or objective-c, but our flutter app uses swift, at least the AppDelegate.swift

https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/mediation_example

can someone translate the mediation iOS code above to swift? or share your code with us :)

thank you.

**Comment by maheshmnj** [comment]
Hi @Hasankanso, thanks for filing the issue.

> can someone translate the mediation iOS code above to swift? or share your code with us :)

I would advise you to please take a look at this [documentation](https://developers.google.com/admob/ios/mediate) and see if this helps. If you need further info, I would advise you to please ask on StackOverflow.
Closing as this isn't an issue with the Google ads mobile flutter.

Thank you.
