### ISSUE TITLE
Iron Source adapter isn't initialized 

### ISSUE THREAD

**Issue by mikron123** [googleads/googleads-mobile-flutter#447]
I followed the AdMob instructions, yet the Iron Source adapter's output is:

`I/flutter (13965): Adapter status for com.google.ads.mediation.ironsource.IronSourceMediationAdapter: 102: IronSource SDK requires an Activity context to initialize.`

Is it needed to even include the adapter even though I only use it in the AdMob waterfall?

**Comment by maheshmnj** [comment]
Hi @mikron123,  Thanks for filing the issue. can you please share the version of the ads plugin you are using and also the complete error logs, Additionally Please refer these docs https://developers.google.com/admob/android/mediation/ironsource

Thanks.

**Comment by mikron123** [comment]
Using 1.0.0 for googleads
and copied the relevant plugin line from the AdMob IronSource adapter docs

**Comment by maheshmnj** [comment]
Thanks for the info, Keeping this issue open for further investigation.

**Comment by kolotum** [comment]
I think we have the same issue with UnityAds.

The mediation adapter worked fine until 0.13.5

Starting with 0.13.6 the mediation adapter can not load ads anymore. This behaviour did not change with google_mobile_ads 1.0.0. So we rolled back to 0.13.5 for now.

**Comment by maheshmnj** [comment]
Closing this issue as fixed if you disagree feel free to write in the comments and I will reopen it.
