### ISSUE TITLE
iOS app doesn't start after integrating ads package in emulator 

### ISSUE THREAD

**Issue by utekau** [googleads/googleads-mobile-flutter#451]
Hi,

I just started to integrate google_mobile_ads with my flutter app. I'm using iOS emulator. I was following the docs here: [google_mobile_ads](https://developers.google.com/admob/flutter/quick-start#ios)

**Plugin version:** 
1.0.0

1. I'm using test account for banner ads. You can see what I added to Info.plist below.

```
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544/2934735716</string>
```

**Expected results:** 
I expect to open the app without any issue.

**Actual results:**
The app doesn't show up. Instead, I'm getting an error like below:

Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
CoreSimulator 776.4 - Device: iPhone 11 (CD575FB1-22E5-4402-9B33-F99D26F8AB45) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 11
terminating with uncaught exception of type NSException
*** **Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID.** Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
abort() called

To overcome this problem, I saw that post, https://stackoverflow.com/questions/58405905/ads-sdk-was-initialized-without-an-application-id. Then, based on what explained, I simply added 	
```
<key>GADIsAdManagerApp</key>
<string>true</string>
```
as well and this problem is fixed. I don't know whether it is a correct way to handle it or not. I just want to be sure that that addition to plist is necessary?

My environment:
Flutter (Channel stable, 2.5.0, on macOS 12.0.1 21A559 darwin-arm, locale tr-TR)
Android toolchain - develop for Android devices (Android SDK version 31.0.0)
Xcode - develop for iOS and macOS
Chrome - develop for the web
Android Studio (version 2020.3)
VS Code (version 1.62.3)

**Comment by darshankawar** [comment]
@utekau 
It seems the entry you are passing in `info.plist` has typo.

`<string>ca-app-pub-3940256099942544/2934735716</string>` should be `~` instead of `/` ie

`<string>ca-app-pub-3940256099942544~2934735716</string>` . Try this and see if it works.

**Comment by utekau** [comment]
Hi @darshankawar,

Normally, there isn't any `~` but for the test account the id includes slash.

**Comment by maheshmnj** [comment]
@utekau can you please try with `~` instead of `/` as can be seen in the ios setup docs https://developers.google.com/admob/flutter/quick-start#ios

**Comment by utekau** [comment]
Hi,
I noticed that I wrongly given id. So, we can close this issue.
