### ISSUE TITLE
Update Documentation to Clarify if Personalized Ads are the Default

### ISSUE THREAD

**Issue by zerox1212** [googleads/googleads-mobile-flutter#457]
## Use case

Using basic banner ads in my flutter applications and it is not clear if the default example will serve personalized ads or not. I searched all the documentation and there is no details about what is default. There are only explanations of the two different kinds of ads.

## Proposal

Explicitly clarify in the the docs if ads are Personalized or Non-personalized when `nonPersonalizedAds = null`.

**Comment by timothyhoang-google** [comment]
[@zerox1212](https://github.com/zerox1212), controls for ads personalization are covered in the GMA SDK for Flutter [CCPA Preparation](https://developers.google.com/admob/flutter/ccpa) documentation. By default, Google will serve personalized ads. 

When either Google's RDP or the [IAB-defined](https://iabtechlab.com/wp-content/uploads/2019/11/Technical-Specifications-FAQ-US-Privacy-IAB-Tech-Lab.pdf) IABUSPrivacy_String parameter is used, Google restricts how it uses certain unique identifiers and other data processed in the provision of services to publishers. As a result, Google will only show non-personalized ads. These parameters override the RDP settings in the UI.
