### ISSUE TITLE
[IOS] Ads in Listviews has frame drops

### ISSUE THREAD

**Issue by creativeandresearch** [googleads/googleads-mobile-flutter#460]
I use this plugin for ios  , when it show ads in scroll , its skip frame . anyone same as me?

## Plugin Version

google_mobile_ads 1.0.1

## Details

**Target Platform:**
ios
**Target OS version:**
15
**Devices:**
iphone 12 pro

**Comment by creativeandresearch** [comment]
https://youtu.be/zQIS5Q-v0J4 this is my slow test.....

**Comment by maheshmnj** [comment]
Hi @creativeandresearch, Please share the output of `flutter doctor -v`, and minimal reproducible steps.

Thanks

**Comment by creativeandresearch** [comment]
the doctor -v is here, thank you.

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.1 20C69 darwin-x64, locale zh-HK)
    • Flutter version 2.5.3 at /Users/creativeandresearch/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/creativeandresearch/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/creativeandresearch/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/creativeandresearch/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 7A14618A-FE80-49F7-817C-3E5840FEDC2C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.93

**Comment by creativeandresearch** [comment]
minimal reproducible steps.

you means this ?
https://youtu.be/IRO5LqZ9VSY

**Comment by creativeandresearch** [comment]
I read so much document. And some document said need to add plist :

	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>

. I set it and feel something good now .  I will test more times . I have no much more info about this. can any one tell me why ?

**Comment by maheshmnj** [comment]
@creativeandresearch does above help improve the frame rate?
 you might want to take a look at this https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro

**Comment by creativeandresearch** [comment]
ok, I test the setting one week. its also slow , when admob has animate adv , its drop more frames.

**Comment by creativeandresearch** [comment]
Any update for this ? I am use resuse inline sample , but is also lag when animate adv , taobao.com adv lag more....

**Comment by maheshmnj** [comment]
Everyone who is facing a similar issue please verify by upgrading to latest `stable 2.8.0`.

Thanks
