### ISSUE TITLE
[Rewarded ad] Get callback when rewardedAd is available to load

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#463]
To show the ad I do this:

    await adState.showRewardedAd();
    await adState.rewardedAd!.show(onUserEarnedReward: (RewardedAd ad, RewardItem reward) {
    // reward
    });
and:

    Future createRewardedAd([bool showVideo = false]) async {
        await RewardedAd.load(
          adUnitId: rewardeUnitAdId,
          request: request,
          rewardedAdLoadCallback: RewardedAdLoadCallback(
            onAdLoaded: (RewardedAd ad) async {
              adState.rewardedAd = ad;
              _numRewardedLoadAttempts = 0;
              if (showVideo) {
                showRewardedAd();
              }
            },
            onAdFailedToLoad: (LoadAdError error) async {
              adState.rewardedAd = null;
              _numRewardedLoadAttempts += 1;
              if (_numRewardedLoadAttempts <= maxFailedLoadAttempts) {
                await createRewardedAd();
              }
            },
          ),
        );
      }
    
      Future<void> showRewardedAd() async {
        if (adState.rewardedAd == null) {
          return await createRewardedAd(true);
        }
    
        adState.rewardedAd!.fullScreenContentCallback =
            await FullScreenContentCallback(
          onAdShowedFullScreenContent: (RewardedAd ad) => {},
          onAdDismissedFullScreenContent: (RewardedAd ad) async {
            ad.dispose();
            await createRewardedAd();
          },
          onAdFailedToShowFullScreenContent: (RewardedAd ad, AdError error) async {
            ad.dispose();
            await createRewardedAd();
          },
        );
      }

So every time we close the rewardAd we create/load it again to have it prepared for next time. Until here everything is fine.

----------

The problem comes when we click to show it again too fast.
When we do:

    if (adState.rewardedAd == null) {
          return await createRewardedAd(true);
        }
I'm forcing it to be loaded and I wait for `await RewardedAd.load()` BUT despite I wait for that, the `onAdLoaded` event takes some time and the async function doesn't know it's not ready yet.

So, when I do `await adState.rewardedAd!` it can be null.

How could I make this more secure? Google's documentation is not covering this

**Comment by erperejildo** [comment]
> HI @erperejildo, Thanks for filing the issue. If I understand correctly you want to show the rewarded ad when it's available but there's no way to know at the moment if the rewarded ad is available to show is that correct?

Correct

**Comment by maheshmnj** [comment]
Thanks for the confirmation, Not sure if the plugin can capture a callback when the ad is available, Labeling this issue as a proposal.

**Comment by erperejildo** [comment]
> Thanks for the confirmation, Not sure if the plugin can capture a callback when the ad is available, Labeling this issue as a proposal.

maybe it could be more a global Flutter question, I don't know, but it's only here where it creates a real issue since it will reduce the number of ads and with that, my earnings

**Comment by diepnle63** [comment]
I need this feature too :) 
Wish you guys spend more time on this plugin because it's very important for us, if admob doesn't work perfectly and fully features like native lib, a lot dev will move back to native code for sure, lol

**Comment by tjerkw** [comment]
This is not a question for this library, but a more generic question of how to deal with asyncs and callbacks.

The solution is just to just keep state of wether the ad has loaded. If the ad has not yet loaded show a message or spinner to the user. 

You can use a StatefulWidget for keeping the state.
