### ISSUE TITLE
Match Rate sharply dropped with Flutter 2.8.0 and Google Ads 1.0.0

### ISSUE THREAD

**Issue by mikron123** [googleads/googleads-mobile-flutter#468]
The AdMob ads stopped functioning right since the app grade, specifically for the new app version using Flutter 2.8.0 + 1.0.0 (Ads package) 
The Match Rate is around 1% ! comparing to the previous 99%!
Still running tests, but it looks like the "flutter upgrade" was the major change I did.

**Comment by maheshmnj** [comment]
Hi @mikron123, Thanks for filing the issue. I am not sure how is the flutter upgrade related to the ads match rate.
Please see why ads match rate might be low https://support.google.com/admob/answer/9655701?hl=en

**Comment by mikron123** [comment]
It seems like it was a coincidence, and not the actual problem.
