### ISSUE TITLE
[Interstitial ad] Callback when  interstitial ads are clicked

### ISSUE THREAD

**Issue by diepnle63** [googleads/googleads-mobile-flutter#469]
Anyone here can help me? 

I need to handle ads click on interstitial popup ads but it seems flutter version of google ads doesn't support. 
It's really important for us, please help!

**Comment by maheshmnj** [comment]
Hi @diepnle63, Thanks for filing the issue. If I understand correctly you are looking for a callback when the interstitial ads are clicked is that correct?

**Comment by diepnle63** [comment]
Yes @maheshmnj , do you have solution?

**Comment by maheshmnj** [comment]
@diepnle63 The plugin currently doesn't support callbacks for interstitial ad clicked. Considering this as a feature request.

**Comment by diepnle63** [comment]
@maheshmnj  Do you have ETA to release this feature?

**Comment by maheshmnj** [comment]
Hi @diepnle63, Unfortunately, we cannot provide any eta on any of the issues. Please Keep an eye on this issue for further updates.

**Comment by maheshmnj** [comment]
@diepnle63, Unfortunately, I don't know how to fix this, else I would have submitted a PR.

**Comment by diepnle63** [comment]
Thank you for your response @maheshmnj . Do you know anyone here can help?
I see we have no update/release for 45 days  for this package. It's very important for us and may be a lot because a lot apps that is generating money only from ads like us.

Thank you.

**Comment by diepnle63** [comment]
Thank you so much! It's working perfectly for me without any issue.

**Comment by maheshmnj** [comment]
Closing as fixed.
