### ISSUE TITLE
Is google_mobile_ads possible for Native Ads ??

### ISSUE THREAD

**Issue by dishant-chudasama** [googleads/googleads-mobile-flutter#470]
i just want to know about is google_mobile_ads is supports native ads?

because i want to need implement native ads on app but just because of google_mobile_ads can't support it i need to use a other package please anyone can help me to with this package ? 

so please kindly inform me on my email [vishaltesting02@gmail.com](mailto:vishaltesting02@gmail.com)

**Comment by maheshmnj** [comment]
Hi @dishant-chudasama,  `google_mobile_ads` does support native ads please check the admob documentation for native ads: https://developers.google.com/admob/flutter/native
Closing as this issue doesn't seem to describe a bug or a feature request.

Thank you.

**Comment by vgkgopalsaroja** [comment]
@maheshmnj 
I checked above like but that link have only java code, We need kotlin code

**Comment by vgkgopalsaroja** [comment]
Hi @dishant-chudasama 

sample code available here https://github.com/googlecodelabs/admob-inline-ads-in-flutter
