### ISSUE TITLE
Banner ads are still getting impressions when app in background

### ISSUE THREAD

**Issue by elkhalifte** [googleads/googleads-mobile-flutter#472]
Banner ads are still getting impressions even if the app is in background mode.
This issue will lead to admob limit (invalid traffic).
I think you should resolve this by adding a lifecycle and then put banner ads in pause when the app is in background.

+ [See how](https://developers.google.com/android/reference/com/google/android/gms/ads/AdView)

**Comment by maheshmnj** [comment]
Hi @elkhalifte, Thanks for filing the issue. Can you please share your output of `flutter doctor -v` and the version of the plugin you are having issues with, And steps to reproduce the issue? 

Thanks

**Comment by elkhalifte** [comment]
@maheshmnj 
`[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.19043.1348], locale fr-MA)
    • Flutter version 2.5.3 at E:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\ASUS\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • SM J530F (mobile) • 5200e3925b58258f • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!`

**Comment by elkhalifte** [comment]
@maheshmnj 

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.19043.1348], locale fr-MA)
    • Flutter version 2.5.3 at E:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\ASUS\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • SM J530F (mobile) • 5200e3925b58258f • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!
```

**Comment by allasca** [comment]
@elkhalifte is that really the reason for getting ad limited? 
wow, this is the big problem. I already deleted all ad unit of my app to get rid off it. if the banner causing it, we can't used it for the moment then.

**Comment by elkhalifte** [comment]
@allasca , yes this banner will cause admob limit (invalid traffic).

**Comment by elkhalifte** [comment]
@maheshmnj i think i have provided enough **feedback** !

**Comment by maheshmnj** [comment]
Did you accidentally closed it?

**Comment by allasca** [comment]
after delete all my ad unit, limit disappears, and I added intertitial only, no banner. at the moment seem/I hope not getting limit again. fyi my app daily active users (DAU) is around 150 users moreless.

**Comment by elkhalifte** [comment]
@maheshmnj no , i was doing a bad impementation. now working fine.

**Comment by maheshmnj** [comment]
You may share what actually was wrong so that your response may help others who are facing similar issues. I have seen someone reporting a similar issue in other issue comments.

**Comment by elkhalifte** [comment]
It wasn't an issue with this plugin, i was using 2 different admob plugins this one and another,  somehow i find that i was using the banner fron the other plugin.
