### ISSUE TITLE
THIS PACKAGE IS CERTAINLY DEAD

### ISSUE THREAD

**Issue by rocketman7** [googleads/googleads-mobile-flutter#475]
Package developers never care about this package.
You guys have to see this issue thread: https://github.com/googleads/googleads-mobile-flutter/issues/269
Never had ANY FEEDBACK on this YEAR-LONG THREAD.

No one cares and wants to fix this problem. 
If anyone wants to implement Admob in your flutter project, better use "native_admob_flutter".

With this package, Native Ad or Banner Ad will make your app's performance drastically low. 
And do you team really think the way to implement Native Ads using this package is appropriate?
Please see "native_admob_flutter" and learn how it implements Native Ads in FLUTTER WAY.
If we have to do all these complex iOS and Android languages to implement "Flutter package", why the heck should we use flutter? Just go native and throw flutter away.

This package is no longer "Official". Flutter team emphasized Google Ads Mobile Flutter on their new version announce, and it's just comedy. Really wonder any of the team have used or implemented to actually show Admob in their flutter app.

**Comment by CripyIce** [comment]
I totally agree with you.
It's sad to see no team interference especially with this package since almost every app on the stores shows ads and it's an income for most developers out there.
It seems like it's an issue related to Flutter itself rather then this package, but I still expect them to team up and solve this issue.

**Comment by rocketman7** [comment]
> I totally agree with you. It's sad to see no team interference especially with this package since almost every app on the stores shows ads and it's an income for most developers out there. It seems like it's an issue related to Flutter itself rather then this package, but I still expect them to team up and solve this issue.

Yeah, I really want to know who to report this issue since no one related to this package cares. Who the hell is in charge??

**Comment by maheshmnj** [comment]
Hi @rocketman7, sorry to hear about your experience. You will hear it from the Engineering team on the issue when they really have an update to share. Feel free to add your insights or file an issue if you encounter any bugs. Closing as this issue doesn't seem to describe a bug or a feature request in the ads plugin.

**Comment by rocketman7** [comment]
> Hi @rocketman7, sorry to hear about your experience. You will hear it from the Engineering team on the issue when they really have an update to share. Feel free to add your insights or file an issue if you encounter any bugs. Closing as this issue doesn't seem to describe a bug or a feature request in the ads plugin.

@maheshmnj See the thread https://github.com/googleads/googleads-mobile-flutter/issues/475#:~:text=this%20issue%20thread%3A-,%23269,-Never%20had%20ANY and tell us what you think, i mean anything! Do you think the whole thread writers are joking or deserve to wait for one year for this bloody stupid issue?? Who the hell is in charge? Who is the owner of this package project, not damn irresponsible collaborators?? 
It's a Google Admob package, man. Not a bloody animating icons package, but the one of the most important money making way for developers!
Really want to know what you think. I mean your honest opinion.

**Comment by rocketman7** [comment]
> Hi @rocketman7, sorry to hear about your experience. You will hear it from the Engineering team on the issue when they really have an update to share. Feel free to add your insights or file an issue if you encounter any bugs. Closing as this issue doesn't seem to describe a bug or a feature request in the ads plugin.

Are you really telling us we have to wait for the "Enginerering team" to have something to share although the original issue has been raised almost A YEAR AGO?? Do you really think so???
