### ISSUE TITLE
For those who are so irresponsible that never fix one issue for a year

### ISSUE THREAD

**Issue by rocketman7** [googleads/googleads-mobile-flutter#476]
https://github.com/googleads/googleads-mobile-flutter/issues/269

So we all get to know that your team never intend to fix this issue. Do you see how many users in that thread feel disgusting of your team's attitude? So you have any excuse for that? Your so called 'Engineering team' has been working on that for ONE YEAR huh? And too busy to respond. What a team! Did you really read that at least one of the all threads in that link??? What do you think about it?? Do you have even a thought?

**Comment by rocketman7** [comment]
So you guys wanna keep deleting and closing this new issue. Well im gonna keep uploading new issues so that new users get to know how much your team is irresponsible.

**Comment by davidgalarza** [comment]
I agree with you @ rocketman7, I can't understand how the "Engineering team" haven't pronounce yet about that. I loved Flutter but this package is making me regret about decided to use it to develop my app.

**Comment by maheshmnj** [comment]
Hi @rocketman7, Please don't file duplicate issues, Filing duplicate issues wouldn't make any difference. Please kindly follow up on the original issue.
Closing as this is neither a bug nor a feature request related to ads plugin.

**Comment by rocketman7** [comment]
@maheshmnj 
Oh, you're so fast for this kind of issue but not for a year-long issue, huh? Why don't you more care about the original issue, #269 ? Are you too busy to answer the real question but so tiny one?
