### ISSUE TITLE
Can i add Facebook add plus unity or anyother add group but not admob

### ISSUE THREAD

**Issue by ZiaUrRahmam** [googleads/googleads-mobile-flutter#478]
Hey can i use this package to ahow ads with bidding from Facebook and unity
Or Facebook and applovin
Or Facebook and startup etc
But i don't want to use Google admob as bidding group. 
Is this possible with this package.

**Comment by maheshmnj** [comment]
Hi @ZiaUrRahmam, Thanks for filing the issue. Are you referring to facebook mediation?

> to ahow ads with bidding from Facebook and unity
Or Facebook and applovin

Can you please share a resource or link about these?

**Comment by ZiaUrRahmam** [comment]
@maheshmnj yes m referring Facebook meditation
But without using admob as a partner.
I want to use other meditaion groups with Facebook like startup, unity, applovin and iron source etc.
Is this possible with this package?

**Comment by maheshmnj** [comment]
Thanks for the clarification yes you can use it. Please see the set of available partner networks https://developers.google.com/admob/android/choose-networks and the doc also covers integrating with each partner.

Hope this answers your question

**Comment by maheshmnj** [comment]
Closing as this is neither a bug nor a feature request.
