### ISSUE TITLE
[📚] No longer need to pass Ad APP ID when initializing the Mobile Ads SDK

### ISSUE THREAD

**Issue by RyanRamchandar** [googleads/googleads-mobile-flutter#48]
README.md states that we need to pass the `AD_APP_ID` when initializing the Mobile Ads SDK. However, these are now taken automatically. This appears to be leftovers from `firebase_admob` instructions.

See:
https://github.com/googleads/googleads-mobile-flutter/blame/master/README.md#L48
https://github.com/googleads/googleads-mobile-flutter/blame/master/README.md#L75

**Comment by kishanhitk** [comment]
Please assign it to me.

**Comment by jjliu15** [comment]
This is still a required step. Your app will not be able to load ads if you do not do this.
-https://developers.google.com/admob/ios/quick-start#update_your_infoplist
-https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml
