### ISSUE TITLE
[Android] No ad config

### ISSUE THREAD

**Issue by luciano-cervantes** [googleads/googleads-mobile-flutter#482]
Hi, I'm getting this error. code 3, In the ad config in my app, it is already in google play it went through all the google verification steps and it has already been added and verified the app-ads.txt file. I believe it is a package error.

**Comment by maheshmnj** [comment]
Hi @luciano-cervantes, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/59, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
