### ISSUE TITLE
Adcolony mediation not working

### ISSUE THREAD

**Issue by gametathya** [googleads/googleads-mobile-flutter#484]
## Plugin Version
      google_mobile_ads: 0.13.4
 
     implementation 'com.adcolony:sdk:4.6.3'
     implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
     implementation 'com.google.ads.mediation:adcolony:4.6.0.0'

## Steps to Reproduce

add all above dependencies and init the app with moblie ads 

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
Adcolony ads working 
**Actual results:** 
W/AdColonyMediationAdapter( 9559): Unexpected SDK version format: . Returning 0.0.0 for SDK version.
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @gametathya, Thanks for filing the issue. You are using an older version of ads plugin could you please try upgrading to the latest plugin `google_mobile_ads: ^1.0.1` and see if the issue persists?

Thank you.

**Comment by maheshmnj** [comment]
Hi @gametathya, Thanks for filing the issue. You are using an older version of ads plugin could you please try upgrading to the latest plugin `google_mobile_ads: ^1.0.1` and see if the issue persists?

Thank you.

**Comment by gametathya** [comment]
W/AdColonyMediationAdapter(23265): Unexpected SDK version format: . Returning 0.0.0 for SDK version.
Still same issue 

implementation 'com.adcolony:sdk:4.6.3'
     //implementation 'com.google.android.gms:play-services-ads-identifier:15.0.0'
     implementation 'com.google.ads.mediation:adcolony:4.6.0.0'
     implementation 'com.google.ads.mediation:tapjoy:12.8.1.0'


 also tapjoy have conflict with this plugin
 com.tapjoy:tapjoy-android-sdk:12.8.1 -> com.google.android.gms:play-services-ads-identifier@[15.0.0,
   17.0.0], but play-services-ads-identifier version was 17.0.0.
  -- Project 'app' depends on project 'google_mobile_ads' which depends onto com.google.android.gms:play-services-ads@20.4
  .0


updated plugin version:
 google_mobile_ads: ^1.0.1

**Comment by maheshmnj** [comment]
Thanks for the info @gametathya, Could you please share the steps to reproduce the issue?

**Comment by gametathya** [comment]
to reproduce just add these dependencies

implementation 'com.adcolony:sdk:4.6.3'
     implementation 'com.google.ads.mediation:adcolony:4.6.0.0'

and call 
  MobileAds.instance
            .updateRequestConfiguration(RequestConfiguration(
                tagForChildDirectedTreatment:
                    TagForChildDirectedTreatment.unspecified))
            .then((value) {});
      });
before 

 runApp(MyApp());

**Comment by maheshmnj** [comment]
@gametathya I am hitting a missing plugin exception (expected) and not any dependency conflict error based on your reproducible steps. Would it be possible for you to share a minimal reproducible project? 

```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:6A745C96-D83E-5C8D-8EE9-5958E598001B }
{ platform:macOS, name:Any Mac }
Connecting to VM Service at ws://127.0.0.1:55886/wZRSSua8fAU=/ws
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
<asynchronous suspension>
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
<asynchronous suspension>
#1      AdInstanceManager.initialize
<asynchronous suspension>
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#updateRequestConfiguration on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
<asynchronous suspension>
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method loadBannerAd on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
<asynchronous suspension>
#1      BannerAd.load
<asynchronous suspension>

```

**Comment by gametathya** [comment]
Hi @maheshmnj in your output look at the your logs

W/AdColonyMediationAdapter( 9795): Unexpected SDK version format: . Returning 0.0.0 for SDK version.


this is main problem you have already reproduced the issue.
As per my opinion plugin is calling adcolony adapter before it being initialized

**Comment by maheshmnj** [comment]
@gametathya, Ah I see thanks, This is reproducible

> W/AdColonyMediationAdapter( 9795): Unexpected SDK version format: . Returning 0.0.0 for SDK version.

**Comment by gametathya** [comment]
Hi @maheshmnj our revenue is suffering from this. Can you please provide us any timeframe for this update .

**Comment by maheshmnj** [comment]
@gametathya unfortunately we cannot provide you with any eta on any of the issues.

**Comment by chaudharydeepanshu** [comment]
Facing this same issue.
```
I/flutter ( 7076): Adapter status for com.google.android.gms.ads.MobileAds: 
I/flutter ( 7076): Adapter status for com.google.ads.mediation.facebook.FacebookMediationAdapter: 
I/Ads     ( 7076): This request is sent from a test device.
W/AdColonyMediationAdapter( 7076): Unexpected SDK version format: . Returning 0.0.0 for SDK version.
W/AdColonyMediationAdapter( 7076): Unexpected SDK version format: . Returning 0.0.0 for SDK version.
```
Previously, simlilar [issue](https://github.com/googleads/googleads-mobile-android-mediation/issues/273) (closed) was found when using **googleads-mobile-android-mediation**. They found it was due to this reason:

> We found a Google Mobile Ads SDK bug where it's calling getSDKVersion() prior to initializing the AdColony adapter. This will be fixed in a future Google Mobile Ads SDK release, but in the meantime this will just be a benign warning log.

**Comment by gametathya** [comment]
hi @maheshmnj  any updates on this bug

**Comment by maheshmnj** [comment]
@gametathya no updates so far. If there are any future updates you will see them here on this issue thread and also get notified via email.

**Comment by Tetracyl** [comment]
I am also experiencing the same issue

**Comment by jjliu15** [comment]
The warning message happens because the SDK is trying to get the adapter version before the AdColony SDK is configured: [code ptr](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java#L162). 

The fix needs to be made in the SDK as opposed to the plugin. However this warning is benign and can be ignored in the meantime. The AdColony mediation adapter configures the AdColony SDK when requesting an ad, and I confirmed I'm still able to load test ads from AdColony.

**Comment by gametathya** [comment]
Hello Sir we know you replied and ignored this threat on another same issue so please dont close it just by saying that it will work fine because it willl not as test ads load only first time after that even first time it is not loading on native android adcolony adapters are working fine only on your plugin it is not working please review it and resolve because companies are depending on your work

**Comment by jjliu15** [comment]
Could you share the full logs? And also the ad load error if there is one?

In my build.gradle I just included 
```
implementation 'com.google.ads.mediation:adcolony:4.7.0.0'
```

**Comment by ouroeight** [comment]
I encounter similar error, I'm using:
google_mobile_ads: ^1.2.0

and in dependencies I'm using:
implementation 'com.google.ads.mediation:adcolony:4.7.1.0'

and I got the following error:
AdColony SDK returned a failure callback
"Code": 100,
"Message": "AdColony SDK returned a failure callback."

I tried to add:
implementation 'com.google.android.gms:play-services-ads:20.6.0'
and it's not working either, same error message.

I could show test ads but cannot show real ads, which is kind of weird, any pointers?

**Comment by raymond9991** [comment]
I encounter similar error, I'm using:
google_mobile_ads: ^1.2.0

and in dependencies I'm using:
implementation 'com.google.ads.mediation:adcolony:4.7.1.0'

and I got the following error:
AdColony SDK returned a failure callback
"Code": 100,
"Message": "AdColony SDK returned a failure callback."

I tried to add:
implementation 'com.google.android.gms:play-services-ads:20.6.0'
and it's not working either, same error message.

I could show test ads but cannot show real ads, which is kind of weird, any pointers?

**Comment by jjliu15** [comment]
It looks like this error happens when AdColony fails to fill the request: 

- [AdColonyMediationAdapter.createSdkError()](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyMediationAdapter.java#L116-L118)
- [AdColonyBannerRenderer.onRequestNotFilled()](https://github.com/googleads/googleads-mobile-android-mediation/blob/3a606b6980483276ed214708f71e6bbcbbd14e45/ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/google/ads/mediation/adcolony/AdColonyBannerRenderer.java#L79)

Could you also attach the full logs? Is any additional information getting logged from AdColony?

**Comment by raymond9991** [comment]
[full log.txt](https://github.com/googleads/googleads-mobile-flutter/files/8578308/full.log.txt)
Hi! Here is the full log from my physical device.

A little background: Admob limited my ad serving amount so I was trying to add mediation, don't know if it's relevant to the problem. Thanks!

**Comment by GauravCreed** [comment]
Hi @gametathya 

I am also facing same error in android also.
I am add only AdColony mediation library in my app, found any solution ?

Thanks(_)

**Comment by jjliu15** [comment]
Hi, unfortunately I'm not sure how to help from here. Given that you can load test ads, and the logs from log.txt in https://github.com/googleads/googleads-mobile-flutter/issues/484#issuecomment-1111559435, it looks like AdColony is just no filling, but I don't see any logs from AdColony that point out the cause. I would recommend reaching out to AdColony to see if they have any pointers for debugging no-fills from them. Also double check AdColony's setup instructions: https://github.com/AdColony/AdColony-Android-SDK/wiki
