### ISSUE TITLE
Is there anybody who is in charge of this shit?

### ISSUE THREAD

**Issue by rocketman7** [googleads/googleads-mobile-flutter#486]
Hey team, or is there any human beings that can be called as a team?
You guys are completely ignoring #269 issue. It is certain that you guys have no clue or plan to solve this issue. 
If you guys dont know how to do it, then just spit it that you are not capable of this. 
Is this a really right way to ignore all angry comments and do bloody nothing on that issue? 
Really wonder is there a human being who at least feel sort of responsibility on this. Or you guys doing this only for adding a line of fancy career?

**Comment by atelog** [comment]
This package is a complete joke :) 
I don't know how it's backed by Google. I just lost a day trying this, everything is horrible, starting from build failure ending with horrible performance issues, my nice app became an unusable piece of lagging software, even more, saw that there are open issues related to initialization failure, being an async method it made thousands of sessions to fail in production. I  will not risk that with my app. This package shall be reported or flagged somewhere IDK, it's not usable. 

P.S. Switched to `admob_flutter` seems to work ok. If Google is not ready to deliver ads on their own flutter platform, I'm gonna use Facebook ads or another provider. Shame on you, Google.

**Comment by maheshmnj** [comment]
Please follow up on the original issue.
Closing as this issue doesn't seem to describe a bug or a feature request.
