### ISSUE TITLE
getting :app:compileDebugJavaWithJavac on adding google_mobile_ads package to my project.

### ISSUE THREAD

**Issue by imyogisingh** [googleads/googleads-mobile-flutter#494]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :google_mobile_ads.
     Required by:
         project :app
      > No matching configuration of project :google_mobile_ads was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 41s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by maheshmnj** [comment]
HI @imyogisingh, Thanks for filing the issue. Please share the output of `flutter doctor -v` the version of ads plugin that you are using and the complete output of `flutter run -v`.

Thanks

**Comment by imyogisingh** [comment]
google_mobile_ads: ^1.0.1

**flutter doctor -v output**

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Android
    • Platform android-31, build-tools 30.0.0
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Java\jdk1.8.0_261\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.62

! Doctor found issues in 1 category.


**flutter run -v**

[ +167 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +189 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[   +1 ms] executing: [C:\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[ +146 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[   +1 ms] 2.8.1
[  +26 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +94 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +96 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +279 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +135 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +276 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +162 ms] executing: C:\Android\platform-tools\adb.exe devices -l
[ +183 ms] List of devices attached
[  +11 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +207 ms] No supported devices connected.
[ +113 ms] The following devices were found, but are not supported by this project:
                    Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
                    Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.62
                    If you would like your app to run on web, consider running `flutter create .` to generate projects for these platforms.

[  +26 ms] "flutter run" took 813ms.
[  +38 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:465:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1248:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +270 ms] ensureAnalyticsSent: 254ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by maheshmnj** [comment]
Thanks for the info @imyogisingh  I don't see the original error that you posted in `flutter run -v`. Can you please do 
`flutter clean` and reshare the complete output of `flutter run -v` as well as `flutter build apk -v` in a text file?

**Comment by imyogisingh** [comment]
hello sir @maheshmnj . i am getting this error only on production apps ! when i use the package on a non - release project it worked for me but if a app is released mode and available on playstore it gives me the error.
i have attached the file below you asked for.

[flutter run -v.txt](https://github.com/googleads/googleads-mobile-flutter/files/7938762/flutter.run.-v.txt)

[flutter build apk -v.txt](https://github.com/googleads/googleads-mobile-flutter/files/7938759/flutter.build.apk.-v.txt)

**Comment by maheshmnj** [comment]
>  i am getting this error only on production apps 

Thanks for the info, labeling this issue for further investigation.

**Comment by imyogisingh** [comment]
flutter clean and upgrade resolved my issue. tq
