### ISSUE TITLE
Exception when showing interstitial ads

### ISSUE THREAD

**Issue by diepnle63** [googleads/googleads-mobile-flutter#501]
Hi,

I'm using v^1.0.1, it often throw exception when showing  interstitial ads. Could you please double check? (android 7.1)

I/flutter (14143): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
I/flutter (14143): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (14143): #2      AdInstanceManager.showAdWithoutView (package:google_mobile_ads/src/ad_instance_manager.dart:602:7)
I/flutter (14143): #3      InterstitialAd.show (package:google_mobile_ads/src/ad_containers.dart:1099:28)

around <10% success, in most case it doesn't work, ads not showing :(

**Comment by maheshmnj** [comment]
Hi @diepnle63, Thanks for filing the issue. Could you please the output of `flutter doctor -v`? And is this issue only on Android 7 or other Android versions too?
 
Thanks

**Comment by diepnle63** [comment]
I have just tried again on android 8, it's the same issue and the same exception.
I'm using this test ads: 
ca-app-pub-3940256099942544/8691691433

flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.8.1 at C:\flutter_windows_2.2.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • MI PAD 4 (mobile) • 192.168.1.3:5555 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Thanks for the info please share the complete output of `flutter run -v`

**Comment by angelbuzon** [comment]
google_mobile_ads: ^1.0.1 or  google_mobile_ads: ^1.1.0, Interstitial fails on my samsung S6 and other devices with SDK 21 or 23.

It works for my:

dependencies {
   .....
        classpath 'com.android.tools.build:gradle:4.2.2'
   .....
}
