### ISSUE TITLE
Screen acting crazy

### ISSUE THREAD

**Issue by dhiaEddineB** [googleads/googleads-mobile-flutter#510]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
Screen scrolling smothly 

**Actual results:** 
Screen acting crazy when the ads is displayed  in the same list with videos when I use the latest plugin, but when I use older versions the app runs as expected .

this is an example when I use the latest version ( v1.0.1, v1.0.0, or v0.13.6)

https://user-images.githubusercontent.com/99422303/153563875-9040bb04-60d0-4387-8ba1-9a46823551c3.mp4

and this is an example when I use the forked one ["https://github.com/SuaMusica/googleads-mobile-flutter.git"](url) and the app runs as expected :

https://user-images.githubusercontent.com/99422303/153564205-64b32a04-1031-4474-aece-c1dc2cdadb14.mp4

this is an example using the latest version:

<details>
  <summary>getStreamVolume isRestricted mode = 0</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @dhiaEddineB, Thanks for filing the issue. Please share the output of `flutter doctor -v` and a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue. Also is the jank only on Android or IOS too?

Thanks

**Comment by medst** [comment]
**same issue here, tabs goes crazy with native ads.**

**make native ad in center of first TabView and another native ad in bottom of second TabView, and the navigation between screen get flickering**

i think this flickering is related to the position of native ads. when both are in center the app work without any glitch.



https://user-images.githubusercontent.com/15349483/153679930-a7728943-18d0-4779-8b8a-4d453af5e5b5.mp4

**Comment by maheshmnj** [comment]
This is being tracked in the flutter repo https://github.com/flutter/flutter/issues/96679

**Comment by medst** [comment]
logs

> I/flutter ( 2866): 1 ad loaded.
I/flutter ( 2866): 0 ad loaded.
I/mali_egl( 2866): eglDestroySurface() in
I/mali_egl( 2866): eglDestroySurface() out
I/mali_winsys( 2866): new_window_surface() [720x1480] return: 0x3000
E/BufferQueueProducer( 2866): [ImageReader-720x1480f1m3-2866-0] disconnect: not connected (req=1)
W/mali_winsys( 2866): native_window_api_disconnect failed: -19
I/mali_winsys( 2866): delete_surface() [720x1480] return
D/SensorManager( 2866): unregisterListener ::   
I/flutter ( 2866): 0
I/flutter ( 2866): ad refreshed
V/RenderScript( 2866): Successfully loaded runtime: libRSDriverArm.so
