### ISSUE TITLE
google_mobile_ads and flutter_inappwebview not working together

### ISSUE THREAD

**Issue by sagarshree** [googleads/googleads-mobile-flutter#511]
## Plugin Version

google_mobile_ads: 1.1.0
flutter_inappwebview: 5.3.2

## Steps to Reproduce

1. Add a banner ad on a page
2. When the ad loads and gets displayed, navigate from the same screen to another screen with webview
3. Then the app crashes

## Error log
`E[/flutter]() (28221): [ERROR:flutter[/fml/platform/android/jni_util.cc]()(211)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E[/flutter]() (28221): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:295)
E[/flutter]() (28221): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:3)
E[/flutter]() (28221): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E[/flutter]() (28221): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E[/flutter]() (28221): 	at android.os.Looper.loop(Looper.java:193)
E[/flutter]() (28221): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E[/flutter]() (28221): 	at java.lang.reflect.Method.invoke(Native Method)
E[/flutter]() (28221): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E[/flutter]() (28221): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
F[/flutter]() (28221): [FATAL:flutter[/shell/platform/android/platform_view_android_jni_impl.cc]()(1301)] Check failed: fml::jni::CheckException(env).`

**Expected results:** 
The webview page should have opened smoothly

**Actual results:** 
App crashes before navigating to webview page

**Comment by hukusuke1007** [comment]
It also occur with webview_flutter

```
E/EGL_emulation(17251): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation(17251): tid 17251: eglQueryContext(2019): error 0x3004 (EGL_BAD_ATTRIBUTE)
E/Surface (17251): getSlotFromBufferLocked: unknown buffer: 0x9e6d4f90
E/ing.developmen(17251): [SurfaceTexture-0-17251-0] attachToContext: SurfaceTexture is already attached to a context
E/flutter (17251): [ERROR:flutter/fml/platform/android/jni_util.cc(211)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter (17251): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:295)
E/flutter (17251): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:57)
E/flutter (17251): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (17251): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (17251): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (17251): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (17251): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17251): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (17251): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (17251): 
F/flutter (17251): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1301)] Check failed: fml::jni::CheckException(env). 
F/crashpad(17586): dlopen: dlopen failed: library "libandroidicu.so" not found: needed by /system/lib/libharfbuzz_ng.so in namespace (default)
F/libc    (17251): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 17251 (ing.development), pid 17251 (ing.development)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
```

**Comment by maheshmnj** [comment]
Hi @sagarshree, Thanks for filing the issue. This is a known issue in `webview_flutter` and is being tracked here https://github.com/flutter/flutter/issues/98155. Please follow up there for further updates. 

Closing, as this issue isn't related to the ads plugin. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by banderberg** [comment]
I think this may be related to google mobile ads.  I will be opening another issue with a link to my demo @maheshmnj

**Comment by BriceFab** [comment]
Hi @maheshj01

This issue appears to be related to https://github.com/pichillilorenzo/flutter_inappwebview/issues/1699 . The method MobileAds.instance.registerWebView(controller) is specifically designed to work with webview_flutter and currently has no implementation for flutter_inappwebview. Since flutter_inappwebview is a different library, the registration process won't work in the same way.

cc @sagarshree
