### ISSUE TITLE
Update android GMA SDK dependency to 20.5.0+

### ISSUE THREAD

**Issue by untp** [googleads/googleads-mobile-flutter#517]
Version 20.5.0 released on 2021‑11‑18 which includes:

* Added support for Android 12 devices for apps targeting API 31.
* Added support for [app set ID ](https://developer.android.com/training/articles/app-set-id)for use cases such as reporting and fraud prevention.

Release Notes: https://developers.google.com/admob/android/rel-notes

**Comment by sukaper** [comment]
We are very concerned with this and we would highly appreciate if we can get an update on this.
Supporting Android 12 at its fullest capacity is a high priority in our team and we would like to see this issue resolved as soon as possible.

**Comment by jjliu15** [comment]
Looking into this now

**Comment by sukaper** [comment]
Thank you for the fix!
When can we expect to see this change pushed on with a new version?
