### ISSUE TITLE
Set ServerSideVerificationOptions after RewardedAd has been loaded

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [googleads/googleads-mobile-flutter#520]
## Use case
When using ServerSideVerificationOptions, you want usually to load generic ads and set the custom data depending on which action is triggering the ad show.

## Proposal
Allow set serverSideVerificationOptions on rewardedAd.show() method OR using other method prior to show.

**Comment by maheshmnj** [comment]
Hi @bcbcbcbcbcl, Thanks for filing the issue. Is that something Admob supports? If so could you please share a link to the resource?

**Comment by bcbcbcbcbcl** [comment]
Hi @maheshmnj, I guess so. Please refer to this https://developers.google.com/admob/android/ssv#custom_data

**Comment by maheshmnj** [comment]
Thanks for the info labeling this issue as a feature request.

**Comment by tjerkw** [comment]
I'm not sure what @bcbcbcbcbcl  means... You can already set the "customData" field in `.RewardedAd.load`.

You need to implement a server side callback in order to get that value. 
But the flutter SDK already implemented the customData field.

**Comment by bcbcbcbcbcl** [comment]
Hi @tjerkw 
The use case I mentioned is that custom data is unknown yet when we first load the ad in the background.
The custom data only available when user performs an action (eg: view post with id of 123).

It would be great if this library provide us another method to set the ServerSideVerificationOptions.

**Comment by jjliu15** [comment]
Version 2.0.0 added [RewardedAd.ServerSideVerificationOptions](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/lib/src/ad_containers.dart#L1157-L1159) that you can use after it is loaded
