### ISSUE TITLE
Console:  D/AudioManager - getStreamVolume

### ISSUE THREAD

**Issue by gjmg2303** [googleads/googleads-mobile-flutter#521]
Hola, en mis pruebas al tener  BannerAd en un ListView, me sale continuamente en la consola el siguiente mensaje

D/AudioManager(15256): getStreamVolume packageName=com.uuuuuu.uuu, index=9, streamType=3

Mi pregunta es si esto consume mucho batería de teléfono y si no le tengo que dar importancia. O hay forma de eliminar el mensaje.

Gracias

_translated using Google translate_

Hello, in my tests when having BannerAd in a ListView, I continually get the following message in the console

D/AudioManager(15256): getStreamVolume packageName=com.uuuuuu.uuu, index=9, streamType=3

My question is if this consumes a lot of phone battery and if I don't have to give importance to it. Or is there a way to remove the message.

Thanks

**Comment by maheshmnj** [comment]
Hi @gjmg2303, Thanks for filing the issue. Please share the output of `flutter doctor -v` in a text file and is the log with a specific ad or any ads?

**Comment by gjmg2303** [comment]
Hi, thanks for your answer

flutter doctor -v: 

[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6.3 20G409 darwin-x64, locale es-UY)
    • Flutter version 2.10.2 at /Users/gastonmenezes/Documents/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/***********/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/***********//Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter



! Doctor found issues in 1 category.

Log:  
<img width="375" alt="image" src="https://user-images.githubusercontent.com/79303601/156993664-d02072e4-e3a9-4a19-8119-a2dc7443808f.png">


Declaration: 

late BannerAd _ad;
Map<String, BannerAd> ads = <String, BannerAd>{};

I want to display advertising in a list:

ads['myBanner$index'] = BannerAd(
                  adUnitId: AdHelper.bannerAdUnitId,
                  size: AdSize.banner,
                  request: AdRequest(),
                  listener: BannerAdListener(
                      onAdClosed: (Ad ad){
                        print("Ad Closed");
                      },

                      onAdFailedToLoad: (Ad ad,LoadAdError error){
                        ad.dispose();
                      },

                      onAdLoaded: (Ad ad){
                        print('Ad Loaded');
                      },

                      onAdOpened: (Ad ad) async {
                        AdManagerBannerAd bannerAd = (ad as AdManagerBannerAd);
                        final AdSize? size = await bannerAd.getPlatformAdSize();
                        if (size == null) {
                          print('Error: getPlatformAdSize() returned null for $bannerAd');
                          return;
                        }
                      }
                  )
                );
                ads['myBanner$index']!..load();

I show advertising:

return Column(
                    children: [

                      Container(
                        child: AdWidget(ad: ads['myBanner$index']!,
                        key: UniqueKey(),),
                        height: 70.0,
                      ),
]
)

Thank you very much in advance for your help.
Gastón

**Comment by maheshmnj** [comment]
Thanks for the info @gjmg2303, could you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)? I tried the below code and I was unable to reproduce those logs. I verified this on the latest stable channel `2.10.3` with  `google_mobile_ads: ^1.1.0`.


<details>
<summary>code sample</summary>

```dart
import 'dart:io';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(
        title: 'Hello',
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    createBannerAd();
  }

  static String get bannerAdUnitId => Platform.isAndroid
      ? 'ca-app-pub-3940256099942544/6300978111'
      : 'ca-app-pub-3940256099942544/2934735716';

  void createBannerAd() {
    _bannerAd = BannerAd(
        adUnitId: bannerAdUnitId,
        size: AdSize.banner,
        request: const AdRequest(),
        listener: AdManagerBannerAdListener(
          onAdFailedToLoad: (Ad ad, LoadAdError error) {
            ad.dispose();
          },
        ));

    _bannerAd.load();
  }

  late BannerAd _bannerAd;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.end,
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    SizedBox(
                      width: 300,
                      height: 50,
                      child: AdWidget(
                        ad: _bannerAd,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by gjmg2303** [comment]
Hello, thank you very much for writing to me, sorry for the delay in answering you.

I have tried with your code.

Unfortunately it keeps giving me the same output. I'm going to try with emulator and another phone

and I will notify you

D/AudioManager(10752): getStreamVolume packageName=com.example.xxxx, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.xxxx, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.xxxx, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.xxxx, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.xxxx, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3
D/AudioManager(10752): getStreamVolume packageName=com.example.base, index=0, streamType=3

**Comment by ChenJinCan** [comment]
me too
