### ISSUE TITLE
ad failed to load LoadAdError 

### ISSUE THREAD

**Issue by ashokavarthanan** [googleads/googleads-mobile-flutter#529]
Hi.
The Error:
`ad failed to load LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))`

I tried searching but not solved.
Test with **debug mode** and  **release mode**
Using Test Ads.
Manifest file added `APPLICATION_ID`
Code: main.dart

	import 'package:flutter/material.dart';
	import 'package:google_mobile_ads/google_mobile_ads.dart';

	AppOpenAd? openAd;

	Future<void> loadAd() async {
	  await AppOpenAd.load(
		  adUnitId: 'ca-app-pub-3940256099942544/3419835294',
		  request: const AdRequest(),
		  adLoadCallback: AppOpenAdLoadCallback(onAdLoaded: (ad) {
			print('ad is loaded');
			openAd = ad;
			// openAd!.show();
		  }, onAdFailedToLoad: (error) {
			print('ad failed to load $error');
		  }),
		  orientation: AppOpenAd.orientationPortrait);
	}

	void showAd() {
	  if (openAd == null) {
		print('trying tto show before loading');
		loadAd();
		return;
	  }

	  openAd!.fullScreenContentCallback =
		  FullScreenContentCallback(onAdShowedFullScreenContent: (ad) {
		print('onAdShowedFullScreenContent');
	  }, onAdFailedToShowFullScreenContent: (ad, error) {
		ad.dispose();
		print('failed to load $error');
		openAd = null;
		loadAd();
	  }, onAdDismissedFullScreenContent: (ad) {
		ad.dispose();
		print('dismissed');
		openAd = null;
		loadAd();
	  });

	  openAd!.show();
	}

	void main() async {
	  List<String> testDeviceIds = ['added_device_id'];
	  WidgetsFlutterBinding.ensureInitialized();

	  await MobileAds.instance.initialize();
	  RequestConfiguration configuration =
		  RequestConfiguration(testDeviceIds: testDeviceIds);
	  MobileAds.instance.updateRequestConfiguration(configuration);
	  await loadAd();
	  runApp(const MyApp());
	}

	class MyApp extends StatelessWidget {
	  const MyApp({Key? key}) : super(key: key);

	  @override
	  Widget build(BuildContext context) {
		return MaterialApp(
		  title: 'Flutter Demo',
		  theme: ThemeData(
			primarySwatch: Colors.blue,
		  ),
		  home: const MyHomePage(title: 'Flutter Demo Home Page'),
		);
	  }
	}

	class MyHomePage extends StatefulWidget {
	  const MyHomePage({Key? key, required this.title}) : super(key: key);

	  final String title;

	  @override
	  State<MyHomePage> createState() => _MyHomePageState();
	}

	class _MyHomePageState extends State<MyHomePage> {
	  int _counter = 0;

	  void _incrementCounter() {
		setState(() {
		  _counter++;
		});
	  }

	  @override
	  Widget build(BuildContext context) {
		return Scaffold(
		  appBar: AppBar(
			title: Text(widget.title),
		  ),
		  body: Center(
			child: Column(
			  mainAxisAlignment: MainAxisAlignment.center,
			  children: <Widget>[
				const Text(
				  'You have pushed the button this many times:',
				),
				Text(
				  '$_counter',
				  style: Theme.of(context).textTheme.headline4,
				),
			  ],
			),
		  ),
		  floatingActionButton: FloatingActionButton(
			onPressed: () {
			  _incrementCounter();
			  showAd();
			},
			tooltip: 'Increment',
			child: const Icon(Icons.add),
		  ),
		);
	  }
	}

**Comment by ashokavarthanan** [comment]
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\ANDROID_SDK_HOME\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\ANDROID_SDK_HOME\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

**Comment by maheshmnj** [comment]
Hi @ashokavarthanan,

There is a similar issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/59, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
