### ISSUE TITLE
 [iOS] Draw flicker occurs in banner ads

### ISSUE THREAD

**Issue by sawaikatyou** [googleads/googleads-mobile-flutter#531]
-------------------------------------------------------------------

The flickering of the drawing remains.
Is there anything I can do to resolve this issue?

## Plugin Version
1.1.0

## Steps to Reproduce

1. run this code.

```dart
import 'package:flutter/material.dart';   
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(const MaterialApp(home: AdBannerExample()));
}

/// Banner advertisement example of listview
class AdBannerExample extends StatefulWidget {
  const AdBannerExample({Key? key}) : super(key: key);

  @override
  _AdBannerExampleState createState() => _AdBannerExampleState();
}

class _AdBannerExampleState extends State<AdBannerExample> {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _reloadAd();
  }

  @override
  void dispose() {
    _ad?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Ad Banner Example')),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            child: ListView.separated(
              itemCount: 30,
              separatorBuilder: (_, __) => Container(height: 40),
              itemBuilder: (BuildContext context, int index) {
                final ad = _ad;
                if (index == 10 && _loaded && ad != null) {
                  return SizedBox(
                      height: ad.sizes[0].height.toDouble(),
                      width: ad.sizes[0].width.toDouble(),
                      child: AdWidget(ad: _ad!));
                }
                return Text('Item. No.$index');
              },
            ),
          ),
        ),
      ),
    );
  }

  void _reloadAd() {
    _ad ??= AdManagerBannerAd(
      adUnitId: '/6499/example/banner',
      request: const AdManagerAdRequest(),
      sizes: <AdSize>[AdSize.banner],
      listener: AdManagerBannerAdListener(
        onAdLoaded: (Ad ad) {
          setState(() {
            _loaded = true;
          });
        },
      ),
    )..load();
  }

  /// banner widget instance
  AdManagerBannerAd? _ad;

  /// loaded flag. true is loaded.
  bool _loaded = false;
}
```

3. touch ad banner area.

4. Go back to my application

**Expected results:** 

 The drawing flicker disappears

**Actual results:** 

 The Drawing flicker remains

 - not occur iOS Simulator and iphone 13. (occured iPhone11 and iPhone8plus)
 - The probability of this bug occurring is low. (3/10)

https://user-images.githubusercontent.com/11250845/158104503-407e3625-2565-4e5c-ad49-17e7398ff2e7.mov

after 7sec.

screen shot.
![screen](https://user-images.githubusercontent.com/11250845/158111118-7c2bd890-e70f-4741-8a6e-6f8ddaf56445.png)

$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-x64, locale
    ja-JP)
    • Flutter version 2.10.3 at /Users/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /User/developer/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1, localhost, ::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (1 available)
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
```

**Comment by sawaikatyou** [comment]
This issue has never occurred in the iOS simulator.
It's happening on iPhone 11 devices.

**Comment by maheshmnj** [comment]
Thanks for the info @sawaikatyou, Unfortunately, we do not have that said device to verify. Labeling this issue for further investigation from the team.

**Comment by SalsabeelaHasan** [comment]
Same here.. occurred in iPhone 13, using:
- flutter 3.3.2 
- google_mobile_ads 2.0.1
