### ISSUE TITLE
Native ads

### ISSUE THREAD

**Issue by SaadNewton** [googleads/googleads-mobile-flutter#533]
Hy Sir,
I want to implement native ads in flutter but I cannot understand the logics where I can initialize native ad. I was using native_admob_flutter before. But this package is deprecated now. In the documentation of this package google_mobile_ads is suggested. 
So kindly guide me how I implement native ads in flutter app.
Thanks,
Regard: SaadNewton

**Comment by maheshmnj** [comment]
Hi @SaadNewton, Thanks for filing the issue. Please refer this [codelab](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#0) which will help you implement the native ads. You can also find the complete example app here https://github.com/googlecodelabs/admob-inline-ads-in-flutter

Closing as this is neither a bug, nor a feature request.

**Comment by SaadNewton** [comment]
I am implementing but I think it needs some integrations with native side for both IOS and Android.
