### ISSUE TITLE
New Google Play Family Policy

### ISSUE THREAD

**Issue by uugurbas** [googleads/googleads-mobile-flutter#535]
Hello;
My app aims at children and uses google ads. For the ads, I use this package and restrict the ads for children. As I know, Google has changed its policy for the apps targeting children. I searched but couldn't find what to do. Should I do something for my ads to be shown to users after the change in the policy goes into effect or since I use this official google ads package, will it automatically adapt itself to the changes?
Thank you.

**Comment by maheshmnj** [comment]
Hi @uugurbas, Thanks for filing the issue .

>  As I know, Google has changed its policy for the apps targeting children

Could you please share the resource you are referring to?

Thanks

**Comment by uugurbas** [comment]
An email I got from Google:
Last July, we announced Advertising policy changes to help bolster security and privacy. We added new restrictions on identifiers used by apps that target children. When users choose to delete their advertising ID in order to opt out of personalization advertising, developers will receive a string of zeros instead of the identifier if they attempt to access the identifier. This behavior will extend to phones, tablets, and Android TV starting April 1, 2022. We also announced that you need to declare an AD_ID permission when you update your app targeting API level to 31 (Android 12). Today, we are sharing that we will give developers more time to ease the transition. We will require this permission declaration when your apps are able to target Android 13 instead of starting with Android 12.

Action Items If you use an advertising ID, you must declare the AD_ID Permission when your app targets Android 13 or above. Apps that don’t declare the permission will get a string of zeros. Note: You’ll be able to target Android 13 later this year. If your app uses an SDK that has declared the Ad ID permission, it will acquire the permission declaration through manifest merge. If your app’s target audience includes children, you must not transmit Android Advertising ID (AAID) from children or users of unknown age.

**Comment by maheshmnj** [comment]
thanks for the update @uugurbas,

> If you use an advertising ID, you must declare the AD_ID Permission when your app targets Android 13 or above.

you can do this by adding `<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>` to manifest

Please see this https://support.google.com/googleplay/android-developer/answer/6048248?hl=en

**Comment by maheshmnj** [comment]
Thanks for pointing that @wiwimaster, As per what I can see the [current implementation](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/android/src/main/AndroidManifest.xml) of the ads SDK does not include any such permissions, so probably you will need to include it in your application.

cc: @jjliu15

**Comment by wiwimaster** [comment]
got it. I believe either solution is fine as long as the implementation and documentation are in-sync. 

For reference - if I add this setting now manually and it is added to the official package later as well, would that lead to an issue (I suppose not)?

**Comment by dpedrinha** [comment]
> got it. I believe either solution is fine as long as the implementation and documentation are in-sync.
> 
> For reference - if I add this setting now manually and it is added to the official package later as well, would that lead to an issue (I suppose not)?

It shouldn't because the Manifest merge should identify repeated declarations and use only one in the final package.

But honestly, this declaration should be added by the plugin. It's a plugin maintained by the google team, for a google project (flutter) required by a google service (google ads).

Amazing that not even themselves can keep up to date with their own updates and changes.

**Comment by GoldenSoju** [comment]
> > got it. I believe either solution is fine as long as the implementation and documentation are in-sync.
> > For reference - if I add this setting now manually and it is added to the official package later as well, would that lead to an issue (I suppose not)?
> 
> It shouldn't because the Manifest merge should identify repeated declarations and use only one in the final package.
> 
> But honestly, this declaration should be added by the plugin. It's a plugin maintained by the google team, for a google project (flutter) required by a google service (google ads).
> 
> Amazing that not even themselves can keep up to date with their own updates and changes.


I am not 100% sure here, but the flutter ```google_mobile_ads``` package (version 1.2.0) includes the ```api 'com.google.android.gms:play-services-ads:20.6.0'```-dependency in it's manifest, and this Google Mobile Ads SDK seems to already include the ```com.google.android.gms.AD_ID permission``` according to this [Source](https://groups.google.com/g/google-admob-ads-sdk/c/jFVRiTrHPW0/m/aZ_B_n4vBAAJ).

So to my understanding, this would mean that the flutter google_mobile_ads package as well as the manifest in your app do not need to specifically include this permission, as it is already included thanks to the SDK.
