### ISSUE TITLE
Release v1.2.1+ to pub.dev

### ISSUE THREAD

**Issue by untp** [googleads/googleads-mobile-flutter#537]
There are some changes in this repository that are not submitted to pub.dev. pub.dev version is currently 1.1.0, it needs to be updated with the latest changes.

**Comment by maheshmnj** [comment]
Hi @untp, We wouldn't need to track a bug for this. The ads team would release the new update with the new improvements and fixes when it is ready.

Closing as this is neither a bug nor a feature request in the ads pluginl.
