### ISSUE TITLE
AdListener not work in the newest version of google_mobile_ads - Flutter

### ISSUE THREAD

**Issue by shelltrywnd** [googleads/googleads-mobile-flutter#543]
after one day of search i found that AdListener work only with google_mobile_ads: ^0.12.0 version else give me error that the AdListener Class doesn't exist , and when i run the application in android studio with google_mobile_ads: ^0.12.0 version i get an error that i need to run flutter sound-null-safety and the application crash, so i need execute this line: flutter run --no-sound-null-safety

am on windows 10, Android Studio Dolphin | 2021.3.1 Canary 7, Flutter version: Channel stable, 2.10.4, on Microsoft Windows [version 10.0.19044.1586],

**Comment by maheshmnj** [comment]
Hi @shelltrywnd, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

**Comment by shelltrywnd** [comment]
thank you for your reply, ok i change AdListener by BannerAdListener and i get an error at those functions:
**`onAppEvent and onApplicationExit and onNativeAdClicked and onNativeAdImpression and onRewardedAdUserEarnedReward`**

this is my code:
```
import 'dart:io';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class AdState {

  AdState({
    required this.initialization
  });
  Future<InitializationStatus> initialization;

  String get bannerAdUniteId{
    if(Platform.isAndroid)
    {
      return 'ca-app-pub-6274345465194613~6499435913';
    }else{
      return 'ca-app-pub-627431256494613/7461959956';
    }
  }

  BannerAdListener get adListener => _adListener;
  BannerAdListener _adListener = BannerAdListener(

    onAdLoaded: (ad) =>print("Ad Loaded:${ad.adUnitId}."),
    onAdFailedToLoad: (ad,error) {
      print("Ad failed to load:${ad.adUnitId}.$error");
    },
    onAdOpened: (ad) => print("Ad Loaded:${ad.adUnitId}."),
    onAdClosed: (ad) => print("Ad closed:${ad.adUnitId}."),
    onAppEvent: (ad,name,data)=>
        print("Ad event:${ad.adUnitId}.$name,$data"),
    onApplicationExit: (ad) =>print("App Exit:${ad.adUnitId}."),
    onNativeAdClicked: (nativeAd)=>
        print("Native add clicked:${nativeAd.adUnitId}."),
    onNativeAdImpression:  (nativeAd)=>
        print("Native add Impression:${nativeAd.adUnitId}."),
    onRewardedAdUserEarnedReward: (ad,reward)=>
        print("Native add Impression:${ad.adUnitId}.${reward.type}"),



  );
}

```

**Comment by maheshmnj** [comment]
@shelltrywnd Looks like you are incorrectly using the api `onRewardedAdUserEarnedReward` and other parameters are not available in `BannerAd` Please refer to the complete example here https://pub.dev/packages/google_mobile_ads/example and the documentation about RewardedAd here https://developers.google.com/admob/flutter/rewarded
