### ISSUE TITLE
iOS app rejected because of "Test Mode" appearing on BannerAds (release mode)

### ISSUE THREAD

**Issue by Tom3652** [googleads/googleads-mobile-flutter#550]
## Plugin Version

```google_mobile_ads: ^1.2.0``` 

## Steps to Reproduce

1. Add a BannerAd to your project
2. Use your real AdMob unit ID 
3. See on the banner the "Test Mode" label in the middle after building in release mode

**Expected results:** 

The "Test mode" label should not appear in release mode on banner ads.

**Actual results:** 

Note that this is different from "Test ads" because test ads are working fine with the test ads unit ID.  
This happens with real ads that have this label in the middle of the banner.

Apple rejected my app because they don't allow any "Test" in production. 

Note : Google has accepted my Android version of the app and is now live on the store with the exact same code except the Ad unit ID that changes. 
I also confirm i have checked x5 times that my Ad unit ID on iOS is the one found in my AdMob account and not the test ads.

Please see the "Test mode" in the middle of the banner :

![Capture d’écran 2022-04-25 à 14 20 19](https://user-images.githubusercontent.com/32631467/165087785-f1264877-2900-475c-87b4-a37260592aea.png)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale fr-FR)
    • Flutter version 2.10.5 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @Tom3652, Thanks for filing the issue. Do you see the `testmode` when running the ios app locally in release mode or only when the app is installed from the appstore? Can you please confirm, if your app is reviewed in AdMob and the approval Status is "ready" state?

**Comment by Tom3652** [comment]
Hi @maheshmnj ! 
I see the `testmode` when running locally in release mode, my app could not get to the App Store yet because of this. 
The screen shot actually comes from the Apple verification team before going live. 
On Android i do not see this "test mode". 

My app is not under review by admob yet since it's not linked to the app store, on Android i have started the review today but it was working before that. 
I have the `Requires review` flag on my iOS app like it was the case on my Android one. 
Now on Android i have `Getting ready`.

**Comment by Tom3652** [comment]
I think i have spotted the issue, i had done the same as mentioned [here](https://stackoverflow.com/questions/70255582/flutter-google-mobile-ads-only-shows-test-ads-on-ios) 
So i have removed my test device 00000000-0000-0000-0000-000000000000 from my AdMob account and i didn't get any ads since then so i will see.

**Comment by Tom3652** [comment]
Yes i confirm that this was the issue :)
