### ISSUE TITLE
[Question] Does this plugin support the IDFA message part of the admob sdk?

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [googleads/googleads-mobile-flutter#559]
In admob privacy and messages section, you can setup the IDFA message.

Does this package support that functionality or I have to do it manually?

The admob UI tells me to only add the "NSUserTrackingUsageDescription" key to Info.plist with my custom message.

is there any other setup i need to do to get this working?

**Comment by maheshmnj** [comment]
Hi @YazeedAlKhalaf, Thanks for filing the issue. I couldn't find more info about IDFA for google mobile ads plugin, I am labeling this issue for further insights from the team. Additionally, Please see if this docs  helps answer your question https://developers.google.com/admob/ump/ios/quick-start 

cc: @jjliu15

**Comment by jjliu15** [comment]
Hi @YazeedAlKhalaf, the latest version added support for the UMP SDK, which can be used to display the IDFDA message. More information can found here: https://developers.google.com/admob/flutter/eu-consent#app_tracking_transparency_ios_only

**Comment by YazeedAlKhalaf** [comment]
thanks

**Comment by unayodev** [comment]
Hi @YazeedAlKhalaf, have you managed to display the IDFA message? Following the instructions from https://developers.google.com/admob/flutter/eu-consent#app_tracking_transparency_ios_only, it only teaches you to show the GDPR message, but the IDFA message is not shown. Is there any specific code to display this message?
