### ISSUE TITLE
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by qwopczy** [googleads/googleads-mobile-flutter#563]
Hello, when loading BannerAd ads, I encountered a crash on the Android emulator, but not on the phone.
## Plugin Version

google_mobile_ads: ^1.2.0
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
I want to see the normal bannerAd ad appear.
**Actual results:** 
Simulator crashes when loading bannerAd ads
<details>
  <summary>Logs</summary>

java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

 called with 667648 frames delivered
I/Ads     ( 2601): HTTP timeout: 60000 milliseconds.
I/flutter ( 2601): Instance of 'BannerAd' loaded: ResponseInfo(responseId: CLHKyIDQ4fcCFWmG6QUdj4QIIQ, mediationAdapterClassName: com.google.ads.mediation.admob.AdMobAdapter, adapterResponses: [AdapterResponseInfo(adapterClassName: com.google.ads.mediation.admob.AdMobAdapter, latencyMillis: 6757), description: {
I/flutter ( 2601):   "Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
I/flutter ( 2601):   "Latency": 6757,
I/flutter ( 2601):   "Credentials": {},
I/flutter ( 2601):   "Ad Error": "null"
I/flutter ( 2601): }, adUnitMapping: {}, adError: null)])
D/EGL_emulation( 2601): eglMakeCurrent: 0xf1de71b0: ver 3 0 (tinfo 0xbd8034d0) (first time)
D/AndroidRuntime( 2601): Shutting down VM
E/AndroidRuntime( 2601): FATAL EXCEPTION: main
E/AndroidRuntime( 2601): Process: com.area.flutterAnswerScanner, PID: 2601
E/AndroidRuntime( 2601): java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

flutter doctor -v                                                              
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.5 20G527 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/xx/Desktop/gitHubCode/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xx/Library/Android/sdk/
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.64

</details>

**Comment by huycozy** [comment]
Hi @qwopczy, 
I tried to run [google mobile ads sample](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads) but don't see that exception. The ads loaded normally on Android emulator (API 30)

<details>
<summary>Demo</summary>

![Screenshot_1652675513](https://user-images.githubusercontent.com/104349824/168520854-864ab080-ed60-4449-ac27-99d6e99f9edb.png)

</details>

It'll be great if you could provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.
And also please upgrade your flutter SDK to the latest version (stable 3.0.0, master 3.1.0-0.0.pre.727)
Thanks.

**Comment by qwopczy** [comment]
Thank you,
  After I upgraded flutter 3.0.1, the emulator did not crash and could load ads normally. But Flutter stable 2.10.4 did crash and reported the above error. At present, I do not plan to use flutter 3.0.1 to launch the application, and some third-party plug-ins have not been fully upgraded.

**Comment by huycozy** [comment]
Hi. Thank you for confirming. Try to open issues on third-party plugin repositories for supporting flutter 3.0. Closing the issue as fixed.
