### ISSUE TITLE
Not able to add Facebook mediation

### ISSUE THREAD

**Issue by parmarravi** [googleads/googleads-mobile-flutter#569]
FLUTTER 

`  google_mobile_ads: ^1.2.0
`

Android 

```
dependencies {
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation("androidx.browser:browser:1.4.0")
    implementation platform('com.google.firebase:firebase-bom:29.0.0')
    implementation 'com.google.firebase:firebase-appcheck-debug:16.0.0'
    implementation 'com.google.android.play:core:1.10.3'
    implementation 'com.google.android.gms:play-services-auth:20.2.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:18.0.1'
    implementation 'androidx.work:work-runtime-ktx:2.7.1'
    implementation 'com.google.ads.mediation:facebook:6.10.0.0'


}

```
MyMediationNetworkExtrasProvider.java

In this file io.flutter.plugins.googlemobileads.MediationNetworkExtrasProvider is not getting imported !!

```
import com.google.ads.mediation.facebook.FacebookAdapter;
import com.google.ads.mediation.facebook.FacebookExtras;
import com.google.android.gms.ads.mediation.MediationExtrasReceiver;
import io.flutter.plugins.googlemobileads.MediationNetworkExtrasProvider;

import java.util.HashMap;
import java.util.Map;

class MyMediationNetworkExtrasProvider implements MediationNetworkExtrasProvider {

    @Override
    public Map<Class<? extends MediationExtrasReceiver>, Bundle> getMediationExtras(
            String adUnitId, @Nullable String identifier) {
        Bundle appFacebook = new FacebookExtras().setNativeBanner(true).build();
        Map<Class<? extends MediationExtrasReceiver>, Bundle> extras = new HashMap<>();
        extras.put(FacebookAdapter.class, appFacebook);
        return extras;
    }
}

```

Main Activity.java

 GoogleMobileAdsPlugin not getting imported!!

```
public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(@Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
    }

    @Override
    protected void onStart() {
        super.onStart();
        getWindow().getDecorView().setVisibility( View.VISIBLE);
    }

    @Override
    protected void onStop() {
        super.onStop();
        getWindow().getDecorView().setVisibility( View.GONE);
    }

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        // Register your MediationNetworkExtrasProvider to provide network extras to ad requests.
        GoogleMobileAdsPlugin.registerMediationNetworkExtrasProvider(
                flutterEngine, new MyMediationNetworkExtrasProvider());
    }
}

```

**Comment by maheshmnj** [comment]
Hi @parmarravi, Thanks for filing the issue. Could you please specify what exactly the issue is? If you are looking for help with your code I would advise switching to platforms like StackOverflow.

Thanks

**Comment by parmarravi** [comment]
Hi @maheshmnj ,

For Mediation there is a documentation where it shows in-order to use Facebook or any other mediation you need to make a separate class in native language  for example something like MyMediationNetworkExtrasProvider that is implemented from MediationNetworkExtrasProvider.


However  MediationNetworkExtrasProvider can't be imported . So does the GoogleMobileAdsPlugin can't be imported.

Due to this I am not able to add mediation feature in the flutter

**Comment by maheshmnj** [comment]
Thanks for the clarification @parmarravi, Labeling this issue for further insights from the team. Looks like this is the interface you are trying to import 

https://github.com/googleads/googleads-mobile-flutter/blob/ebb97e9a01c8a6e007943d213c1b45e8ed81d16c/packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/MediationNetworkExtrasProvider.java#L31

cc: @jjliu15

**Comment by jjliu15** [comment]
From the [android example app](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/android/settings.gradle#L1-L15), can you try adding the following lines to your `settings.gradle`? 

```
def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withInputStream { stream -> plugins.load(stream) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```

**Comment by jjliu15** [comment]
We should update the devsites to mention that this is needed to be able to reference these classes.

**Comment by jjliu15** [comment]
Documentation has been updated in https://developers.google.com/admob/flutter/mediation/get-started#update_your_gradle_settings_android_only
