### ISSUE TITLE
version 1.2.0 cannot be started in Flutter 3.1.0

### ISSUE THREAD

**Issue by agrjp** [googleads/googleads-mobile-flutter#573]
I created a new project and then added dependencies the app crashes
google_mobile_ads: ^1.2.0
Flutter 3.0.1
MacBook Air M1
emulator：iPhone 13 IOS15.5

**Comment by maheshmnj** [comment]
Hi @agrjp,

There is a similar issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/572, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
