### ISSUE TITLE
🐛 RewardedAd not Trigger onRewardedAdUserEarnedReward when finish or close Ad

### ISSUE THREAD

**Issue by mustafa-707** [googleads/googleads-mobile-flutter#58]
**Describe the bug**
i'm using the last update of this plugin and the RewardedAd worked well , but when it finish counting and press on close button the ad not execute onRewardedAdUserEarnedReward . 

im using iOS 14.3

**Comment by jjliu15** [comment]
Could you share the code you're using to load the rewarded ad?

I have not been able to reproduce this issue in the [example app](https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example), on iPhone 12 simulator (iOS 14.3).

**Comment by gkovac42** [comment]
I have also had this issue reported by a few users with Android devices for my Play Store published app. I can't reproduce the issue on any of my devices, though, so I'm in the dark as to the details. But I believe this is worth looking into...

**Comment by mustafa-707** [comment]
@jjliu15  @gkovac42 
today i was tried it and it worked as like as android and all good after version 0.11.0+3
