### ISSUE TITLE
Can We control metadata and gadApp Identifier value from code programmatically?

### ISSUE THREAD

**Issue by itxmubi** [googleads/googleads-mobile-flutter#583]
Hi
For using ads in our app , we need to add metadata in androidmanifest.xml , and <key>GADApplicationIdentifier</key> in info.plist file. Can we add their values from inside code programmatically?

**Comment by maheshmnj** [comment]
Hi @itxmubi,
I believe that should be possible via platform channels, Flutter doesn't provide such api out of the box, For further help please try asking such questions on forums like StackOverflow.
