### ISSUE TITLE
SSV callback is not called after unity meditation ad is shown.

### ISSUE THREAD

**Issue by kim-jinmo** [googleads/googleads-mobile-flutter#586]
We're using the Google_mobile_ads: 1.2.0 plug-in.
And to add unity mediation, we implemented it according to the description of 
https://developers.google.com/admob/android/mediation/unity?authuser=0.
(우리는 google_mobile_ads: 1.2.0 플러그인을 사용하고 있습니다.
그리고 unity mediation을 추가하기 위해 https://developers.google.com/admob/android/mediation/unity?authuser=0 설명에 따라 구현하였습니다.)

While admob ads are showing well and ssv callback is called well, unity mediation ads are showing well but ssv callback is not called.
(admob 광고는 잘 보여지고 ssv 콜백이 잘 호출되지만, unity mediation 광고는 잘 보여지지만 ssv 콜백이 호출되지 않습니다.)

This is the log after the ads is finished.
(광고가 끝나고 난 후의 로그입니다.)

```
flutter: AdMob onUserEarnedReward. adUnitId : ca-app-pub-****************/**********, responseInfo : ResponseInfo(responseId: null, mediationAdapterClassName: GADMediationAdapterUnity, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterUnity, latencyMillis: 16), description: {
flutter:     AdUnitMapping =     {
flutter:         gameId = *******;
flutter:         zoneId = *******************;
flutter:     };
flutter:     Latency = "0.016";
flutter:     Network = GADMAdapterUnity;
flutter: }, adUnitMapping: {zoneId: *******************, gameId: *******}, adError: null)]), item type : , item amount : 1.0
flutter: AdMob onAdDismissedFullScreenContent. adUnitId : ca-app-pub-****************/**********, responseInfo : ResponseInfo(responseId: null, mediationAdapterClassName: GADMediationAdapterUnity, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterUnity, latencyMillis: 16), description: {
flutter:     AdUnitMapping =     {
flutter:         gameId = *******;
flutter:         zoneId = *******************;
flutter:     };
flutter:     Latency = "0.016";
flutter:     Network = GADMAdapterUnity;
flutter: }, adUnitMapping: {zoneId: *******************, gameId: *******}, adError: null)])
-----------------------------------

Strangely, the response Id value is null.
(이상하게 responseId의 값이 null입니다.)

We don't know how to solve this problem.
(우리는 이 문제를 어떻게 해결해야 할지 모르겠습니다.)
```

**Comment by maheshmnj** [comment]
Hi @kim-jinmo, Thanks for filing the issue.  I am quite not sure what are you referring to `ssv callback` ?
Can you please share the complete output of `flutter run -v` in a text file ?

Thanks

**Comment by kim-jinmo** [comment]
We added Tapjoy, Adcolony, Unity ads, and Vungle Adapter to AdMob Mediation.
(우리는 애드몹 미디에이션에 탭조이, 애드콜로니, 유니티, 벙글 어뎁터를 추가하였습니다.)

And when the advertisement was successfully shown, we used "server-side verification (SSV) callbacks" to earn points to the user.
(그리고 광고가 성공적으로 보여줬을때 "server-side verification (SSV) callbacks" 을 이용하여 사용자에게 포인트를 적립 되도록 하였습니다.)

However, Unity Ads and Vungle Adapters show successful ads, but "SSV callbacks" are not called, so points are not earned.
(그런데 Unity Ads와 Vungle 어뎁터는 광고가 성공적으로 보여줬지만 "SSV callbacks"이 호출되지 않아 포인트가 적립 안됩니다.)

We would like to know why "SSV callbacks" are not being called.
(우리는 "SSV callbacks"이 왜 호출이 안되는지 알고 싶습니다.)

**Comment by maheshmnj** [comment]
Hi @kim-jinmo, thanks for the update. I am leaving this issue open for further insights from the team.

**Comment by timothyhoang-google** [comment]
@kim-jinmo, could you share a [Network Trace](https://developers.google.com/admob/android/network-tracing) or [Charles log](https://www.charlesproxy.com/) containing the ad request and ad response for two cases:

1. AdMob mediation ad
2. Unity mediation ad 

For (1), could you also share the corresponding [SSV callback](https://developers.google.com/admob/android/ssv)?
