### ISSUE TITLE
Production Ads will load on iOS but not Android.

### ISSUE THREAD

**Issue by JacoFourie** [googleads/googleads-mobile-flutter#587]
## Plugin Version

1.2.0

## Steps to Reproduce

I developed my app using Test ads with test devices. All worked 100% on iOS and Android. Then came the time to send the app out to external testers. I created the App IDs and Ad Units for both platforms and updated the app. Compiled and loaded it as test apps for external testers on both platforms.

I have created an App ID and ad units in AdMob all is green and ready to serve ads. The same code will work on iOS (with its created ad units) but I get load errors on Android. In the production version of the app.

Here is the error

I/flutter ( 2600): Anchored adaptive banner failedToLoad: LoadAdError(code: 1, domain: com.google.android.gms.ads, message: Error building request URL., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))

As a test I took my app ID and ad units and updated the Demo app for the googleads-mobile-flutter package and I got the same errors so I know it is not my code as the Demo app gives the same load error.

I then logged an issue with the Google ads team as All is in place from a settings point of view on Admob.

https://groups.google.com/g/google-admob-ads-sdk/c/NVq91OTACGM.

The Google Ads team asked me for my App ID and Ad units and was able to load ads in their sample app.
They made the following statement

--------------------------------

Hi Jaco,

Thank you for providing the requested information privately.

I've tested your Ad Unit ID on our sample app, and was able to load ads successfully. Since the issue here seems to be platform specific, we would recommend to post it on [AdMob Flutter issue tracker](https://github.com/googleads/googleads-mobile-flutter/issues) instead. The developer specialist there should be able to assist you further on your concern.

Regards,

--------------------------------

So if somebody from this team can contact me then I will give you the app id and ad units to test to see if you get the same issue.

**Comment by JacoFourie** [comment]
OK so I may have it working. Please tell me if this is correct as I did not see this in any documentation or examples.
It seems that the production ads for Android will only load if I build an app bundle and upload it to the Playstore. I build an app bundle now and sent out a link for testing and I got ads on the devices that I installed the app from the store.
If this is the case then all the documentation is wrong as it does not say you have to do this. It only says replace your ids and remove the test device code.

**Comment by maheshmnj** [comment]
Closing as solved.

**Comment by JacoFourie** [comment]
@maheshmnj I know I have to use test ads when I develop. I Did that as stated, please read my question. It seems you are just dismissing my question. What is does not say in the documentation is that you have to upload the production app the Playstor for Android. On iOS I can build the app in Release mode and install it on test devices from my Macbook and all works 100%. But if I build the app for Release Mode on Android it does not work. Only if I build an app bundle and upload it to the store can I install it on test devices and all works the way it should. Obviously, I have to test the app before I let it loose on the world.
