### ISSUE TITLE
Banner test ads on Android stopped working.

### ISSUE THREAD

**Issue by hicnar** [googleads/googleads-mobile-flutter#597]
I have noticed that a few weeks ago banner test ads for Android (ca-app-pub-3940256099942544/6300978111) stopped to work.

Here's the error message I am getting when requesting the above ad id: 
```
LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))
```
The last changes to my codebase that touched the parts responsible for loading and displaying ads are from Nov 2021, also test banner ads for iOS  work perfectly as do interstitial test ads for both Android and iOS.

I am on the most recent stable version of both Flutter and google_mobile_ads. 
Is there anything that you could advise?

**Comment by hicnar** [comment]
@maheshmnj could you point me to the examples that once were part of this library so that I can try to run one with the above mentioned ad id? The examples were once here (and this is how I learned how to implement them in my projects), but for some reason I cannot find them now.

**Comment by maheshmnj** [comment]
@hicnar  You can try running this example app https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example

**Comment by hicnar** [comment]
I tried to run this but I was not able because it uses the old v1 embedding. Could you please upgrade your examples? I guess you haven't run them for quite a while
![Screenshot 2022-07-11 at 15 27 22](https://user-images.githubusercontent.com/1816194/178288140-0c5c6587-c07e-4021-807f-62818e3876a7.png)

**Comment by maheshmnj** [comment]
@hicnar can you please try this [sample project](https://github.com/googleads/googleads-mobile-flutter/files/9092757/ads_example.zip)? Although I agree that the example needs to be updated.

**Comment by hicnar** [comment]
I had to modify it a bit, but all in all I tested that and it looks like the problem is tied one of my android devices (S9) it works if run on an emulator also it works when run on Google Pixel C tablet. Which makes me thing it has something to do with something related to my S9. Apologies for opening this without running more tests across different types of Android devices.
