### ISSUE TITLE
GoogleAppMeasurement version bounds incompatible with latest firebase_analytics

### ISSUE THREAD

**Issue by csbence10** [googleads/googleads-mobile-flutter#599]
## Plugin Version

`google_mobile_ads: ^1.3.0`

## Steps to Reproduce

1. Use latest `firebase_core` and `firebase_analytics` dependencies. Also use latest `google_mobile_ads` dependency.
2. Build your project for iOS

**Expected results:**
App starts, and works fine :)

**Actual results:**
Pod install fails. See logs

<details>
  <summary>Logs</summary>

[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 9.1.12, which depends on
          Firebase/Analytics (= 9.2.0) was resolved to 9.2.0, which depends on
            Firebase/Core (= 9.2.0) was resolved to 9.2.0, which depends on
              FirebaseAnalytics (~> 9.2.0) was resolved to 9.2.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 9.2.0) was resolved to 9.2.0, which depends on
                  GoogleAppMeasurement (= 9.2.0)
        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (= 8.13.0) was resolved to 8.13.0, which depends on
            GoogleAppMeasurement (< 9.0, >= 7.0)
</details>

**Comment by maheshmnj** [comment]
Hi @csbence10, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/594, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
