### ISSUE TITLE
[Feature Request] get TCString support

### ISSUE THREAD

**Issue by sedobrengocce** [googleads/googleads-mobile-flutter#607]
## Use case
There isn't any function to get the tcString if needed

## Proposal

a new method

ConsentInformation.instance.getTCSTring();

that returns the TCString

**Comment by huycozy** [comment]
Hi @sedobrengocce, thanks for filing the issue. Labeling this issue as a feature request.

**Comment by timothyhoang-google** [comment]
@sedobrengocce - We recommend using the [User Messaging Platform SDK](https://developers.google.com/admob/flutter/eu-consent) which should be supported on v1.3+ to collect and forward user consent (including TC strings).
