### ISSUE TITLE
Can't find NativeAdFactory with id: listTile, null, null

### ISSUE THREAD

**Issue by ting28418** [googleads/googleads-mobile-flutter#613]
can't find nativeadfactory at flutter version 3.0.0 ,google_mobil_ads version 1.2.0

Unhandled Exception: PlatformException(NativeAdError, Can't find NativeAdFactory with id: listTile, null, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
<asynchronous suspension>
#2      NativeAd.load
package:google_mobile_ads/src/ad_containers.dart:1053
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(NativeAdError, Can't find NativeAdFactory with id: listTile, null, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
<asynchronous suspension>
#2      NativeAd.load
package:google_mobile_ads/src/ad_containers.dart:1053
<asynchronous suspension>

**Comment by huycozy** [comment]
Hi @ting28418, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In this case please provide a public repository due to there are also native code files. Also, please provide affected device information as well.

And you are using the old Flutter and `google_mobile_ads` versions; the latest Flutter stable is `3.0.5`, the master is `3.1.0` and `google_mobile_ads` is `1.3.0`. Please try upgrading them and retry to see if this issue still reproduces.

Thank you!

**Comment by kamxy** [comment]
same issue

**Comment by nubloso** [comment]
Open AppDelegate.swift and make sure "return super.application..." is there only **once**.

```
import google_mobile_ads
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    // ----------- Don't return anything yet! -----------

    // TODO: Register ListTileNativeAdFactory
    let listTileFactory = ListTileNativeAdFactory()
    FLTGoogleMobileAdsPlugin.registerNativeAdFactory(
        self, factoryId: "listTile", nativeAdFactory: listTileFactory)

     // ----------- Return here -----------
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Comment by kamxy** [comment]
> 

problem happining on android

**Comment by kamxy** [comment]
> Open AppDelegate.swift and make sure "return super.application..." is there only **once**.
> 
> ```
> import google_mobile_ads
> import UIKit
> import Flutter
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     // ----------- Don't return anything yet! -----------
> 
>     // TODO: Register ListTileNativeAdFactory
>     let listTileFactory = ListTileNativeAdFactory()
>     FLTGoogleMobileAdsPlugin.registerNativeAdFactory(
>         self, factoryId: "listTile", nativeAdFactory: listTileFactory)
> 
>      // ----------- Return here -----------
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```

problem happing on android
