### ISSUE TITLE
Native ad not working on Android 12

### ISSUE THREAD

**Issue by hisham-89** [googleads/googleads-mobile-flutter#619]
Native ads are working on ios, and android versions less than 12,

the issue is :
NativeAd failedToLoad: LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Internal error.,

**Comment by huycozy** [comment]
Hi @hisham-89, which `google_mobile_ads` version are you using?
And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by hisham-89** [comment]
> Hi @hisham-89, which `google_mobile_ads` version are you using? And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

Thank you so much,there was a network issue with that device.

**Comment by huycozy** [comment]
@hisham-89 
>Thank you so much,there was a network issue with that device.

Thanks for updating. Closing, as this isn't an issue with Flutter itself.

**Comment by expertdev-designer** [comment]
Hii @huycozy  what type of network issue ? i also have same issue
