### ISSUE TITLE
Unclear implementation in the documentation

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-flutter#620]
Hi,

I followed the initial integration documentation (https://developers.google.com/admob/flutter/quick-start#platform_specific_setup) and it said "See the Android guide for more information on configuring AndroidManifest.xml and setting app ID". In that link it shows other steps to do (like add dependency 'implementation' com.google.android.gms: play-services-ads: 21.1.0''), do I have to do them or do them the plugin itself (same question for iOS (like SKAdNetworkItems))? (I wonder because I haven't made them at the moment but it seems to work (maybe, in case they aren't needed, you can write that they are not necessary)).

I had asked this question here (https://groups.google.com/g/google-admob-ads-sdk/c/gS9bAD1Y7FA/) but they told me to ask here.

**Comment by huycozy** [comment]
Hi @Francesco-FL, I would like to answer your questions as below:

- For Android, the depencency `'com.google.android.gms:play-services-ads:21.0.0'` has already added to [Android library](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/android) so you don't need to add it into your project's `build.gradle`, see:

https://github.com/googleads/googleads-mobile-flutter/blob/219a3ccf218c29ffe7aa0b16106fb4f0bcd6049e/packages/google_mobile_ads/android/build.gradle#L34

- For iOS, you can see there is no `Info.plist` file in [iOS library](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/ios) so you need to update your project's `Info.plist` (add `GADApplicationIdentifier` and `SKAdNetworkItems` for example)

Does the above explanation make sense?

**Comment by Francesco-FL** [comment]
Now it's clear, thanks

**Comment by huycozy** [comment]
Closing, as it's solved above. Thank you!
