### ISSUE TITLE
Can I able to get swift support as i need many customisation on it. 

### ISSUE THREAD

**Issue by nbpatel94** [googleads/googleads-mobile-flutter#621]

**Comment by huycozy** [comment]
Hi @nbpatel94 
I'm assuming you're asking about NativeAd, right? If so, I believe that you can get Swift support from [this codelabs](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7) or [complete_kotlin_swift](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) Github repository.
