### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by see** [googleads/googleads-mobile-flutter#625]

**Comment by huycozy** [comment]
Hi @see, thanks for filing the issue. 
I see there's an open issue addressing the case you described https://github.com/googleads/googleads-mobile-flutter/issues/525. Even though the issue's title is `Support Ads for Windows platform`, OP also mentioned other platforms too. You can leave there your comment about other platforms and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.
