### ISSUE TITLE
From "nonPersonalizedAds" to "PersonalizedAds"

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-flutter#628]
I don't know whether to call it a feature request or a consideration, but:

in the AdRequest you have added the "nonPersonalizedAds" bool. In my opinion, it is counterintuitive to enable non-personalized ads. In my opinion it is much more intuitive to enable and disable personalized ads.

Also because, usually the programmer modifies that parameter on the basis of a consent requested by the user, which is usually (in fact): do you want personalized ads? Yes or no. And therefore any bool saved by the programmer is "true" personalized ads, or false and therefore non-personalized ads.

However, the plugin thinks differently. In fact, to change that parameter I had to put:

nonPersonalizedAds: SaveData.consent == false

instead of (more intuitive):

PersonalizedAds: SaveData.consent

----------------

My proposal is therefore to change the parameter from "nonPersonalizedAds" to "PersonalizedAds", then saying "true" for personalized ads and "false" for non-personalized ads.

Then I don't know, maybe it's just me who has this reasoning problem.

**Comment by huycozy** [comment]
Hi @Francesco-FL, thanks for filing the issue.
Considering this issue as a feature request and keeping this open for further opinions from the team. Thanks!

**Comment by timothyhoang-google** [comment]
By default, ads are personalized unless the user opts-out of ads personalization. From the GMA SDK's perspective, this is a feature toggle: true - activate feature, false - don't activate feature. 

To avoid confusion over setting the param, the [User Messaging Platform SDK](https://developers.google.com/admob/flutter/eu-consent) can be used to request and store user consent. The user's consent is referenced by the GMA SDK when making ad requests to determine ads personalization state.
