### ISSUE TITLE
AdSize.fluid shows only [Test Ad], but no banner content

### ISSUE THREAD

**Issue by JCKodel** [googleads/googleads-mobile-flutter#632]
## Plugin Version
google_mobile_ads: ^2.0.1

## Steps to Reproduce
Choose `AdSize.fluid` as `size` property of a `BannerAd` and show it as:

```dart
    final screenSize = MediaQuery.of(context).size;

    return SizedBox(
      width: screenSize.width,
      height: 250,
      child: AdWidget(ad: _banner),
    );
```
(the idea here is to increase banner height in devices with large height to width ratio)

**Expected results:** 
The Ad being show at the available size.

**Actual results:** 
Only the Test Ad text, but no ad (and the ad IS loaded): (the grey area at the bottom is the SizedBox with 250px height)

![image](https://user-images.githubusercontent.com/379339/186251141-0e67e94f-bda0-432b-94d6-abea70c5221e.png)

(flutter run --verbose ommited because GitHub is complaining about  body is too long (maximum is 65536 characters))

<details>
  <summary>Logs</summary>

```
Analyzing frontend...                                           
No issues found! (ran in 3.3s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale pt-BR)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Android
    • Platform android-33, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\jckodel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @JCKodel 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Also, there is a [fluid_example sample code](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/fluid_example.dart), you can try using it. The result will look like this:

<details>
<summary>Demo</summary>

<img width="469" alt="Screenshot 2022-08-24 at 11 00 53" src="https://user-images.githubusercontent.com/104349824/186325950-caf05784-d3d1-49ed-ae29-b7686fb55304.png">

</details>


Thank you!

**Comment by korchix** [comment]
Hello, in the [fluid_example sample code](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/fluid_example.dart)  you'r using this adUnitId: '/6499/example/APIDemo/Fluid'. 
what kind of adUnitId is this  ? i tried to replace it with a nativeAdUnitId but i got this error : Ad unit doesn't match format.

**Comment by RichardRaue** [comment]
@korchix this needs an bannerAdUnitId to work. Nevertheless, the issue with fluid Adsize persist. While both, test ad and real ad are loaded successfully, only test ad is shown.
