### ISSUE TITLE
Rewarded Video test ad can't be dismissed by clicking in the close button (after 2.0.0)

### ISSUE THREAD

**Issue by Gilianp** [googleads/googleads-mobile-flutter#633]
## Plugin Version
2.0.0

## Steps to Reproduce
After 2.0.0 version, using test ads, the Rewarded Video can't be dismissed by clicking in the close button. The close button doesn't even become clickable. It only becomes clickable when the video ends, but the reward has already been given.

![Screenshot_1661284265](https://user-images.githubusercontent.com/5700016/186253358-9e4275c8-440a-46b6-bbd2-c12351d39c7d.png)

Until version 1.3.0, it was possible to click the close button when the timer was about 3~2 seconds, but after version 2.0.0 this is no longer possible (test ads). I'am using android emulator

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1110], locale en-029)
    • Flutter version 3.0.5 at G:\SDKs e frameworks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at G:\sdk_android
    • Platform android-31, build-tools 33.0.0-rc1
    • ANDROID_HOME = G:/sdk_android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.
</details>

**Comment by huycozy** [comment]
Hi @Gilianp
I tried running version `1.3.0` but the result is still the same as `2.0.1`. Could you please provide a recorded video for this case?
As defined [here](https://support.google.com/admob/answer/7372450?hl=en), rewarded ad units are non-skippable, but closeable.
Also, this issue may come from the native library as I can also reproduce it with example from [googleads-mobile-android-examples](https://github.com/googleads/googleads-mobile-android-examples).

<details>
<summary>Demo</summary>

<img width="469" alt="Screenshot 2022-08-24 at 11 17 16" src="https://user-images.githubusercontent.com/104349824/186329695-bb803d74-8da4-430b-86a1-f532488ccd89.png">

</details>

There is also a open thread that you can follow up here: https://groups.google.com/g/google-admob-ads-sdk/c/hmx4mWfuDQA

**Comment by Gilianp** [comment]
Hi @huycozy, sorry for the delay.

So far I've always developed using test ads with this lib, and I've always been able to close the Rewarded Video before the countdown ends, thus displaying the message that I wouldn't receive the reward. Now that you mention it, I think the problem actually occurred from version 1.3.0 onwards, I'll try to provide a video, but this was really always possible. I just discovered this glitch now as I was no longer able to test the code that runs when the reward is not given (in fact, it would be weird not being able to test this using the test ads).
Finally, I didn't understand the difference between Rewarded Video being non-skippable, but closeable.
Thanks for you support!

**Comment by huycozy** [comment]
Hi @Gilianp 
Thanks, please try to provide the video, it will be helpful for us and others.

>Finally, I didn't understand the difference between Rewarded Video being non-skippable, but closeable.

It's one of `AdMob rewarded ad format & features`. Please go to https://support.google.com/admob/answer/7372450?hl=en,  scrolling down and there is a section that explains this.
