### ISSUE TITLE
MobileAds.instance.initialize() execution causes jank

### ISSUE THREAD

**Issue by Kabilan21** [googleads/googleads-mobile-flutter#634]
## Details

1. Initializing without await 

- When admob is initialized, the app freezes during the time of initialization causing the app unusable in the meantime.
- During initialization in the background, the app is unable to receive any touch inputs properly.

2. Initializing with await increases app opening time considerably.
3. The issue occurs even on a sample app but is noticeable only when there are animations. ex: In games, jank is easily noticeable as there are continuous animations.
4.  Google mobile ads SDK is taking a long time to initialize and also the task looks heavy. It also initializes mediation adapters if present. Need of a solution to enable/disable mediation adapter initialization. If no adapter is present and SDK is searching for any mediation adapters to initialize, causing increased SDK initialization time and unwanted resource utilization.

**Target Platform:** Android
**Target OS version/browser:** 31
**Devices:** Redmi Note 10

**Comment by huycozy** [comment]
Hi @Kabilan21, could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
Does this issue affect iOS? 
Thank you!

**Comment by Kabilan21** [comment]
`import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    if (_counter == 15) {
      MobileAds.instance.initialize();
    }
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

Added a logic to initialize google mobile ads SDK with a condition.

Actual behavior :
       Clicking on the increment button increases the counter without any problem initially. But when the condition is satisfied, SDK starts to initialize, for further clicks on the counter during this initialization, UI freezes. UI gets back to normal after the SDK initialization gets completed. Issue can be observed only when the increment button is clicked rapidly.
 
The issue is noticeable only when the app is cold started where SDK initialization takes a long time.

**Comment by huycozy** [comment]
Hi @Kabilan21 
According to [Initialize the Mobile Ads SDK](https://developers.google.com/admob/flutter/quick-start#initialize_the_mobile_ads_sdk):
>Before loading ads, have your app initialize the Mobile Ads SDK by calling MobileAds.instance.initialize(), which initializes the SDK and returns a Future that finishes once initialization is complete (or after a 30-second timeout). This needs to be done only once, ideally right before running the app.

The `MobileAds.instance.initialize()` should be called before running the app. For example:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(MyApp());
}
```

Also, regarding `Google mobile ads SDK is taking a long time to initialize`, this is a similar issue being tracked at #429

**Comment by huycozy** [comment]
Hi @Kabilan21 
According to [Initialize the Mobile Ads SDK](https://developers.google.com/admob/flutter/quick-start#initialize_the_mobile_ads_sdk):
>Before loading ads, have your app initialize the Mobile Ads SDK by calling MobileAds.instance.initialize(), which initializes the SDK and returns a Future that finishes once initialization is complete (or after a 30-second timeout). This needs to be done only once, ideally right before running the app.

The `MobileAds.instance.initialize()` should be called before running the app. For example:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(MyApp());
}
```

Also, regarding `Google mobile ads SDK is taking a long time to initialize`, there is a similar issue being tracked at #429.

**Comment by Kabilan21** [comment]
The above code is only for reproducing this issue easily. Even if we tried to start the SDK initialization before running the app, if the SDK initialization is not completed before the user starts to interact with the app or any animation is running, UI freeze can be observed.

**Comment by huycozy** [comment]
@Kabilan21 Based on what you describe, I see that it is similar to what is reported in issue #429 (please see https://github.com/googleads/googleads-mobile-flutter/issues/429#issuecomment-966887764). 
So I will close this issue as a duplicate from now, please follow up on #429 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. If you disagree, please write in the comments and I will reopen it.
Thank you!

**Comment by huycozy** [comment]
@Kabilan21 please take a look at comments on #429 that are related to the effect of SDK initialization (blocking UI/freeze UI/failed to load, etc). Also, it has been confirmed that this issue will be fixed in the future, see https://github.com/googleads/googleads-mobile-flutter/issues/429#issuecomment-983118047.
