### ISSUE TITLE
Status bar could not be hidden for full screen ad on IOS devices

### ISSUE THREAD

**Issue by zumatrahia** [googleads/googleads-mobile-flutter#639]
## 2.0.1

When I use Interstatial ads on iOS devices I receive this warning in debug console.(No problems with ads showing)
`Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.`
 I wasn't able find out where can I implement the hide status bar functionality. Can you help?

**Comment by JoeArmani** [comment]
I ran into this issue and this cleared the error for me:
`import 'package:flutter/services.dart';`
hide status bar:
`SystemChrome.setEnabledSystemUIMode(
      SystemUiMode.manual,
      overlays: <SystemUiOverlay>[],
    );`
show status bar (after ad is closed by user):
`SystemChrome.setEnabledSystemUIMode(
      SystemUiMode.manual,
      overlays: SystemUiOverlay.values,
    );`

**Comment by huycozy** [comment]
Hi @zumatrahia 
Please see [Stricter enforcement of status bar controls](https://developers.google.com/admob/ios/migration#stricter_enforcement_of_status_bar_controls).

> Starting from version 9.0.0, when you present full screen format ads, your app should ensure that the ads are able to control the presentation of the status bar. You will see an error message in the logs if you fail to do so.

> Depending on the specific layout of view controllers in your app, you may not need to make any changes to ensure this, but in some cases, you may need to set your parent view controller's modalPresentationCapturesStatusBarAppearance property.

However, I also don't see a workaround or guideline for this. Labeling this issue for further insights from the team.

**Comment by zumatrahia** [comment]
> I ran into this issue and this cleared the error for me: `import 'package:flutter/services.dart';` hide status bar: `SystemChrome.setEnabledSystemUIMode( SystemUiMode.manual, overlays: <SystemUiOverlay>[], );` show status bar (after ad is closed by user): `SystemChrome.setEnabledSystemUIMode( SystemUiMode.manual, overlays: SystemUiOverlay.values, );`

It works thank you

**Comment by minhdanh** [comment]
@JoeArmani @zumatrahia How do you restore the status bar when the ad is close?
I tried but it doesn't work. I'm not sure how. Here's my code:

```
              SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
              await _showInterstitialAd();
              SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: SystemUiOverlay.values);
              print('Ad has been displayed');
```

Even when I await the _showInterstialAd function, the line 'Ad has been displayed' always finished before the ad finished. Meaning somehow the async function showInterstialAd doesn't wait at all.

Here's the code of _showInterstitialAd():

```
  Future<void> _showInterstitialAd() async {
    if (_interstitialAd != null) {
      _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
        onAdDismissedFullScreenContent: (InterstitialAd ad) {
          ad.dispose();
          _loadInterstitialAd();
        },
        onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
          ad.dispose();
          _loadInterstitialAd();
        },
      );
      await _interstitialAd!.show();
    }
  }
```

**Comment by cristian1980** [comment]
@minhdanh SystemChrome.setEnabledSystemUIMode() is asynchronous, use await SystemChrome.setEnabledSystemUIMode() to make sure the bars are actually hidden before the ad is displayed.

**Comment by Namr547** [comment]
> I ran into this issue and this cleared the error for me: `import 'package:flutter/services.dart';` hide status bar: `SystemChrome.setEnabledSystemUIMode( SystemUiMode.manual, overlays: <SystemUiOverlay>[], );` show status bar (after ad is closed by user): `SystemChrome.setEnabledSystemUIMode( SystemUiMode.manual, overlays: SystemUiOverlay.values, );`

Thanks for the Solution. YOu saved my time
