### ISSUE TITLE
Using AdManager and AdMob in the same app

### ISSUE THREAD

**Issue by nemanja-nisic** [googleads/googleads-mobile-flutter#646]
I have a request from a client to use AdManager and AdMob both in the app and to show ads from each depending on certain criteria. Is this possible to achieve using this plugin if ID in AdManager and AdMob is different?

**Comment by timothyhoang-google** [comment]
It's possible to use both Ad Manager and AdMob simultaneously, though this is not recommended. If issues arise, it is very difficult for Publisher Support to troubleshoot.

If certain Ad Manager features such as key-value targeting are required, use the Ad Manager app ID in the configuration files. You can use the Ad Manager ad unit ID or AdMob ad unit ID whenever you want to show ads from either platform.

Keep in mind that multi-call enforcement will still be applied when using AdMob and Ad Manager in the same application. We strongly recommend that the client re-evaluate their platform requirements and use either AdMob or Ad Manager.

**Comment by nemanja-nisic** [comment]
Hi @timothyhoang-google, thank you for the response.

My issue arises because AdManager app id and AdMob app id are different which means I need to add both to Android Manifest which is not possible. I saw in the test ads that it is possible to use both and decide which ad id will be used in realtime when widgets are rendering ( which awesome by the way ) but in test ads app id for both is the same.

Thanks!

**Comment by FlawLessx** [comment]
did you found solution @nemanja-nisic ? is it possible register multiple com.google.android.gms.ads.APPLICATION_ID in the same app?

**Comment by nemanja-nisic** [comment]
@FlawLessx Hey man sorry I did not see this message from you. I can't remember what I did right now as it was a while ago but I do remember making it work somehow. I also have the project on my machine still so I can take a look when I get a chance, just let me know if you still need it.
