### ISSUE TITLE
Ad-Content should not be selectable (iOS)

### ISSUE THREAD

**Issue by appinteractive** [googleads/googleads-mobile-flutter#655]
Hey, I do encounter the issue, that when I tap and hold on an ad, the content is selected, which is confusing and in my view not intended.  Is there a way to prevent that as a workaround in the meantime!?

## Plugin Version

2.0.1

## Steps to Reproduce

1. open an interstitial ad (iOS)
2. long press on ad content

**Expected results:** 
nothing should happen, no selection, no interaction

**Actual results:** 
all (or partial) text (and close button) on the ad is selected

<img width="427" alt="grafik" src="https://user-images.githubusercontent.com/432828/191467670-87d393b8-0b29-47a1-985a-5dbfd58d8a5a.png">

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale de-DE)
    • Flutter version 3.3.2 on channel stable at /Users/▋▋▋▋//fvm/versions/3.3.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/▋▋▋▋/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/▋▋▋▋//Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64 • Android 10 (API 29)
      (emulator)
    • ▋▋▋▋/ (mobile)                       • ▋▋▋▋▋▋▋▋▋▋            • ios           • iOS 16.0 20A362
    • iPhone 14 Pro (mobile)               • ▋▋▋▋▋▋▋▋▋▋ • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64  • macOS 12.6 21G115
      darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @appinteractive 
I think this is working as intended by the native library, depending on `Ad type` (Text, Image, Video) returned. 
This issue is also reproducible on Android (Flutter). 

I also try running one of the [Android Native Ads Examples](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/RewardedInterstitialExample) and see the similar behavior (text is selectable)

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/191670118-8881ab0c-8f95-4a11-8b50-5a4f2a0b2e31.mp4

</details>

**Comment by appinteractive** [comment]
Hmm okay, find it really disturbing as also the close button gets selected. That destroys the native feel of the app but I guess it's a html view and can't be changed. Also could it result in unwanted ad clicks.

**Comment by huycozy** [comment]
Hi @appinteractive 
I also do the test with [googleads-mobile-ios-examples](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/admob/InterstitialExample) and see that the content is also selectable. I haven't tested with the production ad yet, it will be better if you can do it to make sure the same behavior.

<details>
<summary>Demo iOS native sample - Interstitial Ad</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/191885543-c2a0a1a0-7fd7-4f19-bdb2-d6c78c7ec1d6.png">

</details>

You can also file a new issue on https://groups.google.com/g/google-admob-ads-sdk to have better support there. Thank you!
