### ISSUE TITLE
LoadAdError code 2

### ISSUE THREAD

**Issue by saddem123** [googleads/googleads-mobile-flutter#658]
## Plugin Version
1.3.0

A network error and my internet connection is working fine in the rest of my app. Is there any explanation?

`on ad failed LoadAdError(code: 2, domain: com.google.android.gms.ads, message: Network error., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))`

Ads works in emulator and  in some other devices

**Comment by huycozy** [comment]
Hi @saddem123 
Could you please try upgrading ads plugin version and retrying? The latest version is `google_mobile_ads: ^2.0.1`.
Also, does this log appear when running [ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)?

**Comment by huycozy** [comment]
Hi @saddem123 
Could you please try upgrading ads plugin version and retrying? The latest version is `google_mobile_ads: ^2.0.1`.
Also, does this log appear when running [ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)? 
And please provide the list of affected devive (model, OS version). Thank you!

**Comment by saddem123** [comment]
@huycozy without changing anything it's works now

**Comment by huycozy** [comment]
@saddem123 Given your last message, I feel safe to close this issue from here. Thank you!
