### ISSUE TITLE
New ads error (code: 1, domain: com.google.admob, message: Request Error: No ad to show). occurs on iOS

### ISSUE THREAD

**Issue by saddem123** [googleads/googleads-mobile-flutter#659]
## Plugin Version

v1.3.0 & v2.0.0

## Problem

I left native ads works on ios 1 moth ago and  today when open it i find a new error `LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: CPagwo7FvPoCFcPymgodJd4LkQ, mediationAdapterClassName: null, adapterResponses: []))`

I didn't change anything and it works on android. I updated the version to 2.0.0 and then altered the unit id and had the same problem. I'm blocked to do anything with ads on my ios version.

**Comment by hemid32** [comment]
i have same problem  .
BannerAd failedToLoad: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))

**Comment by large** [comment]
Same problem here too!
`LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [])) case Request Error: No ad to show.`

Using
> [✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-NO)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.3)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability

Noticed in the logs:
```
<Google> To get test ads on this device, set: 
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]
```

Tried to "hack" using swift change without luck too:
```swift
import GoogleMobileAds  /// added this line
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    ///Ref: https://github.com/googleads/googleads-mobile-flutter/issues/209#issuecomment-951742046
    GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ] /// added this line
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by huycozy** [comment]
Hi @saddem123 and anyone facing this issue,
Does this issue only happen with production/real Ad unit id? Have you tried with [Test Unit ID](https://developers.google.com/admob/ios/test-ads#demo_ad_units)?
If so, please check this [ERROR_CODE_INTERNAL_ERROR](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_INTERNAL_ERROR)

**Comment by large** [comment]
I have checked with Ads SDK team and they confirm the same error:

`Hi Lars,

Thank you for providing the requested information.

I've checked your Ad Unit against our iOS sample app, and getting the same no fill error on my end. Also, I've checked your account and can confirm that it is fully setup (Billing and PIN verification) and there's no policy violation under your account. This could be an ad serving issue. However, since you're using flutter app, they we would suggest to reach out to our AdMob team who specifically handles our flutter app via this link and have them check this.

Regards,
Google Logo	
Teejay Wennie
> Mobile Ads SDK Team`

**Comment by saddem123** [comment]
Yes when I tested in the production app It works I think it's about the new restriction of the AdMob to serve test ad 
@huycozy Thank you.

**Comment by huycozy** [comment]
@large @saddem123 thanks for the confirmation. 
But I see there has already an open issue addressing the case you described https://github.com/googleads/googleads-mobile-flutter/issues/458

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
