### ISSUE TITLE
App Tracking Transparency dialog not appearing in iOS 15.5

### ISSUE THREAD

**Issue by omatt** [googleads/googleads-mobile-flutter#660]
## Plugin Version

google_mobile_ads: ^2.0.1

## Steps to Reproduce

1. Use [example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) provided in google_mobile_ads 
2. Follow this [guide](https://developers.google.com/ad-manager/mobile-ads-sdk/flutter/eu-consent) to display ATT dialog in iOS 15.5
3. Add `requestConsentInfoUpdate()` on `initState()` and update Info.plist with `NSUserTrackingUsageDescription`

```dart
@override
  void initState() {
    super.initState();

    final params = ConsentRequestParameters();
    ConsentInformation.instance.requestConsentInfoUpdate(
      params,
      () async {
        debugPrint('AAT request');
        // The consent information state was updated.
        // You are now ready to check if a form is available.
        if (await ConsentInformation.instance.isConsentFormAvailable()) {
          loadForm();
        } else{
          debugPrint('AAT Consent Form unavailable');
        }
      },
      (FormError error) {
        debugPrint('AAT error: $error');
        // Handle the error
      },
    );

    _createInterstitialAd();
    _createRewardedAd();
    _createRewardedInterstitialAd();
  }

void loadForm() {
    ConsentForm.loadConsentForm(
      (ConsentForm consentForm) async {
        var status = await ConsentInformation.instance.getConsentStatus();
        if (status == ConsentStatus.required) {
          consentForm.show(
            (FormError? formError) {
              // Handle dismissal by reloading form
              loadForm();
            },
          );
        }
      },
      (FormError formError) {
        // Handle the error
      },
    );
  }
```

4. Run the app

**Expected results:** 

ATT dialog should appear

**Actual results:** 

No ATT dialog displayed. Logs indicate that there's no consent form available

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-PH)
    • Flutter version 3.3.2 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • B262ADE9-F80C-4797-AA2D-E32F3E1065B2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @omatt, Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? In this case, it contains setup in iOS project, so it will be better if you can push the sample code into a GitHub repository and make it public.
Thank you!

**Comment by omatt** [comment]
You can use the [sample](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) provided in **google_mobile_ads** and use the code snippet I've provided in `main.dart`

**Comment by huycozy** [comment]
@omatt You can try adding `testIdentifiers` in `ConsentDebugSettings` to `ConsentRequestParameters`. You can get `TEST-DEVICE-HASHED-ID` from the console log. 
For more information: https://developers.google.com/ad-manager/mobile-ads-sdk/flutter/eu-consent#testing

<details>
<summary>Sample code - only modified initState()</summary>

```dart
void initState() {
    super.initState();

    ConsentDebugSettings debugSettings = ConsentDebugSettings(
        debugGeography: DebugGeography.debugGeographyEea,
        testIdentifiers: ['TEST-DEVICE-HASHED-ID']);

    final params = ConsentRequestParameters(consentDebugSettings: debugSettings);
    ConsentInformation.instance.requestConsentInfoUpdate(
      params,
          () async {
        debugPrint('AAT request');
        // The consent information state was updated.
        // You are now ready to check if a form is available.
        if (await ConsentInformation.instance.isConsentFormAvailable()) {
          loadForm();
        } else{
          debugPrint('AAT Consent Form unavailable');
        }
      },
          (FormError error) {
        debugPrint('AAT error: $error');
        // Handle the error
      },
    );

    _createInterstitialAd();
    _createRewardedAd();
    _createRewardedInterstitialAd();
  }
```
</details>

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/194346932-114dbd01-0e93-4614-aa73-64fedd6193a8.png">
</details>

**Comment by huycozy** [comment]
@omatt  I'm not sure if the dialog will change in production or different geography, can you try using another `DebugGeography` value to see if it achieves the expected behavior?
 
/cc @jjliu15 for thoughts.

**Comment by c0ffeec0der** [comment]
> ```dart
> AAT Consent Form unavailable
> ```

In android development, following this example would result to 'AAT Consent Form unavailable'. No dialog box appear, even though GDPR message is available

**Comment by huycozy** [comment]
Hi @c0ffeec0der 
Did you add your test identifier ID into `testIdentifiers`? You can find it from the console log.

**Comment by c0ffeec0der** [comment]
Hi @huycozy

Sorry I haven't add it.. 

Just now I added and it's still not working. The response from admob is

`D/UserMessagingPlatform( 5919): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform( 5919): Stored info not exists: IABTCF_TCString
D/UserMessagingPlatform( 5919): Stored info not exists: IABTCF_AddtlConsent
W/UserMessagingPlatform( 5919): Invalid response from server.`

Kindly advise, Thank you

**Comment by huycozy** [comment]
@c0ffeec0der Please check this [SO answer](https://stackoverflow.com/a/69183657/5921933) and please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by c0ffeec0der** [comment]
Hi @huycozy 

The only difference with [SO](https://stackoverflow.com/a/69183657/5921933) is 'tagForUnderAgeOfConsent: false' ; it's still not working..

I have created a [repository ](https://github.com/c0ffeec0der/test_ump)with the code sample as requested

Kindly advise, Many Thanks

**Comment by huycozy** [comment]
@c0ffeec0der Yes, I also can reproduce this issue on Android whilst it works fine on iOS. Labeling the issue for further investigation. 

- Sample code: Can use sample code at https://github.com/googleads/googleads-mobile-flutter/issues/660#issuecomment-1270214942 but need to update Admob App ID with the production one due to this [another issue](https://stackoverflow.com/questions/68457966/failed-to-read-publishers-account-configuration-please-check-your-configured-a) when using the test App ID. 

- Log:
```bash

D/UserMessagingPlatform( 4936): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform( 4936): Stored info not exists: IABTCF_TCString
D/UserMessagingPlatform( 4936): Stored info not exists: IABTCF_AddtlConsent
...
AAT error: Invalid response from server.

```

**Comment by huycozy** [comment]
@c0ffeec0der Yes, I also can reproduce this issue on Android whilst it works fine on iOS. I will reopen https://github.com/googleads/googleads-mobile-flutter/issues/678 due to this issue reporting for iOS. Thanks!
