### ISSUE TITLE
Admob native ads video controls

### ISSUE THREAD

**Issue by BrianTum** [googleads/googleads-mobile-flutter#661]
Hello team, I have an app that can run native video ads by AdMob. I have no way for my users to control the video in their interactions. For instance, in a story-like interaction, there is no way for a user to pause, resume and play a video.

I need a video control feature such a pause(), resume(), play(), for the video ads.

Kindly help as there is no such feature or package that can help with this problem.

**Comment by huycozy** [comment]
Hi @BrianTum Can you share the source of this feature?
