### ISSUE TITLE
Google mobile ads not able to close in iphone 14

### ISSUE THREAD

**Issue by reijerteunis** [googleads/googleads-mobile-flutter#662]
## Plugin Version
2.0.1

## Steps to Reproduce

When you show a full screen ad on the new apple 14 pro max, and maybe other versions as well, the ad cannot be closed anymore.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/69348129/194388532-174f891d-a719-4817-baa1-26f8cf570f4b.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/69348129/194388589-addbab52-d210-4f1f-b768-092904e538f0.png">

**Comment by huycozy** [comment]
@reijerteunis Thanks for the report! This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/191
Closing this issue as a duplicate, so please follow up on it for further updates.
