### ISSUE TITLE
Iphone 14 pro rewarded video

### ISSUE THREAD

**Issue by stoppimyse** [googleads/googleads-mobile-flutter#665]
Plugin Version 2.0.1

rewarded video are impossible to close because is under the new Iphone 14 pro app bar

**Comment by huycozy** [comment]
@stoppimyse 
Thanks for the report! This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/191. You may find a workaround at https://github.com/googleads/googleads-mobile-flutter/issues/191#issuecomment-1273683141

Closing this issue as a duplicate, so please follow up on it for further updates.
