### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by JohannesMilke** [googleads/googleads-mobile-flutter#67]
When does this package support Null Safety?

**Comment by Zeswen** [comment]
Waiting for this to update our application to Flutter 2.0!

It would be awesome to have it ASAP. Thank you for your great work :)

**Comment by untp** [comment]
I migrated this package to null safety. Here is my pull request: #86.

**Comment by Dabhipb** [comment]
Pls, provide support to Null Safety asap.

**Comment by edscodeblenders** [comment]
We need this to migrate to Flutter 2! Please implement it! Thanks.

**Comment by MichalDanielDobrzanski** [comment]
Hello, is it null safety you're looking for?

**Comment by jjliu15** [comment]
This is addressed by https://github.com/googleads/googleads-mobile-flutter/pull/99, in latest version 0.12.0.
