### ISSUE TITLE
google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on           Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on             GoogleAppMeasurement (< 10.0, >= 7.0)

### ISSUE THREAD

**Issue by andrew-a-hall** [googleads/googleads-mobile-flutter#677]
## Plugin Version

2.1.0

## Steps to Reproduce
pubspec.yaml

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  firebase_crashlytics: ^3.0.2
  firebase_messaging: ^14.0.2
  firebase_analytics: ^10.0.2
  flutter_riverpod: ^2.0.2
  cloud_firestore: ^4.0.2
  google_mobile_ads: ^2.1.0

</details>Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

Actual Results:

[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.2, which depends on
          Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
            Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
              FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
                  GoogleAppMeasurement (= 10.0.0)

        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
            GoogleAppMeasurement (< 10.0, >= 7.0)

**Comment by huycozy** [comment]
Hi @andrew-a-hall 
This is a known issue at https://github.com/googleads/googleads-mobile-flutter/issues/673 that has been fixed recently with PR https://github.com/googleads/googleads-mobile-flutter/pull/674. You may need to wait for a new hotfix version for this update. 
Closing this issue as a duplicate.

**Comment by andrew-a-hall** [comment]
Thanks for this. Any idea when the next minor release might be?

**Comment by Charlinjoeaht** [comment]
I am waiting for the next release too

**Comment by guiguito** [comment]
same here waiting for the release to update all firebase dependencies. Works ok on android.
