### ISSUE TITLE
UMP SDK cannot retrieve consent info and form on Android

### ISSUE THREAD

**Issue by c0ffeec0der** [googleads/googleads-mobile-flutter#678]
Hello,

I am trying to implement EU consent as this [documentation](https://developers.google.com/admob/flutter/eu-consent)

The current condition is:

1. Admob account approved
2. App status in review
3. GDPR message created
4. method isConsentFormAvailable() return false

I had earlier [conversation ](https://groups.google.com/g/google-admob-ads-sdk/c/CDRJENy8k_U)with mobileadssdk team and they refer to this channel.

According to them that it should work with App status in review. But why isConsentFormAvailable() return false?

Kindly advise

Thank you

## Plugin Version

2.1.0

## Steps to Reproduce

Create as per [documentation](https://developers.google.com/admob/flutter/eu-consent)

**Expected results:** GDPR message shown

**Actual results:** isConsentFormAvailable() return false

**Comment by huycozy** [comment]
Hi @c0ffeec0der This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/660.
Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by huycozy** [comment]
Hi @c0ffeec0der 
From our discussion at https://github.com/googleads/googleads-mobile-flutter/issues/660#issuecomment-1293077078, I reopen this issue as it's reproducible on Android. Labeling the issue for further investigation. Thank you!

- Sample code: Can use sample code at https://github.com/googleads/googleads-mobile-flutter/issues/660#issuecomment-1270214942 but need to update Admob App ID with the production one due to this [another issue](https://stackoverflow.com/questions/68457966/failed-to-read-publishers-account-configuration-please-check-your-configured-a) when using the test App ID. 

- Log:
```bash

D/UserMessagingPlatform( 4936): Stored info not exists: IDFA_freqCapNumViews
D/UserMessagingPlatform( 4936): Stored info not exists: IABTCF_TCString
D/UserMessagingPlatform( 4936): Stored info not exists: IABTCF_AddtlConsent
...
AAT error: Invalid response from server.

```

**Comment by c0ffeec0der** [comment]
@huycozy While this is being fixed, How do we go about getting EU consent for production? Please advise, Thank you

**Comment by jjliu15** [comment]
Hi @c0ffeec0der, does the form get shown if you use `ConsentDebugSettings` with [`DebugGeography. debugGeographyEea`](n/packages/google_mobile_ads/lib/src/ump/consent_request_parameters.dart#L66)?

My understanding is that you won't get shouldn't get shown a GDPR form unless you're in EU, unless you override using `DebugGeography`.

**Comment by c0ffeec0der** [comment]
Hi @jjliu15 

The form does not get shown with [DebugGeography. debugGeographyEea](https://github.com/googleads/googleads-mobile-flutter/issues/n/packages/google_mobile_ads/lib/src/ump/consent_request_parameters.dart#L66)

I have added you to [repo example](https://github.com/c0ffeec0der/test_ump)

That's why it's confusing why it is not working..

**Comment by jjliu15** [comment]
Can you try adding `ConsentInformation.instance.reset();` before calling `ConsentInformation.instance.requestConsentInfoUpdate()`?

**Comment by jjliu15** [comment]
And also share the logcat?

**Comment by c0ffeec0der** [comment]
Yep, just added the [logcat](https://github.com/c0ffeec0der/test_ump/blob/main/logcat/log_01.log)

**Comment by jjliu15** [comment]
I see the error message:
```
11-13 12:29:56.787  5910  5948 I flutter : AAT error: Instance of 'FormError'
```

Could you print out the errorCode and message of the FormError?

**Comment by c0ffeec0der** [comment]
Hi @jjliu15 It's,

'11-15 23:16:02.923  6475  6507 I flutter : AAT error: 1 - Invalid response from server.'

Doesn't give much info unfortunately.. Here's the latest [log](https://github.com/c0ffeec0der/test_ump/blob/main/logcat/log_03.log)

Question, are you seeing the same result on your end with another dummy live account?

**Comment by c0ffeec0der** [comment]
@jjliu15, just wondering if you are seeing the same error on your end using the [sample repo](https://github.com/c0ffeec0der/test_ump)? But you need to use your live admob dummy app to test

I think @huycozy might have test it and see the same error in this [thread](https://github.com/googleads/googleads-mobile-flutter/issues/678#issuecomment-1293257455)

Please advise. Thanks

**Comment by c0ffeec0der** [comment]
@jjliu15 @huycozy It's working now. I think the issue is caused by admob account not approved yet. I just tested it once again after approved and its working :) Thank you :)
