### ISSUE TITLE
Issue in flutter native video ads

### ISSUE THREAD

**Issue by Shubh-Murtadak** [googleads/googleads-mobile-flutter#688]
In some of the devices play button does not work and  Ad keeps running in the background. I have attached a video for reference. For sample code and flutter doctor -v output please refer [issue 683](https://github.com/googleads/googleads-mobile-flutter/issues/683#issuecomment-1298162118)
 I have attached a video for reference.
 Device - oneplus 10R (ANDROID), Redmi y3 (Android 10)
 

https://user-images.githubusercontent.com/105348249/199665440-4709b872-4410-47fb-bc43-c28104c2d99d.mp4

**Comment by huycozy** [comment]
Hi @Shubh-Murtadak 
I can not reproduce this issue on my Android devices with your sample code at [https://github.com/Shubh-Murtadak/googleads.git ](https://github.com/Shubh-Murtadak/googleads.git). Can you try running [Android native sample code](https://github.com/googleads/googleads-mobile-android-examples) on your devices and check if the issue persists?
