### ISSUE TITLE
iOS ERROR:  [!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK"

### ISSUE THREAD

**Issue by wadychou** [googleads/googleads-mobile-flutter#707]
google_mobile_ads: ^2.3.0
Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm,
Xcode Version 14.0   (Minimum Deployments: iOS 11.0)
MacOS 12.6  M1

## Error
```
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
      In Podfile:
        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (~> 9.13)

    None of your spec sources contain a spec satisfying the dependency: `Google-Mobile-Ads-SDK (~> 9.13)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.
```
![1111](https://user-images.githubusercontent.com/3362060/203756491-cd657c89-97ba-4c92-803b-f77fb3135b37.png)

**Comment by huycozy** [comment]
Hi @wadychou 
Please try following the instructions from the log by executing `pod repo update` and try again to see if the issue still persists.

**Comment by wadychou** [comment]
> Hi @wadychou Please try following the instructions from the log by executing `pod repo update` and try again to see if the issue still persists.

I've tried all of the following and it doesn't work.
1 -------
pod repo update

2------- 
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install
flutter clean
flutter pub get

3------
sudo arch -arm64 gem pristine ffi 
pod install
flutter clean
flutter pub get

**Comment by huycozy** [comment]
@wadychou It looks like a (CocoaPods + Mac M1) issue rather than Ads plugin issue. Can you try running [this sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) to see if the issue can be reproducible?

Also, please check workaround in this https://github.com/googleads/googleads-mobile-flutter/issues/303#issuecomment-1138597539 or find an applicable workaround/solution there.

**Comment by wadychou** [comment]
I have ready fix it, look below.

1. use Rosetta to open Terminal

2. cd into iOS folder

3. sudo arch -x86_64 gem install ffi

4. arch -x86_64 pod repo update

5. arch -x86_64 pod install
