### ISSUE TITLE
How do we use banner in this case

### ISSUE THREAD

**Issue by wadychou** [googleads/googleads-mobile-flutter#721]
# My Routes
HomePage -> page1
HomePage -> page2
HomePage -> page3
HomePage -> page4
HomePage -> page5
......

# My case
All the page will show a banner ad 

# What should I do?
Can I create a public BannerAd() and serve it to each page?

**Comment by NiuXiaoGuang** [comment]
I want to know how you solved it

**Comment by Wenutz** [comment]
I m curious too, If a user navigates quickly to and from pages it will create adrequest in less than the recommended 60 seconds. Does the plugin handle that or do we have to limit the request ourselves?
