### ISSUE TITLE
I got disabled my admob account again with just using this plugin and normal trafic

### ISSUE THREAD

**Issue by dopinco** [googleads/googleads-mobile-flutter#737]
Hi guys

is there anyone who got a disabled account because of invalid traffic? and i don't know why , our app is new in the market but they blocked my admob account while we have a normal and real traffic

seriously we need to know what happened and what need to do? because there isn't anyone from google to answer us.

Thanks for your times

**Comment by dopinco** [comment]
> 

yes

**Comment by huycozy** [comment]
@dopinco Can you provide email content that may contain the cause of the issue? Usually, this kind of issue needs to have stakeholders to help verify the cause, so it may be outside the scope of the plugin. 

Moreover, this plugin is working as expected per feedback from other developers. So, in case you are thinking this is a plugin issue, please investigate and give more information about this.

Also, please see this https://github.com/googleads/googleads-mobile-flutter/issues/155#issuecomment-820617086 for more information.

**Comment by appinteractive** [comment]
I do have the same issue, that is happening without any reason on our side, using only test ads on our devices and in development.

Might not be related but what I did saw was requests from non-existing app versions on the days of deactivations. I even don't get how that is possible.
