### ISSUE TITLE
Error in the console: https://imasdk.googleapis.com/admob/sdkloader/versioned/nx.286.0/native_video_lima.js:936

### ISSUE THREAD

**Issue by saddem123** [googleads/googleads-mobile-flutter#739]
## Plugin Version
2.3.0

## Log

A problem occure sometimes when running native ads
`E/Ads     ( 2719): JS: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map') (https://imasdk.googleapis.com/admob/sdkloader/versioned/nx.286.0/native_video_lima.js:936)
I/chromium( 2719): [INFO:CONSOLE(936)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')", source: https://imasdk.googleapis.com/admob/sdkloader/versioned/nx.286.0/native_video_lima.js (936)`

**Comment by huycozy** [comment]
Hi @saddem123 
Which platform does the issue occur on?

And does this issue happen when running on [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Also, please provide the complete error log as well.

Thank you!

**Comment by huycozy** [comment]
@saddem123 thanks for providing the sample code but when I run it, I don't see the above error log along with `build AdWidgetContainer` log (that is being printed from your AdWidgetContainer) also. There is only a list of videos. Is there something missing to reproduce this issue?

https://user-images.githubusercontent.com/104349824/211977354-398e46e6-4f1c-448a-b476-8d0dd4947f1e.mp4

I'm using `Samsung Galaxy Tab A7 Lite, Android 13 OneUI 5.0, SM-T225`. 

Can you provide the platform does the issue occur and your device info? (OS, model). Thanks!

**Comment by saddem123** [comment]
@huycozy  this issue is no longer occured

**Comment by huycozy** [comment]
Closing the issue as above confirmation. Thanks for your response.

**Comment by saddem123** [comment]
@huycozy  The error happens again and no video ads show even though I'm using  [Native Advanced Video] public ad unit and when I run using android studio I get those errors on the console. I should mention that image content is shown (It's not a video).

`E/Ads: JS: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map') (https://imasdk.googleapis.com/admob/sdkloader/versioned/nx.286.0/native_video_lima.js:936)
I/chromium: [INFO:CONSOLE(936)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')", source: https://imasdk.googleapis.com/admob/sdkloader/versioned/nx.286.0/native_video_lima.js (936)
W/AudioCapabilities: Unsupported mime audio/ac4
W/AudioCapabilities: Unsupported mime audio/x-ima
W/AudioCapabilities: Unsupported mime audio/x-ape
W/AudioCapabilities: Unsupported mime audio/eac3-joc
W/AudioCapabilities: Unsupported mime audio/mpeg-L1
W/AudioCapabilities: Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/x-ms-wma
I/.test_ads_clea: Background concurrent copying GC freed 49136(3`

And I Edit code for reproduction and it's shows now 100%
**Reproduction:** [Reproduction](https://github.com/saddem123/Native-ads-impelemntation). run the android project with android studio to get the error
