### ISSUE TITLE
Request Error: No ad to show from all configured ad networks for test and real ad unit id

### ISSUE THREAD

**Issue by OlehMysak** [googleads/googleads-mobile-flutter#743]
Throws out an error code=9 message=Request Error: No ad to show from all configured ad networks for all types of ads and with all IDs (both real and test). Although everything worked yesterday and nothing changed
Here my code
`NativeAd? _ad;
  bool isAdLoaded = false;

  @override
  void initState() {
    super.initState();

    _ad = NativeAd(
      adUnitId: AdHelper.nativeAdUnitId,
      factoryId: 'listTile',
      request: AdRequest(),
      listener: NativeAdListener(
        onAdLoaded: (ad) {
          setState(() {
            _ad = ad as NativeAd;
            isAdLoaded = true;
          });
        },
        onAdFailedToLoad: (ad, error) {
          ad.dispose();
          print('Ad load failed (code=${error.code} message=${error.message})');
        },
        onAdOpened: (Ad ad) => print('Ad opened.'),
        onAdClosed: (Ad ad) => print('Ad closed.'),
        onAdImpression: (Ad ad) => print('Ad impression.'),
        onAdClicked: (Ad ad) => print('Ad clicked'),
      ),
    );
    loadNativeAd();
  }

  void loadNativeAd() {
    _ad?.load();
  }

  @override
  void dispose() {
    _ad?.dispose();

    super.dispose();
  }`

## Plugin Version

2.3.0

## Steps to Reproduce

Setup the project and run

**Expected results:** see the ads
**Actual results:** `Ad load failed (code=9 message=Request Error: No ad to show from all configured ad networks.)

RewardedAd failed to load: LoadAdError(code: 9, domain: com.google.admob, message: Request Error: No ad to show from all configured ad networks., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})
`

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-x64, locale en-UA)
    • Flutter version 3.3.8 on channel stable at /usr/local/Caskroom/flutter/3.3.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (9 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/centr/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code-2.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile) • 9B65634D-22BE-4D9A-8369-C5CAF88D2C00 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • iPhone 14 Pro (mobile)              • 7B9785BA-61A2-4C2B-89BC-CBC04774DD7A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huycozy** [comment]
Hi @OlehMysak
Can you try running the [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) that contains NativeAd sample at [reusable_inline_example.dart](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/reusable_inline_example.dart) can check if the issue still persists or not?
Thanks!

**Comment by OlehMysak** [comment]
@huycozy there is an update, when I use vpn and choose Poland or another European country, everything is ok, only rewarded ad does not load, and others are displayed, and when I am without vpn from a Ukrainian ip, then this error continues, although as I said, everything was fine yesterday and without vpn

**Comment by huycozy** [comment]
@OlehMysak Does the issue happen on Android or iOS device? 

If it's Android, please try running [googleads-mobile-android-examples](https://github.com/googleads/googleads-mobile-android-examples) and check if you get the same error.

If it's iOS please try with [googleads-mobile-ios-examples](https://github.com/googleads/googleads-mobile-ios-examples)

**Comment by OlehMysak** [comment]
@huycozy yes, it happen on both devices.

**Comment by huycozy** [comment]
@OlehMysak I guess this is network or ads network issue. So please try running two samples at https://github.com/googleads/googleads-mobile-flutter/issues/743#issuecomment-1384821844 and check if you have the same error.
