### ISSUE TITLE
Update admob native documentation. 

### ISSUE THREAD

**Issue by bensonarafat** [googleads/googleads-mobile-flutter#745]
## Use case
Please can the doc be updated to swift and kotlin on how to use the Native ads unit
thanks.

**Comment by huycozy** [comment]
@bensonarafat thanks for filing the issue. 
I see there are some open issues addressing the case you described #461, #52.

Closing this issue as a duplicate, so please follow up on these for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by bensonarafat** [comment]
@huycozy 
Alright thanks
