### ISSUE TITLE
Programmatically click on Interstitial banner close button in integration tests

### ISSUE THREAD

**Issue by apaolino** [googleads/googleads-mobile-flutter#748]
Hi, 
I'm using google_mobile_ads: ^2.3.0 and I was wondering if there is any way to close an interstitial banner in a integration test (using integration_test lib).
On Android I can see that my tests continue to execute despite the banner is shown and they can successfully finish, as it would be transparent to the tests. On iOS, instead, seems like the execution of tests holds and they continue just once I manually click on the close button.

**Comment by darshankawar** [comment]
@apaolino 
Currently it is not possible to interact with native elements using integration_test package. See [this](https://github.com/flutter/flutter/issues/86295) issue for your reference and I suggest you to follow-up in it for further updates.
Closing from here, as this is not specific to ads package or particular ad.
