### ISSUE TITLE
🐛 Native ad performance on android in listview.builder is painful

### ISSUE THREAD

**Issue by zaidkazi** [googleads/googleads-mobile-flutter#75]
Hey guys not sure if anyone else is having issues with an ad in a listview but my app loses the buttery effect as soon as i add a native ad into my list. Any suggestions?

**Comment by GeceGibi** [comment]
Yea. same here.

**Comment by adrienbaron** [comment]
I'm seeing the same issue on Android. Running the app with Ads, even built in production mode really impact performance, it spams the logs with:
```
D/AudioManager(28731): getStreamVolume packageName=com.clashofstats, index=0, streamType=3
D/AudioManager(28731): getStreamVolume packageName=com.clashofstats, index=0, streamType=3
D/AudioManager(28731): getStreamVolume packageName=com.clashofstats, index=0, streamType=3
D/AudioManager(28731): getStreamVolume packageName=com.clashofstats, index=0, streamType=3
```

Those logs:
- Appear after you display an Ad Banner
- Are fired over 10 times/seconds when scrolling a view with Ad Banners
- Are fired every second when standing still (not scrolling)

I'm not sure this is linked but I'd assume this constant polling might impact performance?

Device: [Oppo A72](oppo.com/uk/smartphone-a72/specs/)
Android version: 10.0
Plugin version: `google_mobile_ads: ^0.11.0+4`

**Comment by patman1706** [comment]
Hi,
i'm experiencing the same behavior (very chatty logs even when not scrolling (see below).
did you get to an acceptable solution ? 
those logs seems to downgrade dramatically the performances ...
i have a listeview and under there is an Ad banner.

thanks in advance...

Flutter version 2.0.2
Android SDK version 29.0.3
google_mobile_ads: ^0.12.1+1

D/AudioManager(25577): getStreamVolume() streamType= 3 Request Package= com.example.app
I/chatty  (25577): uid=10599(com.example.app) AdWorker(Defaul identical  9 lines
D/AudioManager(25577): getStreamVolume() streamType= 3 Request Package= com.example.app
D/AudioManager(25577): getStreamVolume() streamType= 3 Request Package= com.example.app
D/AudioManager(25577): getStreamVolume() streamType= 3 Request Package= com.example.app

**Comment by blasten** [comment]
We have added a flag to the Flutter master channel that helps improve the performance. 

It's not a perfect fix since the Ad may be a few frames behind the Flutter frame, but depending on the layout you use, it could be useful.  

Please try it out, and let us know if the performance is improved.

To use this flag, set `PlatformViewsService.synchronizeToNativeViewHierarchy(false)`.  For example: 

```dart
import 'package:flutter/services.dart';

void main() {
   PlatformViewsService.synchronizeToNativeViewHierarchy(false);
   runApp(MyApp());
}
```

I'm closing this issue, and moving the conversation to: https://github.com/googleads/googleads-mobile-flutter/issues/269
