### ISSUE TITLE
await MobileAds.instance.initialize(); slow down the app launch - Flutter

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-flutter#750]
## Plugin Version
2.2.0

## Details
I'm programming in Flutter.

If I add "await MobileAds.instance.initialize();" in the "main" between "WidgetsFlutterBinding.ensureInitialized();" and "runApp" slows down the app startup by a lot (in my tests it slows down the startup by at least 2-3 seconds). I also got a warning in the Google Play Store pre-launch report that the launch was slow in one of their tests.

The alternative would be not to add the word "await", this would speed up execution, but if I load an ad immediately then I shouldn't call initialization at all since it is done automatically when an ad is called.

**Comment by darshankawar** [comment]
@Francesco-FL 
There's similar issue open describing your case : https://github.com/googleads/googleads-mobile-flutter/issues/429
I suggest you to follow-up in that issue and you may also share your findings in that issue for better tracking.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
