### ISSUE TITLE
[Feature Request] Opt-out option for `visibility_detector` workaround

### ISSUE THREAD

**Issue by ilkanimal** [googleads/googleads-mobile-flutter#754]
With the Flutter 3.7 stable release, [the issue](https://github.com/googleads/googleads-mobile-flutter/issues/580) requiring the [visibility_detector workaround](https://github.com/googleads/googleads-mobile-flutter/pull/610) is [expected to be](https://github.com/googleads/googleads-mobile-flutter/issues/580#issuecomment-1386899604) resolved with [this fix](https://github.com/flutter/flutter/pull/114103).

## Use case
An opt-out option needs to be added to get rid of the disadvantages of visibility_detector workaround for those who have upgraded the framework to the latest version.

## Proposal
A bool argument can be added for opt-out at any point in the API, or the plugin can programmatically select it according to the Flutter version.

**Comment by ilkanimal** [comment]
Hi @jjliu15, do you have a chance to check this issue before publishing 2.4.0, according to my checks, the impression issue is fixed in new flutter stable release and this workaround causes almost 4 times decrease in ad show rates.

**Comment by llooz** [comment]
I've followed the various issues and good work about this to everyone!
Flutter 3.7 is out, is there any ETA on the 2.4 release?

**Comment by westy92** [comment]
2.4.0 was released 5 days ago.
https://pub.dev/packages/google_mobile_ads/changelog

**Comment by timothyhoang-google** [comment]
Version 2.4 adds a new flag, AdWidget.optOutOfVisibilityDetectorWorkaround. Setting this to true lets you opt out of the fix added for https://github.com/googleads/googleads-mobile-flutter/issues/580, which was resolved in Flutter 3.7.0.
