### ISSUE TITLE
[📚] Adaptive banners

### ISSUE THREAD

**Issue by davidmartos96** [googleads/googleads-mobile-flutter#76]
Is there any guideline on how to use adaptive banners? There could be a method that exposes a native call to:
 `AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(this, adWidth)`

**Comment by RyanRamchandar** [comment]
I created my own method to get the adaptive height of a banner ad, just pass in the screen dimensions.

```dart
  // Adaptive banner height (max: 15% screen height, min: 50 dp)
  static AdSize adaptiveBannerAdSize(double width, double height) {
    final double minAdaptiveHeight = 50;
    final double maxAdaptiveHeight = height * 0.15;
    final double ratio = 13 / 2; // from my own measurements
    final double adaptiveHeight = (width / ratio).clamp(
      min(minAdaptiveHeight, maxAdaptiveHeight),
      max(minAdaptiveHeight, maxAdaptiveHeight),
    );

    final adSize = AdSize(
      width: width.toInt(),
      height: adaptiveHeight.toInt(),
    );
    print('📐 Banner ad size: ${adSize.width}x${adSize.height}');

    return adSize;
  }
```

**Comment by davidmartos96** [comment]
@RyanRamchandar Thank you for the snippet! I've tried it on a tablet and the ad it's pretty tall though. I wonder if it matches the official implementation. 
I've constrained the width of the ad to 500 dp for now.

**Comment by RyanRamchandar** [comment]
Constraining the width is one option, just take note of the guideline:
> Ensure that your ad view background is opaque to be compliant with AdMob policies when smaller ad sizes serve that do not fill the ad slot.

The method above respects the following:
> Anchored banner height is never larger than 15% of the device's height and never smaller than 50 points. 

https://developers.google.com/admob/ios/banner/adaptive#implementation_notes

However, I did make an assumption on the ratio. I couldn't find an official value for it.
```dart
final double ratio = 13 / 2; // from my own measurements
```

**Comment by bdlukaa** [comment]
I use this plugin for this: https://pub.dev/packages/native_admob_flutter

It supports Adaptive Banners by default. It also supports all the ad formats this plugin supports + App Open and Rewarded Interstitial Ads
