### ISSUE TITLE
Google Mobile Ads SDK Developers Privacy • Terms Flutter App crashes when "google_mobile_ads: ^2.3.0" is added into pubspec.yaml

### ISSUE THREAD

**Issue by Mrugesha811** [googleads/googleads-mobile-flutter#763]
pubspec.yaml like this
===================
name: game_truth_dare
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  get_storage: ^2.0.3
  fluttertoast: ^8.1.2
  flutter_fortune_wheel: ^1.2.0
  lottie: ^2.2.0
  flutter_svg: ^1.1.6
  google_mobile_ads: ^2.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf

===================

main.dart like this
=====================
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // status bar color
    statusBarIconBrightness: Brightness.light
  ));
  await GetStorage.init();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}
=====================

meanifest.xml file like this
======================
            <meta-data
                android:name="com.google.android.gms.ads.APPLICATION_ID"
                android:value="ca-app-pub-3940256099942544~3347511713"/>
======================

android/app/build.gradle file like this
======================
android {
    compileSdkVersion 32
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.coderappstudios.game_truth_dare"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion 32
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.multidex:multidex:2.0.1"
}
====================

**Comment by huycozy** [comment]
Hi @Mrugesha811 
Does this issue happen when running [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)? 

If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In this case, it would be appreciated if you could create a Github repository and share it here. Thanks!

**Comment by Mrugesha811** [comment]
i have solved by refering library's example and do same as in my app it's works fine also chnage in pubspec.yaml file like this : 

environment:
  sdk: '>=2.18.6 <3.0.0'
to this
environment:
  sdk: '>=2.12.0 <3.0.0'

so i close the issue.
