### ISSUE TITLE
onPaidEvent not working properly

### ISSUE THREAD

**Issue by adamlamoglia** [googleads/googleads-mobile-flutter#770]
## Plugin Version

^2.3.0

## Steps to Reproduce

1. Import and implement goggle_mobile_ads on app
2. flutter run --release or build an .aab and put in internal test

**Expected results:** See events sended to third party sdk when onPaidEvent callback is called

**Actual results:**  Events are not sent. In reality, the onPaidEvent callback never occurs.

this is the code I'm using for the reward ad, for example

<details>
 
 
   
    RewardedAd.load(
      adUnitId: adUnitRewarded,
      request: const AdRequest(),
      rewardedAdLoadCallback: RewardedAdLoadCallback(
        onAdLoaded: (RewardedAd ad) {
          _rewardedAd = ad;
          ad.onPaidEvent = (ad, valueMicros, precision, currencyCode) {
            debugPrint(
                'onPaidEvent: $valueMicros - $precision - $currencyCode - ${ad.responseInfo!.adapterResponses!.length}');
            for (var response in ad.responseInfo!.adapterResponses!) {
              debugPrint(
                  'Adapter response: ${response.adapterClassName} - ${response.adSourceName} - ${response.adSourceInstanceName} - ${response.description} ');
                  
             ##SEND TO THIRD PARTY SDK THE AD REVENUE
             
            }
          };
          ##SEND TO THIRD PARTY SDK AD IMPRESSION
        },
        onAdFailedToLoad: (LoadAdError error) {
          Future.delayed(const Duration(seconds: 5), () => _loadRewarded());
        },
      ),
    );

</details>

**Comment by huycozy** [comment]
@adamlamoglia When I try with [google_mobile_ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and add above `onPaidEvent`, I still can see `onPaidEvent` and `Adapter response` log from the console. 
Please retry on the sample code and check if you also see the logs.

Also, what is the 3rd party SDK you are using for sending the data? You should also check that SDK (contact or find the existing issues on the repository) as it can also be the cause of the issue.

**Comment by adamlamoglia** [comment]
Hey @huycozy, i'm using Singular as 3rd party SDK. But also there is no log in app showing up. I will test with the sample code

**Comment by adamlamoglia** [comment]
@huycozy i generate two builds, one in debug mode, and another in release mode. In the debug build, the events are normally sended to singular SDK. But in release mode, there is no event sended.. somehow, ads in production do not make the onPaidEvent method work.

in the google_mobile_ads code it says:

/// Available for allowedlisted accounts only.

is there any step to enable this in production?

![image](https://user-images.githubusercontent.com/26827217/218742367-d8034894-66d8-4b6a-873b-f66bc0f4402d.png)

**Comment by adamlamoglia** [comment]
@huycozy i found it!
[https://support.google.com/admob/answer/11322405](url) 

i was missing the point 2. in **impression-level ad revenue**

![image](https://user-images.githubusercontent.com/26827217/218747888-594450a7-15a4-4015-bce7-662b8d50a83f.png)

Thank you!
