### ISSUE TITLE
App Open Ad video autoplay in full screen when after loaded.

### ISSUE THREAD

**Issue by andj207** [googleads/googleads-mobile-flutter#777]
google_mobile_ads: ^2.3.0
Flutter 3.7.3
Tools • Dart 2.19.2 • DevTools 2.20.1

Everytime the ad preloaded with a video type, the video will automatically open and play in fullscreen.

Step to reproduce:
1. Open the app the first time
2. Close the app to the background and reopen. The app open ad will show as normal, and will be preloaded a new one.
3. Close the ad. When the new ad is preloaded with a video type, the video will automatically play in full screen.

Log: 
flutter: 2023-02-18T08:55:13.839276	D	AdmobAppOpenAdSource._loadAd.<ac>:	 Admob AppOpenAd loaded

See the attach screenshots.

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-18 at 08 55 24](https://user-images.githubusercontent.com/3950215/219825738-768cfd6c-da0b-4308-bcbc-d96198b1ae83.png)

**Comment by huycozy** [comment]
Hi @andj207 
Can you provide a recorded video for this issue? 

And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. You may use [plugin sample code - app open ad](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/app_open_example) to check this as well.

**Comment by andj207** [comment]
Hi @huycozy here is the sample code. I use the app open test ad unit id from here https://developers.google.com/admob/android/test-ads. In this sample code, it not always preloads ad with a video type but when it does, the video will be played automatically in full screen. (In my real app code, video ad preloaded frequently)

Screenshot is the video ad that happens in full screen when it is preloaded.
![Simulator-Screen-Shot---iPhone-14-Pro---2023-02-21-at-08 36 42](https://user-images.githubusercontent.com/3950215/220228557-95f8bcde-40cd-4b89-8918-a64c1f00744d.png)

Sample code:
[admobads_sample_plugin.zip](https://github.com/googleads/googleads-mobile-flutter/files/10788854/admobads_sample_plugin.zip)

**Comment by b4nghh** [comment]
@andj207 I got the same issue. Did you find a solution?

**Comment by trongtindev** [comment]
@huycozy I got the same issue @andj207

- Use [app_open_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/app_open_example)
- Video [https://vimeo.com/837837490](https://vimeo.com/837837490?share=copy)
- Test on iPhone 8 Plus (Debug & Release mode)
- Android and iOS simulator no problems.

1. Launch app, wait ad loaded
2. Close the app to the background and reopen.
3. Close the ad, wait. When the new ad is preloaded with a video type, the video will automatically play in full screen.

```
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Signing iOS app for device deployment using developer identity: "Apple Development: *** (***)"
Xcode build done.                                           14.1s
(lldb) 2023-06-20 14:50:03.847143+0700 Runner[9712:2974000] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
<SKPaymentQueue: 0x280c3efb0>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
 - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-3940256099942544~1458002511
 - <Google>[I-ACS023007] Analytics v.101100000 started
 - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
 - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
 - <Google>[I-ACS023012] Analytics collection enabled
Connecting to VM Service at ws://127.0.0.1:50666/-KBjlNNe0RY=/ws
<Google> To get test ads on this device, set:
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"d5edbe5df16d2a660e4eb17f5fd98182" ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ "d5edbe5df16d2a660e4eb17f5fd98182" ]
<Google> Note that test device identifiers may be reset when uninstalling and reinstalling the application.
flutter: Instance of 'AppOpenAd' loaded
flutter: New AppState state: AppState.background
flutter: New AppState state: AppState.foreground
flutter: Instance of 'AppOpenAd' onAdShowedFullScreenContent
flutter: Instance of 'AppOpenAd' onAdDismissedFullScreenContent
flutter: Instance of 'AppOpenAd' loaded
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x11c0711a0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=9717, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}>
[ProcessSuspension] 0x11c039cb0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=9718, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}>
[ProcessSuspension] 0x11c039d00 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=9712, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}>
[ProcessSuspension] 0x11c039d50 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=9716, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}
```

**Comment by huycozy** [comment]
Sorry for responding late, @trongtindev.
I retry this on my device (iPhone 7, iOS 15.7.2) several times, but can't reproduce the issue with video ad (it always load text ad). 

<details>
<summary>Demo without reproducing issue</summary>

https://github.com/googleads/googleads-mobile-flutter/assets/104349824/441f90af-464e-47fd-93dc-0955f4cc8956

</details>

Since you can reproduce the issue, can you please check iOS native [AppOpenExample](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/admob/AppOpenExample) to see if the issue also occurs there?

Also, does the issue happen on a physical Android device?

**Comment by huycozy** [comment]
@trongtindev It seems the bot is not working well and there is no response from the OP. Would you mind file a new issue for this?
