### ISSUE TITLE
Requesting Linux, MacOS and Windows support

### ISSUE THREAD

**Issue by KristijanZic** [googleads/googleads-mobile-flutter#779]
I'm developing a cross platform app and I'm supporting them all but there is a big issue and frankly vacuum in the ad space. There is literally no options for monetisation via ads on the flutter desktop platform.

Please add support for Linux, MacOS and Windows platform so flutter developers and companies could monetise their apps via ads.

**Comment by huycozy** [comment]
Hi @KristijanZic 
There's an open issue addressing the case you described https://github.com/googleads/googleads-mobile-flutter/issues/525. Even though the issue's title is `Support Ads for Windows platform`, OP also mentioned other platforms too. I will update the label corresponding to this. 

You can leave there your comment and react an upvote to the original comment will help to raise the issue. Closing as a duplication, so please follow up on it for further updates.
