### ISSUE TITLE
🐛 onAdFailedToLoad() argument "error code" different between android and ios?

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#79]
## ios

https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode
GADErrorInvalidRequest = 0
GADErrorNoFill = 1
GADErrorNetworkError = 2

### old

https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest
ERROR_CODE_INTERNAL_ERROR 0
ERROR_CODE_INVALID_REQUEST 1
ERROR_CODE_NETWORK_ERROR 2

### new

https://developers.google.com/android/reference/com/google/android/gms/ads/package-summary

cant find

**Comment by peterweb2005** [comment]
## Search result

### ios

Search results for GADErrorCode
Did you mean: GETErrorCode site:developers.google.com/admob/ios/
GoogleMobileAds Framework Reference | iOS | Google Developers
Google Developers › Google AdMob › Mobile Ads SDK (iOS)
GADErrorCode. enum GADErrorCode : NSInteger {}. NSError codes for GAD error domain.

<< and more>>

### android

Search results for GADErrorCode
Did you mean: GETErrorCode site:developers.google.com/android/
No Results
Search for GADErrorCode on Google

**Comment by jjliu15** [comment]
The plugin just passes the error codes directly from GMASDK, which are different between iOS and Android.

Android error codes can be seen here: https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#constant-summary

The link you shared contains the iOS error codes: https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode
