### ISSUE TITLE
AdWidget sometimes does not show AdChoices icon

### ISSUE THREAD

**Issue by StevenHuang74832** [googleads/googleads-mobile-flutter#795]
## Plugin Version

google_mobile_ads 2.3.0

## Steps to Reproduce

We present NativeAd in our app's list or grid widget, but for some specific ads, the AdChoices icon is not shown.

This happens on both Android and iOS, and the ads without AdChoices icon are mostly for game/dating app.

In Android, the native layout as below:

<com.google.android.gms.ads.nativead.NativeAdView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/native_ad_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/ad_media_bg"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.gms.ads.nativead.MediaView
            android:id="@+id/ad_media"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:alpha="0"/>

        <Button
            android:id="@+id/ad_call_to_action"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/transparent"
            android:visibility="visible"/>

    </FrameLayout>

</com.google.android.gms.ads.nativead.NativeAdView>

**Expected results:** The AdChoices icon should always show.

**Actual results:** The AdChoices icon may not show with specific ads.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @StevenHuang74832 
Please check these answers for more information:

- https://github.com/googleads/googleads-mobile-android-examples/issues/136#issuecomment-423591939
- https://stackoverflow.com/questions/68692828/admob-nativ-ads-not-showing-adchoice-icon

Per the explanation on those answers, you should try your own ad unit ID. Closing this from here. If you still experience this issue with real ad IDs, please write in the comments and I will reopen it. Thanks!

**Comment by huycozy** [comment]
I reopen for further discussion. 

Can you please confirm this issue is only reproducible on Flutter apps? Does it also happen on non-Flutter apps if any?

The scope of this plugin is only allowing to set `AdChoicesPlacement` so I think this problem is out-of-scope that it can be supported (also see this [SO answer](https://stackoverflow.com/a/68827788/5921933)).
