### ISSUE TITLE
we can facing issue when use as fork

### ISSUE THREAD

**Issue by nirajakbari44** [googleads/googleads-mobile-flutter#800]
error:- pubspec. yaml not found in this project.

how to use this package as a fork in a flutter please tell me.

**Comment by huycozy** [comment]
Hi. It looks like you clone this plugin to your machine and run it from the root directory. If so, you should move to the [example project](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and run it on your device. 

Also, I would suggest you start with a simple flutter project first (see https://docs.flutter.dev/get-started/codelab) and then work with [ads plugin](https://pub.dev/packages/google_mobile_ads) later. 

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if you have similar questions. Closing for now.
