### ISSUE TITLE
[Proposal] Upgrade visibility_detector version

### ISSUE THREAD

**Issue by aintend-com** [googleads/googleads-mobile-flutter#807]
Please update the visibility_detector

**Comment by jj-hoeksema** [comment]
Hi, it does not directly conflict in my app, but I would like to update to visibility_detector 0.4.0 because of the improvements

**Comment by coderof19clc7** [comment]
I want to use the package markdown_widget and google_mobile_ads but they conflict because markdown_widget depends on visibility_detector ^0.4.0+2. So please update the dependencies of google_mobile_ads

**Comment by timothyhoang-google** [comment]
This looks like a Flutter request as opposed to a GMA Flutter plugin request.

Flutter 3.7 introduces a fix that makes usage of visibility_detector for impression tracking obsolete for the GMA Flutter plugin. We recommend updating to version 2.4, which adds a new flag, AdWidget.optOutOfVisibilityDetectorWorkaround. Setting this to true lets you opt out of the fix added for https://github.com/googleads/googleads-mobile-flutter/issues/580.

**Comment by coderof19clc7** [comment]
As what I see is that this package has nothing changed and it still conflict with markdown_widget because of difference in the version of dependency visibility_detector, why this issue marked as completed ? Actually i'm new to Github so please explain if I have anything misunderstand, thank you.

**Comment by coderof19clc7** [comment]
@huycozy do you guys have any plan on updating the visibility_detector dependency for this package ?

**Comment by huycozy** [comment]
@timothyhoang-google I think the `visibility_detector` should be upgraded to the latest version since it's conflicted with other packages. Users can use GMA Flutter plugin version 2.4 and above, but it's still being used `visibility_detector: ^0.3.3`. 

Meanwhile, for anyone facing the issue, you can use `dependency_overrides` as a workaround for this:
```
dependency_overrides:
  visibility_detector: ^0.4.0+2
```

**Comment by timothyhoang-google** [comment]
@huycozy - thanks for flagging this issue.

We will need to do another major version release to increase the min Flutter version required and increase the visibility detector version. @jjliu15 will work on this.

**Comment by mulderpf** [comment]
This is closed, but no fix is available for this issue yet...

**Comment by Knackynouille** [comment]
While waiting for the update you can add this :
google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter.git
      ref: 9dabf7b0d1865866f5deb6934f1ae510989c00e9
      path: packages/google_mobile_ads/
