### ISSUE TITLE
how to fix the native ads screen size?

### ISSUE THREAD

**Issue by ssorttang** [googleads/googleads-mobile-flutter#810]
Hi, I try to fix size native ads.

How to fix size TemplateType.medium?
The screen size is displayed differently for each smartphone model

I want to fix the native ads screen size.

this is my code.

==

late NativeAd _nativeAd;
  bool isAdLoaded = false;
  void _createNativeAd() {
    _nativeAd = NativeAd(
      adUnitId: AdMobService.nativeAdUnitId,
      factoryId: "listTile",
      request: const AdRequest(),
      nativeTemplateStyle: NativeTemplateStyle(
          **templateType: TemplateType.medium,**
      ),
      nativeAdOptions: NativeAdOptions(
        shouldRequestMultipleImages: true,
        mediaAspectRatio: MediaAspectRatio.any,
        adChoicesPlacement: AdChoicesPlacement.topLeftCorner,
        videoOptions: VideoOptions(
            clickToExpandRequested: true,
            customControlsRequested: false,
            startMuted: false),
      ),
      listener: NativeAdListener(onAdLoaded: (_) {
        // print('Ad Loaded');
        setState(() {
          isAdLoaded = true;
        });
      }, onAdFailedToLoad: (ad, error) {
        ad.dispose();
        // print(error.message);
      }, onAdClosed: ((ad) {
        // print('Ad Closed');
        // Navigator.pop(context, false);
      }), onAdClicked: ((ad) async {
        // print('Ad Clicked');
        // await Future<int>.delayed(Duration(seconds: 2));
        Navigator.of(dialogContext, rootNavigator: true).pop();
        // Navigator.pop(dialogContext, false);
        // Navigator.of(context, rootNavigator: true).pop();
        // Navigator.pop(context, false);
      })),
    );
    _nativeAd.load();
  }

**Comment by huycozy** [comment]
Please see:

https://github.com/googleads/googleads-mobile-flutter/blob/cd45ae935d42d5a67e155689d437212dbcf05ed5/packages/google_mobile_ads/lib/src/ad_containers.dart#L1067-L1070

If you don't use a template style, you can control the size with your own implementation by parent widget size and native ad xml layout. 

Closing as this is intentional and it is more of a `how-to` question rather than a bug or feature request.
