### ISSUE TITLE
New NativeTemplateStyle implementation has the same dynamic sizing issues as the previous Native API

### ISSUE THREAD

**Issue by ilkanimal** [googleads/googleads-mobile-flutter#811]
I filed [an issue](https://github.com/googleads/googleads-mobile-flutter/issues/442) over a year ago about the sizing issue in native ads, I won't post the same things here again.

Please review the [original issue](https://github.com/googleads/googleads-mobile-flutter/issues/442).

With this missing API, neither the old Native Ads API nor this NativeTemplateStyle API are usable for real life production scenarios.

**Comment by huycozy** [comment]
Closing as a duplicate of the linked issue. Please follow up on it for further updates. Thank you!
