### ISSUE TITLE
Warning about the missing cupertino_icons package when building an Android app with google_mobile_ads

### ISSUE THREAD

**Issue by aalex** [googleads/googleads-mobile-flutter#812]
If we use the `google_mobile_ads` package, when building and appbundle or apk for Android, it displays a warning if I haven't installed [cupertino_icons](https://pub.dev/packages/cupertino_icons).

Warning message:

```
Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
```

## To reproduce
- Create a flutter project
- Set up `google_mobile_ads` in that project
- Build an apk
- This warning appears

## To fix it
- Run `flutter pub add cupertino_icons`
- Rebuild the apk
- It shows no such warning anymore.

## Technical details
- Maybe `google_mobile_ads` should depend on `cupertino_icons` ?

**Comment by huycozy** [comment]
Thanks for filing the issue, @aalex 
As my understanding, you have removed the `cupertino_icons` package from the pubspec.yaml, right? And it works when you added it again. This is a [known issue](https://github.com/flutter/flutter/issues/119074) being tracked at Flutter repository, and please take a look at https://github.com/flutter/flutter/issues/119074#issuecomment-1404102436 for the case.

Closing this issue as it's not ads plugin issue, so please follow up on the linked issue for further updates. Thanks!
