### ISSUE TITLE
factoryId is not not being explained in docs

### ISSUE THREAD

**Issue by dario-digregorio** [googleads/googleads-mobile-flutter#816]
## Plugin Version
v2.4.0

## Steps to Reproduce

Follow the instructions of the docs:
https://developers.google.com/admob/flutter/native/templates

I'd like to use native templates. But when following the instructions using the `NativeAd` class, one parameter `factoryId` is missing. In the docs there is no mentioning for such a parameter although it is required. 
I am not sure where to get this `factoryId`

**Expected results:** To follow docs and having a working implementation 

**Actual results:** Steps unclear and parameter missing in example

**Comment by huycozy** [comment]
`factoryId` is an identifier for the factory that creates the Platform view. You should check [Native setups in Android and iOS](https://developers.google.com/admob/flutter/native/platforms) documentation. 
For a complete sample code, you may check [plugin example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example).

Closing this as it's not an ads plugin issue.

**Comment by rlee1990** [comment]
@huycozy how is this not an ads plugin issue if there is no documentation for this in the plugin docs but this is a required field. Also saying to check the example that also doesn't even show the issue in question as an example. This needs to be reopened.
