### ISSUE TITLE
App Open Ad  background is transparent ,how to setBackgroundColor

### ISSUE THREAD

**Issue by randomhuangpl** [googleads/googleads-mobile-flutter#819]
## Plugin Version
2.4.0

example1: https://support.google.com/admob/thread/190656724/app-open-ads-are-showing-with-the-app-content-as-background-in-android?hl=en
example2: https://groups.google.com/g/google-admob-ads-sdk/c/juKkCxHhzDQ/m/WY2SS0gpAAAJ

![image](https://user-images.githubusercontent.com/113404168/232025291-68e76558-0f14-4900-9be9-773d3ff47313.png)

![image](https://user-images.githubusercontent.com/113404168/232026107-35ba1e60-85bc-4329-bb15-7db841aac285.png)

**Comment by huycozy** [comment]
It looks like you should change it from native side. Please see [this](https://stackoverflow.com/a/70138014/5921933) if it can help. 
Also, as the [reply](https://groups.google.com/g/google-admob-ads-sdk/c/juKkCxHhzDQ/m/WY2SS0gpAAAJ) from the linked thread above, it is working as intended and will not violate any AdMob policies or can affect the CTR.

**Comment by AftabUfaq** [comment]
same issue for iOS. any fix
