### ISSUE TITLE
Open Ads and Interstitial Ad show nothing sometime (even in release mode)

### ISSUE THREAD

**Issue by RamseyWaverley** [googleads/googleads-mobile-flutter#822]
These ad work fine almost time but sometime Interstitial Ads and Open Ads widget (only show "Test Ad" in release) with no content. The way to close it is hit Android Back Button (Navigator) and it would close. Any help? i

Plugin Version

google_mobile_ads: 2.4.0

Reproduction steps
1. Pre load open or insert ads (only request not display)
2. Switch to the background and stay for more than 10 minutes (Android)
3. The advertisement must have been stuck on the loading page without being displayed, and the lifecycle has always been in the 'pause' state

**Comment by huycozy** [comment]
Hi @RamseyWaverley 
Can you try checking [app_open_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/app_open_example) to see if it happens in debug mode?

Also, could you provide a recorded video that shows the issue? Thanks!
