### ISSUE TITLE
i can't install pod

### ISSUE THREAD

**Issue by MazenCoder** [googleads/googleads-mobile-flutter#83]
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (= 6.8.3)

  In Podfile:
    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 7.69.0) was resolved to 7.69.0, which depends on
        GoogleAppMeasurement (~> 7.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `google_mobile_ads`.
   You should run `pod update GoogleAppMeasurement` to apply changes you've made.

**Comment by restart916** [comment]
same issue

**Comment by restart916** [comment]
Hi. I solved it with updated firebase packages version

in my case:
```
# before
#  firebase_core: ^0.5.3
#  firebase_auth: ^0.18.4
#  firebase_dynamic_links: ^0.5.3
#  firebase_crashlytics: ^0.2.4
#  firebase_messaging: ^7.0.3
#  firebase_remote_config: ^0.4.0+2
#  firebase_analytics: ^5.0.2
#  cloud_firestore: ^0.14.4
#  firebase_storage: ^5.2.0

# after
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_dynamic_links: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: ^0.6.0
  firebase_analytics: ^7.0.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
```

and some code :) (because update firebase packages)

**Comment by MazenCoder** [comment]
Hi,

after I updated the firebase packages Its work, Thank you 🙏
