### ISSUE TITLE
No java version specified in build.gradle

### ISSUE THREAD

**Issue by gnudles** [googleads/googleads-mobile-flutter#831]
When I compile with this library I get the following error:

google_mobile_ads-3.0.0/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterMobileAdsWrapper.java:79: error: static interface method invocations are not supported in -source 7
    WebView webView = WebViewFlutterAndroidExternalApi.getWebView(flutterEngine, webViewId);
                                                      ^
  (use -source 8 or higher to enable static interface method invocations)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

**Comment by darshankawar** [comment]
@gnudles 
Can you provide `flutter doctor -v` and `flutter run -v` ? The verbose log will be huge so you can put that in a file and attach it here.

**Comment by gnudles** [comment]
I made a new flutter project with only this package as dependency, and it compiled well.
I compared the gradle.build, with my current project, upgraded gradle to version 7 (from version 6), and it worked :)
