### ISSUE TITLE
google_mobile_ads ^3.0.0 not compatible with visibility_detector ^0.4.0+2 dependence

### ISSUE THREAD

**Issue by lcarielo** [googleads/googleads-mobile-flutter#833]
I tried to install the dependency, but it gives me a compatibility error with the dependency visibility_detector ^0.4.0+2

```
Because my_app depends on google_mobile_ads ^3.0.0 which depends on visibility_detector ^0.3.3, visibility_detector ^0.3.3 is required.
So, because my_app depends on visibility_detector ^0.4.0+2, version solving failed.
```

**Comment by huycozy** [comment]
Hi @lcarielo 
This is a known issue at https://github.com/googleads/googleads-mobile-flutter/issues/807. I will close this issue and leave there my comment, please follow up on it for further updates. Thanks!
