### ISSUE TITLE
iOS : Advertiser assets outside native ad view & MediaView is too small for video 

### ISSUE THREAD

**Issue by glintpursuit** [googleads/googleads-mobile-flutter#844]
The issue is only for iOS with newly provided nativeTemplateStyle.small 

![IMG_286163629B3D-1](https://github.com/googleads/googleads-mobile-flutter/assets/46914085/da7c124d-fb72-4e06-b42d-177686a1dc56)
![IMG_B34ED40E8898-1](https://github.com/googleads/googleads-mobile-flutter/assets/46914085/badee9b5-9c23-4012-bdd8-9f553048df4c)

## Plugin Version

google_mobile_ads: 3.0.0

## Steps to Reproduce
1. Add a Native ad small size to app 
   
   Load Ad 

   `await NativeAd(
            adUnitId: nativeAdUnitId,
            factoryId: 'listTile',
            request: const AdRequest(),
            nativeTemplateStyle: AdStyleHelper()
                .getStyle(templateType: TemplateType.small, context: context),
            listener: NativeAdListener(
              onAdLoaded: (ad) {
                setState(() {
                  _adList = ad as NativeAd;
                });
              },
              onAdFailedToLoad: (ad, error) {            
                ad.dispose();
              },
            ),
          ).load();`

   Display 

   `Padding(
                    padding: const EdgeInsets.only(left: 15, right: 15),
                    child: Container(
                      height: _adList != null ? 90.0 : 0,
                      alignment: Alignment.center,
                      child: AdWidget(ad: _adList!),
                    ),
                  )`

3. keep GADNativeAdValidatorEnabled to true in info.plist 
    `<key>GADNativeAdValidatorEnabled</key>
    <true/>`
4. Run flutter App on iOS iPhone X (iOS : 16.4.1)
5. Ad Validator will display validation error. 

### Sample App with issue (Issue can be reproduced on iPhone SE 3rd generation simulator as well )
[native_template_example.zip](https://github.com/googleads/googleads-mobile-flutter/files/11476513/native_template_example.zip)

### Flutter Doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by huycozy** [comment]
Thanks for filing the issue. I also can see it with [native_template_example](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/native_template_example.dart) code.

With medium type, there is no issue. Labeling the issue for further investigation.
Plugin version: `google_mobile_ads: ^3.0.0`

| small | medium |
| --------------- | --------------- |
<img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/118af6fc-44ec-456b-a272-7f643902cce9"> | <img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/284a2be1-408b-49f8-97c9-8235d9bf5018">

**Comment by glintpursuit** [comment]
@huycozy 
Below are few screenshots for Native inline Ads in production for 90 height container.  

OS : iOS, iphone 14 (16.4.1 (a))
google_mobile_ads: 3.0.0
Flutter : Channel stable, 3.10.0

 
![IMG_DC228B1D18D6-1](https://github.com/googleads/googleads-mobile-flutter/assets/46914085/67ed7886-f15b-4c31-bdcc-7386a4ab40dc)
![IMG_E4EE5D532C7A-1](https://github.com/googleads/googleads-mobile-flutter/assets/46914085/0add21a6-b9aa-4a9d-87ea-02b9cbacbe7c)

**Comment by glintpursuit** [comment]
> @huycozy Below are few screenshots for Native inline Ads in production for 90 height container.
> 
> OS : iOS, iphone 14 (16.4.1 (a)) google_mobile_ads: 3.0.0 Flutter : Channel stable, 3.10.0
> 
> ![IMG_DC228B1D18D6-1](https://user-images.githubusercontent.com/46914085/241752716-67ed7886-f15b-4c31-bdcc-7386a4ab40dc.jpeg) ![IMG_E4EE5D532C7A-1](https://user-images.githubusercontent.com/46914085/241752732-0add21a6-b9aa-4a9d-87ea-02b9cbacbe7c.jpeg)

@huycozy
My bad I had used wrong TemplateType for 90 height, do not consider above message

**Comment by abdullah432** [comment]
This issue is still not fixed. I'm getting this issue.

**Comment by rakib205** [comment]
Still not fixed.

**Comment by jjliu15** [comment]
The second warning (assets outside native ad view) should be fixed at head with https://github.com/googleads/googleads-mobile-flutter/pull/874.
The first warning is WAI - the small template purposefully has a small media view and video will not serve into it.

**Comment by Larisa-amugini** [comment]
plugin version 4.0.0
this problem is still not fixed

**Comment by KimiChiu** [comment]
>Advertiser assets outside native ad view

I'm not using flutter but also having this issue. It only occurred when the `Advertiser` string is empty. I tried to set `minHeight` and `minWidth` on my `UILabel` but it still keeps showing this message.

**Comment by kienvtqhi** [comment]
same issue with the latest Google Mobile Ads 4.0.0 and Flutter 3.19. Anyone has solution? Do we need to create a custom xib    file for the small native ad?

**Comment by wdikiz** [comment]
plugin version 4.0.0
this problem is still not fixed

**Comment by ertan95** [comment]
same issue seems not fixed

**Comment by walkinrey** [comment]
same

**Comment by georgeselkhoury** [comment]
why would you show a warning if nothing can be done on small? Any updates?

**Comment by padit69** [comment]
plugin version 5.2.0
this problem is still not fixed.

**Comment by hoangvanlinh** [comment]
plugin version 5.3.1
this problem is still not fixed.

**Comment by tumluliu** [comment]
plugin version 6.0.0
this problem is still not fixed

**Comment by broheat** [comment]
plugin version 6.0.0
this problem is still not fixed

**Comment by kotaroyamazaki** [comment]
same
google_mobile_ads: ^5.1.0

**Comment by josevictormoreno** [comment]
I'm still experiencing this bug.
