### ISSUE TITLE
Google Admob Mediation Is not Showing, Adapter Has Installed

### ISSUE THREAD

**Issue by flameblue59** [googleads/googleads-mobile-flutter#846]
I am trying to show Audience Network ad, AdColony, AppLovin through my admob mediation. However, the only ad which showing are Admob. The rest is not showing properly. AppLovin has ~1% match rate, the rest is 0%

**Plugin Version**

3.0.0

**Steps To Reproduce**

Adding adapters to build.gradle

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.ads.mediation:facebook:6.14.0.0'
    implementation "com.google.ads.mediation:applovin:11.9.0.0"
    implementation "com.google.ads.mediation:adcolony:4.8.0.2"
}
```

I also have set network_security_config.xml

```
<domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">127.0.0.1</domain>
    <domain includeSubdomains="true">dsimlife.com</domain>
    <domain includeSubdomains="true">id1.dsimlife.com</domain>
</domain-config>
```

Here is the log for adapters

```
com.google.android.gms.ads.MobileAdsAdapterInitializationState.ready
com.google.ads.mediation.facebook.FacebookMediationAdapterAdapterInitializationState.ready
com.google.ads.mediation.applovin.AppLovinMediationAdapterAdapterInitializationState.ready
com.google.ads.mediation.adcolony.AdColonyMediationAdapterAdapterInitializationState.ready
```

I have no clue why the only ad showing is Admob ad only. I have set everything fine.

1. Configuring Ad Unit Mapping in mediation
2. Setting waterfall
3. Adapter installed successfully

Does this plugin does not support mediation?

**Comment by huycozy** [comment]
Hi @flameblue59 
Mediation has been supported. You can take a look at these resources::

- Documentation: https://developers.google.com/admob/flutter/mediation/get-started
- Sample code: https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/mediation_example

If you have issues during implementation, you can search for the issue at this repository as well, for eg: [mediation filter](https://github.com/googleads/googleads-mobile-flutter/issues?q=is%3Aissue+label%3Amediation). Please take a look at it and check if there is any useful information.

Also, regarding match rate, it depends on many other factors of production data. If there's no more information that can identify if this is a plugin issue, it's not easy for us to investigate.

**Comment by nechtas** [comment]
This is so similar to my previous #issue845  We also see the most drops on mediation networks.
