### ISSUE TITLE
Add Not Show give error

### ISSUE THREAD

**Issue by DineshJat123** [googleads/googleads-mobile-flutter#865]
Ad failed to load : 0
 Failed to load rewarded ad, Error: LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Unable to obtain a JavascriptEngine., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))

**Comment by huycozy** [comment]
Hi @DineshJat123 
Based on the provided log, it looks similar to a known issue which is being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/527.

Closing this issue in favor of that issue. Please follow it for further updates.
