### ISSUE TITLE
depends on visibility_detector 0.3.3 while 0.4.0+2 is out

### ISSUE THREAD

**Issue by gysipos** [googleads/googleads-mobile-flutter#873]
## Use case
We use this package alongside visibility_detector, but this package depends on an old version (0.3.3) of it. So, we cannot use the latest visibility detector because of this:

 Because <YOUR_APP> depends on google_mobile_ads ^3.0.0 which depends on visibility_detector ^0.3.3, visibility_detector ^0.3.3 is required.
So, because realmonitor_app depends on visibility_detector ^0.4.0+2, version solving failed.

## Proposal

If possible, bump the dependency in google_mobile_ads to the latest visibility_detector.

Thank you!

**Comment by darshankawar** [comment]
@gysipos 
This seems to have been fixed already as part of https://github.com/googleads/googleads-mobile-flutter/pull/835/files
Check and see if it helps to resolve the issue.

**Comment by gysipos** [comment]
Yes, that pull request is perfect for this :-)
