### ISSUE TITLE
[Feature Request] Reading what consent was given

### ISSUE THREAD

**Issue by mulderpf** [googleads/googleads-mobile-flutter#882]
I'm busy implementing the consent form for my European users (GDPR) and I'm having some further difficulty with a huge gap in the documentation.

Firstly, when creating a new GDPR message in the AdMob platform, we have the great functionality to "Add purposes for own use" and that's great.  The thing is, once we've collected the details about these purposes, there seems to be no way of actually reading it!  How do we go about finding out whether the user consents?  (For example, on my consent form, there is a question about "Use precise geolocation data" - since my app uses location data, I need to be able to access whether the user turned this off so that I don't attempt to use this data inadvertently).

Regardless of what options I select, the following snippet always returns ConsentStatus.obtained:
```
                                      ConsentStatus consentStatus =
                                          await ConsentInformation.instance
                                              .getConsentStatus();

```

As a point of interest, I browsed this website yesterday (I'm in the EU): https://airlive.net/ and I tested out what would happen if I turn off everything.  I can see none of the Google Ads are serving, but the website has another source of ads too and despite de-selecting "Select basic ads" (it's OFF), I see the "other" ads which are not Google.

We really need a way to determine what it is that the user selected to inform us about what we can and cannot do in the app.  And asking twice is not really an option, because what happens if we get conflicting information?

**Comment by huycozy** [comment]
Hi @mulderpf 
I have checked some UMP API [here](https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/package-summary) but can't see available API can be used corresponding to your expectation. 

This looks like a new feature request for UMP SDK which is out of scope for this plugin currently. You may also check this [thread](https://groups.google.com/g/google-admob-ads-sdk/c/TbgQsZjtnyQ/m/bL6coV55AgAJ) (and also other threads there) that could be helpful as well. And then back here with more information that will help us to verify the issue better. Thank you!

**Comment by Wes1324** [comment]
I am also really struggling with this issue.

It is frustrating and disappointing that the docs state that we can configure an AdRequest object to specify that only non-personalized ads should be requested [here](https://developers.google.com/admob/flutter/eu-consent#forward_consent_to_the_google_mobile_ads_sdk), but then gives no detail about how to actually determine whether the user has accepted or declined personalized ads.

From [this blog](https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent#inspecting-consent-choices) it seems like the react-native-google-mobile-ads package is able to offer this functionality. I did some investigation and it looks like it does so via [this function](https://github.com/invertase/react-native-google-mobile-ads/blob/2bd13399666501d0e6b563c142ec131d3d47c522/src/AdsConsent.ts#L96). Something like that is definitely needed in this package.

**Comment by Wes1324** [comment]
Why has this issue been closed? There has been no resolution.

The automatic comment says 'we are unfortunately not sure how to resolve this issue' but I think the solution is clearly to add the same functionality that the react-native-google-mobile-ads package has, as I said in my comment above.

**Comment by mulderpf** [comment]
> Why has this issue been closed? There has been no resolution.
> 
> The automatic comment says 'we are unfortunately not sure how to resolve this issue' but I think the solution is clearly to add the same functionality that the react-native-google-mobile-ads package has, as I said in my comment above.

Is this library an official Google one - from what it seems, it's a third-party library that's using the workarounds which have been suggested before (to go poking around the data which is stored on the device).  I also want a resolution to this, but I think the issue here is a poorly-thought through library by Google without actually considering who they are developing it for (and a refusal to listen either as the internet forums are literally filled with complaints about this), rather than a missing feature in the Flutter library.  Of course, I might be wrong and maybe it is the official Google version (in which case it's only right that we get the same functionality when using Flutter).

That said, if the suggestion is to go poking around the data stored on the phone, it would make sense for Google to just incorporate this fully into their library so that we are protected against changes in future which might break our own awkward workarounds.

**Comment by malandr2** [comment]
Sharing docs for [iOS](https://developers.google.com/admob/ios/privacy/gdpr#how_to_read_consent_choices) and [Android](https://developers.google.com/admob/android/privacy/gdpr#how_to_read_consent_choices_2) to help read what consent was given.

**Comment by malandr2** [comment]
If you are still looking for how to do this please read out iOS and Android docs. You can also file a feature request in at [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) for an API in iOS/Android. 

Thanks!
