### ISSUE TITLE
We see production ads in Android emulator instead of test ads

### ISSUE THREAD

**Issue by aalex** [googleads/googleads-mobile-flutter#884]
We see production ads in Android emulator instead of test ads

## Plugin Version
Version `^3.0.0` (currently using the actual `3.0.0` version)

## OS
- Verified on macOS

## Platform
- This bug occurs only when the Flutter app is running on Android.

### Description of the problem
Production ads are shown when using an Android emulator.

## Steps to Reproduce
1. Implement ads
1. Set up your production ad ids
1. Run your app in an Android emulator

**Expected results:** We should see the test ads, since we are running in an emulator.

**Actual results:** We see our production ads.

**Comment by huycozy** [comment]
Hi @aalex 
Are you seeing this issue only on emulator API 33? I see there is a similar issue filed in Developer Forum: https://groups.google.com/g/google-admob-ads-sdk/c/Kk0kDDYVbX0 (the team is still investigating the issue). If so, it could be a general issue so I would suggest you follow it for further updates. It's worth checking this on [Android native example](https://github.com/googleads/googleads-mobile-android-examples) as well.
