### ISSUE TITLE
error in production: com.google.android.gms.ads.internal.client.zzee.attachInfo java.lang.IllegalStateException

### ISSUE THREAD

**Issue by DktPhl2019** [googleads/googleads-mobile-flutter#886]
Hello!

This error only occurs in production. If I run the same code on the Android Studio Emulator, then I don't see this error. 

Users in production are getting the crash error: com.google.android.gms.ads.internal.client.zzee.attachInfo java.lang.IllegalStateException

Google Play Crash Error: Exception java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException

google_mobile_ads: ^2.3.0

Android Manifest file:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp">
    <!-- The INTERNET permission is required for development. Specifically,
         the Flutter tool needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <application>
        <!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxxx~yyyyyyyyyyy"/>
   </application>
</manifest>
```

I confirmed that I got the correct App and Ad Unit Ids. 

Could you please explain what causes the error or what I should do to fix the error. 

Thank You

**Comment by huycozy** [comment]
Hi @DktPhl2019 
Please make sure you set the correct `APPLICATION ID` value from Admob App settings in Dashboard. A common cause that someone encounters is setting the AD id for the APP id (please see [this](https://github.com/googleads/googleads-mobile-flutter/issues/614#issuecomment-1324940803)).

**Comment by DktPhl2019** [comment]
Hello! Please close the ticket. I needed to copy APP ID into Android Manifest.xml under main folder. This is non-issue. Thank You
