### ISSUE TITLE
[Feature Request] override toString() for UMP FormError class

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#891]
as title

now no, ref:
https://github.com/googleads/googleads-mobile-flutter/blob/7599cbae4e56d139f533043fc3b2838c6f86fd0b/packages/google_mobile_ads/lib/src/ump/form_error.dart#L16

**Comment by NVentimiglia** [comment]
Thanks, I will submit this feature request to the SDK team.

**Comment by peterweb2005** [comment]
still no https://github.com/googleads/googleads-mobile-flutter/issues/891

**Comment by peterweb2005** [comment]
@NVentimiglia  why still no?
more than 1 year, i need to catch the error then crash log the code & message
if the library just override tostring(), no need that lines of code

**Comment by lucavenir** [comment]
Why did you close this issue if it's technically still open? 😓 
We can see `Instance of 'FormError'` pop up in our crashlytics instance and it took us a while to understand where the error came from, and what was that.

**Comment by lucavenir** [comment]
I don't understand, you want me to PR this? 😊
