### ISSUE TITLE
lag when scrolling listview with banner ads (IOS only)

### ISSUE THREAD

**Issue by OmerTrainer** [googleads/googleads-mobile-flutter#892]
## Plugin Version

google_mobile_ads: ^3.0.0

## Steps to Reproduce

https://github.com/OmerTrainer/one-sampleapp-ads

1. clone sample app.
2. import your own ca-app-pub in the ios runner info.plist file.
3. run the app on physical ios device. (the newer ones, i personally run it with Iphone 14+).
4. scroll inside the app and notice the lag when scrolling.

**Expected results:** 
smoothly scrolling screen displaying the banner ads.

**Actual results:** 
choppy / laggy scrolling screen when displaying the banner ads.

[✓] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IL)
    • Flutter version 3.10.4 on channel stable at /Users/developer/Documents/ONEAPP/Plugins/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (7 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

**Comment by cyanglaz** [comment]
Could you provide the iOS version on your iPhone?

**Comment by OmerTrainer** [comment]
> 

yes, sorry for the missing information.. 
I am currently on 16.3 IOS version

**Comment by huycozy** [comment]
Hi @OmerTrainer 

I checked this issue on my device iPhone 7, iOS 15.7.2 (I have only this one) but it isn't laggy when scrolling:

<details>
<summary>Demo video</summary>


https://github.com/googleads/googleads-mobile-flutter/assets/104349824/73c30919-0519-449b-9f34-11fb3b5bab72


</details>

Can you please try running the app in `profile` mode to see if it's still laggy? It would be appreciated if you could provide a recorded video so we can notice how lag it is. Thank you!

**Comment by OmerTrainer** [comment]
> Hi @OmerTrainer
> 
> I checked this issue on my device iPhone 7, iOS 15.7.2 (I have only this one) but it isn't laggy when scrolling:
> 
> Demo video
>  Image.from.iOS.MP4 
> Can you please try running the app in `profile` mode to see if it's still laggy? It would be appreciated if you could provide a recorded video so we can notice how lag it is. Thank you!

on older devices the lag doesn't appear this is why i said that it should be ran on newer physical ios device(13/14).
 (it was filmed with profile build iphone 14+ physical device)
i hope that the attached videos will help :

https://github.com/googleads/googleads-mobile-flutter/assets/92077528/a7057a63-e1f9-4618-98d3-e3ea18f2cf21


https://github.com/googleads/googleads-mobile-flutter/assets/92077528/87011f8a-a68f-44f9-ad87-380e8e34fb51

**Comment by huycozy** [comment]
Thanks for the videos. It looks smooth, though. Can you please enable performance overlay in profile mode to see if there are any jank? And please also attach the timeline trace JSON file as well. You can find the instructions for it at https://github.com/flutter/flutter/issues/74833#issue-795394794.

**Comment by quan2nd** [comment]
I also encountered this issue on iOS. The first time I run the application, everything is very smooth. However, after I kill the app or run it for the second time and onwards, my listview becomes laggy. I use all the latest versions(IOS, Flutter, GoogleAds)

**Comment by quan2nd** [comment]
@OmerTrainer Try turning off Impeller
https://docs.flutter.dev/perf/impeller
I solved my problem

**Comment by OmerTrainer** [comment]
> @OmerTrainer Try turning off Impeller https://docs.flutter.dev/perf/impeller I solved my problem

I have already tried it didn't resolve the issue

**Comment by huycozy** [comment]
@llooz Thanks for linking the issue. It seems that's indeed related issue when the OP also mentioned in the first comment (specific OS, device). Also, it's not an Impeller issue (you can check at that issue's labels), it's a platform-views issue.

I will close this in favor of Flutter issue https://github.com/flutter/flutter/issues/129632. Please follow up on it for further updates.

**Comment by glennmichaelmejias** [comment]
any updates for this?
