### ISSUE TITLE
[iOS] TemplateType.small - MediaView is too small for video

### ISSUE THREAD

**Issue by jhlee-danbi** [googleads/googleads-mobile-flutter#894]
### Plugin Version
2.4.0

Hello, has the following issue been resolved?
-> `"MediaView is too small for video"`
![KakaoTalk_Photo_2023-07-26-11-51-08](https://github.com/googleads/googleads-mobile-flutter/assets/99167999/7aa7da22-3cdd-4b3b-b00d-c78868eb6f4d)

I only want to use a small-sized banner..

```
   nativeTemplateStyle: NativeTemplateStyle(
          templateType: TemplateType.small,
        ))
```

1. I'm wondering if this error has been fixed.
2. Would it be okay to release the app ignoring this error?

**Comment by huycozy** [comment]
Thanks for the report, @jhlee-danbi 

This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/844. Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by Larisa-amugini** [comment]
this problem is still not fixed
