### ISSUE TITLE
[InterstitialAds] Video ads is not loading

### ISSUE THREAD

**Issue by jigar-f** [googleads/googleads-mobile-flutter#897]
## Plugin Version
 google_mobile_ads: ^2.4.0

### [REQUIRED] Step 2: Describe the problem
I am trying to implement InterstitialAds ads, Whenever I enable video ads from the Google Abmod dashboard, I am getting an Error and if I disable video ads it shows fine.

## Steps to Reproduce
Use the version provided and enable video ads 

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
It should show all types of ads.
**Actual results:** 
When video ads are enabled ads load to fail.

<details>

[Ads Request] failed to load LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Internal error., responseInfo: ResponseInfo(responseId: CI-R4dSpwIADFW3OFgUdhzgLGg, mediationAdapterClassName: , adapterResponses: [AdapterResponseInfo(adapterClassName: com.google.ads.mediation.admob.AdMobAdapter, latencyMillis: 60002, description: {
I/flutter ( 7038): │ 💡   "Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
I/flutter ( 7038): │ 💡   "Latency": 60002,
I/flutter ( 7038): │ 💡   "Ad Source Name": "AdMob Network",
I/flutter ( 7038): │ 💡   "Ad Source ID": "5450213213286189855",
I/flutter ( 7038): │ 💡   "Ad Source Instance Name": "AdMob Network",
I/flutter ( 7038): │ 💡   "Ad Source Instance ID": "1279038790339170",
I/flutter ( 7038): │ 💡   "Credentials": {},
I/flutter ( 7038): │ 💡   "Ad Error": {
I/flutter ( 7038): │ 💡     "Code": 0,
I/flutter ( 7038): │ 💡     "Message": "Internal error.",
I/flutter ( 7038): │ 💡     "Domain": "com.google.android.gms.ads",
I/flutter ( 7038): │ 💡     "Cause": "null"
I/flutter ( 7038): │ 💡   }
I/flutter ( 7038): │ 💡 }, adUnitMapping: {}, adError: AdError(code: 0, domain: com.google.android.gms.ads, message: Internal error.), adSourceName: AdMob Network, adSourceId: 5450213213286189855, adSourceInstanceName: AdMob Network, adSourceInstanceId: 1279038790339170)], loadedAdapterResponseInfo: null), responseExtras: {mediation_group_name: Group 1 Interstitial Android - 1 app - all countries})
I/flutter ( 7038): └───────────────────────────────────────────
E/Ads     ( 7038): JS: Uncaught ReferenceError: mys is not defined (https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_sai_demuxedGcache_xSeconds&eid=318496669%2C318508243%2C318500618%2C318486317%2C318491267%2C318483611%2C318484497%2C318501517%2C318509544%2C318510113%2C318502753&format=interstitial_mb&heap_free=4054646&heap_max=268435456&heap_total=17148494&js=afma-sdk-a-v232400999.223104000.1&mr=320836887173365033%2C320836887173365033%2C441481461792713482%2C441481461792713482%2C495375689810413332%2C571507183067140268%2C571507183067140268%2C704656398860646830%2C704656398860646830%2C-135586696034906668%2C-135586696034906668%2C-387539673451131755%2C-387539673451131755%2C-599219540856561395%2C1482991024747282243%2C1482991024747282243%2C3489565298360570308%2C3489565298360570308%2C3671971995970406487%2C3671971995970406487%2C3822813767177282760%2C3822813767177282760%2C4224879067302196864%2C4224879067302196864%2C6979379435802787336%2C6979379435802787336%2C7052127602611262115%2C7052127602611262115%2C7666685596251494226%2C7666685596251494226%2C8170361138688771984%2C8170361138688771984%2C8422704372357307975%2C8422704372357307975%2C-1633121354420415130%2C-1633121354420415130%2C-2063040043205619361%2C-2063040043205619361%2C-2398460099647624915%2C-2398460099647624915%2C-3413144680219348566%2C-3413144680219348566%2C-4562223171300871199%2C-4562223171300871199%2C-5256458235790664137%2C-5256458235790664137%2C-5514912998155372313%2C-5514912998155372313%2C-6065229541770422583%2C-6065229541770422583%2C-6497982968349083789%2C-6497982968349083789%2C-7068168871293549077%2C-7068168871293549077%2C-7236648455813875823%2C-7236648455813875823%2C-7714213481980920108%2C-7714213481980920108%2C-8222410896178884681%2C-8222410896178884681%2C-8449402895971754212%2C-8449402895971754212&msid=org.getlantern.lantern&preqs=0&seq_num=1&target_api=33:1)
I/chromium( 7038): [INFO:CONSOLE(1)] "Uncaught ReferenceError: mys is not defined", source: https://googleads.g.doubleclick.net/mads/gma?caps=inlineVideo_interactiveVideo_mraid1_mraid2_mraid3_sdkVideo_exo3_th_autoplay_mediation_scroll_av_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo_ipdof_gls_gcache_sai_demuxedGcache_xSeconds&eid=318496669%2C318508243%2C318500618%2C318486317%2C318491267%2C318483611%2C318484497%2C318501517%2C318509544%2C318510113%2C318502753&format=interstitial_mb&heap_free=4054646&heap_max=268435456&heap_total=17148494&js=afma-sdk-a-v232400999.223104000.1&mr=320836887173365033%2C320836887173365033%2C441481461792713482%2C441481461792713482%2C495375689810413332%2C571507183067140268%2C571507183067140268%2C704656398860646830%2C704656398860646830%2C-135586696034906668%2C-135586696034906668%2C-387539673451131755%2C-387539673451131755%2C-599219540856561395%2C1482991024747282243%2C1482991024747282243%2C3489565298360570308%2C3489565298360570308%2C3671971995970406487%2C3671971995970406487%2C3822813767177282760%2C3822813767177282760%2C4224879067302196864%2C4224879067302196864%2C6979379435802787336%2C6979379435802787336%2C7052127602611262115%2C7052127602611262115%2C7666685596251494226%2C7666685596251494226%2C8170361138688771984%2C8170361138688771984%2C8422704372357307975%2C8422704372357307975%2C-1633121354420415130%2C-1633121354420415130%2C-2063040043205619361%2C-2063040043205619361%2C-2398460099647624915%2C-2398460099647624915%2C-3413144680219348566%2C-3413144680219348566%2C-4562223171300871199%2C-4562223171300871199%2C-5256458235790664137%2C-5256458235790664137%2C-5514912998155372313%2C-5514912998155372313%2C-6065229541770422583%2C-6065229541770422583%2C-6497982968349083789%2C-6497982968349083789%2C-7068168871293549077%2C-7068168871293549077%2C-7236648455813875823%2C-7236648455813875823%2C-7714213481980920108%2C-7714213481980920108%2C-8222410896178884681%2C-8222410896178884681%2C-8449402895971754212%2C-8449402895971754212&msid=org.getlantern.lantern&preqs=0&seq_num=1&target_api=33 (1)

**Comment by jigar-f** [comment]
Hey @huycozy, just to clear things up, I'm using our actual INTERSTITIAL_AD_UNIT_ID and not a test ID. Though, I did use the test id for testing purposes while I was developing the feature, Do you think that might cause this issue?

**Comment by huycozy** [comment]
Hi @jigar-f 
No, I don't think it may cause the issue. But what I mentioned above is about the corresponding pairs of IDs.

You should use separate pairs of IDs in production and test environment, for eg:
- For testing: 
    - App ID test: `ca-app-pub-3940256099942544~3347511713` (from [here](https://developers.google.com/admob/android/quick-start#import_the_mobile_ads_sdk))
    - [Interstitial Video](https://developers.google.com/admob/android/interstitial#create_an_interstitial_ad_object): `ca-app-pub-3940256099942544/8691691433` (from [here](https://developers.google.com/admob/android/test-ads#demo_ad_units))
- For production:
    - App ID:  (your created app ID from Admob dashboard)
    - Interstitial Video: (your created Interstitial unit ad ID from Admob dashboard)
