### ISSUE TITLE
rewared ad not showing in full screen 

### ISSUE THREAD

**Issue by alihader34343** [googleads/googleads-mobile-flutter#902]
https://drive.google.com/file/d/1R9cWmS5xkFnFnCKLNPBx1k8Twq-GWQdZ/view?usp=sharing
 see this is showing then admob  policy violation issue showing 
how to solve in flutter

**Comment by huycozy** [comment]
Hi @alihader34343 
Which platform are you testing on?

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include other 3rd party plugins or complex production code so that we may verify this. 

Also, you can try [plugin's sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/rewarded_interstitial_example) on your device to see if it works as expected.

**Comment by alihader34343** [comment]
i am testing on my real phone  and I am using official code copy of plugin
 void _createRewardedAd() {
    RewardedAd.load(
        adUnitId: Platform.isAndroid
            ? 'ca-app-pub-3940256099942544/5224354917'
            : 'ca-app-pub-3940256099942544/1712485313',
        request: request,
        rewardedAdLoadCallback: RewardedAdLoadCallback(
          onAdLoaded: (RewardedAd ad) {
            print('$ad loaded.');
            _rewardedAd = ad;
            _numRewardedLoadAttempts = 0;
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('RewardedAd failed to load: $error');
            _rewardedAd = null;
            _numRewardedLoadAttempts += 1;
            if (_numRewardedLoadAttempts < maxFailedLoadAttempts) {
              _createRewardedAd();
            }
          },
        ));
  }

  void _showRewardedAd() {
    if (_rewardedAd == null) {
      print('Warning: attempt to show rewarded before loaded.');
      return;
    }
    _rewardedAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (RewardedAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (RewardedAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createRewardedAd();
      },
      onAdFailedToShowFullScreenContent: (RewardedAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createRewardedAd();
      },
    );

    _rewardedAd!.setImmersiveMode(true);
    _rewardedAd!.show(
        onUserEarnedReward: (AdWithoutView ad, RewardItem reward) {
      print('$ad with reward $RewardItem(${reward.amount}, ${reward.type})');
    });
    _rewardedAd = null;
  }

**Comment by alihader34343** [comment]
you can download offical code expample and try on your self after some ads then show that picture error

**Comment by huycozy** [comment]
Looks like you are loading RewardedAd instead of RewardedInterstitialAd. I run [rewarded_example sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/rewarded_example), the reward ad is displaying well on my side:

<details>
<summary>Demo</summary>

![Screenshot 2023-08-11 at 18 20 44](https://github.com/googleads/googleads-mobile-flutter/assets/104349824/e8efbbc2-bdd0-45d4-9671-c38d2e5083b5)

</details>

**Comment by alihader34343** [comment]
bro use this one
https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/main.dart
reward ad showing after 4 to 5 ads then showing error
[image: WhatsApp Image 2023-08-10 at 3.52.11 PM.jpeg]
in test mode  and in real ads policy violation showing in admob account
iframe sizzing issue like that

**Comment by huycozy** [comment]
It displays well with that sample code as well.

<details>
<summary>Demo</summary>

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/2fb36c6f-5bfe-4d41-8b4d-61f9d899df99"> | <img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/a1154212-c1dc-435c-a285-696b00774c78">

</details>

Which device are you seeing this (OS, model)? Can you please provide a recorded video of the error?

**Comment by akshat9902** [comment]
hi ,
why Rewards and Interstrials Ads Not Show in Full Screen..check below images.
use INtrestrial ads and rewrds ads code link ==>https://github.com/googleads/googleads-mobile-android-examples

![reward_2](https://github.com/googleads/googleads-mobile-flutter/assets/118596531/f00da4d6-af77-499f-95b9-aadd12b83655)
![int_one](https://github.com/googleads/googleads-mobile-flutter/assets/118596531/56f678bc-d11f-41db-87d0-7a03d6bd56d8)
