### ISSUE TITLE
App Open ad is displayed under the status bar.

### ISSUE THREAD

**Issue by razahel** [googleads/googleads-mobile-flutter#910]
### [REQUIRED] Step 1: Describe your environment
- iPhone 14
- iOS 16.6

## Plugin Version
- google_mobile_ads 3.0.0

## Describe the problem
- When Display Zoom is set as Larger Text, App Open ad is put under the status bar so the users cannot dismiss the add.

## Steps to Reproduce
1. Open Settings app
2. Go to Display & Brightness > Display Zoom
3. Select Larger Text
4. Open the app
5. Display an App Open ad

**Expected results:**
The ad is shown below the status bar.

**Actual results:**
The ad is shown under the status bar. The issue is reproduced even when the status bar is set to be hidden.

![KakaoTalk_Photo_2023-08-25-01-40-25](https://github.com/googleads/googleads-mobile-flutter/assets/143121515/dcd5096e-adc1-4e39-a9c3-ed77b66cd66a)

**Comment by huycozy** [comment]
Hi @razahel 
I increased the text size to ~70% or even maximum 100% but the ad is still displaying below status bar:

| ad | text size setting |
| --------------- | --------------- |
<img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/a6f9490b-5dba-4133-a585-0ed2e74a9a2f"> | <img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/d23346b1-1485-46e3-aea1-4f815971e246">

Can you try with [app_open_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/app_open_example) and confirm again?

**Comment by razahel** [comment]
@huycozy Hello. Thanks for testing. I confirmed it's reproduced on the iPhone 14 Pro simulator with [app_open_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/app_open_example). I think you used the setting of Accessibility but my case was reproduced by changing a setting of Display & Brightness. Could you test again by checking the steps I provided? I also attached the screenshots you may refer to.

![2](https://github.com/googleads/googleads-mobile-flutter/assets/143121515/84fdce29-6638-4edc-819a-43ef3c751221) ![3](https://github.com/googleads/googleads-mobile-flutter/assets/143121515/656ecd33-f205-43b7-ae16-d3688317fea9) ![4](https://github.com/googleads/googleads-mobile-flutter/assets/143121515/f517c720-4862-44ad-9290-ccbad241fbef) ![1](https://github.com/googleads/googleads-mobile-flutter/assets/143121515/df925b93-130c-427c-8ca3-f69dc1e97e9a)

**Comment by huycozy** [comment]
Hi @razahel 
I checked this on my physical device iPhone 7 which has Display Zoom feature and can enable it. But I still can close the ad, the ad displays over the status bar. Comparing with your screenshot above, it seems the ad also displays over the status bar as well. But can't you close it by pressing on `Continue to app` button?

I also check with [AppOpenExample](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/admob/AppOpenExample) (iOS native sample project). I can close ad as well. The ad displays under the status bar, though. 

Can you also check this native sample code as well?

| flutter | ios native |
| --------------- | --------------- |
<img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/0ee8d5d7-912c-4356-a209-a4d25c5b26d2"> | <img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/4d5f8844-9bd4-4965-ac3e-36ff024e2578">

**Comment by darshankawar** [comment]
@razahel Can you take a look at [this](https://github.com/googleads/googleads-mobile-flutter/issues/191#issuecomment-1273683141) and check if it helps in your case ?

**Comment by hungrymissilepod** [comment]
I've not got this issue with App Open ads, however I am having it with NativeAds.

In my video you can see the NativeAd behind the iOS status bar.

I've tried the link in @darshankawar 's comment but it didn't work for me

https://github.com/googleads/googleads-mobile-flutter/assets/46930094/173c65b6-7fa6-4a29-8539-49f3d3f6eda0

**Comment by tbm98** [comment]
It should not be closed.
