### ISSUE TITLE
Banner load and ad impressions still ocurring when widget is not current (ModalRoute.of(context)?.isCurrent)

### ISSUE THREAD

**Issue by nozari** [googleads/googleads-mobile-flutter#915]
### [REQUIRED] Step 1: Describe your environment

* any android 

## Plugin Version

* google_mobile_ads: ^3.0.0

### [REQUIRED] Step 2: Describe the problem

* When Navigating (`Navigator.pushNamed`) to new route banner is still printing Ads even if the Widget is not current
* Log

```
I/flutter (10902): Widget.build: ModalRoute.of(context)?.isCurrent == true
I/flutter (10902): BannerAdListener.onAdImpression: print banner AD 2023-09-05T22:17:02.314598
I/flutter (10902): BannerAdListener.onAdLoaded: banner load 2023-09-05T22:17:02.352217
I/flutter (10902): Widget.build: ModalRoute.of(context)?.isCurrent == true
I/flutter (10902): Navigating to new route
I/flutter (10902): Widget.build: ModalRoute.of(context)?.isCurrent == false
I/flutter (10902): BannerAdListener.onAdLoaded: banner load 2023-09-05T22:18:14.159880
I/flutter (10902): BannerAdListener.onAdImpression: print banner AD 2023-09-05T22:18:14.164852
I/flutter (10902): Widget.build: ModalRoute.of(context)?.isCurrent == false
I/flutter (10902): BannerAdListener.onAdLoaded: banner load 2023-09-05T22:19:26.137575
I/flutter (10902): BannerAdListener.onAdImpression: print banner AD 2023-09-05T22:19:26.141164
I/flutter (10902): Widget.build: ModalRoute.of(context)?.isCurrent == false
```

## Steps to Reproduce

1. Add banner  Ad to a Widget routeName="/home" 
2. Add logs on BannerAdListener `onAdLoaded` and `onAdImpression`
3. Navigator.pushNamed("/other-page")
4. Wait few minutes and it still going to log banner load and ad impression

Note you can log on `Widget build`  method if the Widget is current or not (`ModalRoute.of(context)?.isCurrent`)

**Comment by huycozy** [comment]
Hi @nozari 
This looks like you haven't called `dispose()` for banner ad when navigating to the 2nd page. Please see [plugin example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) for reference. 

If you have called `dispose()` but still see ad impression on new page, please provide a minimal sample code so we may verify this. Thanks!

**Comment by nozari** [comment]
Hi @huycozy 

The problem I found is that `dispose()` is only called when the widget is removed from the tree. If you navigate forward to another route the widget is still in the "background".

I did a quick change on the [inline_adaptive_example.dart](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/inline_adaptive_example.dart) and [anchored_adaptive_example.dart](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/anchored_adaptive_example.dart) to give you an example of the issue.

Please add the the bottom navigation bar on both files so you can navigate from one to another.
```
bottomNavigationBar: BottomNavigationBar(
        selectedFontSize: 20,
        unselectedFontSize: 20,
        iconSize: 30,
        currentIndex: 0,
        onTap: (value) {
          if (value == 0) {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => InlineAdaptiveExample()),
            );
          } else {
            Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (context) => AnchoredAdaptiveExample()),
            );
          }
        },
        items: const [
          BottomNavigationBarItem(
              icon: Icon(Icons.ad_units), label: 'inline adaptive'),
          BottomNavigationBarItem(
              icon: Icon(Icons.ad_units), label: 'anchored adaptive'),
        ],
      ),
```

After that run the app and go to Inline or Achored adaptive banner and navigate between both.
You will see on your widget tree that both are there (see image below)
<img width="266" alt="Screenshot 2023-09-07 at 11 35 03 AM" src="https://github.com/googleads/googleads-mobile-flutter/assets/1474165/c17dbef2-090f-45fc-86fa-89a79463acf1">

If you wait a minute or two after that you will see that both ads (inline and anchored) are kept alive.

On my app you can navigate from one screen to another screen and since both have ads and you can keep navigating further, without going back using `Navigator.pop` to remove the Widget from the "stack", the ads are still refreshing.

On my app I remove the Ad from the tree (for the `dispose()` to be called) if the route is not the current (`ModalRoute.of(context)?.isCurrent == false`)

IMHO that behavior should be done on the SDK.


Thanks for your time to review it.

**Comment by huycozy** [comment]
>On my app I remove the Ad from the tree (for the dispose() to be called) if the route is not the current (ModalRoute.of(context)?.isCurrent == false)

Thanks for your update. I think this approach is appropriate for the current API. You should manage to solve it with your own implementation. There has been a feature request here for a similar issue https://github.com/googleads/googleads-mobile-flutter/issues/653. Please take a look at https://github.com/googleads/googleads-mobile-flutter/issues/653#issuecomment-1269006755 for more information. 

If you think https://github.com/googleads/googleads-mobile-flutter/issues/653 should be implemented and it can help to solve this issue, please let me know, I will re-open it and close this issue.

**Comment by nozari** [comment]
I believe that can solve the issue I'm seeing.
My current solution (removing the ad from the tree) is not optimal since if the user goes to another view and back pretty quickly it will load a new ad while we could have just kept the same ad as before.

P.S.: I just found this issue because my app got flagged with invalid traffic and then I started to dig in to find what could have been the cause.

**Comment by huycozy** [comment]
Thanks for your confirmation. I will close this issue and re-open that one. Please follow up on it for updates. You may leave your comment there and react an upvote to the original comment will help to raise the issue. Thank you!
