### ISSUE TITLE
[ios] [integration] any error equivalent to: AdError code 3, message: "the ad can not be shown when app is not in foreground"?

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#917]
https://developers.google.com/admob/ios/api/reference/Enums/GADPresentationErrorCode

seeems no??
and i cant copy here as the docs blocked

**Comment by huycozy** [comment]
Closing this issue in favor of https://github.com/googleads/googleads-mobile-flutter/issues/906. Please follow up on that issue for updates.

**Comment by peterweb2005** [comment]
i found that for ios, there is NO AdError code 3, message: "the ad can not be shown when app is not in foreground"

and also in ios, the network error #905
