### ISSUE TITLE
Loading ad in reward granted callback fails on iOS

### ISSUE THREAD

**Issue by caseycrogers** [googleads/googleads-mobile-flutter#919]
### [REQUIRED] Step 1: Describe your environment

Deploying on iOS using a real device with test ads.
Note that I could not replicate this on Android.

## Plugin Version

version 3.0.0

## Steps to Reproduce

1. Call `show` on a loaded rewarded ad
2. Replace the ad with a new ad and load it in the on reward callback
3. Close the ad at least a second or two after the reward is granted
4. Call `show` on the new ad

**Expected results:**
The new ad shows

**Actual results:**

`AdError(code: 17, domain: com.google.admob, message: The provided view controller is not being presented.)`

**Notes:**
It seems like I can't load the next ad until the previous ad has been closed by the user. It seems like the new ad is seeing that the old ad is obscuring the app content and thus is refusing to display. Maybe the check to see if there is obscuring content is in `load` when it should be in `show`?
Loading the next ad when `onAdDissmissedFullScreenContent` seems to resolve the issue, but I figure this should still be fixed as the current situation seems like a pretty bad foot gun. Simplest solution would be to throw an exception if you attempt to load a new ad before the previous ad is closed.

**Comment by huycozy** [comment]
Hi @caseycrogers 
I use plugin [sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and follow your steps but can't reproduce the error. The RewardedAd can be displayed every time I call to show it (from popup menu). 

Can you try the plugin sample code and confirm? If your implementation is not the same, please provide a minimal sample code. Thanks!

**Comment by marcsanny** [comment]
I had similar issue and adding small delay before loading the ad helped me (but it's more like a workaround not the actual solution)
