### ISSUE TITLE
Ad inspector - No adapters found

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-flutter#920]
## Environment
iOS, iPhone 6s

## Plugin Version
Flutter plugin 3.0.0
Google Mobile Ads SDK v.10.4.0

## The problem
When I go to Ad inspector, it tells me that no adapters were found. However AppLovin is present, wins the auction for the interstitial and displays it without problems.

![IMG_2710](https://github.com/googleads/googleads-mobile-flutter/assets/83022092/439a8e4f-42b8-4bc9-ad44-cd5cf643a89f)
![IMG_2709](https://github.com/googleads/googleads-mobile-flutter/assets/83022092/b33c0a5d-e4e1-41cd-a2f9-9c1a7fa215b0)

<details>
  <summary>Logs</summary>

No issues found! (ran in 3.4s)

[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale
    it-IT)
    • Flutter version 3.13.3 on channel stable at
      /Users/_/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (7 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by huycozy** [comment]
Hi @Francesco-FL 
Per [Understand SDK adapter issues](https://support.google.com/admob/answer/12659455?hl=en), adapter not found issue means that the GMA SDK cannot find your third-party adapter or SDK. 

Could you confirm the ad is displaying on your test device? (with test ad id and production ad id)

**Comment by Francesco-FL** [comment]
I placed the adapters in the Podfile and on iOS devices the AppLovin mediation ads always show correctly. it's as if everything is working fine, but the Ad Inspector incomprehensibly tells me that he can't find them.

The point is that AppLovin manages to work correctly in mediation, wins auctions and shows ads, and it is strange that I don't find it in the Ad Inspector.

As for the app-banner ids, I use the ones AdMob assigned to me for the app and the advertising units.

<img width="915" alt="Screenshot 2023-09-14 alle 16 56 13" src="https://github.com/googleads/googleads-mobile-flutter/assets/83022092/f45e03c6-0432-4a16-8798-fa0fc37b433f">

**Comment by huycozy** [comment]
This seems to be an implementation issue. Please confirm whether the ad is displaying on your test device or not (with test ad id and production ad id)

**Comment by malandr2** [comment]
Closing this ticket due to inactivity. Please re-open if necessary.
