### ISSUE TITLE
Banner Ads are not cut off and look horrible

### ISSUE THREAD

**Issue by patolax** [googleads/googleads-mobile-flutter#928]
I have tried several Google forums to get this fixed or obtain a proper implementation method.

This is the last response I got. Not sure where to go from here. 
![image](https://github.com/googleads/googleads-mobile-flutter/assets/29444156/dc25838d-9917-48e6-9b27-e31c23b948d9)

I can't release the app ads shown like this. It looks horrible.
![image](https://github.com/googleads/googleads-mobile-flutter/assets/29444156/e88d2649-8df5-42cc-bb04-5f39f8e52fdc)

This is my code. Please provide me a working solution.

```dart
class AdBanner extends StatefulWidget {
  const AdBanner({Key? key}) : super(key: key);

  @override
  State<AdBanner> createState() => _AdBannerState();
}

class _AdBannerState extends State<AdBanner> {
  BannerAd? _inlineAdaptiveAd;
  bool _isLoaded = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      var windowwidth = MediaQuery.of(context).size.width.truncate();
      _loadAd(windowwidth);
    });
  }

  void _loadAd(int windowwidth) async {
    await _inlineAdaptiveAd?.dispose();
    // Get an inline adaptive size for the current orientation.
    AdSize size = AdSize.banner;
    size = (await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
        windowwidth)) as AdSize;

    _inlineAdaptiveAd = BannerAd(
      adUnitId: AdHelper.bannerAdUnitId,
      size: size,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) async {
          debugPrint('Inline BannerAdListener onAdLoaded');
          if (mounted) {
            setState(() {
              _isLoaded = true;
            });
          }
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          debugPrint('Inline adaptive banner failedToLoad: $error');
          _isLoaded = false;
          ad.dispose();
        },
      ),
    );
    await _inlineAdaptiveAd!.load();
  }

  @override
  Widget build(BuildContext context) {
    return (_isLoaded && _inlineAdaptiveAd != null)
        ? Align(
            alignment: Alignment.bottomCenter,
            child: SizedBox(
                width: _inlineAdaptiveAd!.size.width.toDouble(),
                height: _inlineAdaptiveAd!.size.height.toDouble(),
                child: AdWidget(
                  ad: _inlineAdaptiveAd!,
                )))
        : const SizedBox(
            width: 0,
            height: 0,
          );
  }

  @override
  void dispose() {
    _inlineAdaptiveAd?.dispose();

    super.dispose();
  }
}
```

**Comment by huycozy** [comment]
Hi @patolax 
When checking this issue on my device Realme 6, Android 11, the banner looks fine in the center:

![Screenshot 2023-10-09 at 18 43 30](https://github.com/googleads/googleads-mobile-flutter/assets/104349824/35216a8e-0317-4bad-9665-8af648fb1e29)

Which device are you seeing the issue?

Could you try running native sample [AdaptiveBannerExample](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/AdaptiveBannerExample) on your device to see if the issue also occurs?

**Comment by patolax** [comment]
This is from my own Android app using admob integration using Java running on the same device.

![image](https://github.com/googleads/googleads-mobile-flutter/assets/29444156/7f902274-b139-40d9-85ec-c07a8f661fbb)

As you can see the ad is working fine without any miss alignments.

This is my test device https://www.motorola.com.au/smartphone-motorola-moto-g22/p

**Comment by patolax** [comment]
And here is the output from https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/AdaptiveBannerExample. Its working fine.

![image](https://github.com/googleads/googleads-mobile-flutter/assets/29444156/bab55481-eec3-423c-b8f2-49b801f04dbe)

**Comment by huycozy** [comment]
Thanks for checking this. I will re-open https://github.com/googleads/googleads-mobile-flutter/issues/261 as many reports along with information there. Please leave there a comment (or update your comment) with a demo above and device information as well.

Closing this as a duplicate.
