### ISSUE TITLE
The instance member '_interstitialAd' can't be accessed in an initializer.

### ISSUE THREAD

**Issue by pallavc34** [googleads/googleads-mobile-flutter#93]
## Bug report

Cannot use variables, and context in listener events. 

### Steps to reproduce

Try calling any variable or for this purpose set _isInterstitialAdReady to true on Interstitial onAdLoaded event. It gives an instance member can't be accessed in an initializer error.

### Expected behavior

As with the firebaseAdmob plugin, on _onInterstitialAdEvent you could perform actions such as exit app once ad is closed and so on but in Google Ads plugin nothing of that sort can be done!

## Additional context

Any workaround/solution to this problem could be appreciated. 

Flutter version : 2.0.1
Google_mobile_ads version : 0.11.0+3

**Comment by maheshmnj** [comment]
Hi @pallavc34, Thanks for filing the issue, Please share the out]put of `flutter doctor -v` along with a [minimal and complete  reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks
