### ISSUE TITLE
[QUESTION] Does this work on "streaming devices" (e.g. Chromecast with Google TV)?

### ISSUE THREAD

**Issue by under3415** [googleads/googleads-mobile-flutter#934]
I have a user complaining that ads do not play on his "streamer". I assume he is using one of the "smart TV streaming boxes" running Android OS. 

Has anyone tested this on these devices or do I need to go out and buy one? Are there any virtual devices out there?

**Comment by huycozy** [comment]
Hi @under3415 
As I can see, Admob SDK does not officially support Android TV this time, please take a look at [this](https://groups.google.com/g/google-admob-ads-sdk/c/djpBsZeq6sE/m/sNH0aGriBAAJ) and similar questions there in [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk). 

This ad plugin uses Google Mobile Ads library internally. Closing this issue as it is out of plugin scope.

**Comment by under3415** [comment]
Hi
It actually works on Android TV, but does not work on Chromecast with Google TV.
Regards
Dejan

**Comment by huycozy** [comment]
Could you please raise this on [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk)? If ad service can actually run on Chromecast, then perhaps this plugin can support.
