### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by pierre-softimpact** [googleads/googleads-mobile-flutter#935]
Plugin Version: `google_mobile_ads: ^3.0.0`

Flutter version: `3.13.0 channel stable`

The problem:

The performance of our apps got drastically worse after implementing banner ads using this plugin, specially on newer iPhone models.

The issue is far more noticeable on iOS than on Android, we are using Impeller but the performance on Skia is the same.

While scrolling, there is a very obvious flickering effect that happens on newer iPhone models. Based on other issues and discussions here, one of the problems should be the Pro Motion feature from Apple. We also have an iPhone X for testing, while the performance is better, it is not the best.

We do not believe it is an issue from our code base, since disabling the ads result in a perfect running app. 

Are there any workarounds that you could suggest? The use of native views for the ads is making the app unusable, and our clients are very disappointed with the results. The main revenue of the apps is based on the Ads that are present, so shipping an app without Ads is impossible for our requirements.

**Comment by huycozy** [comment]
Hi @pierre-softimpact 
It looks like you are hitting https://github.com/googleads/googleads-mobile-flutter/issues/892 which is indicated that it's a platform-views issue in Flutter. 

I would suggest you follow https://github.com/flutter/flutter/issues/129632 for further updates. Closing the issue. If you think your case is different, please write in comments with more information and I will re-open this.
