### ISSUE TITLE
Upgrading to gradle 8.0 generates a compilation error

### ISSUE THREAD

**Issue by ivanfemia** [googleads/googleads-mobile-flutter#939]
## Plugin Version
Plugin version 3.1.0
Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (8 days ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

## Steps to Reproduce

Dependecie to gradle 8.0 updated to 
classpath 'com.android.tools.build:gradle:8.1.0' (automatically)

**Expected results:**
Application to build correctly

**Actual results:** 
```
A problem occurred configuring project ':google_mobile_ads'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```
**Workaround:**
Downgrading gradle to its previous value ```classpath 'com.android.tools.build:gradle:7.4.2'``` application compiles as expected

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/839. It's fixed but hasn't been released yet. Closing this issue as a duplicate, so please follow up on it for further updates.
