### ISSUE TITLE
[Feature request] Collapsible banner ads Flutter support

### ISSUE THREAD

**Issue by zfc0812** [googleads/googleads-mobile-flutter#941]
I noticed there is a new ads format called collapsible banner ads which is supported on both [Android](https://developers.google.com/admob/android/banner/collapsible) and [iOS](https://developers.google.com/admob/ios/banner/collapsible).

Is collapsible banner ads supported in Flutter?

**Comment by GeceGibi** [comment]
any change or work about this ?

**Comment by malandr2** [comment]
@GeceGibi no change to report other than this is something the team is aware of. Nothing official has been time budgeted for next steps as we approach 2024.

**Comment by victorvhpg** [comment]
Any update?

**Comment by NhaPCS** [comment]
any update?

**Comment by vavadiyahiren** [comment]
+1

**Comment by ThuyenPV** [comment]
any news ?

**Comment by hautvfami** [comment]
Will flutter or native have better revenue from advertising? how to maximize revenue from flutter app?

**Comment by Phlphat746** [comment]
ผมคิดว่าการใช้แอปพลิเคชั่นflutterก็ไม่เลวร้ายอะไรในการหารายใด้เพิ่มหรือว่าเลือกใด้อย่างเดียวแล้วตอนนี้ที่ผมทำมันยังไม่สำเร็จหรือปล่าวถ้ายังจะมีวิธีการแก้ไขใด้หรือไม่เพราะผมก็อยากเพิ่มรายใด้จากการโฆษณานั่นแหละครับ.

**Comment by Hieuntdz** [comment]
any update

**Comment by trunghaudinh** [comment]
Now you can setup banner collapsible. Add AdRequest to request in BannerAd.
exam:
`BannerAd(
        adUnitId: key,
        size: size,
        request: AdRequest(extras: {"collapsible": "bottom"}),
         );`

remember setup collapsible in admob

**Comment by Hieuntdz** [comment]
@trunghaudinh can you share doc

**Comment by trunghaudinh** [comment]
@Hieuntdz check this link: https://developers.google.com/ad-manager/mobile-ads-sdk/android/banner/collapsible

**Comment by danieeelfc** [comment]
@trunghaudinh is awesome. It's not documented on flutter but you found it out. Massive kudos!

**Comment by Sanaullah49** [comment]
> @trunghaudinh can you share document say add `extras: {"collapsible": "bottom"}`

Well, it doesn't work anyway

**Comment by danieeelfc** [comment]
I would advise to add also the following to extras: {"collapsible_request_id": generateUUID()} 

Otherwise the banner will expand every 30-120 seconds, depending on your refresh rate.

**Comment by malandr2** [comment]
Hi @all,

We've just published a [developer guide for Collapsible Banner in Flutter](https://developers.google.com/admob/flutter/banner/collapsible)

**Comment by hhzhangzy** [comment]
> Hi @ALL,
> 
> We've just published a [developer guide for Collapsible Banner in Flutter](https://developers.google.com/admob/flutter/banner/collapsible)

Is version google_mobile_ads ^4.0.0 supported?

**Comment by Jigneshiosdeveloper** [comment]
I implemented collapsible banner ads in my Flutter project. It is working very fine for both Android and iOS platforms. It allows the collapse button to back the banner in standard size. You can checkout examples to integrate [collapsible banner adMob](https://fluttertutorialhub.com/admob/collapsible-banner-admob-ads-flutter/) in Flutter.

**Comment by Xarvalus** [comment]
> I would advise to add also the following to extras: {"collapsible_request_id": generateUUID()}
> 
> Otherwise the banner will expand every 30-120 seconds, depending on your refresh rate.

Can someone confirm that it's indeed needed?
I have landed on couple of Android resources and it seems it (at least was) needed to omit refreshing already loaded ad as expended.

    import 'package:uuid/uuid.dart';

    var uuid = Uuid();

    void _loadBannerAd() async {
      // ...

      var adRequest = AdRequest(extras: {
        "collapsible": "bottom",
        "collapsible_request_id": uuid.v4(),
      });
    }

**Comment by faizahmaddae** [comment]
> Now you can setup banner collapsible. Add AdRequest to request in BannerAd. example: `BannerAd( adUnitId: key, size: size, request: AdRequest(extras: {"collapsible": "bottom"}), );`
> 
> remember setup collapsible in admob

not working bro

`import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:insta/ads/consent_manager.dart';

class BannerAdWidget extends StatefulWidget {
  final String adUnitId;

  const BannerAdWidget({
    super.key,
    required this.adUnitId,
  });

  @override
  _BannerAdWidgetState createState() => _BannerAdWidgetState();
}

class _BannerAdWidgetState extends State<BannerAdWidget> {
  BannerAd? _bannerAd;
  bool _isAdLoaded = false;
  final ConsentManager _consentManager = ConsentManager.instance;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _gatherConsentAndLoadAd();
  }

  void _gatherConsentAndLoadAd() {
    _consentManager.gatherConsent((FormError? error) async {
      if (error == null) {
        bool canRequestAds = await _consentManager.canRequestAds();
        if (canRequestAds) {
          _loadAd();
        } else {
          debugPrint('User consent is not sufficient to request ads.');
        }
      } else {
        debugPrint('Error gathering consent: ${error.message}');
      }
    });
  }

  Future<void> _loadAd() async {
    await _bannerAd?.dispose();
    setState(() {
      _bannerAd = null;
      _isAdLoaded = false;
    });

    final AnchoredAdaptiveBannerAdSize? adSize = await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
      MediaQuery.of(context).size.width.truncate(),
    );

    if (adSize == null) {
      debugPrint('Unable to get height of anchored banner.');
      return;
    }

    const adRequest = AdRequest(extras: {
      "collapsible": "bottom",
    });

    _bannerAd = BannerAd(
      adUnitId: widget.adUnitId,
      size: adSize,
      request: adRequest,
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          debugPrint('$ad loaded: ${ad.responseInfo}');
          setState(() {
            _bannerAd = ad as BannerAd;
            _isAdLoaded = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          debugPrint('Banner ad failed to load: $error');
          ad.dispose();
        },
      ),
    );
    _bannerAd!.load();
  }

  Widget _buildAdWidget() {
    return OrientationBuilder(
      builder: (context, orientation) {
        if (_bannerAd != null && _isAdLoaded) {
          return Container(
            alignment: Alignment.bottomCenter,
            width: _bannerAd!.size.width.toDouble(),
            height: _bannerAd!.size.height.toDouble(),
            child: AdWidget(ad: _bannerAd!),
          );
        }
        return const SizedBox.shrink();
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return _buildAdWidget();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }
}
`

**Comment by baotrankhtn** [comment]
> > Now you can setup banner collapsible. Add AdRequest to request in BannerAd. example: `BannerAd( adUnitId: key, size: size, request: AdRequest(extras: {"collapsible": "bottom"}), );`
> > remember setup collapsible in admob
> 
> not working bro
> 
> `import 'package:flutter/material.dart'; import 'package:google_mobile_ads/google_mobile_ads.dart'; import 'package:insta/ads/consent_manager.dart';
> 
> class BannerAdWidget extends StatefulWidget { final String adUnitId;
> 
> const BannerAdWidget({ super.key, required this.adUnitId, });
> 
> [@OverRide](https://github.com/OverRide) _BannerAdWidgetState createState() => _BannerAdWidgetState(); }
> 
> class _BannerAdWidgetState extends State { BannerAd? _bannerAd; bool _isAdLoaded = false; final ConsentManager _consentManager = ConsentManager.instance;
> 
> [@OverRide](https://github.com/OverRide) void didChangeDependencies() { super.didChangeDependencies(); _gatherConsentAndLoadAd(); }
> 
> void _gatherConsentAndLoadAd() { _consentManager.gatherConsent((FormError? error) async { if (error == null) { bool canRequestAds = await _consentManager.canRequestAds(); if (canRequestAds) { _loadAd(); } else { debugPrint('User consent is not sufficient to request ads.'); } } else { debugPrint('Error gathering consent: ${error.message}'); } }); }
> 
> Future _loadAd() async { await _bannerAd?.dispose(); setState(() { _bannerAd = null; _isAdLoaded = false; });
> 
> ```
> final AnchoredAdaptiveBannerAdSize? adSize = await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
>   MediaQuery.of(context).size.width.truncate(),
> );
> 
> if (adSize == null) {
>   debugPrint('Unable to get height of anchored banner.');
>   return;
> }
> 
> const adRequest = AdRequest(extras: {
>   "collapsible": "bottom",
> });
> 
> _bannerAd = BannerAd(
>   adUnitId: widget.adUnitId,
>   size: adSize,
>   request: adRequest,
>   listener: BannerAdListener(
>     onAdLoaded: (Ad ad) {
>       debugPrint('$ad loaded: ${ad.responseInfo}');
>       setState(() {
>         _bannerAd = ad as BannerAd;
>         _isAdLoaded = true;
>       });
>     },
>     onAdFailedToLoad: (Ad ad, LoadAdError error) {
>       debugPrint('Banner ad failed to load: $error');
>       ad.dispose();
>     },
>   ),
> );
> _bannerAd!.load();
> ```
> 
> }
> 
> Widget _buildAdWidget() { return OrientationBuilder( builder: (context, orientation) { if (_bannerAd != null && _isAdLoaded) { return Container( alignment: Alignment.bottomCenter, width: _bannerAd!.size.width.toDouble(), height: _bannerAd!.size.height.toDouble(), child: AdWidget(ad: _bannerAd!), ); } return const SizedBox.shrink(); }, ); }
> 
> [@OverRide](https://github.com/OverRide) Widget build(BuildContext context) { return _buildAdWidget(); }
> 
> [@OverRide](https://github.com/OverRide) void dispose() { _bannerAd?.dispose(); super.dispose(); } } `

have you found the solution? I follow the guide but it shows the basic banner ad only
