### ISSUE TITLE
iOS: No sound in RewardedAd video

### ISSUE THREAD

**Issue by adpg** [googleads/googleads-mobile-flutter#942]
### [REQUIRED] Step 1: Describe your environment
- flutter version 3.13.8
- dart version 3.1.4
- Xcode 15.0.1
- google_mobile_ads v 3.1.0

### [REQUIRED] Step 2: Describe the problem
When a test RewardedAd is played in a iOS mobile app, video shows fine but audio is missing. The same app playing a test RewardedAd in Android outputs video with working audio, as expected.

## Steps to Reproduce

1. Download and setup example code for the 'Adding AdMob ads to a Flutter app' codelab from https://github.com/googlecodelabs/admob-ads-in-flutter (completed code)
2. Update pubspec.yaml to set environment/sdk to sdk: ">=3.0.5 <4.0.0"; set google_mobile_ads plugin to version 3.1.0, google_fonts v. 6.1.0
3. Run the app using iOS Simulator or physical iPhone, tap the 'Hints' button to get a RewardedAd video
4. RewardedAd video plays fine but audio is missing

**Expected results: RewardedAd video with audio (as is the result in Android app on emulator or physical Android device)** 

**Actual results: RewardedAd video with audio missing on iOS Simulator/device** 

<details>
  <summary>Logs
Running the app with 'flutter run --verbose' shows no errors or exceptions, both flutter analyze and flutter doctor output 'No issues found!'.
</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Thanks for the update. Regarding your tests, the issue only appears with simulator. I'm leaning more towards the simulator issue than the ad plugin (the simulator won't be as accurate as the physical device in some cases not just with ad: text rendering, camera, etc).

To make sure about this, could you help to check with ad native iOS example [here](https://github.com/googleads/googleads-mobile-ios-examples) on simulator?

**Comment by adpg** [comment]
I tested two of the [googleads-mobile-ios-examples](https://github.com/googleads/googleads-mobile-ios-examples) modules you pointed out: Native Advanced Example and Rewarded Video Example, with the following results (equal for both modules):
- simulator iPhone SE (3rd generation): muting/unmuting was necessary for audio to be present with video, every time the simulator device was restarted;
- simulator iPhone 15 Pro: audio present with video regardless of restarting simulator device, no muting/unmuting necessary;
- connected physical iPhone SE 2016: audio present with video regardless of restarting physical device

So, like you concluded, it seems that the issue only appears with simulator and then only with the SE 3rd generation model (I'm not to keen testing all the other available Simulator models), so I'm assuming no problems with my app using the google admob plugin on actual devices.

**Comment by huycozy** [comment]
Thank you for checking this across simulators. It's probably a simulator issue rather than ad plugin issue, so I'm going to close this issue from here.
