### ISSUE TITLE
[Feature request][iOS] Sending an error message when AdMob app ID is incorrect

### ISSUE THREAD

**Issue by muddi900** [googleads/googleads-mobile-flutter#943]
---

## Plugin Version

3.0.0

## Steps to Reproduce

1. Create a flutter project.
2. Add incorrect id to info.plist
3. Add this package and init.
4. Run the file in the iOS simulator or a connected device.

**Expected results:** An error message in the IDE debug console/stderr/stdout.

**Actual results:** App crashes because the error in not handled. Which throws a SIGABRT on iOS, causing a crash.

<details>
  <summary>Logs</summary>

Apple crash logs: https://rentry.co/maiker-crash-report

```
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.13.8 on channel stable at /Users/mudassirchapra/.puro/envs/main/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (7 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mudassirchapra/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • CECC9192-6301-4991-B148-75144438B0CC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 118.0.5993.88

[✓] Network resources
    • All expected network resources are available.

```

</details>

The issue can be resolved by adding the correct id value. However, this should not crash the app altogether. It took me a week and lots of frustration and filing an issue with the main flutter repo, and then poring over the logs and Apple's docs to fix the issue. Error handling would solve it.

**Comment by huycozy** [comment]
Hi @muddi900 
This is documented at https://developers.google.com/admob/flutter/quick-start#ios for providing a `GADApplicationIdentifier` with AdMob app ID value.

>However, this should not crash the app altogether

I also see the app crashed even with iOS native example [here](https://github.com/googleads/googleads-mobile-ios-examples). I'm not quite sure about the feasibility of preventing crashes in the plugin layer, so I'll label this issue as a proposal to other's inputs.

**Comment by hedihadi** [comment]
would be great if they add it, i literally spent 2 days debugging what was crashing my app, had to test my packages one by one to find out i forgot to add the appid

**Comment by malandr2** [comment]
Hi @hedihadi, this is a [known Flutter issue](https://github.com/flutter/flutter/issues/22536) that some logs are not propagated in the Flutter console. When this happens, the best thing to do is open the iOS project and run it directly in Xcode to see any iOS exception logs.

As for the crash itself, the Google Mobile Ads SDK crashes the app by design if the app ID is not implemented correctly. As @huycozy was saying, refer to the [Get started](https://developers.google.com/admob/flutter/quick-start#ios) docs for providing a GADApplicationIdentifier with AdMob app ID value.
