### ISSUE TITLE
[Feature Request] Support Ads for Desktop platforms for Game Engines

### ISSUE THREAD

**Issue by kirill-21** [googleads/googleads-mobile-flutter#947]
Hi, i've seen that this feature request was already present in this repo right here: https://github.com/googleads/googleads-mobile-flutter/issues/525, however, it was closed, but this idea can be reconsidered from a different angle.

Since Flutter now supports game development with [Flutter Flame](https://pub.dev/packages/flame) and soon there will be [Rive GameKit](https://rive.app/renderer), ads support becomes essential, that's literally one of the most-used monetization methods in Gaming, especially 2D ones.

**Comment by huycozy** [comment]
Hi @kirill-21 
I think we can re-open https://github.com/googleads/googleads-mobile-flutter/issues/525. Please leave there your comment that may help to consolidate that issue.

Closing this issue in favor of that one.
