### ISSUE TITLE
App lagging when writing on a textfield if trying to 

### ISSUE THREAD

**Issue by alpebubekir** [googleads/googleads-mobile-flutter#949]
IOS app lagging when try to write on a TextField if any banner ad called. 

It is not happining with other ad types.

With Banner ad:
<img width="280" alt="Screenshot 2023-11-03 at 20 20 31" src="https://github.com/googleads/googleads-mobile-flutter/assets/72945401/5cc07243-2946-4905-a1dc-41486cddfca6">

Without Banner ad:
<img width="280" alt="Screenshot 2023-11-03 at 20 23 09" src="https://github.com/googleads/googleads-mobile-flutter/assets/72945401/fcfca1ff-5d1f-4e36-bd36-26023a3a8832">

**Comment by huycozy** [comment]
Hi @alpebubekir 

Which device are you seeing this issue? (OS, model)

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include other 3rd party plugins or complex production code so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by alpebubekir** [comment]
Page1:
`import 'package:flutter/material.dart';

class Page1 extends StatefulWidget {
  const Page1({super.key});

  @override
  State<Page1> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          BannerAdWidget(),
          ElevatedButton(
            onPressed: () {
              Navigator.push(
                  context, MaterialPageRoute(builder: (c) => Page2()));
            },
            child: Text("Go To Page2"),
          )
        ],
      ),
    );
  }
}
`

Page2:

`import 'package:flutter/material.dart';

class Page2 extends StatefulWidget {
  const Page2({super.key});

  @override
  State<Page2> createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          TextField(),
        ],
      ),
    );
  }
}
`
@huycozy thanks for reply. Above you have an example of my situation.

`[✓] Flutter (Channel master, 3.16.0-20.0.pre.1, on macOS 14.0 23A344 darwin-arm64, locale en-TR)
    • Flutter version 3.16.0-20.0.pre.1 on channel master at /Users/apple/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e12d1a798c (12 days ago), 2023-10-29 15:00:30 -0700
    • Engine revision 84dcb4fb93
    • Dart version 3.3.0 (build 3.3.0-71.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/apple/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 0931D16E-6181-459D-B040-68AB9A47408C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!`

and here is my "flutter doctor -v" result.

**Comment by malandr2** [comment]
Thanks for the code snippet @alpebubekir, this is currently being investigated by the team. I will respond here as soon as I have an update

**Comment by alpebubekir** [comment]
Hi again @malandr2. You have any update so far?

**Comment by malandr2** [comment]
Hi @alpebubekir,

The lagging cannot be reproduced. Can you provide the code to your `BannerAdWidget()`?. Or if possible, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include other 3rd party plugins or complex production code so that we may verify this.

**Comment by NiuXiaoGuang** [comment]
I also encountered the same problem

**Comment by NiuXiaoGuang** [comment]
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const PingPage(),
    );
  }
}

class PingPage extends StatefulWidget {
  const PingPage({super.key});

  @override
  State<StatefulWidget> createState() {
    return PingPageState();
  }
}

class PingPageState extends State<PingPage> {
  final List<Widget> _widgetList = [];

  //横幅广告
  BannerAd? _bannerAd;

  //横幅广告加载标记
  bool _isLoaded = false;

  @override
  Future<void> didChangeDependencies() async {
    super.didChangeDependencies();
    //加载广告
    _loadBannerAd();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body:ListView(
          children: [Column(
            children: [
              if (_bannerAd != null && _isLoaded)
                Container(
                  margin: const EdgeInsets.only(top: 3),
                  color: Colors.white,
                  width: _bannerAd!.size.width.toDouble(),
                  height: _bannerAd!.size.height.toDouble(),
                  child: AdWidget(ad: _bannerAd!),
                ),
              const TextField(),
            ],
          )],
        )
    );
  }

  //获取横幅横幅广告尺寸
  Future<void> _loadBannerAd() async {
    // Get an AnchoredAdaptiveBannerAdSize before loading the ad.
    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      //Global.logger.w('无法获得锚定横幅的高度.');
      return;
    }

    _bannerAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          //Global.logger.w('$ad 锚定自适应横幅 加载成功: ${ad.responseInfo}');
          setState(() {
            _bannerAd = ad as BannerAd;
            _isLoaded = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          //Global.logger.w('锚定自适应横幅 加载失败: $error');
          ad.dispose();
        },
      ),
    );
    return _bannerAd!.load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }
}

**Comment by NiuXiaoGuang** [comment]
`import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const PingPage(),
    );
  }
}

class PingPage extends StatefulWidget {
  const PingPage({super.key});

  @override
  State<StatefulWidget> createState() {
    return PingPageState();
  }
}

class PingPageState extends State<PingPage> {
  final List<Widget> _widgetList = [];

  //横幅广告
  BannerAd? _bannerAd;

  //横幅广告加载标记
  bool _isLoaded = false;

  @override
  Future<void> didChangeDependencies() async {
    super.didChangeDependencies();
    //加载广告
    _loadBannerAd();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body:ListView(
          children: [Column(
            children: [
              if (_bannerAd != null && _isLoaded)
                Container(
                  margin: const EdgeInsets.only(top: 3),
                  color: Colors.white,
                  width: _bannerAd!.size.width.toDouble(),
                  height: _bannerAd!.size.height.toDouble(),
                  child: AdWidget(ad: _bannerAd!),
                ),
              const TextField(),
            ],
          )],
        )
    );
  }

  //获取横幅横幅广告尺寸
  Future<void> _loadBannerAd() async {
    // Get an AnchoredAdaptiveBannerAdSize before loading the ad.
    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      //Global.logger.w('无法获得锚定横幅的高度.');
      return;
    }

    _bannerAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          //Global.logger.w('$ad 锚定自适应横幅 加载成功: ${ad.responseInfo}');
          setState(() {
            _bannerAd = ad as BannerAd;
            _isLoaded = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          //Global.logger.w('锚定自适应横幅 加载失败: $error');
          ad.dispose();
        },
      ),
    );
    return _bannerAd!.load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }
}
`

**Comment by alpebubekir** [comment]
> I also encountered the same problem

Hi @NiuXiaoGuang. I solved this issue by writing a statefull widget for banner ads. Not disposing the banner ad causes this error. You should dispose the banner ad when it is no longer in use. I am closing the issue because it is resolved.
