### ISSUE TITLE
Match Rate from 96% to 40%

### ISSUE THREAD

**Issue by akhilgorantala** [googleads/googleads-mobile-flutter#952]
match rate from 96% to 40% after the update, in the start i used to have a native app i moved everything to the flutter and used this package, sometime i even get 30% match rate very poor package.

**Comment by huycozy** [comment]
Hi @akhilgorantala 
Does this issue appear after creating a new ad unit id? If so, please give it a week as mentioned in the AdMob support: https://support.google.com/admob/answer/9655701

**Comment by malandr2** [comment]
Closing this issue out as it is not directly related to the flutter plugin but rather ad serving which the plugin as no control over. If you still are experiencing issues please create a thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk). Thanks.
