### ISSUE TITLE
[iOS] Support Google-Mobile-Ads-SDK 10.11.0 and iOS 17

### ISSUE THREAD

**Issue by cog-iagentur** [googleads/googleads-mobile-flutter#953]
Could you update supported Google-Mobile-Ads-SDK version to 10.11.0, it fixes a bug in iOS 17 which "could cause some creatives to display incorrectly when an ad is loaded in one orientation but presented in another".

**Comment by malandr2** [comment]
Hi @cog-iagentur, the next release will include support for the latest iOS and Android Google Mobile Ads SDK versions. We expect have another release before the end of the year.
