### ISSUE TITLE
Interstitial and rewarded not presented for Flutter Android in emulator.

### ISSUE THREAD

**Issue by AnyMindG** [googleads/googleads-mobile-flutter#955]
**System/Configuration** 

Flutter version 3.13.2
Dart version 3.1.0
Android SDK version 33.0.2
Android Studio (version 2022.2)
google_mobile_ads: ^3.1.0
CocoaPods version 1.12.1
(Xcode 14.3)

Interstitial and rewarded are loaded but not presented in Flutter Android. Flutter iOS is working fine.

**Comment by huycozy** [comment]
Hi @AnyMindG 
I'm still seeing Interstitial and Rewarded ads on Android emulator with [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example):

| Interstitial | Rewarded |
| --------------- | --------------- |
<img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/cf90889f-582d-4156-affa-a76897b01e2b"> | <img width="400" src="https://github.com/googleads/googleads-mobile-flutter/assets/104349824/338f84ac-78c6-48d0-8023-65077fbef0b3">

Please also try running this sample on your side. If the ads still can't be shown, please provide the emulator info (OS version, model). Thanks!

**Comment by malandr2** [comment]
Closing this issue as I also cannot replicate - if this issue still persists, please provide more information, per @huycozy
