### ISSUE TITLE
UMP consent dialog does not initialise or show on iOS 17.2 Beta but works as expected on earlier iOS versions. 

### ISSUE THREAD

**Issue by chrissy-dev** [googleads/googleads-mobile-flutter#958]
## Plugin Version

` google_mobile_ads: ^3.1.0`

### Step 2: Describe the problem

UMP consent dialog does not initialise or show on iOS 17.2 Beta. It works as expected on earlier iOS versions. 

## Steps to Reproduce

1. [Download iOS 17.2 simulator runtime](https://developer.apple.com/download/all/?q=Simulator%20Runtime) and install it or update a test device to iOS 17.2 beta.
2. Implement the basic UMP consent message for here: [https://developers.google.com/admob/flutter/eu-consent](https://developers.google.com/admob/flutter/eu-consent)
3. Attempting to initialise the dialog results error: ```The URL can’t be shown```.

**Comment by huycozy** [comment]
Hi @chrissy-dev 
Could you please share a minimal sample code for this? Please also provide the complete error message if any. Thank you!

**Comment by malandr2** [comment]
Closing this issue as it it not something that can be addressed by the flutter plugin team. That being said, this has been acknowledged and is already being addressed internally by the greater engineering team. The update for this will not require an update to the plugin. The fix should be addressed before the end of the week.

If you are still affected by this issue after next week, please start a thread in the [Developers forum](https://groups.google.com/g/google-admob-ads-sdk)
