### ISSUE TITLE
onAdImpression not called after the ad is reloaded

### ISSUE THREAD

**Issue by phamconganh** [googleads/googleads-mobile-flutter#959]
## Plugin Version
`google_mobile_ads: ^3.1.0`

## Steps to Reproduce

1. load `BannerAd` or `NativeAd` for the first time; log `ad.adUnitId`, `ad.responseInfo?.responseId` on `onAdLoaded`, `onAdImpression`; and display the ad when completed.
2. Reload the ad and render when done. `onAdLoaded` was logged but `onAdImpression` was not.
3. Re-show the ad without reloading it. `onAdImpression` is logged;

**Expected results:** 
`onAdImpression` is called in step 2;
**Actual results:** 
`onAdImpression` is called in step 3;

**Comment by malandr2** [comment]
Hi @phamconganh,

Using our [Banner sample](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/banner_example) I was able to see `onAdImpression` is called the first time the ad was loaded/rendered.

Tested with:
Android Pixel 4 API 32
iOS 17.0 iPhone SE

Can you confirm this behavior as well?

**Comment by phamconganh** [comment]
@malandr2 Thanks for your replying. I was a newbie. Do you mean load the banner just once? If loading for the first time, display and then reload again. Problems will happen.

**Comment by phamconganh** [comment]
In my app, I load the banner ad and then reload after some minutes

**Comment by malandr2** [comment]
@phamconganh got it, thanks. So if I'm understanding this correctly you're saying ad impression is only logged once when the ad is first loaded but when the ad is reloaded, no impression is logged. 

Please try out our [Banner sample](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/banner_example), I am able to see an ad impression each time the ad is reloaded for both iOS/Android. Can you confirm? (iOS screenshot attached).


<img width="1394" alt="Screenshot 2023-11-17 at 9 26 59 AM" src="https://github.com/googleads/googleads-mobile-flutter/assets/5905170/261d26f6-6df8-4e46-b657-fb06376cd15a">


This leads me to believe this is an implementation error. If you have a minimum reproducible example to share I can take a look, but next steps would be to further debug your implementation. Remember that "an impression is counted when one or more pixels of the ad creative is visible on a device's screen."

Thanks.
