### ISSUE TITLE
Ads fail to load on iPhone with 5G Connection

### ISSUE THREAD

**Issue by lukeirvin** [googleads/googleads-mobile-flutter#961]
**Versions:**
`google_mobile_ads: ^3.1.0`
`flutter: 3.13.8`
`iOS 17.1.1`

While connected to my home wifi, all ads load without any issue.

If I switch my iPhone to 5G, I get `LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show.`

**Comment by malandr2** [comment]
Closing this issue out as this is an ad serving issue, which the mobile ads flutter plugin does not control. Please create a thread in the [Developer forum](https://groups.google.com/g/google-admob-ads-sdk) to have your issue addressed properly.

Thanks
