### ISSUE TITLE
How much native advertising is loaded initially?

### ISSUE THREAD

**Issue by Kristina-Isakovich** [googleads/googleads-mobile-flutter#968]
The documentation for Android says that there are two methods for loading native advertising: `loadAd()` and `loadAds()`.
The documentation for Flutter does not contain any information about the number of ads loaded when the `await NativeAd(.....).load()` function is called.
Can you please tell me how many ads are loaded?

**Comment by malandr2** [comment]
Hi @Kristina-Isakovich,

The [`load()`](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/NativeAd/load.html) function only loads one ad.
