### ISSUE TITLE
🐛 Your issue title here

### ISSUE THREAD

**Issue by imeDevelopers** [googleads/googleads-mobile-flutter#97]
E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232): Failed to handle method call
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232): java.lang.IllegalArgumentException: Ad forfollowing adId already exists: ٠
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:66)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:244)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +4 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.MessageQueue.nativePollOnce(Native Method)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.MessageQueue.next(MessageQueue.java:336)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.Looper.loop(Looper.java:184)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.app.ActivityThread.main(ActivityThread.java:7853)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at java.lang.reflect.Method.invoke(Native
Method)
[   +7 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232): Failed to handle method call
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232): java.lang.IllegalArgumentException: Ad forfollowing adId already exists: ١
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:66)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:244)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[   +4 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.MessageQueue.nativePollOnce(Native Method)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.MessageQueue.next(MessageQueue.java:336)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.os.Looper.loop(Looper.java:184)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
android.app.ActivityThread.main(ActivityThread.java:7853)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at java.lang.reflect.Method.invoke(Native
Method)
[   +3 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[   +2 ms] E/MethodChannel#plugins.flutter.io/google_mobile_ads(16232):         at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[   +3 ms] V/SensorManager(16232): unRegisterListener by com.hemanthraj.fluttercompass.FlutterCompassPlugin$1
[   +2 ms] V/SensorManager(16232): RegisterListener Rotation Vector  Non-wakeup type:11 delay:66667us by
com.hemanthraj.fluttercompass.FlutterCompassPlugin$1
[  +74 ms] W/hnology.ime.ap(16232): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist,      
linking, allowed)
[ +493 ms] E/flutter (16232): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception:
PlatformException(error, Ad for following adId already exists: ٠, null, java.lang.IllegalArgumentException: Ad forfollowing adId already exists: ٠
[  +10 ms] E/flutter (16232):   at
io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:66)
[   +5 ms] E/flutter (16232):   at
io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:244)
[  +51 ms] E/flutter (16232):   at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[   +6 ms] E/flutter (16232):   at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +4 ms] E/flutter (16232):   at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +3 ms] E/flutter (16232):   at android.os.MessageQueue.nativePollOnce(Native Method)
[   +4 ms] E/flutter (16232):   at android.os.MessageQueue.next(MessageQueue.java:336)
[   +3 ms] E/flutter (16232):   at android.os.Looper.loop(Looper.java:184)
[   +2 ms] E/flutter (16232):   at android.app.ActivityThread.main(ActivityThread.java:7853)
[   +2 ms] E/flutter (16232):   at java.lang.reflect.Method.invoke(Native Method)
[   +3 ms] E/flutter (16232):   at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[   +4 ms] E/flutter (16232):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[   +2 ms] E/flutter (16232): )
[   +3 ms] E/flutter (16232): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:581:7)
[   +2 ms] E/flutter (16232): #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:158:18)
[   +4 ms] E/flutter (16232): <asynchronous suspension>
[   +1 ms] E/flutter (16232): #2      BannerAd.load (package:google_mobile_ads/src/ad_containers.dart:455:5)      
[   +2 ms] E/flutter (16232): <asynchronous suspension>
[   +1 ms] E/flutter (16232): 
[   +2 ms] E/flutter (16232): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception:
PlatformException(error, Ad for following adId already exists: ١, null, java.lang.IllegalArgumentException: Ad forfollowing adId already exists: ١
[   +3 ms] E/flutter (16232):   at
io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:66)
[   +3 ms] E/flutter (16232):   at
io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:244)
[   +3 ms] E/flutter (16232):   at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[   +2 ms] E/flutter (16232):   at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +2 ms] E/flutter (16232):   at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +3 ms] E/flutter (16232):   at android.os.MessageQueue.nativePollOnce(Native Method)
[   +1 ms] E/flutter (16232):   at android.os.MessageQueue.next(MessageQueue.java:336)
[   +1 ms] E/flutter (16232):   at android.os.Looper.loop(Looper.java:184)
[   +1 ms] E/flutter (16232):   at android.app.ActivityThread.main(ActivityThread.java:7853)
[   +1 ms] E/flutter (16232):   at java.lang.reflect.Method.invoke(Native Method)
[   +2 ms] E/flutter (16232):   at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[   +2 ms] E/flutter (16232):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[   +2 ms] E/flutter (16232): )
[   +1 ms] E/flutter (16232): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:581:7)
[   +3 ms] E/flutter (16232): #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:158:18)
[   +2 ms] E/flutter (16232): <asynchronous suspension>
[   +2 ms] E/flutter (16232): #2      BannerAd.load (package:google_mobile_ads/src/ad_containers.dart:455:5)
[   +2 ms] E/flutter (16232): <asynchronous suspension>
[   +1 ms] E/flutter (16232):

**Comment by maheshmnj** [comment]
Hi @imeDevelopers when filing issues please try to fill all or some of the info requested info in the issue template this helps to better investigate the issue.

<details>
<summary>Issue template</summary>

```
<!-- Thank you for using Google Mobile Ads for Flutter!

     If you have found a bug or if our documentation doesn't have an answer
     to what you're looking for, then fill out the template below. Please read
     the Flutter's team guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
-->

## Plugin Version

<!-- Please tell us the version of the plugin used in your app. -->

## Steps to Reproduce

<!-- You must include full steps to reproduce so that we can reproduce the problem. -->

1. Run `flutter create bug`.
2. Update the files as follows: ... <!-- include every file that is different from the template app! -->
3. ... <!-- describe how to reproduce the problem -->

**Expected results:** <!-- what did you want to see? -->

**Actual results:** <!-- what did you see? -->

<details>
  <summary>Logs</summary>

<!--
      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->

```
```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->

```
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
```

</details>

```
</details>


 please provide the output of `flutter doctor -v` possibly a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exact steps to reproduce the issue.

Thanks.
