### ISSUE TITLE
Banner ads and TextField in the same Page will consume a lot of CUP resources

### ISSUE THREAD

**Issue by NiuXiaoGuang** [googleads/googleads-mobile-flutter#977]
### When TextField gets focus or gives up focus, it will occupy a lot of CPU resources and some memory.
Flutter Version :  3.16.2
Admob Version :   google_mobile_ads: ^4.0.0
Device ：Iphone 14 pro (ios17.2)
<img width="1792" alt="截屏2023-12-16 00 04 25" src="https://github.com/googleads/googleads-mobile-flutter/assets/30843465/297ddf62-dbc1-440d-82b5-4177d81835a1">
```
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const PingPage(),
    );
  }
}

class PingPage extends StatefulWidget {
  const PingPage({super.key});

  @override
  State<StatefulWidget> createState() {
    return PingPageState();
  }
}

class PingPageState extends State<PingPage> {
  BannerAd? _bannerAd;
  bool _isLoaded = false;

  @override
  Future<void> didChangeDependencies() async {
    super.didChangeDependencies();
    _loadBannerAd();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView(
      children: [
        Column(
          children: [
            if (_bannerAd != null && _isLoaded)
              Container(
                margin: const EdgeInsets.only(top: 3),
                color: Colors.white,
                width: _bannerAd!.size.width.toDouble(),
                height: _bannerAd!.size.height.toDouble(),
                child: AdWidget(ad: _bannerAd!),
              ),
            const TextField(),
          ],
        )
      ],
    ));
  }

  Future<void> _loadBannerAd() async {
    // Get an AnchoredAdaptiveBannerAdSize before loading the ad.
    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      return;
    }

    _bannerAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          setState(() {
            _bannerAd = ad as BannerAd;
            _isLoaded = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
        },
      ),
    );
    return _bannerAd!.load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }
}

```

**Comment by MrTavus** [comment]
i have same problem. when i use banner ads, consume lots of cpu. xcode shows 105% cpu. there is any solution?

**Comment by TiesPol** [comment]
I'm also experiencing a lot of jank when scrolling.

**Comment by malandr2** [comment]
@NiuXiaoGuang I am also to replicate the issue you are experiencing. 

If you put a log `print("HERE");` at `didChangeDependencies()` you will see that it gets called dozens of times when the keyboard is brought in/out of focus. Which means `loadBannerAd` is being called unnecessarily resulting in a the issue you are seeing. This is not a google_mobile_ads flutter plugin but rather an implementation issue that I see is being documented in our [Adaptive Banner Sample](https://github.com/googleads/googleads-mobile-flutter/blob/main/samples/admob/adaptive_banner_example/lib/main.dart#L51).

I will work on a solution and report back as soon as I have a PR. Thanks all.

**Comment by phamconganh** [comment]
By default admod has auto refresh feature, so i think the hot fix for this problem is to add `maxCacheDuration` (after `onAdLoaded`) around 2-4 hours and ad load `frequency` around 2 hours (after `onAdImpression`). With the Adaptive banner, I approach by creating 2 banner `landscape` and `portrait`, but if it's the same ad unit id, it's an issue #982.

**Comment by malandr2** [comment]
@all Check out https://github.com/googleads/googleads-mobile-flutter/pull/983 for the code changes needed to address this issue. Hoping to get it merged in next week.
