### ISSUE TITLE
[production] increased LoadAdError(code: 8, message: Not supported.. (ad request was not made due to a missing app ID) 

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#978]
as title

no code changed, just updated version

**Comment by malandr2** [comment]
Hi @peterweb2005,

The error code you are seeing appears to be from the [Android layer](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_APP_ID_MISSING) of the Google Mobile Ads codebase. This something that the AdMob Developers forum can help resolve. Please create an issue there as a next step. Thanks.
