### ISSUE TITLE
Ad suddenly stop showing without any notice - Ad failed to load : 3

### ISSUE THREAD

**Issue by BulbulH** [googleads/googleads-mobile-flutter#980]
I/Ads     (27163): GMA Debug BEGIN
I/Ads     (27163): GMA Debug CONTENT {"timestamp":1702926880842,"event":"onNetworkResponseBody","components":["network_request_3d3c029d-36f6-4a2c-b357-7eb3468877d4"],"params":{"body":"","bodylength":0}}
I/Ads     (27163): GMA Debug FINISH
I/Ads     (27163): Ad failed to load : 3
I/Ads     (27163): GMA Debug BEGIN
I/Ads     (27163): GMA Debug CONTENT {"timestamp":1702926880949,"event":"onNetworkRequest","components":["network_request_6842d61e-38eb-4368-acd7-167fa51353ec"],"params":{"firstline":{"uri":"https://csi.gstatic.com/csi?app=com.bulbulcse01.italian_card_leader_board&is_bstar=0&os=12&e=318496669%2C318500618%2C318486317%2C318491267%2C318482078%2C318483611%2C318484141%2C318484497%2C318501517%2C318508442%2C318503827%2C318509850%2C318512169%2C318512455%2C318512673%2C318513021%2C318512225%2C318512272&network_coarse=1&task.request-parcel=s.1&task.renderer=f.5&task.webview-cookie=s.14&task.server-transaction=s.837&task.signals=s.50&s=gmob_sdk&scar=false&is_lite_sdk=0&v=3&task.render-config-init=f.1&action=ftl&api_v=31&sdkVersion=afma-sdk-a-v234310999.233702000.1&network_fine=0&device=Xiaomi%20POCO%20M2%20Pro&gqi=IJqAZdK-KNCb9fwPtqWsOA&ftl=3&ed=com.google.android.gms.ads","verb":"GET"},"headers":[{"name":"User-Agent","value":"Mozilla/5.0 (Linux; Android 12; POCO M2 Pro Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36 (Mobile; afma-sdk-a-v234310999.233702000.1)"}]}}
I/Ads     (27163): GMA Debug FINISH
I/flutter (27163): Inline adaptive banner failedToLoad: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No fill., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})
I/Ads     (27163): GMA Debug BEGIN
I/Ads     (27163): GMA Debug CONTENT {"timestamp":1702926883187,"event":"onNetworkResponse","components":["network_request_6842d61e-38eb-4368-acd7-167fa51353ec"],"params":{"firstline":{"code":204},"headers":[{"name":null,"value":"HTTP/1.1 204 No Content"},{"name":"Alt-Svc","value":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"},{"name":"Server","value":"Golfe2"},{"name":"Access-Control-Allow-Origin","value":"*"},{"name":"Last-Modified","value":"Wed, 21 Jan 2004 19:51:30 GMT"},{"name":"Pragma","value":"no-cache"},{"name":"X-Android-Received-Millis","value":"1702926883182"},{"name":"Date","value":"Mon, 18 Dec 2023 19:14:42 GMT"},{"name":"X-Android-Selected-Protocol","value":"http/1.1"},{"name":"Cache-Control","value":"no-cache, no-store, must-revalidate"},{"name":"X-Android-Response-Source","value":"NETWORK 204"},{"name":"Cross-Origin-Resource-Policy","value":"cross-origin"},{"name":"Expires","value":"Fri, 01 Jan 1990 00:00:00 GMT"},{"name":"X-Android-Sent-Millis","value":"1702926882140"},{"name":"Content-Length","value":"0"},{"name":"Content-Type","value":"image/gif"}]}}
I/Ads     (27163): GMA Debug FINISH
D/DecorView[](27163): onWindowFocusChanged hasWindowFocus false
D/DecorView[](27163): onWindowFocusChanged hasWindowFocus true

**Comment by BulbulH** [comment]
flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] Connected device (5 available)
    ! Device emulator-5578 is offline.
[√] Network resources

! Doctor found issues in 2 categories.


flutter analyze
Resolving dependencies... 
  intl 0.18.1 (0.19.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  package_rename 1.5.1 (1.5.2 available)
  path 1.8.3 (1.9.0 available)
  synchronized 3.1.0 (3.1.0+1 available)
  test_api 0.6.1 (0.7.0 available)
  url_launcher 6.2.1 (6.2.2 available)
  url_launcher_linux 3.1.0 (3.1.1 available)
  url_launcher_web 2.2.1 (2.2.2 available)
  url_launcher_windows 3.1.0 (3.1.1 available)
  web 0.3.0 (0.4.0 available)
Got dependencies!
14 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Analyzing card_score_counter_updated...                                 

warning - The include file 'package:flutter_lints/flutter.yaml' in 'C:\Users\Administrator\StudioProjects\card_score_counter_updated\analysis_options.yaml' can't be found when analyzing
       'C:\Users\Administrator\StudioProjects\card_score_counter_updated' - analysis_options.yaml:10:10 - include_file_not_found
   info - 'canLaunch' is deprecated and shouldn't be used. Use canLaunchUrl instead - lib\AboutUs.dart:90:15 - deprecated_member_use
   info - 'launch' is deprecated and shouldn't be used. Use launchUrl instead - lib\AboutUs.dart:91:13 - deprecated_member_use
warning - Unused import: 'package:italian_card_leader_board/AppDrawer.dart' - lib\CustomScore\CustomPlayersScore.dart:4:8 - unused_import
warning - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: customPlayersScore.playerList - lib\CustomScore\CustomPlayersScore.dart:16:7 -
       must_be_immutable
warning - Unused import: 'dart:convert' - lib\CustomScore\ScoreBoard.dart:1:8 - unused_import
   info - The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\CustomScore\ScoreBoard.dart:4:8 - unnecessary_import  
warning - Unused import: 'package:italian_card_leader_board/AppDrawer.dart' - lib\CustomScore\ScoreBoard.dart:10:8 - unused_import
warning - The value of the field '_fadeInFadeOut' isn't used - lib\CustomScore\ScoreBoard.dart:53:26 - unused_field
warning - The left operand can't be null, so the right operand is never executed - lib\CustomScore\ScoreBoard.dart:653:44 - dead_null_aware_expression
warning - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\CustomScore\ScoreBoard.dart:658:27 - unused_catch_clause
warning - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\CustomScore\ScoreBoard.dart:681:37 - unused_catch_clause
warning - The value of the local variable 'result' isn't used - lib\CustomScore\ScoreBoard.dart:748:11 - unused_local_variable
warning - This function has a nullable return type of 'FutureOr<List<Widget>?>', but ends without returning a value - lib\CustomScore\ScoreBoard.dart:754:25 - body_might_complete_normally_nullable
warning - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\CustomScore\ScoreBoard.dart:969:43 - unused_catch_clause
warning - The operand can't be null, so the condition is always 'true' - lib\CustomScore\ScoreBoard.dart:1340:35 - unnecessary_null_comparison
warning - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ScoreList.isDark - lib\CustomScore\ScoreBoard.dart:1460:7 - must_be_immutable
warning - The operand can't be null, so the condition is always 'true' - lib\CustomScore\databaseModel\model.dart:29:12 - unnecessary_null_comparison
warning - The operand can't be null, so the condition is always 'true' - lib\CustomScore\databaseModel\model.dart:87:12 - unnecessary_null_comparison
warning - Unused import: 'package:italian_card_leader_board/AppDrawer.dart' - lib\CustomScore\history.dart:6:8 - unused_import
warning - Unused import: 'dart:io' - lib\ItalianScore\admobAdd.dart:2:8 - unused_import
warning - The value of the field '_interstitialAd' isn't used - lib\ItalianScore\admobAdd.dart:17:19 - unused_field
warning - The value of the field '_numInterstitialLoadAttempts' isn't used - lib\ItalianScore\admobAdd.dart:18:7 - unused_field
warning - The value of the field '_rewardedAd' isn't used - lib\ItalianScore\admobAdd.dart:20:15 - unused_field
warning - The value of the field '_numRewardedLoadAttempts' isn't used - lib\ItalianScore\admobAdd.dart:21:7 - unused_field
warning - Unused import: 'ItalianScore/ItalianLeaderBoard.dart' - lib\splashScreen.dart:3:8 - unused_import
warning - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SplashScreen.splash - lib\splashScreen.dart:6:7 - must_be_immutable
   info - The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\utilits\CommonFunctions.dart:3:8 - unnecessary_import 
   info - 'canLaunch' is deprecated and shouldn't be used. Use canLaunchUrl instead - lib\utilits\CommonFunctions.dart:8:13 - deprecated_member_use
   info - 'launch' is deprecated and shouldn't be used. Use launchUrl instead - lib\utilits\CommonFunctions.dart:9:11 - deprecated_member_use
warning - Unused import: 'package:italian_card_leader_board/model/model.dart' - lib\utilits\DB_Helper.dart:2:8 - unused_import
warning - Unused import: '../ItalianScore/ItalianLeaderBoard.dart' - lib\widgets\widgets.dart:3:8 - unused_import
warning - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: BoardGroup.CallButtonPressed, BoardGroup.BonusCallButton, BoardGroup.onDismissed,       
       BoardGroup.GroupScore, BoardGroup.GroupName, BoardGroup.GrupCallText, BoardGroup.isCalled, BoardGroup.GroupCalled, BoardGroup.isFinised - lib\widgets\widgets.dart:7:7 - must_be_immutable
warning - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: CustomHistoryListView.GroupA1, CustomHistoryListView.GroupA2,
       CustomHistoryListView.GroupAresult, CustomHistoryListView.GroupB1, CustomHistoryListView.GroupB2, CustomHistoryListView.GroupBresult, CustomHistoryListView.isGroupASuccess, CustomHistoryListView.isGroupBSuccess -
       lib\widgets\widgets.dart:403:7 - must_be_immutable
  error - Target of URI doesn't exist: 'package:card_score_counter_updated/main.dart' - test\widget_test.dart:11:8 - uri_does_not_exist
  error - The name 'MyApp' isn't a class - test\widget_test.dart:16:35 - creation_with_non_type

36 issues found. (ran in 11.3s)

**Comment by malandr2** [comment]
Hi @BulbulH 

It seems your issue is best suited on [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk). I can see there are some similar issue there with above error code and message:

https://groups.google.com/g/google-admob-ads-sdk/c/1Q9rRNVAKYo/m/XBhQseM2AQAJ
https://groups.google.com/g/google-admob-ads-sdk/c/iyh17o76g44/m/UozyrWyHAAAJ

That being said, this googleads-mobile-flutter plugin and ads SDK in general don't have control on ad request fill rate. So I will close this issue as it's not a plugin issue. Thanks!

**Comment by vijayvaghela72** [comment]
any possible solution ?
