### ISSUE TITLE
AnchoredAdaptiveBanner examples contain wrong test AdUnitId

### ISSUE THREAD

**Issue by sperochon** [googleads/googleads-mobile-flutter#989]
Hello,

As state in the official doc here:
https://developers.google.com/admob/android/test-ads#demo_ad_units

Adaptive Banner test AdUnitId should be "ca-app-pub-3940256099942544/9214589741" but it is not here:
https://github.com/googleads/googleads-mobile-flutter/blob/3e9786a2d07c8cc57c6492318eebc8e13e976e89/packages/google_mobile_ads/example/lib/anchored_adaptive_example.dart#L64
neither here
https://github.com/googleads/googleads-mobile-flutter/blob/3e9786a2d07c8cc57c6492318eebc8e13e976e89/samples/admob/adaptive_banner_example/lib/main.dart#L44
Those values correspond to the simple normal banner AdUnitId, not the Adaptive one.

The same issue for iOS values (as state here https://developers.google.com/admob/ios/test-ads#demo_ad_units) which should be "ca-app-pub-3940256099942544/2435281174" below:
https://github.com/googleads/googleads-mobile-flutter/blob/3e9786a2d07c8cc57c6492318eebc8e13e976e89/packages/google_mobile_ads/example/lib/anchored_adaptive_example.dart#L65
and here
https://github.com/googleads/googleads-mobile-flutter/blob/3e9786a2d07c8cc57c6492318eebc8e13e976e89/samples/admob/adaptive_banner_example/lib/main.dart#L45

I did not check for other examples and other banner styles...

Thanks,
Seb.

**Comment by malandr2** [comment]
Hi @sperochon thanks for calling this out. I've put a PR https://github.com/googleads/googleads-mobile-flutter/pull/990 to replace the ad units. Thanks!

**Comment by malandr2** [comment]
Closing as https://github.com/googleads/googleads-mobile-flutter/pull/990 has been merged in.
