### ISSUE TITLE
The iOS app crashes on launch after upgrading the package to ^3.0.0.

### ISSUE THREAD

**Issue by chandankumarshanbhag** [googleads/googleads-mobile-flutter#993]
I tried all the versions from 3.0.0 to 4.0.0. the same package is working for Android but not for IOS. The problem is associated with the registration of platform views using the **webview_flutter_wkwebview** package. Specifically there is a memory spike during the registration process, indicated by the error message "VM - pmap_enter retried due to resource shortage."

`
Incident Identifier: E3EAF373-FCB2-4913-BCB0-BDA7BBA5C4B3
CrashReporter Key:   30B8AAF3-51EA-1C67-CBF7-21D4402E5555
Hardware Model:      Mac14,9
Process:             Runner [29403]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/29328854-033A-416A-A9E9-A83D387EEED9/data/Containers/Bundle/Application/C526A1C4-4467-4FB5-9F36-CCB9CF00BED1/Runner.app/Runner
Identifier:          com.ami.pep
Version:             1.1.0 (22)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [10663]
Coalition:           com.apple.CoreSimulator.SimDevice.29328854-033A-416A-A9E9-A83D387EEED9 [242629]
Responsible Process: SimulatorTrampoline [2530]

Date/Time:           2024-01-16 10:22:21.1494 +0530
Launch Time:         2024-01-16 10:22:12.1781 +0530
OS Version:          macOS 13.2.1 (22D68)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	       0x1047f69a8 ???
1   <translation info unavailable>	       0x1067a50e4 ???
2   libsystem_pthread.dylib       	       0x11db16f7b pthread_kill + 263
3   libsystem_c.dylib             	       0x119444ef2 __abort + 139
4   libsystem_c.dylib             	       0x119444e67 abort + 145
5   Flutter                       	       0x126ed4ca3 fml::KillProcess() + 9
6   Flutter                       	       0x126ed4c9a fml::LogMessage::~LogMessage() + 376
7   Flutter                       	       0x126bbcdb9 flutter::FlutterPlatformViewsController::RegisterViewFactory(NSObject<FlutterPlatformViewFactory>*, NSString*, FlutterPlatformViewGestureRecognizersBlockingPolicy) + 127
8   webview_flutter_wkwebview     	       0x114fb3de5 +[FLTWebViewFlutterPlugin registerWithRegistrar:] + 2213 (FLTWebViewFlutterPlugin.m:115)
9   Runner                        	       0x102de5796 +[GeneratedPluginRegistrant registerWithRegistry:] + 2902 (GeneratedPluginRegistrant.m:242)
10  Runner                        	       0x102de58c4 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 260 (AppDelegate.swift:16)
11  Runner                        	       0x102de5b67 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 183
12  UIKitCore                     	       0x13a09d2c3 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 271
13  UIKitCore                     	       0x13a09f186 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 4288
14  UIKitCore                     	       0x13a0a4ed2 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1236
15  UIKitCore                     	       0x1394be23e -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
16  UIKitCore                     	       0x139b3c510 _UIScenePerformActionsWithLifecycleActionMask + 88
17  UIKitCore                     	       0x1394bedd9 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
18  UIKitCore                     	       0x1394be81a -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 252
19  UIKitCore                     	       0x1394bec22 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 846
20  UIKitCore                     	       0x1394be41b -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 354
21  UIKitCore                     	       0x1394cd529 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 178
22  UIKitCore                     	       0x139a09703 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 833
23  UIKitCore                     	       0x139b5a5b0 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 257
24  UIKitCore                     	       0x1394cd1a9 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 348
25  UIKitCore                     	       0x1392afeed __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.601 + 815
26  UIKitCore                     	       0x1392ae903 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 245
27  UIKitCore                     	       0x1392afa9a -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 255
28  UIKitCore                     	       0x13a0a36d8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 733
29  UIKitCore                     	       0x139a3c11f -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 350
30  FrontBoardServices            	       0x1211b1bea -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 415
31  FrontBoardServices            	       0x1211e0c0e __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke.187 + 102
32  FrontBoardServices            	       0x1211bfbfc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
33  FrontBoardServices            	       0x1211e0815 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke + 344
34  libdispatch.dylib             	       0x1165320d9 _dispatch_client_callout + 8
35  libdispatch.dylib             	       0x116535bf2 _dispatch_block_invoke_direct + 491
36  FrontBoardServices            	       0x121207507 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
37  FrontBoardServices            	       0x1212073fd -[FBSSerialQueue _targetQueue_performNextIfPossible] + 174
38  FrontBoardServices            	       0x12120752f -[FBSSerialQueue _performNextFromRunLoopSource] + 19
39  CoreFoundation                	       0x118c4fb8f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
40  CoreFoundation                	       0x118c4fad1 __CFRunLoopDoSource0 + 157
41  CoreFoundation                	       0x118c4f2cd __CFRunLoopDoSources0 + 217
42  CoreFoundation                	       0x118c499ba __CFRunLoopRun + 889
43  CoreFoundation                	       0x118c49264 CFRunLoopRunSpecific + 560
44  GraphicsServices              	       0x12498e24e GSEventRunModal + 139
45  UIKitCore                     	       0x13a0a17bf -[UIApplication _run] + 994
46  UIKitCore                     	       0x13a0a65de UIApplicationMain + 123
47  Runner                        	       0x102de62ef main + 63 (AppDelegate.swift:9)
48  dyld_sim                      	       0x10ce39384 start_sim + 10
49  dyld                          	       0x20492f310 start + 2432

**Comment by domesticmouse** [comment]
PTAL @zoeyfan

**Comment by zoeyfan** [comment]
@malandr2 would you please share how I can pass this to the vendor team to triage and repro this issue?
